-- [[
-- sof_dsb_raid.lua -- shared helpers for the Deepscar (dragonscaleb v51)
-- and Big Bynn I (dragonscaleb v52) raids. Generated by gen_dsb_raid.py.
-- ]]

local M = {}

-- dragonscaleb instance version, or 0 in the static zone.
function M.version()
	local v = eq.get_zone_instance_version()
	if v == 51 or v == 52 then return v end
	return 0
end

function M.alive_clients(cx, cy, r)
	local out = {}
	local list = eq.get_entity_list():GetClientList()
	if not list then return out end
	for c in list.entries do
		if c and c:GetHPRatio() > 0
			and math.abs(c:GetX() - cx) <= r and math.abs(c:GetY() - cy) <= r then
			out[#out + 1] = c
		end
	end
	return out
end

function M.random_client(npc, radius)
	local list = M.alive_clients(npc:GetX(), npc:GetY(), radius or 200)
	if #list == 0 then return nil end
	return list[math.random(#list)]
end

function M.ae_damage(npc, radius, dmg, emote)
	if emote then eq.zone_emote(15, emote) end
	for _, c in ipairs(M.alive_clients(npc:GetX(), npc:GetY(), radius)) do
		pcall(function() c:Damage(npc, dmg, 0, 28) end)
	end
end

function M.ae_at(x, y, radius, npc, dmg)
	for _, c in ipairs(M.alive_clients(x, y, radius)) do
		pcall(function() c:Damage(npc, dmg, 0, 28) end)
	end
end

function M.spawn_adds(npc_type, count, cx, cy, cz, radius)
	local ids = {}
	for _ = 1, count do
		local m = eq.spawn2(npc_type, 0, 0,
			cx + math.random(-radius, radius), cy + math.random(-radius, radius), cz, 0)
		if m then ids[#ids + 1] = m:GetID() end
	end
	return ids
end

function M.chest(enc, chest_id, event_name)
	local exp = eq.get_expedition()
	if not exp.valid then return end
	local c = eq.unique_spawn(chest_id, 0, 0, enc:GetX(), enc:GetY(), enc:GetZ() + 5, 0)
	if c then exp:SetLootEventBySpawnID(c:GetID(), event_name) end
end

function M.signal(controller, key)
	eq.signal(controller, key)
end

function M.flag_all(bucket, value)
	local list = eq.get_entity_list():GetClientList()
	if not list then return end
	for c in list.entries do
		if c and c.valid then c:SetBucket(bucket, tostring(value)) end
	end
end

function M.alive_type(npc_type)
	local list = eq.get_entity_list():GetNPCList()
	if not list then return false end
	for n in list.entries do
		if n and n:GetNPCTypeID() == npc_type and n:GetHPRatio() > 0 then
			return true
		end
	end
	return false
end

function M.count_type(npc_type)
	local n = 0
	local list = eq.get_entity_list():GetNPCList()
	if not list then return 0 end
	for e in list.entries do
		if e and e:GetNPCTypeID() == npc_type and e:GetHPRatio() > 0 then
			n = n + 1
		end
	end
	return n
end

function M.max_heal(npc)
	pcall(function() npc:SetHP(npc:GetMaxHP()) end)
end

return M
