-- [[
-- sof_bloodmoon_raid.lua -- shared helpers for the three Bloodmoon Keep
-- raids (bloodmoon instance versions 1/2/3). Encounter scripts require
-- this for the repeated chest / alive-client / controller-signal code.
-- Rasper: raidBloodmoon1/2/3.html. Generated by gen_bloodmoon_raid.py.
-- ]]

local M = {}

M.CTRL = { [1] = 445547, [2] = 445548, [3] = 445549 }
M.CHEST = { [1] = 445540, [2] = 445541, [3] = 445542 }
M.SIG = { [1] = 1101, [2] = 1102, [3] = 1103 }

-- bloodmoon instance version, or 0 when in the static zone
function M.version()
	local v = eq.get_zone_instance_version()
	if v == 1 or v == 2 or v == 3 then return v end
	return 0
end

function M.alive_clients(cx, cy, r)
	local out = {}
	local list = eq.get_entity_list():GetClientList()
	if not list then return out end
	for c in list.entries do
		if c and c:GetHPRatio() > 0
			and math.abs(c:GetX() - cx) <= r and math.abs(c:GetY() - cy) <= r then
			out[#out + 1] = c
		end
	end
	return out
end

function M.chest(enc, chest_id, event_name)
	local exp = eq.get_expedition()
	if not exp.valid then return end
	local c = eq.unique_spawn(chest_id, 0, 0, enc:GetX(), enc:GetY(), enc:GetZ() + 5, 0)
	if c then exp:SetLootEventBySpawnID(c:GetID(), event_name) end
end

function M.signal(version, key)
	eq.signal(M.CTRL[version], key)
end

function M.flag_all(bucket, value)
	local list = eq.get_entity_list():GetClientList()
	if not list then return end
	for c in list.entries do
		if c and c.valid then c:SetBucket(bucket, tostring(value)) end
	end
end

function M.npc_by_id(id)
	return eq.get_entity_list():GetNPCByID(id)
end

function M.alive_type(npc_type)
	local list = eq.get_entity_list():GetNPCList()
	if not list then return false end
	for n in list.entries do
		if n and n:GetNPCTypeID() == npc_type and n:GetHPRatio() > 0 then
			return true
		end
	end
	return false
end

function M.aura_damage(src, radius, damage, emote)
	if emote then eq.zone_emote(15, emote) end
	for _, c in ipairs(M.alive_clients(src:GetX(), src:GetY(), radius)) do
		pcall(function() c:Damage(src, damage) end)
	end
end

function M.max_heal(npc)
	pcall(function() npc:SetHP(npc:GetMaxHP()) end)
end

function M.spawn_adds(npc_type, count, cx, cy, cz, radius)
	local ids = {}
	for _ = 1, count do
		local m = eq.spawn2(npc_type, 0, 0,
			cx + math.random(-radius, radius), cy + math.random(-radius, radius), cz, 0)
		if m then ids[#ids + 1] = m:GetID() end
	end
	return ids
end

return M
