-- [[
-- Clockwork Warmarshal (436010) -- Fortress Mechanotus.
--   * faction task giver (tasks 300020, 300021) -- as generated by
--     sof_content/gen_givers.py (this file is excluded from that generator).
--   * Meldrath's Majestic Mansion raid requester:
--       request phrase "Wish to have the honors" ("honors")
--       -> mechanotus instance version 1, 54-player, 8h, 72h replay lockout
--       gate: level 70+ and the SoF progression task 301011 (Exploring the
--       Mansion) complete. The live "Tier 2 completion" requirement has no
--       equivalent tracker on this server, so 301011 stands in for it.
--       entry: the mansion door (OBJ_MMC_MAINDR, mechanotus doorid 3).
--     "ready" re-enters an active expedition.
-- Rasper: raidMMM.html.
-- ]]

local fort = require("sof_fortress")

local TASKS = {
	300020, 300021,             -- Breaking Things Down, A Slave to the Grind
	fort.TASK_ENDLESS,          -- 300027 Endless Enemies
	fort.TASK_GEARS,            -- 300028 Switching Gears
	fort.TASK_HUNT_SPY,         -- 300029 Hunt a Spy
}
local REQUIRES = {
	[fort.TASK_HUNT_SPY] = fort.TASK_ENDLESS, -- start with the kill task first
}

local PROGRESSION_TASK = 301011 -- Exploring the Mansion (stage 3)

local mmm_raid = {
	expedition = { name = "Meldrath's Majestic Mansion", min_players = 1, max_players = 54 },
	instance   = { zone = "mechanotus", version = 1, duration = eq.seconds("8h") },
	compass    = { zone = "mechanotus", x = 14, y = 1520, z = 678.05 },
	safereturn = { zone = "mechanotus", x = 14, y = 1520, z = 678.05, h = 0 },
	zonein     = { x = 14, y = 1520, z = 678.05, h = 0 }, -- mansion hall, past OBJ_MMC_MAINDR (TUNABLE)
}

local function offer_tasks(e)
	e.self:Say("These are the duties I can entrust to you, " .. e.other:GetCleanName() .. ".")
	local available = {}
	for _, tid in ipairs(TASKS) do
		local required = REQUIRES[tid]
		if required == nil or e.other:IsTaskCompleted(required) then
			available[#available + 1] = tid
		end
	end
	eq.task_selector(available)
end

local function request_raid(e)
	if e.other:GetLevel() < 70 then
		e.self:Say("You'd be scrap before the first door. Return at level 70.")
		return
	end
	if not e.other:IsTaskCompleted(PROGRESSION_TASK) then
		e.self:Say("My scouts must first map the mansion (Exploring the Mansion) "
			.. "before I commit a raid to Meldrath's hall.")
		return
	end
	local current = e.other:GetExpedition()
	if current.valid then
		e.self:Say("You already hold a claim to an expedition. Use it or let it lapse.")
		return
	end
	local dz = e.other:CreateExpedition(mmm_raid)
	if dz.valid then
		dz:AddReplayLockout(eq.seconds("72h"))
		e.self:Say("Honors, then. Meldrath's Majestic Mansion is yours to storm -- "
			.. "clear every event before you face him. Tell me when you are [ready].")
	else
		e.self:Say("The mansion doors are cycling. Ask me again shortly.")
	end
end

function event_say(e)
	if e.message:findi("hail") then
		e.self:Say("Hail, " .. e.other:GetCleanName() .. ". There is work to be done if you "
			.. "would lend a hand. Ask me about a [task], or whether you have the [honors] "
			.. "to storm Meldrath's Majestic Mansion.")
	elseif e.message:findi("honors") or e.message:findi("meldrath") or e.message:findi("mansion raid") then
		request_raid(e)
	elseif e.message:findi("task") or e.message:findi("work") or e.message:findi("offer") or e.message:findi("jobs") then
		offer_tasks(e)
	elseif e.message:findi("ready") or e.message:findi("enter") then
		local dz = e.other:GetExpedition()
		if dz.valid then
			e.self:Say("Back into the mansion, " .. e.other:GetCleanName() .. ".")
			e.other:MovePCDynamicZone(dz:GetZoneID())
		else
			e.self:Say("You belong to no expedition.")
		end
	end
end

function event_trade(e)
	local item_lib = require("items")
	item_lib.return_items(e.self, e.other, e.trade)
end
