-- badword_filter_restore.sql
-- Restores the badword filters that were removed from the live peq database.
--   1. name_filter    : 280 bad words used by Database::CheckNameFilter (character,
--                       channel, mercenary, bot name validation).
--   2. profanity_list : 284-word chat redaction list seeded from GetBadWords()
--                       (common/strings_misc.cpp), used by EQ::ProfanityManager.
-- Idempotent / safe to re-run. Existing rows in profanity_list are preserved (INSERT IGNORE).
USE `peq`;

-- ------------------------------------------------------------------
-- name_filter
-- ------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `name_filter` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(30) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `name_search_index` (`name`)
) ENGINE=InnoDB AUTO_INCREMENT=284 DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;

DELETE FROM `name_filter`;

INSERT INTO `name_filter` VALUES

(1,'-GM'),
(218,'aborshion'),
(2,'abortion'),
(3,'acid'),
(245,'akka'),
(4,'allah'),
(5,'anal'),
(6,'ass'),
(7,'asshole'),
(8,'ballbeater'),
(9,'ballhitter'),
(10,'balllicker'),
(11,'ballsucker'),
(12,'bangher'),
(13,'bastard'),
(14,'bastid'),
(208,'bewb'),
(212,'bewbs'),
(15,'biatch'),
(222,'Biotch'),
(16,'bitch'),
(17,'blow'),
(18,'bodhisattva'),
(223,'boner'),
(19,'boob'),
(20,'boobie'),
(210,'bowjob'),
(21,'breast'),
(22,'browneye'),
(23,'buddha'),
(24,'butt'),
(25,'capitalist'),
(26,'cavedude'),
(27,'cazic'),
(28,'cheat'),
(29,'chink'),
(262,'chlamidia'),
(259,'chlamydia'),
(30,'christ'),
(260,'clamydia'),
(31,'clit'),
(32,'cock'),
(33,'coke'),
(34,'communist'),
(35,'coonass'),
(36,'corrupt'),
(37,'crack'),
(38,'cracka'),
(39,'cracker'),
(40,'crank'),
(41,'crap'),
(42,'cSR'),
(43,'cum'),
(44,'cunt'),
(209,'dammit'),
(45,'damn'),
(46,'deiffin'),
(47,'democrat'),
(48,'dick'),
(49,'dingleberry'),
(50,'diq'),
(51,'dong'),
(52,'donkeypunch'),
(53,'douche'),
(54,'drug'),
(230,'dumbich'),
(224,'dyke'),
(231,'epeen'),
(55,'EyeP'),
(56,'eyepfreely'),
(57,'fack'),
(58,'fag'),
(213,'Fagina'),
(219,'Fart'),
(274,'fart'),
(220,'Farted'),
(59,'fathernitwit'),
(60,'feck'),
(61,'fennin'),
(62,'fuck'),
(225,'fudgepacker'),
(63,'fuk'),
(247,'funbag'),
(64,'fuqu'),
(214,'Furtaco'),
(65,'fuxxor'),
(255,'genital'),
(66,'ghey'),
(67,'gM-'),
(68,'gM_'),
(69,'god'),
(265,'gonorea'),
(264,'gonorhea'),
(258,'gonorrea'),
(257,'gonorrhea'),
(70,'goo'),
(71,'gook'),
(236,'Gopr'),
(72,'grandCreation'),
(73,'hebrew'),
(272,'hepatitis'),
(74,'heroin'),
(256,'herpe'),
(75,'hillBilly'),
(76,'hitler'),
(77,'hoe'),
(78,'homo'),
(79,'honkey'),
(80,'hooker'),
(249,'hooter'),
(237,'Huffin'),
(81,'innoruuk'),
(82,'Isuccacocc'),
(83,'itchy'),
(84,'jackoff'),
(85,'jehova'),
(86,'jehovah'),
(87,'jesus'),
(88,'jew'),
(89,'jigaboo'),
(244,'jihad'),
(90,'jiz'),
(91,'karana'),
(92,'kerafyrm'),
(93,'kike'),
(239,'Kilz'),
(263,'klamidia'),
(261,'klamydia'),
(94,'kls'),
(95,'klukluxklan'),
(96,'kneeGrow'),
(248,'knockers'),
(281,'krotch'),
(97,'kunt'),
(98,'labia'),
(99,'lawli'),
(100,'lawlicake'),
(101,'lesbian'),
(243,'lesbo'),
(102,'lester'),
(103,'level'),
(104,'loot'),
(105,'lootmeh'),
(106,'lsd'),
(238,'Mackal'),
(107,'marijuana'),
(108,'maryjane'),
(109,'masterbait'),
(110,'masterbate'),
(111,'masturbait'),
(227,'meatflap'),
(112,'medirty'),
(113,'messiah'),
(228,'milf'),
(114,'moelester'),
(115,'mohlester'),
(116,'nazi'),
(117,'negro'),
(118,'niga'),
(119,'nigg'),
(120,'nigga'),
(121,'nigger'),
(122,'nipple'),
(123,'nork'),
(124,'nympho'),
(125,'panis'),
(271,'papilloma'),
(126,'penis'),
(127,'pEQ'),
(275,'phart'),
(128,'pinkeye'),
(129,'piss'),
(130,'player'),
(131,'poon'),
(277,'poop'),
(132,'porchmonkey'),
(133,'porn'),
(135,'prick'),
(136,'private'),
(137,'pubic'),
(138,'pussy'),
(139,'pve'),
(140,'pvp'),
(141,'pwn'),
(142,'quarm'),
(215,'queef'),
(216,'queeftaco'),
(143,'Quirfag'),
(144,'qunt'),
(145,'raghead'),
(146,'rallos'),
(147,'rape'),
(148,'redneck'),
(149,'reno'),
(150,'republican'),
(151,'retard'),
(152,'satan'),
(276,'schit'),
(211,'Schlong'),
(153,'screw'),
(226,'scrotum'),
(154,'seaman'),
(155,'seamans'),
(240,'secks'),
(242,'secsea'),
(241,'secsee'),
(156,'seeman'),
(157,'seemen'),
(158,'semen'),
(159,'server'),
(160,'sex'),
(161,'shard'),
(162,'shit'),
(163,'shitstain'),
(269,'sifilis'),
(270,'siphilis'),
(164,'sitt'),
(165,'sittstain'),
(166,'skank'),
(167,'skanq'),
(280,'skinflute'),
(168,'sleeper'),
(169,'slut'),
(170,'snatch'),
(171,'socialist'),
(172,'sony'),
(173,'spade'),
(174,'spawnthemonkey'),
(175,'speed'),
(176,'spick'),
(177,'splodge'),
(217,'Sploog'),
(178,'spoog'),
(179,'spook'),
(180,'stain'),
(181,'sTFU'),
(182,'suck'),
(183,'suckme'),
(184,'sucks'),
(185,'sux'),
(268,'syfhilis'),
(267,'syfilis'),
(266,'syphilis'),
(273,'Tacvi'),
(186,'tallon'),
(187,'tarbaby'),
(188,'tard'),
(254,'teatea'),
(253,'teetee'),
(250,'terroris'),
(189,'testicle'),
(282,'Thecoon'),
(283,'thecoon'),
(190,'tit'),
(191,'tunare'),
(192,'tvz'),
(193,'twat'),
(194,'tzvz'),
(252,'vageen'),
(195,'vagina'),
(232,'vajay'),
(251,'vajeen'),
(234,'vajeh'),
(196,'vallon'),
(197,'vtz'),
(233,'vuhjay'),
(235,'vuhjey'),
(198,'vztz'),
(199,'wanker'),
(200,'weed'),
(201,'wetback'),
(202,'whitehorse'),
(278,'Whitepower'),
(279,'Whiteprivilege'),
(203,'whore'),
(204,'wildcard'),
(205,'wtf'),
(246,'xxx'),
(206,'ylosh'),
(207,'_GM');;

-- ------------------------------------------------------------------
-- profanity_list
-- ------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `profanity_list` (
  `word` varchar(16) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;

INSERT IGNORE INTO `profanity_list` (`word`) VALUES
('2g1c')
('acrotomophilia')
('anal')
('anilingus')
('anus')
('apeshit')
('arsehole')
('ass')
('asshole')
('assmunch')
('autoerotic')
('babeland')
('bangbros')
('bangbus')
('bareback')
('barenaked')
('bastard')
('bastardo')
('bastinado')
('bbw')
('bdsm')
('beaner')
('beaners')
('beaver')
('beastiality')
('bestiality')
('bimbos')
('birdlock')
('bitch')
('bitches')
('blowjob')
('blumpkin')
('bollocks')
('bondage')
('boner')
('boob')
('boobs')
('bukkake')
('bulldyke')
('bullshit')
('bung')
('bunghole')
('busty')
('butt')
('buttcheeks')
('butthole')
('camel toe')
('camgirl')
('camslut')
('camwhore')
('carpetmuncher')
('cialis')
('circlejerk')
('clit')
('clitoris')
('clusterfuck')
('cock')
('cocks')
('coprolagnia')
('coprophilia')
('cornhole')
('coon')
('coons')
('creampie')
('cum')
('cumming')
('cumshot')
('cumshots')
('cunnilingus')
('cunt')
('darkie')
('daterape')
('deepthroat')
('dendrophilia')
('dick')
('dildo')
('dingleberry')
('dingleberries')
('doggiestyle')
('doggystyle')
('dolcett')
('domination')
('dominatrix')
('dommes')
('hump')
('dvda')
('ecchi')
('ejaculation')
('erotic')
('erotism')
('escort')
('eunuch')
('fag')
('faggot')
('fecal')
('felch')
('fellatio')
('feltch')
('femdom')
('figging')
('fingerbang')
('fingering')
('fisting')
('footjob')
('frotting')
('fuck')
('fuckin')
('fucking')
('fucktards')
('fudgepacker')
('futanari')
('gangbang')
('gangbang')
('gaysex')
('genitals')
('goatcx')
('goatse')
('gokkun')
('goodpoop')
('goregasm')
('grope')
('g-spot')
('guro')
('handjob')
('hentai')
('homoerotic')
('honkey')
('hooker')
('horny')
('humping')
('incest')
('intercourse')
('jailbait')
('jigaboo')
('jiggaboo')
('jiggerboo')
('jizz')
('juggs')
('kike')
('kinbaku')
('kinkster')
('kinky')
('knobbing')
('livesex')
('lolita')
('lovemaking')
('masturbate')
('masturbating')
('masturbation')
('milf')
('mong')
('motherfucker')
('muffdiving')
('nambla')
('nawashi')
('negro')
('neonazi')
('nigga')
('nigger')
('nimphomania')
('nipple')
('nipples')
('nsfw')
('nude')
('nudity')
('nutten')
('nympho')
('nymphomania')
('octopussy')
('omorashi')
('orgasm')
('orgy')
('paedophile')
('paki')
('panties')
('panty')
('pedobear')
('pedophile')
('pegging')
('penis')
('pikey')
('pissing')
('pisspig')
('playboy')
('ponyplay')
('poof')
('poon')
('poontang')
('punany')
('poopchute')
('porn')
('porno')
('pornography')
('pthc')
('pubes')
('pussy')
('queaf')
('queef')
('quim')
('raghead')
('rape')
('raping')
('rapist')
('rectum')
('rimjob')
('rimming')
('sadism')
('santorum')
('scat')
('schlong')
('scissoring')
('semen')
('sex')
('sexcam')
('sexo')
('sexy')
('sexual')
('sexually')
('sexuality')
('shemale')
('shibari')
('shit')
('shitblimp')
('shitty')
('shota')
('shrimping')
('skeet')
('slanteye')
('slut')
('s&m')
('smut')
('snatch')
('snowballing')
('sodomize')
('sodomy')
('spastic')
('spic')
('splooge')
('spooge')
('spunk')
('strapon')
('strappado')
('suck')
('sucks')
('swastika')
('swinger')
('threesome')
('throating')
('thumbzilla')
('tight white')
('tit')
('tits')
('titties')
('titty')
('topless')
('tosser')
('towelhead')
('tranny')
('tribadism')
('tubgirl')
('tushy')
('twat')
('twink')
('twinkie')
('undressing')
('upskirt')
('urophilia')
('vagina')
('viagra')
('vibrator')
('vorarephilia')
('voyeur')
('voyeurweb')
('voyuer')
('vulva')
('wank')
('wetback')
('whore')
('worldsex')
('xx')
('xxx')
('yaoi')
('yiffy')
('zoophilia');