# Kimem Saydel - Crescent Reach
# The Serpent's Spine :: low-level armour line (levels 20-30), all four types.
# Components: Blightfire-Infused materials (64105-64108) + Blightfire patterns (64109-64115).
# Auto-generated by gen_kimem.py

sub EVENT_SAY {
  if ($text=~/hail/i) {
    quest::say("Vasha, $name. You have the stride of an adventurer about you. They say that an adventurer is only as good as the [" . quest::saylink("armor") . "] they wear.");
  }
  if ($text=~/armor/i) {
    quest::say("I may be able to fashion you some protection. Adventurers returning from the Blightfire Moors bring [" . quest::saylink("materials") . "] that have picked up a bit of the curse that plagues that land, and I can tap the magic within them.");
  }
  if ($text=~/materials/i) {
    quest::say("Bring me Blightfire-Infused material and the matching Blightfire pattern for the piece you want, and I will fashion it for you.");
  }
}

sub EVENT_ITEM {
  my $class = $client->GetClass();
  if ($class != 1 && $class != 2 && $class != 3 && $class != 4 && $class != 5 && $class != 6 && $class != 7 && $class != 8 && $class != 9 && $class != 10 && $class != 11 && $class != 12 && $class != 13 && $class != 14 && $class != 15 && $class != 16) {
    quest::say("This armour is not for your calling, friend.");
    plugin::return_items(\%itemcount);
    return;
  }

  # ================= PLATE =================
  if (plugin::check_handin(\%itemcount, 64105 => 4, 64115 => 1)) {
    my %reward = (1 => 53006, 2 => 53013, 3 => 53020, 5 => 53034, 8 => 53055);
    quest::summonitem($reward{$class});
    quest::say("These will work nicely. Let me fashion this into a Breastplate for you.");
    plugin::return_items(\%itemcount);
    return;
  }
  if (plugin::check_handin(\%itemcount, 64105 => 3, 64111 => 1)) {
    my %reward = (1 => 53002, 2 => 53009, 3 => 53016, 5 => 53030, 8 => 53051);
    quest::summonitem($reward{$class});
    quest::say("These will work nicely. Let me fashion this into a Vambraces for you.");
    plugin::return_items(\%itemcount);
    return;
  }
  if (plugin::check_handin(\%itemcount, 64105 => 4, 64114 => 1)) {
    my %reward = (1 => 53007, 2 => 53014, 3 => 53021, 5 => 53035, 8 => 53056);
    quest::summonitem($reward{$class});
    quest::say("These will work nicely. Let me fashion this into a Greaves for you.");
    plugin::return_items(\%itemcount);
    return;
  }
  if (plugin::check_handin(\%itemcount, 64105 => 3, 64113 => 1)) {
    my %reward = (1 => 53001, 2 => 53008, 3 => 53015, 5 => 53029, 8 => 53050);
    quest::summonitem($reward{$class});
    quest::say("These will work nicely. Let me fashion this into a Helm for you.");
    plugin::return_items(\%itemcount);
    return;
  }
  if (plugin::check_handin(\%itemcount, 64105 => 2, 64110 => 1)) {
    my %reward = (1 => 53004, 2 => 53011, 3 => 53018, 5 => 53032, 8 => 53053);
    quest::summonitem($reward{$class});
    quest::say("These will work nicely. Let me fashion this into a Gauntlets for you.");
    plugin::return_items(\%itemcount);
    return;
  }
  if (plugin::check_handin(\%itemcount, 64105 => 2, 64112 => 1)) {
    my %reward = (1 => 53005, 2 => 53012, 3 => 53019, 5 => 53033, 8 => 53054);
    quest::summonitem($reward{$class});
    quest::say("These will work nicely. Let me fashion this into a Boots for you.");
    plugin::return_items(\%itemcount);
    return;
  }
  if (plugin::check_handin(\%itemcount, 64105 => 1, 64109 => 1)) {
    my %reward = (1 => 53003, 2 => 53010, 3 => 53017, 5 => 53031, 8 => 53052);
    quest::summonitem($reward{$class});
    quest::say("These will work nicely. Let me fashion this into a Bracer for you.");
    plugin::return_items(\%itemcount);
    return;
  }

  # ================= CHAIN =================
  if (plugin::check_handin(\%itemcount, 64106 => 4, 64115 => 1)) {
    my %reward = (4 => 53027, 9 => 53062, 10 => 53069, 16 => 53111);
    quest::summonitem($reward{$class});
    quest::say("These will work nicely. Let me fashion this into a Coat for you.");
    plugin::return_items(\%itemcount);
    return;
  }
  if (plugin::check_handin(\%itemcount, 64106 => 3, 64111 => 1)) {
    my %reward = (4 => 53023, 9 => 53058, 10 => 53065, 16 => 53107);
    quest::summonitem($reward{$class});
    quest::say("These will work nicely. Let me fashion this into a Sleeves for you.");
    plugin::return_items(\%itemcount);
    return;
  }
  if (plugin::check_handin(\%itemcount, 64106 => 4, 64114 => 1)) {
    my %reward = (4 => 53028, 9 => 53063, 10 => 53070, 16 => 53112);
    quest::summonitem($reward{$class});
    quest::say("These will work nicely. Let me fashion this into a Leggings for you.");
    plugin::return_items(\%itemcount);
    return;
  }
  if (plugin::check_handin(\%itemcount, 64106 => 3, 64113 => 1)) {
    my %reward = (4 => 53022, 9 => 53057, 10 => 53064, 16 => 53106);
    quest::summonitem($reward{$class});
    quest::say("These will work nicely. Let me fashion this into a Coif for you.");
    plugin::return_items(\%itemcount);
    return;
  }
  if (plugin::check_handin(\%itemcount, 64106 => 2, 64110 => 1)) {
    my %reward = (4 => 53025, 9 => 53060, 10 => 53067, 16 => 53109);
    quest::summonitem($reward{$class});
    quest::say("These will work nicely. Let me fashion this into a Gauntlets for you.");
    plugin::return_items(\%itemcount);
    return;
  }
  if (plugin::check_handin(\%itemcount, 64106 => 2, 64112 => 1)) {
    my %reward = (4 => 53026, 9 => 53061, 10 => 53068, 16 => 53110);
    quest::summonitem($reward{$class});
    quest::say("These will work nicely. Let me fashion this into a Boots for you.");
    plugin::return_items(\%itemcount);
    return;
  }
  if (plugin::check_handin(\%itemcount, 64106 => 1, 64109 => 1)) {
    my %reward = (4 => 53024, 9 => 53059, 10 => 53066, 16 => 53108);
    quest::summonitem($reward{$class});
    quest::say("These will work nicely. Let me fashion this into a Wristguard for you.");
    plugin::return_items(\%itemcount);
    return;
  }

  # ================= LEATHER =================
  if (plugin::check_handin(\%itemcount, 64107 => 4, 64115 => 1)) {
    my %reward = (6 => 53041, 7 => 53048, 15 => 53104);
    quest::summonitem($reward{$class});
    quest::say("These will work nicely. Let me fashion this into a Tunic for you.");
    plugin::return_items(\%itemcount);
    return;
  }
  if (plugin::check_handin(\%itemcount, 64107 => 3, 64111 => 1)) {
    my %reward = (6 => 53037, 7 => 53044, 15 => 53100);
    quest::summonitem($reward{$class});
    quest::say("These will work nicely. Let me fashion this into a Armwraps for you.");
    plugin::return_items(\%itemcount);
    return;
  }
  if (plugin::check_handin(\%itemcount, 64107 => 4, 64114 => 1)) {
    my %reward = (6 => 53042, 7 => 53049, 15 => 53105);
    quest::summonitem($reward{$class});
    quest::say("These will work nicely. Let me fashion this into a Leggings for you.");
    plugin::return_items(\%itemcount);
    return;
  }
  if (plugin::check_handin(\%itemcount, 64107 => 3, 64113 => 1)) {
    my %reward = (6 => 53036, 7 => 53043, 15 => 53099);
    quest::summonitem($reward{$class});
    quest::say("These will work nicely. Let me fashion this into a Cowl for you.");
    plugin::return_items(\%itemcount);
    return;
  }
  if (plugin::check_handin(\%itemcount, 64107 => 2, 64110 => 1)) {
    my %reward = (6 => 53039, 7 => 53046, 15 => 53102);
    quest::summonitem($reward{$class});
    quest::say("These will work nicely. Let me fashion this into a Gloves for you.");
    plugin::return_items(\%itemcount);
    return;
  }
  if (plugin::check_handin(\%itemcount, 64107 => 2, 64112 => 1)) {
    my %reward = (6 => 53040, 7 => 53047, 15 => 53103);
    quest::summonitem($reward{$class});
    quest::say("These will work nicely. Let me fashion this into a Boots for you.");
    plugin::return_items(\%itemcount);
    return;
  }
  if (plugin::check_handin(\%itemcount, 64107 => 1, 64109 => 1)) {
    my %reward = (6 => 53038, 7 => 53045, 15 => 53101);
    quest::summonitem($reward{$class});
    quest::say("These will work nicely. Let me fashion this into a Wristguard for you.");
    plugin::return_items(\%itemcount);
    return;
  }

  # ================= CLOTH =================
  if (plugin::check_handin(\%itemcount, 64108 => 4, 64115 => 1)) {
    my %reward = (11 => 53076, 12 => 53083, 13 => 53090, 14 => 53097);
    quest::summonitem($reward{$class});
    quest::say("These will work nicely. Let me fashion this into a Robe for you.");
    plugin::return_items(\%itemcount);
    return;
  }
  if (plugin::check_handin(\%itemcount, 64108 => 3, 64111 => 1)) {
    my %reward = (11 => 53072, 12 => 53079, 13 => 53086, 14 => 53093);
    quest::summonitem($reward{$class});
    quest::say("These will work nicely. Let me fashion this into a Sleeves for you.");
    plugin::return_items(\%itemcount);
    return;
  }
  if (plugin::check_handin(\%itemcount, 64108 => 4, 64114 => 1)) {
    my %reward = (11 => 53077, 12 => 53084, 13 => 53091, 14 => 53098);
    quest::summonitem($reward{$class});
    quest::say("These will work nicely. Let me fashion this into a Pants for you.");
    plugin::return_items(\%itemcount);
    return;
  }
  if (plugin::check_handin(\%itemcount, 64108 => 3, 64113 => 1)) {
    my %reward = (11 => 53071, 12 => 53078, 13 => 53085, 14 => 53092);
    quest::summonitem($reward{$class});
    quest::say("These will work nicely. Let me fashion this into a Cap for you.");
    plugin::return_items(\%itemcount);
    return;
  }
  if (plugin::check_handin(\%itemcount, 64108 => 2, 64110 => 1)) {
    my %reward = (11 => 53074, 12 => 53081, 13 => 53088, 14 => 53095);
    quest::summonitem($reward{$class});
    quest::say("These will work nicely. Let me fashion this into a Gloves for you.");
    plugin::return_items(\%itemcount);
    return;
  }
  if (plugin::check_handin(\%itemcount, 64108 => 2, 64112 => 1)) {
    my %reward = (11 => 53075, 12 => 53082, 13 => 53089, 14 => 53096);
    quest::summonitem($reward{$class});
    quest::say("These will work nicely. Let me fashion this into a Sandals for you.");
    plugin::return_items(\%itemcount);
    return;
  }
  if (plugin::check_handin(\%itemcount, 64108 => 1, 64109 => 1)) {
    my %reward = (11 => 53073, 12 => 53080, 13 => 53087, 14 => 53094);
    quest::summonitem($reward{$class});
    quest::say("These will work nicely. Let me fashion this into a Wristband for you.");
    plugin::return_items(\%itemcount);
    return;
  }

  plugin::return_items(\%itemcount);
}
