# Tenish - Crescent Reach
# The Serpent's Spine :: full armour line - Plate (Bard/Cleric/Paladin/SK/Warrior),
# Chain (Berserker/Ranger/Rogue/Shaman), Leather (Druid/Monk/Beastlord),
# Silk (Necromancer/Wizard/Magician/Enchanter). Part 1 crafts; Part 2 empowers.
# Auto-generated by gen_tenish2.py

sub EVENT_SAY {
  if ($text=~/hail/i) {
    quest::say("Vasha, friend! Excuse me if I seem distracted, but I was just studying this text on ancient and powerful [" . quest::saylink("artifacts") . "] that Librarian Hemfar has compiled.");
  }
  if ($text=~/artifacts/i) {
    quest::say("This entire area is rich with ancient magic. I have learned to imbue ordinary [" . quest::saylink("armor") . "] with extraordinary properties, if you can locate the [" . quest::saylink("components") . "] the tome hints at.");
  }
  if ($text=~/armor/i) {
    quest::say("Armor of all types! Bring me the components for your calling and I will craft a piece. Return it with a glowing powersource and I can empower it [" . quest::saylink("further") . "].");
  }
  if ($text=~/components/i) {
    quest::say("Frosted and ash-covered materials lie near the giant city and the volcano; the molds are hoarded by the most powerful denizens of those lands.");
  }
  if ($text=~/further/i) {
    quest::say("Bring me a piece I have made, along with the matching glowing powersource from Valdeholm or the Vergalid Mines, and I shall add its latent power.");
  }
}

sub EVENT_ITEM {
  my $class = $client->GetClass();
  if ($class != 1 && $class != 2 && $class != 3 && $class != 4 && $class != 5 && $class != 6 && $class != 7 && $class != 8 && $class != 9 && $class != 10 && $class != 11 && $class != 12 && $class != 13 && $class != 14 && $class != 15 && $class != 16) {
    quest::say("This craft is not for your calling, friend.");
    plugin::return_items(\%itemcount);
    return;
  }

  # ================= PLATE =================
  # --- Plate Part 1 ---
  if (plugin::check_handin(\%itemcount, 32815 => 4, 32825 => 1)) {
    my %reward = (1 => 53776, 2 => 53783, 3 => 53790, 5 => 53804, 8 => 53825);
    quest::summonitem($reward{$class});
    quest::say("My theory was correct! Here is your Breastplate. Return it with the right powersource and I can empower it further.");
    plugin::return_items(\%itemcount);
    return;
  }
  if (plugin::check_handin(\%itemcount, 32815 => 3, 32827 => 1)) {
    my %reward = (1 => 53772, 2 => 53779, 3 => 53786, 5 => 53800, 8 => 53821);
    quest::summonitem($reward{$class});
    quest::say("My theory was correct! Here is your Vambraces. Return it with the right powersource and I can empower it further.");
    plugin::return_items(\%itemcount);
    return;
  }
  if (plugin::check_handin(\%itemcount, 32811 => 4, 32826 => 1)) {
    my %reward = (1 => 53777, 2 => 53784, 3 => 53791, 5 => 53805, 8 => 53826);
    quest::summonitem($reward{$class});
    quest::say("My theory was correct! Here is your Greaves. Return it with the right powersource and I can empower it further.");
    plugin::return_items(\%itemcount);
    return;
  }
  if (plugin::check_handin(\%itemcount, 32811 => 3, 32831 => 1)) {
    my %reward = (1 => 53771, 2 => 53778, 3 => 53785, 5 => 53799, 8 => 53820);
    quest::summonitem($reward{$class});
    quest::say("My theory was correct! Here is your Helm. Return it with the right powersource and I can empower it further.");
    plugin::return_items(\%itemcount);
    return;
  }
  if (plugin::check_handin(\%itemcount, 32811 => 2, 32828 => 1)) {
    my %reward = (1 => 53774, 2 => 53781, 3 => 53788, 5 => 53802, 8 => 53823);
    quest::summonitem($reward{$class});
    quest::say("My theory was correct! Here is your Gauntlets. Return it with the right powersource and I can empower it further.");
    plugin::return_items(\%itemcount);
    return;
  }
  if (plugin::check_handin(\%itemcount, 32815 => 2, 32829 => 1)) {
    my %reward = (1 => 53775, 2 => 53782, 3 => 53789, 5 => 53803, 8 => 53824);
    quest::summonitem($reward{$class});
    quest::say("My theory was correct! Here is your Boots. Return it with the right powersource and I can empower it further.");
    plugin::return_items(\%itemcount);
    return;
  }
  if (plugin::check_handin(\%itemcount, 32811 => 1, 32830 => 1)) {
    my %reward = (1 => 53773, 2 => 53780, 3 => 53787, 5 => 53801, 8 => 53822);
    quest::summonitem($reward{$class});
    quest::say("My theory was correct! Here is your Bracer. Return it with the right powersource and I can empower it further.");
    plugin::return_items(\%itemcount);
    return;
  }
  # --- Plate Part 2 ---
  my %b_plate_breastplate = (1 => 53776, 2 => 53783, 3 => 53790, 5 => 53804, 8 => 53825);
  if (plugin::check_handin(\%itemcount, 32847 => 1, $b_plate_breastplate{$class} => 1)) {
    my %upg = (1 => 53246, 2 => 53253, 3 => 53260, 5 => 53274, 8 => 53295);
    quest::summonitem($upg{$class});
    quest::say("The powersource has taken hold. Your Breastplate is now far greater than before!");
    plugin::return_items(\%itemcount);
    return;
  }
  my %b_plate_vambraces = (1 => 53772, 2 => 53779, 3 => 53786, 5 => 53800, 8 => 53821);
  if (plugin::check_handin(\%itemcount, 32847 => 1, $b_plate_vambraces{$class} => 1)) {
    my %upg = (1 => 53242, 2 => 53249, 3 => 53256, 5 => 53270, 8 => 53291);
    quest::summonitem($upg{$class});
    quest::say("The powersource has taken hold. Your Vambraces is now far greater than before!");
    plugin::return_items(\%itemcount);
    return;
  }
  my %b_plate_greaves = (1 => 53777, 2 => 53784, 3 => 53791, 5 => 53805, 8 => 53826);
  if (plugin::check_handin(\%itemcount, 32847 => 1, $b_plate_greaves{$class} => 1)) {
    my %upg = (1 => 53247, 2 => 53254, 3 => 53261, 5 => 53275, 8 => 53296);
    quest::summonitem($upg{$class});
    quest::say("The powersource has taken hold. Your Greaves is now far greater than before!");
    plugin::return_items(\%itemcount);
    return;
  }
  my %b_plate_helm = (1 => 53771, 2 => 53778, 3 => 53785, 5 => 53799, 8 => 53820);
  if (plugin::check_handin(\%itemcount, 32847 => 1, $b_plate_helm{$class} => 1)) {
    my %upg = (1 => 53241, 2 => 53248, 3 => 53255, 5 => 53269, 8 => 53290);
    quest::summonitem($upg{$class});
    quest::say("The powersource has taken hold. Your Helm is now far greater than before!");
    plugin::return_items(\%itemcount);
    return;
  }
  my %b_plate_gauntlets = (1 => 53774, 2 => 53781, 3 => 53788, 5 => 53802, 8 => 53823);
  if (plugin::check_handin(\%itemcount, 32847 => 1, $b_plate_gauntlets{$class} => 1)) {
    my %upg = (1 => 53244, 2 => 53251, 3 => 53258, 5 => 53272, 8 => 53293);
    quest::summonitem($upg{$class});
    quest::say("The powersource has taken hold. Your Gauntlets is now far greater than before!");
    plugin::return_items(\%itemcount);
    return;
  }
  my %b_plate_boots = (1 => 53775, 2 => 53782, 3 => 53789, 5 => 53803, 8 => 53824);
  if (plugin::check_handin(\%itemcount, 32847 => 1, $b_plate_boots{$class} => 1)) {
    my %upg = (1 => 53245, 2 => 53252, 3 => 53259, 5 => 53273, 8 => 53294);
    quest::summonitem($upg{$class});
    quest::say("The powersource has taken hold. Your Boots is now far greater than before!");
    plugin::return_items(\%itemcount);
    return;
  }
  my %b_plate_bracer = (1 => 53773, 2 => 53780, 3 => 53787, 5 => 53801, 8 => 53822);
  if (plugin::check_handin(\%itemcount, 32847 => 1, $b_plate_bracer{$class} => 1)) {
    my %upg = (1 => 53243, 2 => 53250, 3 => 53257, 5 => 53271, 8 => 53292);
    quest::summonitem($upg{$class});
    quest::say("The powersource has taken hold. Your Bracer is now far greater than before!");
    plugin::return_items(\%itemcount);
    return;
  }

  # ================= CHAIN =================
  # --- Chain Part 1 ---
  if (plugin::check_handin(\%itemcount, 32814 => 4, 32818 => 1)) {
    my %reward = (4 => 53797, 9 => 53832, 10 => 53839, 16 => 53881);
    quest::summonitem($reward{$class});
    quest::say("My theory was correct! Here is your Coat. Return it with the right powersource and I can empower it further.");
    plugin::return_items(\%itemcount);
    return;
  }
  if (plugin::check_handin(\%itemcount, 32814 => 3, 32820 => 1)) {
    my %reward = (4 => 53793, 9 => 53828, 10 => 53835, 16 => 53877);
    quest::summonitem($reward{$class});
    quest::say("My theory was correct! Here is your Sleeves. Return it with the right powersource and I can empower it further.");
    plugin::return_items(\%itemcount);
    return;
  }
  if (plugin::check_handin(\%itemcount, 32810 => 4, 32819 => 1)) {
    my %reward = (4 => 53798, 9 => 53833, 10 => 53840, 16 => 53882);
    quest::summonitem($reward{$class});
    quest::say("My theory was correct! Here is your Leggings. Return it with the right powersource and I can empower it further.");
    plugin::return_items(\%itemcount);
    return;
  }
  if (plugin::check_handin(\%itemcount, 32810 => 3, 32824 => 1)) {
    my %reward = (4 => 53792, 9 => 53827, 10 => 53834, 16 => 53876);
    quest::summonitem($reward{$class});
    quest::say("My theory was correct! Here is your Coif. Return it with the right powersource and I can empower it further.");
    plugin::return_items(\%itemcount);
    return;
  }
  if (plugin::check_handin(\%itemcount, 32810 => 2, 32821 => 1)) {
    my %reward = (4 => 53795, 9 => 53830, 10 => 53837, 16 => 53879);
    quest::summonitem($reward{$class});
    quest::say("My theory was correct! Here is your Gauntlets. Return it with the right powersource and I can empower it further.");
    plugin::return_items(\%itemcount);
    return;
  }
  if (plugin::check_handin(\%itemcount, 32814 => 2, 32822 => 1)) {
    my %reward = (4 => 53796, 9 => 53831, 10 => 53838, 16 => 53880);
    quest::summonitem($reward{$class});
    quest::say("My theory was correct! Here is your Boots. Return it with the right powersource and I can empower it further.");
    plugin::return_items(\%itemcount);
    return;
  }
  if (plugin::check_handin(\%itemcount, 32810 => 1, 32823 => 1)) {
    my %reward = (4 => 53794, 9 => 53829, 10 => 53836, 16 => 53878);
    quest::summonitem($reward{$class});
    quest::say("My theory was correct! Here is your Wristguard. Return it with the right powersource and I can empower it further.");
    plugin::return_items(\%itemcount);
    return;
  }
  # --- Chain Part 2 ---
  my %b_chain_coat = (4 => 53797, 9 => 53832, 10 => 53839, 16 => 53881);
  if (plugin::check_handin(\%itemcount, 32846 => 1, $b_chain_coat{$class} => 1)) {
    my %upg = (4 => 53267, 9 => 53302, 10 => 53309, 16 => 53351);
    quest::summonitem($upg{$class});
    quest::say("The powersource has taken hold. Your Coat is now far greater than before!");
    plugin::return_items(\%itemcount);
    return;
  }
  my %b_chain_sleeves = (4 => 53793, 9 => 53828, 10 => 53835, 16 => 53877);
  if (plugin::check_handin(\%itemcount, 32846 => 1, $b_chain_sleeves{$class} => 1)) {
    my %upg = (4 => 53263, 9 => 53298, 10 => 53305, 16 => 53347);
    quest::summonitem($upg{$class});
    quest::say("The powersource has taken hold. Your Sleeves is now far greater than before!");
    plugin::return_items(\%itemcount);
    return;
  }
  my %b_chain_leggings = (4 => 53798, 9 => 53833, 10 => 53840, 16 => 53882);
  if (plugin::check_handin(\%itemcount, 32846 => 1, $b_chain_leggings{$class} => 1)) {
    my %upg = (4 => 53268, 9 => 53303, 10 => 53310, 16 => 53352);
    quest::summonitem($upg{$class});
    quest::say("The powersource has taken hold. Your Leggings is now far greater than before!");
    plugin::return_items(\%itemcount);
    return;
  }
  my %b_chain_coif = (4 => 53792, 9 => 53827, 10 => 53834, 16 => 53876);
  if (plugin::check_handin(\%itemcount, 32846 => 1, $b_chain_coif{$class} => 1)) {
    my %upg = (4 => 53262, 9 => 53297, 10 => 53304, 16 => 53346);
    quest::summonitem($upg{$class});
    quest::say("The powersource has taken hold. Your Coif is now far greater than before!");
    plugin::return_items(\%itemcount);
    return;
  }
  my %b_chain_gauntlets = (4 => 53795, 9 => 53830, 10 => 53837, 16 => 53879);
  if (plugin::check_handin(\%itemcount, 32846 => 1, $b_chain_gauntlets{$class} => 1)) {
    my %upg = (4 => 53265, 9 => 53300, 10 => 53307, 16 => 53349);
    quest::summonitem($upg{$class});
    quest::say("The powersource has taken hold. Your Gauntlets is now far greater than before!");
    plugin::return_items(\%itemcount);
    return;
  }
  my %b_chain_boots = (4 => 53796, 9 => 53831, 10 => 53838, 16 => 53880);
  if (plugin::check_handin(\%itemcount, 32846 => 1, $b_chain_boots{$class} => 1)) {
    my %upg = (4 => 53266, 9 => 53301, 10 => 53308, 16 => 53350);
    quest::summonitem($upg{$class});
    quest::say("The powersource has taken hold. Your Boots is now far greater than before!");
    plugin::return_items(\%itemcount);
    return;
  }
  my %b_chain_wristguard = (4 => 53794, 9 => 53829, 10 => 53836, 16 => 53878);
  if (plugin::check_handin(\%itemcount, 32846 => 1, $b_chain_wristguard{$class} => 1)) {
    my %upg = (4 => 53264, 9 => 53299, 10 => 53306, 16 => 53348);
    quest::summonitem($upg{$class});
    quest::say("The powersource has taken hold. Your Wristguard is now far greater than before!");
    plugin::return_items(\%itemcount);
    return;
  }

  # ================= LEATHER =================
  # --- Leather Part 1 ---
  if (plugin::check_handin(\%itemcount, 51874 => 4, 51492 => 1)) {
    my %reward = (6 => 53811, 7 => 53818, 15 => 53874);
    quest::summonitem($reward{$class});
    quest::say("My theory was correct! Here is your Tunic. Return it with the right powersource and I can empower it further.");
    plugin::return_items(\%itemcount);
    return;
  }
  if (plugin::check_handin(\%itemcount, 51874 => 3, 51979 => 1)) {
    my %reward = (6 => 53807, 7 => 53814, 15 => 53870);
    quest::summonitem($reward{$class});
    quest::say("My theory was correct! Here is your Armwraps. Return it with the right powersource and I can empower it further.");
    plugin::return_items(\%itemcount);
    return;
  }
  if (plugin::check_handin(\%itemcount, 51983 => 4, 51481 => 1)) {
    my %reward = (6 => 53812, 7 => 53819, 15 => 53875);
    quest::summonitem($reward{$class});
    quest::say("My theory was correct! Here is your Leggings. Return it with the right powersource and I can empower it further.");
    plugin::return_items(\%itemcount);
    return;
  }
  if (plugin::check_handin(\%itemcount, 51983 => 3, 52462 => 1)) {
    my %reward = (6 => 53806, 7 => 53813, 15 => 53869);
    quest::summonitem($reward{$class});
    quest::say("My theory was correct! Here is your Cowl. Return it with the right powersource and I can empower it further.");
    plugin::return_items(\%itemcount);
    return;
  }
  if (plugin::check_handin(\%itemcount, 51983 => 2, 51934 => 1)) {
    my %reward = (6 => 53809, 7 => 53816, 15 => 53872);
    quest::summonitem($reward{$class});
    quest::say("My theory was correct! Here is your Gloves. Return it with the right powersource and I can empower it further.");
    plugin::return_items(\%itemcount);
    return;
  }
  if (plugin::check_handin(\%itemcount, 51874 => 2, 51478 => 1)) {
    my %reward = (6 => 53810, 7 => 53817, 15 => 53873);
    quest::summonitem($reward{$class});
    quest::say("My theory was correct! Here is your Boots. Return it with the right powersource and I can empower it further.");
    plugin::return_items(\%itemcount);
    return;
  }
  if (plugin::check_handin(\%itemcount, 51983 => 1, 52154 => 1)) {
    my %reward = (6 => 53808, 7 => 53815, 15 => 53871);
    quest::summonitem($reward{$class});
    quest::say("My theory was correct! Here is your Wristguard. Return it with the right powersource and I can empower it further.");
    plugin::return_items(\%itemcount);
    return;
  }
  # --- Leather Part 2 ---
  my %b_leather_tunic = (6 => 53811, 7 => 53818, 15 => 53874);
  if (plugin::check_handin(\%itemcount, 32848 => 1, $b_leather_tunic{$class} => 1)) {
    my %upg = (6 => 53281, 7 => 53288, 15 => 53344);
    quest::summonitem($upg{$class});
    quest::say("The powersource has taken hold. Your Tunic is now far greater than before!");
    plugin::return_items(\%itemcount);
    return;
  }
  my %b_leather_armwraps = (6 => 53807, 7 => 53814, 15 => 53870);
  if (plugin::check_handin(\%itemcount, 32848 => 1, $b_leather_armwraps{$class} => 1)) {
    my %upg = (6 => 53277, 7 => 53284, 15 => 53340);
    quest::summonitem($upg{$class});
    quest::say("The powersource has taken hold. Your Armwraps is now far greater than before!");
    plugin::return_items(\%itemcount);
    return;
  }
  my %b_leather_leggings = (6 => 53812, 7 => 53819, 15 => 53875);
  if (plugin::check_handin(\%itemcount, 32848 => 1, $b_leather_leggings{$class} => 1)) {
    my %upg = (6 => 53282, 7 => 53289, 15 => 53345);
    quest::summonitem($upg{$class});
    quest::say("The powersource has taken hold. Your Leggings is now far greater than before!");
    plugin::return_items(\%itemcount);
    return;
  }
  my %b_leather_cowl = (6 => 53806, 7 => 53813, 15 => 53869);
  if (plugin::check_handin(\%itemcount, 32848 => 1, $b_leather_cowl{$class} => 1)) {
    my %upg = (6 => 53276, 7 => 53283, 15 => 53339);
    quest::summonitem($upg{$class});
    quest::say("The powersource has taken hold. Your Cowl is now far greater than before!");
    plugin::return_items(\%itemcount);
    return;
  }
  my %b_leather_gloves = (6 => 53809, 7 => 53816, 15 => 53872);
  if (plugin::check_handin(\%itemcount, 32848 => 1, $b_leather_gloves{$class} => 1)) {
    my %upg = (6 => 53279, 7 => 53286, 15 => 53342);
    quest::summonitem($upg{$class});
    quest::say("The powersource has taken hold. Your Gloves is now far greater than before!");
    plugin::return_items(\%itemcount);
    return;
  }
  my %b_leather_boots = (6 => 53810, 7 => 53817, 15 => 53873);
  if (plugin::check_handin(\%itemcount, 32848 => 1, $b_leather_boots{$class} => 1)) {
    my %upg = (6 => 53280, 7 => 53287, 15 => 53343);
    quest::summonitem($upg{$class});
    quest::say("The powersource has taken hold. Your Boots is now far greater than before!");
    plugin::return_items(\%itemcount);
    return;
  }
  my %b_leather_wristguard = (6 => 53808, 7 => 53815, 15 => 53871);
  if (plugin::check_handin(\%itemcount, 32848 => 1, $b_leather_wristguard{$class} => 1)) {
    my %upg = (6 => 53278, 7 => 53285, 15 => 53341);
    quest::summonitem($upg{$class});
    quest::say("The powersource has taken hold. Your Wristguard is now far greater than before!");
    plugin::return_items(\%itemcount);
    return;
  }

  # ================= SILK =================
  # --- Silk Part 1 ---
  if (plugin::check_handin(\%itemcount, 51518 => 4, 51484 => 1)) {
    my %reward = (11 => 53846, 12 => 53853, 13 => 53860, 14 => 53867);
    quest::summonitem($reward{$class});
    quest::say("My theory was correct! Here is your Robe. Return it with the right powersource and I can empower it further.");
    plugin::return_items(\%itemcount);
    return;
  }
  if (plugin::check_handin(\%itemcount, 51518 => 3, 51485 => 1)) {
    my %reward = (11 => 53842, 12 => 53849, 13 => 53856, 14 => 53863);
    quest::summonitem($reward{$class});
    quest::say("My theory was correct! Here is your Sleeves. Return it with the right powersource and I can empower it further.");
    plugin::return_items(\%itemcount);
    return;
  }
  if (plugin::check_handin(\%itemcount, 51520 => 4, 51489 => 1)) {
    my %reward = (11 => 53847, 12 => 53854, 13 => 53861, 14 => 53868);
    quest::summonitem($reward{$class});
    quest::say("My theory was correct! Here is your Pants. Return it with the right powersource and I can empower it further.");
    plugin::return_items(\%itemcount);
    return;
  }
  if (plugin::check_handin(\%itemcount, 51520 => 3, 51490 => 1)) {
    my %reward = (11 => 53841, 12 => 53848, 13 => 53855, 14 => 53862);
    quest::summonitem($reward{$class});
    quest::say("My theory was correct! Here is your Cap. Return it with the right powersource and I can empower it further.");
    plugin::return_items(\%itemcount);
    return;
  }
  if (plugin::check_handin(\%itemcount, 51520 => 2, 51488 => 1)) {
    my %reward = (11 => 53844, 12 => 53851, 13 => 53858, 14 => 53865);
    quest::summonitem($reward{$class});
    quest::say("My theory was correct! Here is your Gloves. Return it with the right powersource and I can empower it further.");
    plugin::return_items(\%itemcount);
    return;
  }
  if (plugin::check_handin(\%itemcount, 51518 => 2, 51486 => 1)) {
    my %reward = (11 => 53845, 12 => 53852, 13 => 53859, 14 => 53866);
    quest::summonitem($reward{$class});
    quest::say("My theory was correct! Here is your Sandals. Return it with the right powersource and I can empower it further.");
    plugin::return_items(\%itemcount);
    return;
  }
  if (plugin::check_handin(\%itemcount, 51520 => 1, 51487 => 1)) {
    my %reward = (11 => 53843, 12 => 53850, 13 => 53857, 14 => 53864);
    quest::summonitem($reward{$class});
    quest::say("My theory was correct! Here is your Wristband. Return it with the right powersource and I can empower it further.");
    plugin::return_items(\%itemcount);
    return;
  }
  # --- Silk Part 2 ---
  my %b_silk_robe = (11 => 53846, 12 => 53853, 13 => 53860, 14 => 53867);
  if (plugin::check_handin(\%itemcount, 32849 => 1, $b_silk_robe{$class} => 1)) {
    my %upg = (11 => 53316, 12 => 53323, 13 => 53330, 14 => 53337);
    quest::summonitem($upg{$class});
    quest::say("The powersource has taken hold. Your Robe is now far greater than before!");
    plugin::return_items(\%itemcount);
    return;
  }
  my %b_silk_sleeves = (11 => 53842, 12 => 53849, 13 => 53856, 14 => 53863);
  if (plugin::check_handin(\%itemcount, 32849 => 1, $b_silk_sleeves{$class} => 1)) {
    my %upg = (11 => 53312, 12 => 53319, 13 => 53326, 14 => 53333);
    quest::summonitem($upg{$class});
    quest::say("The powersource has taken hold. Your Sleeves is now far greater than before!");
    plugin::return_items(\%itemcount);
    return;
  }
  my %b_silk_pants = (11 => 53847, 12 => 53854, 13 => 53861, 14 => 53868);
  if (plugin::check_handin(\%itemcount, 32849 => 1, $b_silk_pants{$class} => 1)) {
    my %upg = (11 => 53317, 12 => 53324, 13 => 53331, 14 => 53338);
    quest::summonitem($upg{$class});
    quest::say("The powersource has taken hold. Your Pants is now far greater than before!");
    plugin::return_items(\%itemcount);
    return;
  }
  my %b_silk_cap = (11 => 53841, 12 => 53848, 13 => 53855, 14 => 53862);
  if (plugin::check_handin(\%itemcount, 32849 => 1, $b_silk_cap{$class} => 1)) {
    my %upg = (11 => 53311, 12 => 53318, 13 => 53325, 14 => 53332);
    quest::summonitem($upg{$class});
    quest::say("The powersource has taken hold. Your Cap is now far greater than before!");
    plugin::return_items(\%itemcount);
    return;
  }
  my %b_silk_gloves = (11 => 53844, 12 => 53851, 13 => 53858, 14 => 53865);
  if (plugin::check_handin(\%itemcount, 32849 => 1, $b_silk_gloves{$class} => 1)) {
    my %upg = (11 => 53314, 12 => 53321, 13 => 53328, 14 => 53335);
    quest::summonitem($upg{$class});
    quest::say("The powersource has taken hold. Your Gloves is now far greater than before!");
    plugin::return_items(\%itemcount);
    return;
  }
  my %b_silk_sandals = (11 => 53845, 12 => 53852, 13 => 53859, 14 => 53866);
  if (plugin::check_handin(\%itemcount, 32849 => 1, $b_silk_sandals{$class} => 1)) {
    my %upg = (11 => 53315, 12 => 53322, 13 => 53329, 14 => 53336);
    quest::summonitem($upg{$class});
    quest::say("The powersource has taken hold. Your Sandals is now far greater than before!");
    plugin::return_items(\%itemcount);
    return;
  }
  my %b_silk_wristband = (11 => 53843, 12 => 53850, 13 => 53857, 14 => 53864);
  if (plugin::check_handin(\%itemcount, 32849 => 1, $b_silk_wristband{$class} => 1)) {
    my %upg = (11 => 53313, 12 => 53320, 13 => 53327, 14 => 53334);
    quest::summonitem($upg{$class});
    quest::say("The powersource has taken hold. Your Wristband is now far greater than before!");
    plugin::return_items(\%itemcount);
    return;
  }

  plugin::return_items(\%itemcount);
}
