#--------------------------------------------------------------------------
# TBS Solteris Access arc - Associate Researcher Plik (416011)
# Auto-generated by tbs_content/gen_elnot_plik.py.
# Endpoint of task #0 "A City in Peril".
#--------------------------------------------------------------------------
sub EVENT_SAY {
  if ($text=~/hail/i) {
    if (quest::istaskcompleted(620050)) {
      quest::say("Good to see you again, $name. The sphinx studies continue - Elnot will know where you are needed next.");
    } elsif (quest::istaskactive(620050)) {
      quest::say("Ahh, so Prime Researcher Elnot sent you to speak with the sphinx about our [problem], yes? Then you have done what he asked - return to him and tell him what we discussed.");
    } else {
      quest::say("The Prime Researcher has theories enough for all of us. Speak with him if you wish to [help] the city.");
    }
  }
  if ($text=~/problem|help/i) {
    quest::say("The Pellarus Satum dims and the protective domes weaken with it. If you wish to serve, Elnot will point your feet.");
  }
}

sub EVENT_ITEM {
  plugin::return_items(\%itemcount);
}

