#--------------------------------------------------------------------------
# TBS Solteris Access arc - Prime Researcher Elnot Waymun (416006)
# Auto-generated by tbs_content/gen_elnot_plik.py.
# Hands out the Combine Signet Ring and offers the arc's tasks in order.
# Group missions are Shared tasks (tasks.type = 1) that create an instanced
# dynamic zone from dynamic_zone_templates 6101-6108; say "enter" while one is
# active to be moved into your instance. A single player may request.
#--------------------------------------------------------------------------
my @arc = (620050, 620051, 620052, 620053, 620054, 620055, 620056, 620057, 620058, 620059, 620060, 620061, 620062, 620063);

# mission task -> [zone_id, zone_version] matching dynamic_zone_templates
my %dz = (
    620051 => [418, 0],
    620053 => [417, 0],
    620056 => [419, 0],
    620057 => [419, 0],
    620059 => [419, 0],
    620062 => [420, 0],
    620063 => [420, 0],
);

my %titles = (
    620050 => 'speak with Associate Researcher Plik',
    620051 => 'mission: Knowledge for Power (Jewel of Atiiki)',
    620052 => 'report to Associate Researcher Maladoks',
    620053 => 'mission: Locating the Statue (Barren Coast)',
    620054 => 'deliver the rubbing to Head Mage Antius',
    620055 => 'return to Elnot Waymun',
    620056 => 'mission: Snakes Hiding Something (Zhisza)',
    620057 => 'mission: Counter-Attack (Zhisza)',
    620058 => 'return to Elnot Waymun',
    620059 => 'mission: Confront Emperor Vaakiszh (Zhisza)',
    620060 => 'make contact with Vizier Zio',
    620061 => 'mission: Where There\'s a Will (Silyssar)',
    620062 => 'mission: Slay the Serpent (Silyssar)',
    620063 => 'mission: Stop the Ritual (Silyssar)',
);

sub EVENT_SAY {
  my $done = 0;
  for my $t (@arc) { $done++ if quest::istaskcompleted($t); }

  if ($text=~/guidance/i) {
    if ($done >= scalar(@arc)) {
      quest::say("You have done it, $name. The way to Solteris stands open. Speak with me no more - go and finish this.");
    } elsif ($done == 0) {
      quest::say("Speak with me of the [grave peril] and we shall begin.");
    } else {
      my $next = $arc[$done];
      quest::say("Your next step: " . ($titles{$next} || "return to me") . ".");
    }
    return;
  }

  if ($text=~/pursue|grave peril|dark times|weaker|failing|work|task/i) {
    if ($done >= scalar(@arc)) {
      quest::say("It is finished, $name. Solteris awaits.");
      return;
    }
    if ($done == 0 && !quest::istaskactive($arc[0])) {
      quest::say("No one knows why the Pellarus Satum is failing, but we would not be the Combine if we did not have at least two theories being pursued! Our current location is due to a... misunderstanding we had with Prexus. Some believe Prexus himself has returned to finish his work. My own theory is less refined: the Sphinx may hold the answer. That is the tack I wish to [pursue]. Take this ring - wear it always; it will record your service to the city.");
      quest::summonitem(79901);
      quest::assigntask($arc[0]);
      return;
    }
    my $next = -1;
    for my $i (0 .. $#arc) {
      if (!quest::istaskcompleted($arc[$i])) { $next = $i; last; }
    }
    if ($next >= 0) {
      my $tid = $arc[$next];
      if (quest::istaskactive($tid)) {
        quest::say("You are already at work, $name - " . ($titles{$tid} || "see it done") . ". Return when it is finished.");
      } else {
        quest::say("Well done so far, $name. The next matter: " . ($titles{$tid} || "see me") . ". Go with my thanks.");
        quest::assigntask($tid);
      }
    }
    return;
  }

  if ($text=~/enter|instance|mission/i) {
    for my $t (@arc) {
      next if !$dz{$t};
      if (quest::istaskactive($t)) {
        quest::say("The way is open, $name. Step through - and take your companions with you.");
        $client->MovePCDynamicZone($dz{$t}[0], $dz{$t}[1]);
        return;
      }
    }
    quest::say("You have no mission of mine to enter, $name. Ask me of the [dark times] to begin.");
    return;
  }

  if ($text=~/solteris|throne of ro/i) {
    if ($done >= scalar(@arc)) {
      quest::say("The Throne of Ro stands open, $name. Gather your raid and go.");
      $client->CreateExpeditionFromTemplate(6109);
      $client->MovePCDynamicZone(421, 0);
    } else {
      quest::say("Solteris is not yet open to you, $name. Finish the work I have given you.");
    }
    return;
  }

  if ($text=~/hail/i) {
    quest::say("Good day to you, $name. Or as good as it can be in these [dark times]. If you have lost your way and need [guidance], let me know.");
  }
}

sub EVENT_ITEM {
  plugin::return_items(\%itemcount);
}

