#-----------------------------------------------------------------------------
# TBS Buried Sea island missions - Logan Grimm
# npc_types id 423107 (#Logan_Grimm)
# Auto-generated by tbs_content/gen_jonas_givers.py from scraped Allakhazam dialogs.
# Offers tasks in order; each task is non-repeatable.
#-----------------------------------------------------------------------------

my %chains = (
    620024 =>
        [
         "Yar! Are ye looking fer some " . quest::saylink("errands") . " to undertake?  There are some things that need doin', and you might be able to do them.  Though I doubt you'd be able to pass as any sort of Blacksail!  You don't look like you could hold up to a light rain on the sea.  But mayhap ye can handle yerself against Sharpeye's worthless scabs.",
         ["What errands?", "There ye be, $name."],
        ],
    620025 =>
        [
         "Yar! Are ye looking fer some " . quest::saylink("errands") . " to undertake?  There are some things that need doin', and you might be able to do them.  Though I doubt you'd be able to pass as any sort of Blacksail!  You don't look like you could hold up to a light rain on the sea.  But mayhap ye can handle yerself against Sharpeye's worthless scabs.",
         ["What errands?", "There ye be, $name."],
        ],
    620026 =>
        [
         "Yar! Are ye looking fer some " . quest::saylink("errands") . " to undertake?  There are some things that need doin', and you might be able to do them.  Though I doubt you'd be able to pass as any sort of Blacksail!  You don't look like you could hold up to a light rain on the sea.  But mayhap ye can handle yerself against Sharpeye's worthless scabs.",
         ["What errands?", "There ye be, $name."],
        ],
    620027 =>
        [
         "Yar! Are ye looking fer some " . quest::saylink("errands") . " to undertake?  There are some things that need doin', and you might be able to do them.  Though I doubt you'd be able to pass as any sort of Blacksail!  You don't look like you could hold up to a light rain on the sea.  But mayhap ye can handle yerself against Sharpeye's worthless scabs.",
         ["What errands?", "There ye be, $name."],
        ],
    620028 =>
        [
         "Yar! Are ye looking fer some " . quest::saylink("errands") . " to undertake?  There are some things that need doin', and you might be able to do them.  Though I doubt you'd be able to pass as any sort of Blacksail!  You don't look like you could hold up to a light rain on the sea.  But mayhap ye can handle yerself against Sharpeye's worthless scabs.",
         ["What errands?", "There ye be, $name."],
        ],
);

my @mytasks = (620024, 620025, 620026, 620027, 620028);

sub EVENT_SAY {
  # first task of mine the player has not completed
  my $next = -1;
  for my $i (0 .. $#mytasks) {
    if (!quest::istaskcompleted($mytasks[$i])) { $next = $i; last; }
  }
  if ($next < 0) {
    if ($text=~/hail/i) {
      quest::say("You have done more than enough for me, $name. The sea itself owes you a debt now.");
    }
    return;
  }
  my $tid = $mytasks[$next];
  if (quest::istaskactive($tid)) {
    if ($text=~/hail/i) {
      quest::say("Get a move on, $name! The work will not do itself.");
    }
    return;
  }
  my $chain = $chains{$tid};
  return if !$chain;
  my $hail = $chain->[0];
  my @hops = @{$chain}[1 .. $#$chain];

  if ($text=~/hail/i) {
    quest::say($hail);
    return;
  }

  # find which hop the player triggered
  my $hit = -1;
  for my $i (0 .. $#hops) {
    if ($text=~/\Q$hops[$i][0]\E/i) { $hit = $i; last; }
  }
  return if $hit < 0;
  quest::say($hops[$hit][1]);
  # the final hop hands out the work
  if ($hit == $#hops) {
    quest::assigntask($tid);
  }
}

sub EVENT_ITEM {
  # deliver steps of the island tasks are task-deliveries;
  # anything else handed to us is returned.
  plugin::return_items(\%itemcount);
}
