#-----------------------------------------------------------------------------
# TBS Buried Sea island missions - Bilgewater Bill
# npc_types id 423079 (Bilgewater_Bill)
# Auto-generated by tbs_content/gen_jonas_givers.py from scraped Allakhazam dialogs.
# Offers tasks in order; each task is non-repeatable.
#-----------------------------------------------------------------------------

my %chains = (
    620010 =>
        [
         "Well, hail yerself.  What brings you to this little spot of heaven?  From the look of you, yer not here because you were recruited, like I was.  In fact, you must be a fool to be here at all, especially if you're here by your own choosing.  Me, I'm here because I'm stupid.  I allowed myself to pass out drinking in a dockside bar.  That's stupid.  But coming here?  Amazingly stupid, if you ask me.  Of course you didn't, so I don't know why I'm still talking to you.  I have " . quest::saylink("work") . " to do.",
         ["What work?", "Hah!  Well, I call it work.  You might call it torture.  Why, I don't think someone like you could do what I do every day.  There's no glory in it and there's little enough pay.  But then, I can't spend my pay on anything.  I started by saving my 'pay' hoping that I could buy my way out of this job.  I was an idiot then, I know better now.  In fact, I think I know how I want to spend my money on now.  I'll pay you if you'll " . quest::saylink("do some") . " of my work for me.  Heck, that would be like a vacation for me."],
         ["I", "This will be fun to watch."],
        ],
);

my @mytasks = (620010);

sub EVENT_SAY {
  # first task of mine the player has not completed
  my $next = -1;
  for my $i (0 .. $#mytasks) {
    if (!quest::istaskcompleted($mytasks[$i])) { $next = $i; last; }
  }
  if ($next < 0) {
    if ($text=~/hail/i) {
      quest::say("You have done more than enough for me, $name. The sea itself owes you a debt now.");
    }
    return;
  }
  my $tid = $mytasks[$next];
  if (quest::istaskactive($tid)) {
    if ($text=~/hail/i) {
      quest::say("Back again? Take another bucket and get to it!");
      quest::summonitem(88244);
    }
    return;
  }
  my $chain = $chains{$tid};
  return if !$chain;
  my $hail = $chain->[0];
  my @hops = @{$chain}[1 .. $#$chain];

  if ($text=~/hail/i) {
    quest::say($hail);
    return;
  }

  # find which hop the player triggered
  my $hit = -1;
  for my $i (0 .. $#hops) {
    if ($text=~/\Q$hops[$i][0]\E/i) { $hit = $i; last; }
  }
  return if $hit < 0;
  quest::say($hops[$hit][1]);
  # the final hop hands out the work
  if ($hit == $#hops) {
    quest::assigntask($tid);
  }
}

sub EVENT_ITEM {
  # deliver steps of the island tasks are task-deliveries;
  # anything else handed to us is returned.
  plugin::return_items(\%itemcount);
}
