#-----------------------------------------------------------------------------
# TBS Buried Sea island missions - Captain Pete
# npc_types id 423152 (Captain_Pete)
# Auto-generated by tbs_content/gen_jonas_givers.py from scraped Allakhazam dialogs.
# Offers tasks in order; each task is non-repeatable.
#-----------------------------------------------------------------------------

my %chains = (
    620040 =>
        [
         "Ah $name! I'd heard ye were on this island. Surprised I've heard of ye, eh? In my business it pays to be informed. Well, it used to anyways. Ye see ever since the " . quest::saylink("wreck") . " I've been a bit on the outs with people round here.",
         ["What wreck?", "We was sailin over near the island called Maiden's Grave ye see. There be sirens on that island that got the better o' me and me crew. Most of the crew died when the Wretched Sands went down, but me and a few others managed to make it to shore. If'n ye thought the sirens were bad while ye were on a ship its nothing as to how bad they are if ye set foot on their island. I was the only one to make it offa there alive. And that's what got me inta me present problem. The way I sees it there be only one " . quest::saylink("thing") . " fer me to do."],
         ["What thing?", "Well, there might be " . quest::saylink("two") . ", but I figures I needs to bring the remains of me crew back to their families. If they see I care about me crew, might'n be possible fer me to assemble a new one. Problem is I ain't going back to that island unless I'm dead meself. This is where you come in, if'n ye catch me " . quest::saylink("drift") . "."],
         ["I catch your drift", "Good man! I'll be here when you find their remains. There's no telling what happened to their corpses so ye'll have to search most of the island more than likely. Best of luck to ye me hearty!"],
        ],
    620041 =>
        [
         "Ah $name! I'd heard ye were on this island. Surprised I've heard of ye, eh? In my business it pays to be informed. Well, it used to anyways. Ye see ever since the " . quest::saylink("wreck") . " I've been a bit on the outs with people round here.",
         ["What wreck?", "We was sailin over near the island called Maiden's Grave ye see. There be sirens on that island that got the better o' me and me crew. Most of the crew died when the Wretched Sands went down, but me and a few others managed to make it to shore. If'n ye thought the sirens were bad while ye were on a ship its nothing as to how bad they are if ye set foot on their island. I was the only one to make it offa there alive. And that's what got me inta me present problem. The way I sees it there be only one " . quest::saylink("thing") . " fer me to do."],
         ["What thing?", "Well, there might be " . quest::saylink("two") . ", but I figures I needs to bring the remains of me crew back to their families. If they see I care about me crew, might'n be possible fer me to assemble a new one. Problem is I ain't going back to that island unless I'm dead meself. This is where you come in, if'n ye catch me " . quest::saylink("drift") . "."],
         ["Two?", "It might not get me back in good with the rest of the scallywags round here, but might help any other poor sot who lands on that forsaken chunk of rock. The reason none of the other mates from me ship made it out is we got ourselves lost. If'n we'd had a map of the island we'd have made it out with many more of the crew. If'n yer " . quest::saylink("willing") . ", I'd like ye to go back there fer me and map out the place."],
         ["I am willing", "Ah yer a grand one ye are. Once ye get back I'll get all the captains round these parts a copy of it and we'll see if we can't get the better of those sirens."],
        ],
);

my @mytasks = (620040, 620041);

sub EVENT_SAY {
  # first task of mine the player has not completed
  my $next = -1;
  for my $i (0 .. $#mytasks) {
    if (!quest::istaskcompleted($mytasks[$i])) { $next = $i; last; }
  }
  if ($next < 0) {
    if ($text=~/hail/i) {
      quest::say("You have done more than enough for me, $name. The sea itself owes you a debt now.");
    }
    return;
  }
  my $tid = $mytasks[$next];
  if (quest::istaskactive($tid)) {
    if ($text=~/hail/i) {
      quest::say("Get a move on, $name! The work will not do itself.");
    }
    return;
  }
  my $chain = $chains{$tid};
  return if !$chain;
  my $hail = $chain->[0];
  my @hops = @{$chain}[1 .. $#$chain];

  if ($text=~/hail/i) {
    quest::say($hail);
    return;
  }

  # find which hop the player triggered
  my $hit = -1;
  for my $i (0 .. $#hops) {
    if ($text=~/\Q$hops[$i][0]\E/i) { $hit = $i; last; }
  }
  return if $hit < 0;
  quest::say($hops[$hit][1]);
  # the final hop hands out the work
  if ($hit == $#hops) {
    quest::assigntask($tid);
  }
}

sub EVENT_ITEM {
  # deliver steps of the island tasks are task-deliveries;
  # anything else handed to us is returned.
  plugin::return_items(\%itemcount);
}
