#-----------------------------------------------------------------------------
# TBS Buried Sea island missions - Murderous Mal
# npc_types id 423091 (Murderous_Mal)
# Auto-generated by tbs_content/gen_jonas_givers.py from scraped Allakhazam dialogs.
# Offers tasks in order; each task is non-repeatable.
#-----------------------------------------------------------------------------

my %chains = (
    620012 =>
        [
         "Hello.  I'm Mal.  Welcome to my place of business, friend.  Now, I don't know that I can sell you any of my products.  You see I'm really only allowed to sell to my brothers of the Blacksail.  But I suppose if you're discrete then I might have a thing or two of interest to you.  At the same time you might have " . quest::saylink("some things") . " of use to me as well.",
         ["Some things?", "Well, not things, exactly, more like skills.  Ya see I have a lot of trouble with the locals here, my sworn brothers and sisters.  I'm not exactly the most dangerous pirate to ever join the Blacksail.  Never you mind the name they've given me, they did that to tease me.  Pirates aren't known for their overwhelming respect for others, you know. But I know how to run a business and they need me for some things.  Maybe you can help me with " . quest::saylink("some tasks") . " that I can't do on my own right now, I have to stay here and watch over my goods."],
         ["Some tasks?", "Ay, I have a few things that need doing."],
        ],
    620013 =>
        [
         "Hello.  I'm Mal.  Welcome to my place of business, friend.  Now, I don't know that I can sell you any of my products.  You see I'm really only allowed to sell to my brothers of the Blacksail.  But I suppose if you're discrete then I might have a thing or two of interest to you.  At the same time you might have " . quest::saylink("some things") . " of use to me as well.",
         ["Some things?", "Well, not things, exactly, more like skills.  Ya see I have a lot of trouble with the locals here, my sworn brothers and sisters.  I'm not exactly the most dangerous pirate to ever join the Blacksail.  Never you mind the name they've given me, they did that to tease me.  Pirates aren't known for their overwhelming respect for others, you know. But I know how to run a business and they need me for some things.  Maybe you can help me with " . quest::saylink("some tasks") . " that I can't do on my own right now, I have to stay here and watch over my goods."],
         ["Some tasks?", "Ay, I have a few things that need doing."],
        ],
    620014 =>
        [
         "Hello.  I'm Mal.  Welcome to my place of business, friend.  Now, I don't know that I can sell you any of my products.  You see I'm really only allowed to sell to my brothers of the Blacksail.  But I suppose if you're discrete then I might have a thing or two of interest to you.  At the same time you might have " . quest::saylink("some things") . " of use to me as well.",
         ["Some things?", "Well, not things, exactly, more like skills.  Ya see I have a lot of trouble with the locals here, my sworn brothers and sisters.  I'm not exactly the most dangerous pirate to ever join the Blacksail.  Never you mind the name they've given me, they did that to tease me.  Pirates aren't known for their overwhelming respect for others, you know. But I know how to run a business and they need me for some things.  Maybe you can help me with " . quest::saylink("some tasks") . " that I can't do on my own right now, I have to stay here and watch over my goods."],
         ["Some tasks?", "Ay, I have a few things that need doing."],
        ],
);

my @mytasks = (620012, 620013, 620014);

sub EVENT_SAY {
  # first task of mine the player has not completed
  my $next = -1;
  for my $i (0 .. $#mytasks) {
    if (!quest::istaskcompleted($mytasks[$i])) { $next = $i; last; }
  }
  if ($next < 0) {
    if ($text=~/hail/i) {
      quest::say("You have done more than enough for me, $name. The sea itself owes you a debt now.");
    }
    return;
  }
  my $tid = $mytasks[$next];
  if (quest::istaskactive($tid)) {
    if ($text=~/hail/i) {
      quest::say("Get a move on, $name! The work will not do itself.");
    }
    return;
  }
  my $chain = $chains{$tid};
  return if !$chain;
  my $hail = $chain->[0];
  my @hops = @{$chain}[1 .. $#$chain];

  if ($text=~/hail/i) {
    quest::say($hail);
    return;
  }

  # find which hop the player triggered
  my $hit = -1;
  for my $i (0 .. $#hops) {
    if ($text=~/\Q$hops[$i][0]\E/i) { $hit = $i; last; }
  }
  return if $hit < 0;
  quest::say($hops[$hit][1]);
  # the final hop hands out the work
  if ($hit == $#hops) {
    quest::assigntask($tid);
  }
}

sub EVENT_ITEM {
  # deliver steps of the island tasks are task-deliveries;
  # anything else handed to us is returned.
  plugin::return_items(\%itemcount);
}
