#-----------------------------------------------------------------------------
# TBS Buried Sea island missions - Pirate Symthe
# npc_types id 423900 (None)
# Auto-generated by tbs_content/gen_jonas_givers.py from scraped Allakhazam dialogs.
# Offers tasks in order; each task is non-repeatable.
#-----------------------------------------------------------------------------

my %chains = (
    620039 =>
        [
         "You there! You will help me finish my " . quest::saylink("maps") . ", or me sword will be finding yer gullet!",
         ["I", "Aye, ye scurvy-riddled landlubber! There be one thing a pirate o' quality like meself needs more than all else -- maps of the sea. Ye can't be expected to get anywhere if yer not knowin' where the reefs be now can ye? Now, I've got me a start on the charts o' this area but there be " . quest::saylink("more") . " I'm needin'."],
         ["What more?", "More? Ye daft grog-snarfin' swine! Didn't I just say me maps weren't complete? I need ye to fetch me the maps o' other ships for me. Blimey! I can tell I be needin' ta lay things out step by bloody step for ye. Ye see there's this island called " . quest::saylink("Maiden's Grave") . ", 'member?"],
         ["Maiden", "Har har, ye lily-livered swine!  That island be lived on by them scrappy sirens, aye. More than a few swabbies been lost to the barnacled rocks on that isle. That why she be called the Maiden's Grave! Them no-good buckos hear that sweet siren song and forget the only lady that means a thing. That's right, their ship! Blimey! No real sailor would forget! Now listen up ye pox-faced rat -- them lost ships no longer need of their charts, aye? I want ye to buck up and " . quest::saylink("retrieve") . " 'em for me."],
         ["I will retrieve ", "Aye yer darn right yer off to retrieve 'em for me. Now get yer lazy, rotten bones outta me sight and check the waters 'round that island!"],
        ],
);

my @mytasks = (620039);

sub EVENT_SAY {
  # first task of mine the player has not completed
  my $next = -1;
  for my $i (0 .. $#mytasks) {
    if (!quest::istaskcompleted($mytasks[$i])) { $next = $i; last; }
  }
  if ($next < 0) {
    if ($text=~/hail/i) {
      quest::say("You have done more than enough for me, $name. The sea itself owes you a debt now.");
    }
    return;
  }
  my $tid = $mytasks[$next];
  if (quest::istaskactive($tid)) {
    if ($text=~/hail/i) {
      quest::say("Get a move on, $name! The work will not do itself.");
    }
    return;
  }
  my $chain = $chains{$tid};
  return if !$chain;
  my $hail = $chain->[0];
  my @hops = @{$chain}[1 .. $#$chain];

  if ($text=~/hail/i) {
    quest::say($hail);
    return;
  }

  # find which hop the player triggered
  my $hit = -1;
  for my $i (0 .. $#hops) {
    if ($text=~/\Q$hops[$i][0]\E/i) { $hit = $i; last; }
  }
  return if $hit < 0;
  quest::say($hops[$hit][1]);
  # the final hop hands out the work
  if ($hit == $#hops) {
    quest::assigntask($tid);
  }
}

sub EVENT_ITEM {
  # deliver steps of the island tasks are task-deliveries;
  # anything else handed to us is returned.
  plugin::return_items(\%itemcount);
}
