#-----------------------------------------------------------------------------
# TBS Buried Sea island missions - Rickan
# npc_types id 423146 (Rickan)
# Auto-generated by tbs_content/gen_jonas_givers.py from scraped Allakhazam dialogs.
# Offers tasks in order; each task is non-repeatable.
#-----------------------------------------------------------------------------

my %chains = (
    620019 =>
        [
         "Have you any idea, any concept of who you're speaking to, Wolf?  Look a little closer, cur.  It's the scourge of the seas, the blade that bleeds, the smuggler of the Buried Sea.  I am feared by sailors, envied by pirates, and chased by comely wenches.  No doubt you felt my magnanimous presence when you first stepped foot upon Jardel's Hook.  It is I, the " . quest::saylink("legendary") . " Rickan!",
         ["Legendary?", "Yes!  You have heard tell of my grand adventures, to be certain - how I sailed the salty waters of Norrath several times over, fending off attacks from man and beast alike, plundering every port that had the misfortune of appearing on my horizon.  Now go, go and " . quest::saylink("spread the word") . ", $name.  You must be dying to inform your friends that you met the legendary Rickan."],
         ["My appearance?", "Yes, I can tell you've a keen eye.  My " . quest::saylink("armor") . " is in need of a change, something that'd instill thoughts of fear and awe into my enemies.  And my " . quest::saylink("clothing") . " has become tattered and worn from my adventures.  Not to mention the sad state my " . quest::saylink("hat") . " is in.  From what Johnny has spoken about Redfeather Isle, I think it'd be just the place to get what I need."],
         ["What clothing?", "Have yourself a trip to Redfeather Isle and return to me with the pelts and skins of the inhabitants.  With the raw materials I'll have Matilda stitch me up a new outfit."],
        ],
    620020 =>
        [
         "Have you any idea, any concept of who you're speaking to, Wolf?  Look a little closer, cur.  It's the scourge of the seas, the blade that bleeds, the smuggler of the Buried Sea.  I am feared by sailors, envied by pirates, and chased by comely wenches.  No doubt you felt my magnanimous presence when you first stepped foot upon Jardel's Hook.  It is I, the " . quest::saylink("legendary") . " Rickan!",
         ["Legendary?", "Yes!  You have heard tell of my grand adventures, to be certain - how I sailed the salty waters of Norrath several times over, fending off attacks from man and beast alike, plundering every port that had the misfortune of appearing on my horizon.  Now go, go and " . quest::saylink("spread the word") . ", $name.  You must be dying to inform your friends that you met the legendary Rickan."],
         ["My appearance?", "Yes, I can tell you've a keen eye.  My " . quest::saylink("armor") . " is in need of a change, something that'd instill thoughts of fear and awe into my enemies.  And my " . quest::saylink("clothing") . " has become tattered and worn from my adventures.  Not to mention the sad state my " . quest::saylink("hat") . " is in.  From what Johnny has spoken about Redfeather Isle, I think it'd be just the place to get what I need."],
        ],
    620021 =>
        [
         "Have you any idea, any concept of who you're speaking to, Wolf?  Look a little closer, cur.  It's the scourge of the seas, the blade that bleeds, the smuggler of the Buried Sea.  I am feared by sailors, envied by pirates, and chased by comely wenches.  No doubt you felt my magnanimous presence when you first stepped foot upon Jardel's Hook.  It is I, the " . quest::saylink("legendary") . " Rickan!",
         ["Legendary?", "Yes!  You have heard tell of my grand adventures, to be certain - how I sailed the salty waters of Norrath several times over, fending off attacks from man and beast alike, plundering every port that had the misfortune of appearing on my horizon.  Now go, go and " . quest::saylink("spread the word") . ", $name.  You must be dying to inform your friends that you met the legendary Rickan."],
         ["My appearance?", "Yes, I can tell you've a keen eye.  My " . quest::saylink("armor") . " is in need of a change, something that'd instill thoughts of fear and awe into my enemies.  And my " . quest::saylink("clothing") . " has become tattered and worn from my adventures.  Not to mention the sad state my " . quest::saylink("hat") . " is in.  From what Johnny has spoken about Redfeather Isle, I think it'd be just the place to get what I need."],
        ],
);

my @mytasks = (620019, 620020, 620021);

sub EVENT_SAY {
  # first task of mine the player has not completed
  my $next = -1;
  for my $i (0 .. $#mytasks) {
    if (!quest::istaskcompleted($mytasks[$i])) { $next = $i; last; }
  }
  if ($next < 0) {
    if ($text=~/hail/i) {
      quest::say("You have done more than enough for me, $name. The sea itself owes you a debt now.");
    }
    return;
  }
  my $tid = $mytasks[$next];
  if (quest::istaskactive($tid)) {
    if ($text=~/hail/i) {
      quest::say("Get a move on, $name! The work will not do itself.");
    }
    return;
  }
  my $chain = $chains{$tid};
  return if !$chain;
  my $hail = $chain->[0];
  my @hops = @{$chain}[1 .. $#$chain];

  if ($text=~/hail/i) {
    quest::say($hail);
    return;
  }

  # find which hop the player triggered
  my $hit = -1;
  for my $i (0 .. $#hops) {
    if ($text=~/\Q$hops[$i][0]\E/i) { $hit = $i; last; }
  }
  return if $hit < 0;
  quest::say($hops[$hit][1]);
  # the final hop hands out the work
  if ($hit == $#hops) {
    quest::assigntask($tid);
  }
}

sub EVENT_ITEM {
  # deliver steps of the island tasks are task-deliveries;
  # anything else handed to us is returned.
  plugin::return_items(\%itemcount);
}
