#-----------------------------------------------------------------------------
# TBS Buried Sea island missions - Scurv-acious Bella Straw
# npc_types id 423105 (Scurv-acious_Bella_Straw)
# Auto-generated by tbs_content/gen_jonas_givers.py from scraped Allakhazam dialogs.
# Offers tasks in order; each task is non-repeatable.
#-----------------------------------------------------------------------------

my %chains = (
    620011 =>
        [
         "I sure would!  I'd " . quest::saylink("kill a few") . " of those uncouth dogs.  That would teach the rest to respect me and treat me like the delicate and virtuous flower that I am.",
         ["I", "Why, that would be very heroic of you!"],
        ],
);

my @mytasks = (620011);

sub EVENT_SAY {
  # first task of mine the player has not completed
  my $next = -1;
  for my $i (0 .. $#mytasks) {
    if (!quest::istaskcompleted($mytasks[$i])) { $next = $i; last; }
  }
  if ($next < 0) {
    if ($text=~/hail/i) {
      quest::say("You have done more than enough for me, $name. The sea itself owes you a debt now.");
    }
    return;
  }
  my $tid = $mytasks[$next];
  if (quest::istaskactive($tid)) {
    if ($text=~/hail/i) {
      quest::say("Get a move on, $name! The work will not do itself.");
    }
    return;
  }
  my $chain = $chains{$tid};
  return if !$chain;
  my $hail = $chain->[0];
  my @hops = @{$chain}[1 .. $#$chain];

  if ($text=~/hail/i) {
    quest::say($hail);
    return;
  }

  # find which hop the player triggered
  my $hit = -1;
  for my $i (0 .. $#hops) {
    if ($text=~/\Q$hops[$i][0]\E/i) { $hit = $i; last; }
  }
  return if $hit < 0;
  quest::say($hops[$hit][1]);
  # the final hop hands out the work
  if ($hit == $#hops) {
    quest::assigntask($tid);
  }
}

sub EVENT_ITEM {
  # deliver steps of the island tasks are task-deliveries;
  # anything else handed to us is returned.
  plugin::return_items(\%itemcount);
}
