-- Donart Rithkin (443168) -- Secrets of Faydwer faction tasks.
-- Generated by sof_content/gen_givers.py -- do not hand-edit.
local TASKS = {300100, 300101, 300102, 300113, 300114}
local REQUIRES = {}

function event_say(e)
	if e.message:findi("hail") then
		e.self:Say("Hail, " .. e.other:GetCleanName() .. ". There is work to be done if you would lend a hand. Ask me about a [task].")
	elseif e.message:findi("task") or e.message:findi("work") or e.message:findi("offer") or e.message:findi("jobs") then
		e.self:Say("These are the duties I can entrust to you, " .. e.other:GetCleanName() .. ".")
		local available = {}
		for _, tid in ipairs(TASKS) do
			local required = REQUIRES[tid]
			if required == nil or e.other:IsTaskCompleted(required) then
				available[#available + 1] = tid
			end
		end
		eq.task_selector(available)
	end
end

function event_trade(e)
	local item_lib = require("items")
	item_lib.return_items(e.self, e.other, e.trade)
end
