-- [[
-- Larquin Fangbreaker (443157) -- Bloodmoon Keep missions + raids.
-- Generated by sof_content/gen_bloodmoon_raid.py -- do not hand-edit.
-- ]]
local MISSIONS = {301200, 301201, 301202}
local REQUIRES = {}
local DEFS = {
	[301200] = { name = "The Bloodmoon", max = 6 },
	[301201] = { name = "Walking into Spider Webs", max = 6 },
	[301202] = { name = "BronzeBeard's Fate", max = 6 },
}

local BUCKET = "sof.loping.missions"
local BUCKET_TOTAL = 7

local RAIDS = {
	["dangerous"] = { name = "Bloodmoon: Crazok Moonfang", version = 2, bucket = "sof.bm.raid.fanged_moon" },
	["ralkor"] = { name = "Bloodmoon: Ralkor's Crystals", version = 3, bucket = "sof.bm.raid.crazok" },
}

local GX, GY, GZ = -3195.0, -1405.0, 702.875

local function bucket_ge(c, name, v)
	return (tonumber(c:GetBucket(name)) or 0) >= v
end

function event_task_complete(e)
	for _, tid in ipairs(MISSIONS) do
		if e.task_id == tid then
			local n = tonumber(e.other:GetBucket(BUCKET)) or 0
			if n < BUCKET_TOTAL then
				e.other:SetBucket(BUCKET, tostring(n + 1))
			end
			return
		end
	end
end

function event_say(e)
	local c = e.other
	if e.message:findi("hail") then
		e.self:Say("Hail, " .. c:GetCleanName() .. ". The Bloodmoon will not fall on its own. Ask me about a [mission] or a [raid].")
	elseif e.message:findi("mission") or e.message:findi("task") or e.message:findi("work") then
		local available = {}
		for _, tid in ipairs(MISSIONS) do
			local required = REQUIRES[tid]
			if required == nil or c:IsTaskCompleted(required) then
				available[#available + 1] = tid
			end
		end
		eq.task_selector(available)
	elseif e.message:findi("enter") or e.message:findi("zone in") or e.message:findi("go in") then
		local active = nil
		for _, tid in ipairs(MISSIONS) do
			if c:IsTaskActive(tid) then active = tid; break end
		end
		if active == nil then
			e.self:Say("You hold no mission of mine to lead you in.")
			return
		end
		local dz = c:GetExpedition()
		if dz.valid then c:MovePCDynamicZone(dz:GetZoneID()); return end
		local d = DEFS[active]
		dz = c:CreateExpedition({
			expedition = { name = d.name, min_players = 1, max_players = d.max },
			instance = { zone = "bloodmoon", version = 0, duration = eq.seconds("6h") },
			compass = { zone = "lopingplains", x = GX, y = GY, z = GZ },
			safereturn = { zone = "lopingplains", x = GX, y = GY, z = GZ, h = 0 },
			zonein = { x = 0, y = 0, z = 0, h = 0 },
			switchid = 0,
		})
		if dz.valid then c:MovePCDynamicZone(dz:GetZoneID()) end
	elseif e.message:findi("ready") then
		local dz = c:GetExpedition()
		if dz.valid then
			e.self:Say("Pass through, " .. c:GetCleanName() .. ".")
			c:MovePCDynamicZone(dz:GetZoneID())
		else
			e.self:Say("You belong to no expedition.")
		end
	else
		for kw, r in pairs(RAIDS) do
			if e.message:findi(kw) then
				if not c:IsTaskCompleted(301204) then
					e.self:Say("Walk the Dark Crystals for Maria first.")
					return
				end
				if r.bucket and not bucket_ge(c, r.bucket, 1) then
					e.self:Say("That raid is not yet yours to call.")
					return
				end
				if c:GetLevel() < 70 then
					e.self:Say("Return at level 70, " .. c:GetCleanName() .. ".")
					return
				end
				local dz = c:GetExpedition()
				if dz.valid then
					e.self:Say("You already hold an expedition. Use it or let it lapse.")
					return
				end
				dz = c:CreateExpedition({
					expedition = { name = r.name, min_players = 1, max_players = 54 },
					instance = { zone = "bloodmoon", version = r.version, duration = eq.seconds("8h") },
					compass = { zone = "lopingplains", x = GX, y = GY, z = GZ },
					safereturn = { zone = "lopingplains", x = GX, y = GY, z = GZ, h = 0 },
					zonein = { x = 0, y = 120, z = 2, h = 0 },
					switchid = 0,
				})
				if dz.valid then
					dz:AddReplayLockout(eq.seconds("72h"))
					e.self:Say("Then to Bloodmoon. Strike true.")
				else
					e.self:Say("The way is blocked -- ask me again shortly.")
				end
				return
			end
		end
	end
end

function event_trade(e)
	local item_lib = require("items")
	item_lib.return_items(e.self, e.other, e.trade)
end
