-- Dwinn Axeheaver (443164) -- Secrets of Faydwer faction tasks.
-- Generated by sof_content/gen_givers.py -- do not hand-edit.
local TASKS = {302001, 302002, 302003, 302004, 302005, 302006, 302007, 302008, 302009}
local REQUIRES = {[302002] = 302001, [302003] = 302002, [302004] = 302003, [302005] = 302004, [302006] = 302005, [302007] = 302006, [302008] = 302007, [302009] = 302008}

function event_say(e)
	if e.message:findi("hail") then
		e.self:Say("Hail, " .. e.other:GetCleanName() .. ". There is work to be done if you would lend a hand. Ask me about a [task].")
	elseif e.message:findi("task") or e.message:findi("work") or e.message:findi("offer") or e.message:findi("jobs") then
		e.self:Say("These are the duties I can entrust to you, " .. e.other:GetCleanName() .. ".")
		local available = {}
		for _, tid in ipairs(TASKS) do
			local required = REQUIRES[tid]
			if required == nil or e.other:IsTaskCompleted(required) then
				available[#available + 1] = tid
			end
		end
		eq.task_selector(available)
	end
end

function event_task_complete(e)
	if e.task_id == 302009 then
		e.other:AddAAPoints(3)
	end
end

function event_trade(e)
	local item_lib = require("items")
	item_lib.return_items(e.self, e.other, e.trade)
end
