-- Guardian Expediator Mark (37950) -- teleports to floor 2.
-- Generated by sof_content/gen_guardian_expedition.py -- do not hand-edit.
local ZONEID, X, Y, Z, H = 447, 148.25, -266.0, -202.5, 0

function event_item_click(e)
	local who = e.owner
	if who == nil then return end
	who:MovePC(ZONEID, X, Y, Z, H)
end
