-- Guardian Expediator Mark (37952) -- teleports to floor 4.
-- Generated by sof_content/gen_guardian_expedition.py -- do not hand-edit.
local ZONEID, X, Y, Z, H = 447, 106.75, -231.875, -556.375, 0

function event_item_click(e)
	local who = e.owner
	if who == nil then return end
	who:MovePC(ZONEID, X, Y, Z, H)
end
