#-----------------------------------------------------------------------------
# TBS Buried Sea island missions - Trophy Hunter Locke
# npc_types id 422004 (#Trophy_Hunter_Locke)
# Auto-generated by tbs_content/gen_jonas_givers.py from scraped Allakhazam dialogs.
# Offers tasks in order; each task is non-repeatable.
#-----------------------------------------------------------------------------

my %chains = (
    620044 =>
        [
         "Good day [$name].  You look like you are an " . quest::saylink("adventurer") . ".",
         ["I am an adventurer!", "Indeed you are!  And as such a great adventurer, I should think you'd enjoy some challenging work.  Listen here, I am trying to start a business that offers services to trophy hunters -- you know, folk who like to boast of hunting the most rare and dangerous beasts! In this business, though, we do the hunting, they do the bragging! To get started I will need some help collecting some beasts for trophy-making from an island in the " . quest::saylink("Buried Sea") . "."],
         ["The Buried Sea?", "The Buried sea is a sea to the east of here. Lots of activity here lately with the whirlpool showing up and all that. I'm most interested in an " . quest::saylink("island") . " rumored to have many wild beasts."],
         ["What island?", "Yes, it's called Monkey Rock, though I hear there is more than monkeys there. In fact, judging by your interest, maybe you can handle several of the " . quest::saylink("tasks") . " I have to complete to get this business off the ground. I will reward you well!"],
         ["What tasks?", "Progress! Now, listen, take one of the ships from here to the Buried Sea. You may have a bit of swimming ahead of you too.  Monkey Rock is far southwest from where the ships docks in the Buried Sea."],
        ],
    620045 =>
        [
         "Good day [$name].  You look like you are an " . quest::saylink("adventurer") . ".",
         ["I am an adventurer!", "Indeed you are!  And as such a great adventurer, I should think you'd enjoy some challenging work.  Listen here, I am trying to start a business that offers services to trophy hunters -- you know, folk who like to boast of hunting the most rare and dangerous beasts! In this business, though, we do the hunting, they do the bragging! To get started I will need some help collecting some beasts for trophy-making from an island in the " . quest::saylink("Buried Sea") . "."],
         ["The Buried Sea?", "The Buried sea is a sea to the east of here. Lots of activity here lately with the whirlpool showing up and all that. I'm most interested in an " . quest::saylink("island") . " rumored to have many wild beasts."],
         ["What island?", "Yes, it's called Monkey Rock, though I hear there is more than monkeys there. In fact, judging by your interest, maybe you can handle several of the " . quest::saylink("tasks") . " I have to complete to get this business off the ground. I will reward you well!"],
         ["What tasks?", "Progress! Now, listen, take one of the ships from here to the Buried Sea. You may have a bit of swimming ahead of you too.  Monkey Rock is far southwest from where the ships docks in the Buried Sea."],
        ],
    620046 =>
        [
         "Good day [$name].  You look like you are an " . quest::saylink("adventurer") . ".",
         ["I am an adventurer!", "Indeed you are!  And as such a great adventurer, I should think you'd enjoy some challenging work.  Listen here, I am trying to start a business that offers services to trophy hunters -- you know, folk who like to boast of hunting the most rare and dangerous beasts! In this business, though, we do the hunting, they do the bragging! To get started I will need some help collecting some beasts for trophy-making from an island in the " . quest::saylink("Buried Sea") . "."],
         ["The Buried Sea?", "The Buried sea is a sea to the east of here. Lots of activity here lately with the whirlpool showing up and all that. I'm most interested in an " . quest::saylink("island") . " rumored to have many wild beasts."],
         ["What island?", "Yes, it's called Monkey Rock, though I hear there is more than monkeys there. In fact, judging by your interest, maybe you can handle several of the " . quest::saylink("tasks") . " I have to complete to get this business off the ground. I will reward you well!"],
         ["What tasks?", "Progress! Now, listen, take one of the ships from here to the Buried Sea. You may have a bit of swimming ahead of you too.  Monkey Rock is far southwest from where the ships docks in the Buried Sea."],
        ],
    620047 =>
        [
         "Good day [$name].  You look like you are an " . quest::saylink("adventurer") . ".",
         ["I am an adventurer!", "Indeed you are!  And as such a great adventurer, I should think you'd enjoy some challenging work.  Listen here, I am trying to start a business that offers services to trophy hunters -- you know, folk who like to boast of hunting the most rare and dangerous beasts! In this business, though, we do the hunting, they do the bragging! To get started I will need some help collecting some beasts for trophy-making from an island in the " . quest::saylink("Buried Sea") . "."],
         ["The Buried Sea?", "The Buried sea is a sea to the east of here. Lots of activity here lately with the whirlpool showing up and all that. I'm most interested in an " . quest::saylink("island") . " rumored to have many wild beasts."],
         ["What island?", "Yes, it's called Monkey Rock, though I hear there is more than monkeys there. In fact, judging by your interest, maybe you can handle several of the " . quest::saylink("tasks") . " I have to complete to get this business off the ground. I will reward you well!"],
         ["What tasks?", "Progress! Now, listen, take one of the ships from here to the Buried Sea. You may have a bit of swimming ahead of you too.  Monkey Rock is far southwest from where the ships docks in the Buried Sea."],
        ],
    620048 =>
        [
         "Good day [$name].  You look like you are an " . quest::saylink("adventurer") . ".",
         ["I am an adventurer!", "Indeed you are!  And as such a great adventurer, I should think you'd enjoy some challenging work.  Listen here, I am trying to start a business that offers services to trophy hunters -- you know, folk who like to boast of hunting the most rare and dangerous beasts! In this business, though, we do the hunting, they do the bragging! To get started I will need some help collecting some beasts for trophy-making from an island in the " . quest::saylink("Buried Sea") . "."],
         ["The Buried Sea?", "The Buried sea is a sea to the east of here. Lots of activity here lately with the whirlpool showing up and all that. I'm most interested in an " . quest::saylink("island") . " rumored to have many wild beasts."],
         ["What island?", "Yes, it's called Monkey Rock, though I hear there is more than monkeys there. In fact, judging by your interest, maybe you can handle several of the " . quest::saylink("tasks") . " I have to complete to get this business off the ground. I will reward you well!"],
         ["What tasks?", "Progress! Now, listen, take one of the ships from here to the Buried Sea. You may have a bit of swimming ahead of you too.  Monkey Rock is far southwest from where the ships docks in the Buried Sea."],
        ],
);

my @mytasks = (620044, 620045, 620046, 620047, 620048);

sub EVENT_SAY {
  # first task of mine the player has not completed
  my $next = -1;
  for my $i (0 .. $#mytasks) {
    if (!quest::istaskcompleted($mytasks[$i])) { $next = $i; last; }
  }
  if ($next < 0) {
    if ($text=~/hail/i) {
      quest::say("You have done more than enough for me, $name. The sea itself owes you a debt now.");
    }
    return;
  }
  my $tid = $mytasks[$next];
  if (quest::istaskactive($tid)) {
    if ($text=~/hail/i) {
      quest::say("Get a move on, $name! The work will not do itself.");
    }
    return;
  }
  my $chain = $chains{$tid};
  return if !$chain;
  my $hail = $chain->[0];
  my @hops = @{$chain}[1 .. $#$chain];

  if ($text=~/hail/i) {
    quest::say($hail);
    return;
  }

  # find which hop the player triggered
  my $hit = -1;
  for my $i (0 .. $#hops) {
    if ($text=~/\Q$hops[$i][0]\E/i) { $hit = $i; last; }
  }
  return if $hit < 0;
  quest::say($hops[$hit][1]);
  # the final hop hands out the work
  if ($hit == $#hops) {
    quest::assigntask($tid);
  }
}

sub EVENT_ITEM {
  # deliver steps of the island tasks are task-deliveries;
  # anything else handed to us is returned.
  plugin::return_items(\%itemcount);
}
