#-----------------------------------------------------------------------------
# TBS Buried Sea island missions - Brynden Snow
# npc_types id 422019 (Brynden_Snow)
# Auto-generated by tbs_content/gen_jonas_givers.py from scraped Allakhazam dialogs.
# Offers tasks in order; each task is non-repeatable.
#-----------------------------------------------------------------------------

my %chains = (
    620034 =>
        [
         "Hail!  What brings you to this forsaken shore?  If you're looking for adventure, that's easily enough found out on the Buried Sea.  This place is for traders and fisherfolk.  Me, I'm a trader.  I don't have anything for sale, getting goods out here is far too difficult.  But I'm interested in " . quest::saylink("obtaining") . " a few items.  All I have to do now is figure out what those items might be.' Brynden smiles.",
         ["Obtaining what items?", "There are a number of things that hold my interests in the direction of Suncrest."],
        ],
    620035 =>
        [
         "Hail!  What brings you to this forsaken shore?  If you're looking for adventure, that's easily enough found out on the Buried Sea.  This place is for traders and fisherfolk.  Me, I'm a trader.  I don't have anything for sale, getting goods out here is far too difficult.  But I'm interested in " . quest::saylink("obtaining") . " a few items.  All I have to do now is figure out what those items might be.' Brynden smiles.",
         ["Obtaining what items?", "There are a number of things that hold my interests in the direction of Suncrest."],
        ],
    620036 =>
        [
         "Hail!  What brings you to this forsaken shore?  If you're looking for adventure, that's easily enough found out on the Buried Sea.  This place is for traders and fisherfolk.  Me, I'm a trader.  I don't have anything for sale, getting goods out here is far too difficult.  But I'm interested in " . quest::saylink("obtaining") . " a few items.  All I have to do now is figure out what those items might be.' Brynden smiles.",
         ["Obtaining what items?", "There are a number of things that hold my interests in the direction of Suncrest."],
        ],
    620037 =>
        [
         "Hail!  What brings you to this forsaken shore?  If you're looking for adventure, that's easily enough found out on the Buried Sea.  This place is for traders and fisherfolk.  Me, I'm a trader.  I don't have anything for sale, getting goods out here is far too difficult.  But I'm interested in " . quest::saylink("obtaining") . " a few items.  All I have to do now is figure out what those items might be.' Brynden smiles.",
         ["Obtaining what items?", "There are a number of things that hold my interests in the direction of Suncrest."],
        ],
    620038 =>
        [
         "Hail!  What brings you to this forsaken shore?  If you're looking for adventure, that's easily enough found out on the Buried Sea.  This place is for traders and fisherfolk.  Me, I'm a trader.  I don't have anything for sale, getting goods out here is far too difficult.  But I'm interested in " . quest::saylink("obtaining") . " a few items.  All I have to do now is figure out what those items might be.' Brynden smiles.",
         ["Obtaining what items?", "There are a number of things that hold my interests in the direction of Suncrest."],
        ],
);

my @mytasks = (620034, 620035, 620036, 620037, 620038);

sub EVENT_SAY {
  # first task of mine the player has not completed
  my $next = -1;
  for my $i (0 .. $#mytasks) {
    if (!quest::istaskcompleted($mytasks[$i])) { $next = $i; last; }
  }
  if ($next < 0) {
    if ($text=~/hail/i) {
      quest::say("You have done more than enough for me, $name. The sea itself owes you a debt now.");
    }
    return;
  }
  my $tid = $mytasks[$next];
  if (quest::istaskactive($tid)) {
    if ($text=~/hail/i) {
      quest::say("Get a move on, $name! The work will not do itself.");
    }
    return;
  }
  my $chain = $chains{$tid};
  return if !$chain;
  my $hail = $chain->[0];
  my @hops = @{$chain}[1 .. $#$chain];

  if ($text=~/hail/i) {
    quest::say($hail);
    return;
  }

  # find which hop the player triggered
  my $hit = -1;
  for my $i (0 .. $#hops) {
    if ($text=~/\Q$hops[$i][0]\E/i) { $hit = $i; last; }
  }
  return if $hit < 0;
  quest::say($hops[$hit][1]);
  # the final hop hands out the work
  if ($hit == $#hops) {
    quest::assigntask($tid);
  }
}

sub EVENT_ITEM {
  # deliver steps of the island tasks are task-deliveries;
  # anything else handed to us is returned.
  plugin::return_items(\%itemcount);
}
