-- [[
-- Bloodmoon_Raid_Controller_I (445547) -- Bloodmoon raid controller (version 1).
-- Registers the raid win chest as a loot event on instance boot and adds a
-- 72h lockout when the encounter signals completion. Passive, non-combat.
-- Rasper: raidBloodmoon1.html. Generated by gen_bloodmoon_raid.py -- do not hand-edit.
-- ]]
local M = require("sof_bloodmoon_raid")
local LOCKOUT = eq.seconds("72h")
local EVENT = { name = "Bloodmoon: The Fanged Moon", chest = 445540 }

function event_spawn(e)
	local exp = eq.get_expedition()
	if not exp.valid then return end
	exp:SetLootEventByNPCTypeID(EVENT.chest, EVENT.name)

end

function event_signal(e)
	if e.signal ~= 1101 then return end
	local exp = eq.get_expedition()
	if exp.valid and not exp:HasLockout(EVENT.name) then
		exp:AddLockout(EVENT.name, LOCKOUT)
		eq.zone_emote(15, EVENT.name .. " has been defeated!")
	end
end
