-- ============================================================================
-- Secrets of Faydwer -- Bloodmoon Keep group missions (7).
-- Shared-task + dz-template pattern (gen_missions.py / TBS Solteris).
-- Generated by sof_content/gen_loping_missions.py -- do not hand-edit.
-- ============================================================================

DELETE FROM `task_activities` WHERE `taskid` BETWEEN 301200 AND 301206;
DELETE FROM `tasks` WHERE `id` BETWEEN 301200 AND 301206;
DELETE FROM `dynamic_zone_templates` WHERE `id` BETWEEN 6150 AND 6156;

INSERT INTO `tasks` (id,type,duration,duration_code,title,description,reward_text,reward_id_list,cash_reward,exp_reward,reward_method,reward_points,reward_point_type,min_level,max_level,level_spread,min_players,max_players,repeatable,faction_reward,completion_emote,replay_timer_group,replay_timer_seconds,request_timer_group,request_timer_seconds,dz_template_id,lock_activity_id,faction_amount,enabled) VALUES
(301200,1,21600,0,'The Bloodmoon','Slip into Bloodmoon Keep, thin the wolf and orc garrison, and strip five equipment crates of their harnesses for Larquin.','Experience',79705,0,250000,0,0,0,70,0,0,1,6,0,1191,'',0,0,0,0,6150,-1,40,1),
(301201,1,21600,0,'Walking into Spider Webs','Destroy the spider nursery in the northeast of Bloodmoon Keep and cull its brood.','Experience',79706,0,250000,0,0,0,70,0,0,1,6,0,1191,'',0,0,0,0,6151,-1,20,1),
(301202,1,21600,0,'Bronzebeard\'s Fate','Free the Bloodmoon slaves with jailor keys, then face what Hurley Bronzebeard has become.','Experience',79707,0,250000,0,0,0,70,0,0,1,6,0,1191,'',0,0,0,0,6152,-1,20,1),
(301203,1,21600,0,'The Departed','Cut through Bloodmoon\'s departed to the Spirit of Falstaff and put the old ghost to rest for Maria Starforge.','Experience',79708,0,250000,0,0,0,70,0,0,1,6,0,1191,'',0,0,0,0,6153,-1,40,1),
(301204,1,21600,0,'The Dark Crystals','Steal the Bloodmoon engineers\' charged crystals and sabotage their explosives cache for Maria Starforge.','Experience',79709,0,250000,0,0,0,70,0,0,1,6,0,1191,'',0,0,0,0,6154,-1,40,1),
(301205,1,21600,0,'Moonfang','Clear Bloodmoon Keep of its garrison before rousing Moonfang in the stables.','Experience',79703,0,250000,0,0,0,70,0,0,1,12,0,1191,'',0,0,0,0,6155,-1,40,1),
(301206,1,21600,0,'The Broodmother','Descend into the spider dens and destroy the Broodmother.','Experience',79704,0,250000,0,0,0,70,0,0,1,12,0,1191,'',0,0,0,0,6156,-1,40,1);

INSERT INTO `dynamic_zone_templates`
  (`id`,`zone_id`,`zone_version`,`name`,`min_players`,`max_players`,
   `duration_seconds`,`dz_switch_id`,`compass_zone_id`,`compass_x`,`compass_y`,
   `compass_z`,`return_zone_id`,`return_x`,`return_y`,`return_z`,`return_h`,
   `override_zone_in`,`zone_in_x`,`zone_in_y`,`zone_in_z`,`zone_in_h`) VALUES
(6150,445,0,'Bloodmoon: The Bloodmoon',1,6,21600,0,443,-3195.0,-1405.0,702.875,443,-3195.0,-1405.0,702.875,0,0,0,0,0,0),
(6151,445,0,'Bloodmoon: Walking into Spider Webs',1,6,21600,0,443,-3195.0,-1405.0,702.875,443,-3195.0,-1405.0,702.875,0,0,0,0,0,0),
(6152,445,0,'Bloodmoon: Bronzebeard\'s Fate',1,6,21600,0,443,-3195.0,-1405.0,702.875,443,-3195.0,-1405.0,702.875,0,0,0,0,0,0),
(6153,445,0,'Bloodmoon: The Departed',1,6,21600,0,443,-3284.0,-1418.0,702.875,443,-3284.0,-1418.0,702.875,0,0,0,0,0,0),
(6154,445,0,'Bloodmoon: The Dark Crystals',1,6,21600,0,443,-3284.0,-1418.0,702.875,443,-3284.0,-1418.0,702.875,0,0,0,0,0,0),
(6155,445,0,'Bloodmoon: Moonfang',1,12,21600,0,443,-3157.0,-1361.0,702.875,443,-3157.0,-1361.0,702.875,0,0,0,0,0,0),
(6156,445,0,'Bloodmoon: The Broodmother',1,12,21600,0,443,-3157.0,-1361.0,702.875,443,-3157.0,-1361.0,702.875,0,0,0,0,0,0);

INSERT INTO `task_activities` (taskid,activityid,req_activity_id,step,activitytype,target_name,goalmethod,goalcount,description_override,npc_match_list,item_id_list,item_list,dz_switch_id,min_x,min_y,min_z,max_x,max_y,max_z,skill_list,spell_list,zones,zone_version,optional,list_group) VALUES
(301200,0,-1,1,2,'Bloodmoon orcs',0,15,'Destroy 15 Bloodmoon orcs','445001|445002|445006|445008|445012|445013|445022','','',0,0,0,0,0,0,0,'-1','0','445',-1,0,0),
(301200,1,-1,2,2,'worgs',0,15,'Destroy 15 worgs','445003|445016','','',0,0,0,0,0,0,0,'-1','0','445',-1,0,0),
(301200,2,-1,3,2,'equipment crates',0,5,'Destroy 5 equipment crates','443644','','',0,0,0,0,0,0,0,'-1','0','445',-1,0,0),
(301200,3,-1,4,3,'',0,5,'Loot 5 Bloodmoon Wolf Harness','','36233','Bloodmoon Wolf Harness',0,0,0,0,0,0,0,'-1','0','445',-1,0,0),
(301200,4,-1,5,1,'Larquin Fangbreaker',0,5,'Deliver to Larquin Fangbreaker','443157','36233','',0,0,0,0,0,0,0,'-1','0','445',-1,0,0),
(301201,0,-1,1,2,'egg sacs',0,10,'Destroy 10 egg sacs','443645','','',0,0,0,0,0,0,0,'-1','0','445',-1,0,0),
(301201,1,-1,2,2,'cocoons',0,5,'Destroy 5 cocoons','443646','','',0,0,0,0,0,0,0,'-1','0','445',-1,0,0),
(301201,2,-1,3,2,'spiders',0,15,'Destroy 15 spiders','445024|445027','','',0,0,0,0,0,0,0,'-1','0','445',-1,0,0),
(301201,3,-1,4,4,'Larquin Fangbreaker',0,1,'Speak with Larquin Fangbreaker','443157','','',0,0,0,0,0,0,0,'-1','0','445',-1,0,0),
(301202,0,-1,1,2,'Bloodmoon jailors',0,5,'Destroy 5 Bloodmoon jailors','445012','','',0,0,0,0,0,0,0,'-1','0','445',-1,0,0),
(301202,1,-1,2,3,'',0,5,'Loot 5 Bloodmoon Shackle Key','','36234','Bloodmoon Shackle Key',0,0,0,0,0,0,0,'-1','0','445',-1,0,0),
(301202,2,-1,3,2,'Bloodmoon orcs',0,3,'Destroy 3 Bloodmoon orcs','445001|445002|445006|445008|445012|445013|445022','','',0,0,0,0,0,0,0,'-1','0','445',-1,0,0),
(301202,3,-1,4,2,'Hurley Bronzebeard',0,1,'Destroy 1 Hurley Bronzebeard','443640','','',0,0,0,0,0,0,0,'-1','0','445',-1,0,0),
(301202,4,-1,5,4,'Larquin Fangbreaker',0,1,'Speak with Larquin Fangbreaker','443157','','',0,0,0,0,0,0,0,'-1','0','445',-1,0,0),
(301203,0,-1,1,2,'ghosts',0,10,'Destroy 10 ghosts','445011','','',0,0,0,0,0,0,0,'-1','0','445',-1,0,0),
(301203,1,-1,2,2,'bile speakers',0,10,'Destroy 10 bile speakers','445015','','',0,0,0,0,0,0,0,'-1','0','445',-1,0,0),
(301203,2,-1,3,2,'shadow priests',0,10,'Destroy 10 shadow priests','445009','','',0,0,0,0,0,0,0,'-1','0','445',-1,0,0),
(301203,3,-1,4,2,'the Spirit of Falstaff',0,1,'Destroy 1 the Spirit of Falstaff','443647','','',0,0,0,0,0,0,0,'-1','0','445',-1,0,0),
(301203,4,-1,5,4,'Falstaff Moondancer',0,1,'Speak with Falstaff Moondancer','445025','','',0,0,0,0,0,0,0,'-1','0','445',-1,0,0),
(301203,5,-1,6,4,'Maria Starforge',0,1,'Speak with Maria Starforge','443167','','',0,0,0,0,0,0,0,'-1','0','445',-1,0,0),
(301204,0,-1,1,2,'Bloodmoon jailors',0,5,'Destroy 5 Bloodmoon jailors','445012','','',0,0,0,0,0,0,0,'-1','0','445',-1,0,0),
(301204,1,-1,2,3,'',0,5,'Loot 5 Bloodmoon Shackle Key','','36234','Bloodmoon Shackle Key',0,0,0,0,0,0,0,'-1','0','445',-1,0,0),
(301204,2,-1,3,2,'a Bloodmoon engineer',0,1,'Destroy 1 a Bloodmoon engineer','443643','','',0,0,0,0,0,0,0,'-1','0','445',-1,0,0),
(301204,3,-1,4,3,'',0,1,'Loot 1 Bloodmoon Torch','','36236','Bloodmoon Torch',0,0,0,0,0,0,0,'-1','0','445',-1,0,0),
(301204,5,-1,6,2,'Bloodmoon orcs',0,5,'Destroy 5 Bloodmoon orcs','445001|445002|445006|445008|445012|445013|445022','','',0,0,0,0,0,0,0,'-1','0','445',-1,0,0),
(301204,6,-1,7,3,'',0,1,'Loot 1 Bloodmoon Crystal Samples','','36237','Bloodmoon Crystal Samples',0,0,0,0,0,0,0,'-1','0','445',-1,0,0),
(301204,7,-1,8,1,'Maria Starforge',0,1,'Deliver to Maria Starforge','443167','36237','',0,0,0,0,0,0,0,'-1','0','445',-1,0,0),
(301205,0,-1,1,2,'Bloodmoon orcs',0,20,'Destroy 20 Bloodmoon orcs','445001|445002|445006|445008|445012|445013|445022','','',0,0,0,0,0,0,0,'-1','0','445',-1,0,0),
(301205,1,-1,2,2,'worgs',0,15,'Destroy 15 worgs','445003|445016','','',0,0,0,0,0,0,0,'-1','0','445',-1,0,0),
(301205,2,-1,3,2,'spiders',0,15,'Destroy 15 spiders','445024|445027','','',0,0,0,0,0,0,0,'-1','0','445',-1,0,0),
(301205,3,-1,4,2,'Moonfang',0,1,'Destroy 1 Moonfang','443641','','',0,0,0,0,0,0,0,'-1','0','445',-1,0,0),
(301205,4,-1,5,4,'Kadara Fangbreaker',0,1,'Speak with Kadara Fangbreaker','443156','','',0,0,0,0,0,0,0,'-1','0','445',-1,0,0),
(301206,0,-1,1,2,'spiders',0,15,'Destroy 15 spiders','445024|445027','','',0,0,0,0,0,0,0,'-1','0','445',-1,0,0),
(301206,1,-1,2,2,'the Broodmother',0,1,'Destroy 1 the Broodmother','443642','','',0,0,0,0,0,0,0,'-1','0','445',-1,0,0),
(301206,2,-1,3,4,'Kadara Fangbreaker',0,1,'Speak with Kadara Fangbreaker','443156','','',0,0,0,0,0,0,0,'-1','0','445',-1,0,0);

-- explore activities: boxes anchored around the explosives cache spawn
INSERT INTO `task_activities` (taskid,activityid,req_activity_id,step,activitytype,target_name,goalmethod,goalcount,description_override,npc_match_list,item_id_list,item_list,dz_switch_id,min_x,min_y,min_z,max_x,max_y,max_z,skill_list,spell_list,zones,zone_version,optional,list_group)
SELECT 301204,4,-1,5,5,'the explosives cache',1,1,'the explosives cache','','','',0,x-40,y-40,z-40,x+40,y+40,z+40,'-1','0','445',-1,0,0 FROM (SELECT s2.x x,s2.y y,s2.z z FROM spawn2 s2 JOIN spawnentry se ON se.spawngroupID=s2.spawngroupID WHERE s2.zone='bloodmoon' AND s2.version=0 AND se.npcID=445000 ORDER BY s2.id LIMIT 1) q;

-- ============================================================
-- Mission NPCs (443640+, clone + authored envelope). Bosses and
-- objective objects are version-0 static spawns (house pattern).
-- ============================================================
DELETE FROM `npc_types` WHERE `id` IN (443640,443641,443642,443643,443644,443645,443646,443647);
DROP TEMPORARY TABLE IF EXISTS sof_lpm_nt;
CREATE TEMPORARY TABLE sof_lpm_nt AS SELECT * FROM npc_types WHERE 0;
INSERT INTO sof_lpm_nt SELECT * FROM npc_types WHERE id = 443022;
UPDATE sof_lpm_nt SET id = 443640, name = '#Hurley_Bronzebeard', level = 80, maxlevel = 80, hp = 120000, mindmg = 100, maxdmg = 1400, AC = 500, ATK = 250, Accuracy = 310, loottable_id = 0 WHERE id = 443022;
INSERT INTO sof_lpm_nt SELECT * FROM npc_types WHERE id = 443025;
UPDATE sof_lpm_nt SET id = 443641, name = '#Moonfang', level = 82, maxlevel = 82, hp = 220000, mindmg = 150, maxdmg = 6000, AC = 560, ATK = 280, Accuracy = 340, loottable_id = 0, special_abilities = '1,1^4,1', raid_target = 0 WHERE id = 443025;
INSERT INTO sof_lpm_nt SELECT * FROM npc_types WHERE id = 445027;
UPDATE sof_lpm_nt SET id = 443642, name = '#The_Broodmother', level = 82, maxlevel = 82, hp = 200000, mindmg = 140, maxdmg = 4800, AC = 560, ATK = 280, Accuracy = 340, loottable_id = 0 WHERE id = 445027;
INSERT INTO sof_lpm_nt SELECT * FROM npc_types WHERE id = 445002;
UPDATE sof_lpm_nt SET id = 443643, name = '#a_Bloodmoon_engineer', level = 80, maxlevel = 80, hp = 100000, mindmg = 100, maxdmg = 2200, AC = 480, ATK = 240, Accuracy = 300, loottable_id = 1520001302 WHERE id = 445002;
INSERT INTO sof_lpm_nt SELECT * FROM npc_types WHERE id = 445015;
UPDATE sof_lpm_nt SET id = 443644, name = '#an_equipment_crate', level = 1, maxlevel = 1, hp = 5000, mindmg = 0, maxdmg = 10, AC = 100, ATK = 0, Accuracy = 0, loottable_id = 1520001301, npc_faction_id = 0, aggroradius = 0 WHERE id = 445015;
INSERT INTO sof_lpm_nt SELECT * FROM npc_types WHERE id = 445027;
UPDATE sof_lpm_nt SET id = 443645, name = '#an_egg_sac', level = 1, maxlevel = 1, hp = 8000, mindmg = 0, maxdmg = 10, AC = 100, ATK = 0, Accuracy = 0, loottable_id = 0, npc_faction_id = 0, aggroradius = 0 WHERE id = 445027;
INSERT INTO sof_lpm_nt SELECT * FROM npc_types WHERE id = 445027;
UPDATE sof_lpm_nt SET id = 443646, name = '#a_cocoon', level = 1, maxlevel = 1, hp = 10000, mindmg = 0, maxdmg = 10, AC = 100, ATK = 0, Accuracy = 0, loottable_id = 0, npc_faction_id = 0, aggroradius = 0 WHERE id = 445027;
INSERT INTO sof_lpm_nt SELECT * FROM npc_types WHERE id = 445011;
UPDATE sof_lpm_nt SET id = 443647, name = '#Spirit_of_Falstaff', level = 81, maxlevel = 81, hp = 150000, mindmg = 120, maxdmg = 4000, AC = 520, ATK = 260, Accuracy = 330, loottable_id = 0 WHERE id = 445011;
INSERT INTO `npc_types` SELECT * FROM sof_lpm_nt;
DROP TEMPORARY TABLE sof_lpm_nt;

-- ============================================================
-- Static spawns (spawngroups 1520001171+). TUNABLE coords.
-- ============================================================
DELETE FROM `spawnentry` WHERE `spawngroupID` BETWEEN 1520001171 AND 1520001200;
DELETE FROM `spawn2` WHERE `spawngroupID` BETWEEN 1520001171 AND 1520001200;
DELETE FROM `spawngroup` WHERE `id` BETWEEN 1520001171 AND 1520001200;
INSERT INTO `spawngroup` (`id`,`name`,`spawn_limit`,`dist`,`delay`,`mindelay`,`despawn`) VALUES
(1520001171,'sof_lpm_443640',0,0,1800,900,0),
(1520001172,'sof_lpm_443641',0,0,1800,900,0),
(1520001173,'sof_lpm_443642',0,0,1800,900,0),
(1520001174,'sof_lpm_443643',0,0,900,450,0),
(1520001175,'sof_lpm_443647',0,0,1500,750,0),
(1520001176,'sof_lpm_443644',0,0,450,225,0),
(1520001177,'sof_lpm_443645',0,0,450,225,0),
(1520001178,'sof_lpm_443646',0,0,450,225,0);
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES
(1520001171,443640,100),
(1520001172,443641,100),
(1520001173,443642,100),
(1520001174,443643,100),
(1520001175,443647,100),
(1520001176,443644,100),
(1520001177,443645,100),
(1520001178,443646,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) VALUES
(1520001171,'bloodmoon',0,300,400,-21,0,3600),
(1520001172,'bloodmoon',0,-500,200,-21,0,3600),
(1520001173,'bloodmoon',0,-950,650,-54,0,3600),
(1520001174,'bloodmoon',0,-600,300,-21,0,1800),
(1520001175,'bloodmoon',0,-700,900,-54,0,3000),
(1520001176,'bloodmoon',0,120,60,-21,0,900),
(1520001176,'bloodmoon',0,260,120,-21,0,900),
(1520001176,'bloodmoon',0,400,180,-21,0,900),
(1520001176,'bloodmoon',0,540,240,-21,0,900),
(1520001176,'bloodmoon',0,680,300,-21,0,900),
(1520001177,'bloodmoon',0,-760,520,-54,0,900),
(1520001177,'bloodmoon',0,-800,560,-54,0,900),
(1520001177,'bloodmoon',0,-840,600,-54,0,900),
(1520001177,'bloodmoon',0,-880,640,-54,0,900),
(1520001177,'bloodmoon',0,-920,560,-54,0,900),
(1520001177,'bloodmoon',0,-960,600,-54,0,900),
(1520001177,'bloodmoon',0,-1000,640,-54,0,900),
(1520001177,'bloodmoon',0,-1040,580,-54,0,900),
(1520001177,'bloodmoon',0,-760,680,-54,0,900),
(1520001177,'bloodmoon',0,-900,700,-54,0,900),
(1520001178,'bloodmoon',0,-820,520,-54,0,900),
(1520001178,'bloodmoon',0,-900,560,-54,0,900),
(1520001178,'bloodmoon',0,-980,600,-54,0,900),
(1520001178,'bloodmoon',0,-860,660,-54,0,900),
(1520001178,'bloodmoon',0,-940,680,-54,0,900);

-- ============================================================
-- Loot: crate harnesses, engineer torch, miner crystal samples.
-- ============================================================
DELETE FROM `loottable_entries` WHERE `loottable_id` BETWEEN 1520001301 AND 1520001310;
DELETE FROM `lootdrop_entries` WHERE `lootdrop_id` BETWEEN 1520001301 AND 1520001310;
DELETE FROM `lootdrop` WHERE `id` BETWEEN 1520001301 AND 1520001310;
DELETE FROM `loottable` WHERE `id` BETWEEN 1520001301 AND 1520001310;
INSERT INTO `loottable` (`id`,`name`,`mincash`,`maxcash`,`avgcoin`) VALUES
(1520001301,'SoF_LPM_Equipment_Crate',0,0,0),
(1520001302,'SoF_LPM_Engineer',2000,5000,3000);
INSERT INTO `lootdrop` (`id`,`name`) VALUES
(1520001301,'SoF_LPM_Crate_Harness'),(1520001302,'SoF_LPM_Engineer_Torch');
INSERT INTO `lootdrop_entries` (`lootdrop_id`,`item_id`,`item_charges`,`equip_item`,`chance`) VALUES
(1520001301,36233,1,0,100),(1520001302,36236,1,0,100);
INSERT INTO `loottable_entries` (`loottable_id`,`lootdrop_id`,`multiplier`,`droplimit`,`mindrop`,`probability`) VALUES
(1520001301,1520001301,5,0,0,100),(1520001302,1520001302,1,0,0,100);

-- ============================================================
-- Ground spawn: Bloodmoon Crystal Samples among the slave
-- miners (mission 5 hand-in source; miners ship with no loot).
-- ============================================================
DELETE FROM `ground_spawns` WHERE `id` = 1520006412;
INSERT INTO `ground_spawns` (`id`,`zoneid`,`version`,`max_x`,`max_y`,`max_z`,`min_x`,`min_y`,`heading`,`name`,`item`,`max_allowed`,`comment`,`respawn_timer`,`fix_z`) VALUES
(1520006412,445,0,-248,802,10000,-252,798,0,'','36237',1,'SoF: Bloodmoon Crystal Samples (miner pens)',900,1);

-- ============================================================
-- Brett of the Watch (443163): Fang Rk. III elite supplier.
-- Gate = Ally faction (1100) AND all 7 Bloodmoon missions done
-- (counter bucket sof.loping.missions, incremented by the giver
-- scripts' event_task_complete; comparison 2 = GreaterOrEqual).
-- ============================================================
UPDATE `merchantlist` SET `faction_required` = 1100, `bucket_name` = 'sof.loping.missions', `bucket_value` = '7', `bucket_comparison` = 2 WHERE `merchantid` = 443163 AND `item` IN (115147,115153,115200,115333,115469,115493,115917,116007,116096,116165,116240,116380,116453);
