-- ============================================================================
-- Secrets of Faydwer -- Mechamatic Guardian (zone 447) expedition plumbing.
-- Rasper: raspersrealm.com/Everquest/SoF/openGuardian.html
-- Generated by sof_content/gen_guardian_expedition.py -- do not hand-edit.
-- Idempotent: deletes version rows / templates / ground spawns first.
-- ============================================================================

-- ---------------------------------------------------------------- cleanup
DELETE FROM `spawn2` WHERE `zone`='guardian' AND `version` BETWEEN 1 AND 5;
DELETE FROM `doors` WHERE `zone`='guardian' AND `version` BETWEEN 1 AND 5;
DELETE FROM `zone` WHERE `zoneidnumber`=447 AND `version` BETWEEN 1 AND 5;
DELETE FROM `dynamic_zone_templates` WHERE `id` BETWEEN 2200 AND 2209;
DELETE FROM `ground_spawns` WHERE `zoneid`=447;

-- ---------------------------------------------------------------- zone versions
-- v0 is the generic instance (untouched). v1-v5 are single-floor missions.
DROP TEMPORARY TABLE IF EXISTS gz;
CREATE TEMPORARY TABLE gz AS SELECT * FROM `zone` WHERE `zoneidnumber`=447 AND `version`=0;
ALTER TABLE gz MODIFY `id` INT NULL;
UPDATE gz SET `version`=1, `id`=NULL;
INSERT INTO `zone` SELECT * FROM gz;
UPDATE gz SET `version`=2, `id`=NULL;
INSERT INTO `zone` SELECT * FROM gz;
UPDATE gz SET `version`=3, `id`=NULL;
INSERT INTO `zone` SELECT * FROM gz;
UPDATE gz SET `version`=4, `id`=NULL;
INSERT INTO `zone` SELECT * FROM gz;
UPDATE gz SET `version`=5, `id`=NULL;
INSERT INTO `zone` SELECT * FROM gz;
DROP TEMPORARY TABLE gz;

-- ---------------------------------------------------------------- mission spawns
-- Each floor's v0 spawns copied into its mission version with a long
-- respawn (effectively no respawn). Ids auto-assigned.
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,
`respawntime`,`variance`,`pathgrid`,`path_when_zone_idle`,`_condition`,
`cond_value`,`animation`,`min_expansion`,`max_expansion`,`content_flags`,
`content_flags_disabled`)
SELECT `spawngroupID`, 'guardian', 1, `x`,`y`,`z`,`heading`, 86400, `variance`,`pathgrid`,`path_when_zone_idle`,`_condition`,`cond_value`,`animation`,`min_expansion`,`max_expansion`,`content_flags`,`content_flags_disabled` FROM `spawn2` WHERE `zone`='guardian' AND `version`=0 AND `_condition`=0 AND (z >= 0)
UNION ALL SELECT `spawngroupID`, 'guardian', 2, `x`,`y`,`z`,`heading`, 86400, `variance`,`pathgrid`,`path_when_zone_idle`,`_condition`,`cond_value`,`animation`,`min_expansion`,`max_expansion`,`content_flags`,`content_flags_disabled` FROM `spawn2` WHERE `zone`='guardian' AND `version`=0 AND `_condition`=0 AND (z < 0 AND z >= -300)
UNION ALL SELECT `spawngroupID`, 'guardian', 3, `x`,`y`,`z`,`heading`, 86400, `variance`,`pathgrid`,`path_when_zone_idle`,`_condition`,`cond_value`,`animation`,`min_expansion`,`max_expansion`,`content_flags`,`content_flags_disabled` FROM `spawn2` WHERE `zone`='guardian' AND `version`=0 AND `_condition`=0 AND (z < -300 AND z >= -450)
UNION ALL SELECT `spawngroupID`, 'guardian', 4, `x`,`y`,`z`,`heading`, 86400, `variance`,`pathgrid`,`path_when_zone_idle`,`_condition`,`cond_value`,`animation`,`min_expansion`,`max_expansion`,`content_flags`,`content_flags_disabled` FROM `spawn2` WHERE `zone`='guardian' AND `version`=0 AND `_condition`=0 AND (z < -450 AND z >= -650)
UNION ALL SELECT `spawngroupID`, 'guardian', 5, `x`,`y`,`z`,`heading`, 86400, `variance`,`pathgrid`,`path_when_zone_idle`,`_condition`,`cond_value`,`animation`,`min_expansion`,`max_expansion`,`content_flags`,`content_flags_disabled` FROM `spawn2` WHERE `zone`='guardian' AND `version`=0 AND `_condition`=0 AND (z < -650);

-- ---------------------------------------------------------------- mission doors
-- Copy guardian object/teleporter doors into each mission version.
DROP TEMPORARY TABLE IF EXISTS gd;
CREATE TEMPORARY TABLE gd AS SELECT * FROM `doors` WHERE `zone`='guardian' AND `version`=0;
ALTER TABLE gd MODIFY `id` INT NULL;
UPDATE gd SET `version`=1, `id`=NULL;
INSERT INTO `doors` SELECT * FROM gd;
UPDATE gd SET `version`=2, `id`=NULL;
INSERT INTO `doors` SELECT * FROM gd;
UPDATE gd SET `version`=3, `id`=NULL;
INSERT INTO `doors` SELECT * FROM gd;
UPDATE gd SET `version`=4, `id`=NULL;
INSERT INTO `doors` SELECT * FROM gd;
UPDATE gd SET `version`=5, `id`=NULL;
INSERT INTO `doors` SELECT * FROM gd;
DROP TEMPORARY TABLE gd;

-- ---------------------------------------------------------------- dz templates
INSERT INTO `dynamic_zone_templates`
(`id`,`zone_id`,`zone_version`,`name`,`min_players`,`max_players`,
`duration_seconds`,`dz_switch_id`,`compass_zone_id`,`compass_x`,`compass_y`,
`compass_z`,`return_zone_id`,`return_x`,`return_y`,`return_z`,`return_h`,
`override_zone_in`,`zone_in_x`,`zone_in_y`,`zone_in_z`,`zone_in_h`) VALUES
(2200, 447, 0, 'The Mechamatic Guardian', 1, 6, 7200, 0, 442, -2514.375, 3642.25, 26.375, 442, -2514.375, 3642.25, 26.375, 2.0, 1, -115.0, 60.0, 4.0, 0),
(2201, 447, 1, 'The Mechamatic Guardian: First Floor', 1, 6, 7200, 0, 442, -2514.375, 3642.25, 26.375, 442, -2514.375, 3642.25, 26.375, 2.0, 1, -115.0, 60.0, 4.0, 0),
(2202, 447, 2, 'The Mechamatic Guardian: Second Floor', 1, 6, 7200, 0, 442, -2514.375, 3642.25, 26.375, 442, -2514.375, 3642.25, 26.375, 2.0, 1, -115.0, 60.0, 4.0, 0),
(2203, 447, 3, 'The Mechamatic Guardian: Third Floor', 1, 6, 7200, 0, 442, -2514.375, 3642.25, 26.375, 442, -2514.375, 3642.25, 26.375, 2.0, 1, -115.0, 60.0, 4.0, 0),
(2204, 447, 4, 'The Mechamatic Guardian: Fourth Floor', 1, 6, 7200, 0, 442, -2514.375, 3642.25, 26.375, 442, -2514.375, 3642.25, 26.375, 2.0, 1, -115.0, 60.0, 4.0, 0),
(2205, 447, 5, 'The Mechamatic Guardian: Top Floor', 1, 6, 7200, 0, 442, -2514.375, 3642.25, 26.375, 442, -2514.375, 3642.25, 26.375, 2.0, 1, -115.0, 60.0, 4.0, 0);

-- ---------------------------------------------------------------- Expediator Marks
-- Ground spawns: Mark I-IV on floors 2-5. Click teleports up (item scripts).
INSERT INTO `ground_spawns` (`zoneid`,`version`,`max_x`,`max_y`,`max_z`,
`min_x`,`min_y`,`heading`,`name`,`item`,`max_allowed`,`comment`,
`respawn_timer`,`fix_z`) VALUES
(447, 0, 156.25, -258.0, -194.5, 140.25, -274.0, 0, 'Expediator Mark', 37950, 1, 'Guardian floor 2 mark', 300, 1),
(447, 0, 75.0, -131.0, -369.625, 59.0, -147.0, 0, 'Expediator Mark', 37951, 1, 'Guardian floor 3 mark', 300, 1),
(447, 0, 114.75, -223.875, -548.375, 98.75, -239.875, 0, 'Expediator Mark', 37952, 1, 'Guardian floor 4 mark', 300, 1),
(447, 0, 272.125, -240.75, -994.25, 256.125, -256.75, 0, 'Expediator Mark', 37953, 1, 'Guardian floor 5 mark', 300, 1);
