-- ============================================================================
-- Secrets of Faydwer -- Mechamatic Guardian (zone 447): the nine named rares.
-- Rasper: raspersrealm.com/Everquest/SoF/openGuardian.html
-- Generated by sof_content/gen_guardian_rares.py -- do not hand-edit.
-- Idempotent: DELETE+INSERT on explicit verified-free ids.
-- ============================================================================

-- ---------------------------------------------------------------- gating
DELETE FROM `spawn_conditions` WHERE `zone` = 'guardian' AND `id` = 1;
INSERT INTO `spawn_conditions` (`zone`,`id`,`value`,`onchange`,`name`) VALUES ('guardian',1,0,2,'Guardian_Rares');

-- ---------------------------------------------------------------- spell lists
DELETE FROM `npc_spells_entries` WHERE `npc_spells_id` BETWEEN 94901 AND 94904;
DELETE FROM `npc_spells` WHERE `id` BETWEEN 94901 AND 94904;

INSERT INTO `npc_spells` (`id`,`name`,`parent_list`,`attack_proc`,`proc_chance`) VALUES
(94901,'Guardian_JonE_V',0,7972,20),
(94902,'Guardian_Destructorizor',0,7972,20),
(94903,'Guardian_Coleoptera',0,7969,25),
(94904,'Guardian_MetalSlime',0,-1,0);
INSERT INTO `npc_spells_entries` (`id`,`npc_spells_id`,`spellid`,`type`,`minlevel`,`maxlevel`,`manacost`,`recast_delay`,`priority`) VALUES
(719920,94901,7623,1,1,255,-1,-1,1),
(719921,94902,7623,1,1,255,-1,-1,1),
(719922,94904,7973,1,1,255,-1,-1,1);

-- ---------------------------------------------------------------- rares
DROP TEMPORARY TABLE IF EXISTS sof_guardian_nt;
CREATE TEMPORARY TABLE sof_guardian_nt AS SELECT * FROM npc_types WHERE 0;

-- #Steam_Engineer_LIIV: first floor
INSERT INTO sof_guardian_nt SELECT * FROM npc_types WHERE id = 447002;
UPDATE sof_guardian_nt SET id = 447070, name = '#Steam_Engineer_LIIV', level = 82, hp = 260000, mindmg = 0, maxdmg = 2000, AC = 480, ATK = 250, Accuracy = 250, slow_mitigation = 0, loottable_id = 1520007901, npc_spells_id = 0, special_abilities = '', aggroradius = 70, see_invis = 0, raid_target = 0, runspeed = 1.25 WHERE id = 447002;
INSERT IGNORE INTO npc_types SELECT * FROM sof_guardian_nt;
DELETE FROM sof_guardian_nt;

-- #Jon_E_V: second floor
INSERT INTO sof_guardian_nt SELECT * FROM npc_types WHERE id = 447002;
UPDATE sof_guardian_nt SET id = 447071, name = '#Jon_E_V', level = 83, hp = 280000, mindmg = 0, maxdmg = 2200, AC = 490, ATK = 250, Accuracy = 250, slow_mitigation = 0, loottable_id = 1520007902, npc_spells_id = 94901, special_abilities = '', aggroradius = 70, see_invis = 0, raid_target = 0, runspeed = 1.25 WHERE id = 447002;
INSERT IGNORE INTO npc_types SELECT * FROM sof_guardian_nt;
DELETE FROM sof_guardian_nt;

-- #THE_Destructorizor_XOOX: end of the second floor
INSERT INTO sof_guardian_nt SELECT * FROM npc_types WHERE id = 447038;
UPDATE sof_guardian_nt SET id = 447072, name = '#THE_Destructorizor_XOOX', level = 84, hp = 320000, mindmg = 0, maxdmg = 2400, AC = 500, ATK = 250, Accuracy = 250, slow_mitigation = 0, loottable_id = 1520007903, npc_spells_id = 94902, special_abilities = '', aggroradius = 70, see_invis = 0, raid_target = 0, runspeed = 1.25 WHERE id = 447038;
INSERT IGNORE INTO npc_types SELECT * FROM sof_guardian_nt;
DELETE FROM sof_guardian_nt;

-- #Whirlie_Fizzlebot: end of the second floor
INSERT INTO sof_guardian_nt SELECT * FROM npc_types WHERE id = 447033;
UPDATE sof_guardian_nt SET id = 447073, name = '#Whirlie_Fizzlebot', level = 82, hp = 240000, mindmg = 0, maxdmg = 2000, AC = 470, ATK = 250, Accuracy = 250, slow_mitigation = 0, loottable_id = 1520007904, npc_spells_id = 0, special_abilities = '', aggroradius = 70, see_invis = 0, raid_target = 0, runspeed = 1.25 WHERE id = 447033;
INSERT IGNORE INTO npc_types SELECT * FROM sof_guardian_nt;
DELETE FROM sof_guardian_nt;

-- #Fuzzbert_Cogsworth: third floor (wizard)
INSERT INTO sof_guardian_nt SELECT * FROM npc_types WHERE id = 447012;
UPDATE sof_guardian_nt SET id = 447074, name = '#Fuzzbert_Cogsworth', level = 83, hp = 250000, mindmg = 0, maxdmg = 2000, AC = 470, ATK = 250, Accuracy = 250, slow_mitigation = 0, loottable_id = 1520007905, npc_spells_id = 0, special_abilities = '', aggroradius = 70, see_invis = 0, raid_target = 0, runspeed = 1.25 WHERE id = 447012;
INSERT IGNORE INTO npc_types SELECT * FROM sof_guardian_nt;
DELETE FROM sof_guardian_nt;

-- #Metal_Slime: third floor (casts Ooze Swarm)
INSERT INTO sof_guardian_nt SELECT * FROM npc_types WHERE id = 447015;
UPDATE sof_guardian_nt SET id = 447075, name = '#Metal_Slime', level = 82, hp = 260000, mindmg = 0, maxdmg = 2100, AC = 480, ATK = 250, Accuracy = 250, slow_mitigation = 0, loottable_id = 1520007906, npc_spells_id = 94904, special_abilities = '', aggroradius = 70, see_invis = 0, raid_target = 0, runspeed = 1.25 WHERE id = 447015;
INSERT IGNORE INTO npc_types SELECT * FROM sof_guardian_nt;
DELETE FROM sof_guardian_nt;

-- #Gearlord_Memorantis: fourth floor
INSERT INTO sof_guardian_nt SELECT * FROM npc_types WHERE id = 447030;
UPDATE sof_guardian_nt SET id = 447076, name = '#Gearlord_Memorantis', level = 85, hp = 340000, mindmg = 0, maxdmg = 2400, AC = 520, ATK = 250, Accuracy = 250, slow_mitigation = 0, loottable_id = 1520007907, npc_spells_id = 0, special_abilities = '', aggroradius = 70, see_invis = 0, raid_target = 0, runspeed = 1.25 WHERE id = 447030;
INSERT IGNORE INTO npc_types SELECT * FROM sof_guardian_nt;
DELETE FROM sof_guardian_nt;

-- #Mechano_Sendaii_Dronequeen: fourth floor
INSERT INTO sof_guardian_nt SELECT * FROM npc_types WHERE id = 447047;
UPDATE sof_guardian_nt SET id = 447077, name = '#Mechano_Sendaii_Dronequeen', level = 84, hp = 300000, mindmg = 0, maxdmg = 2300, AC = 500, ATK = 250, Accuracy = 250, slow_mitigation = 0, loottable_id = 1520007908, npc_spells_id = 0, special_abilities = '', aggroradius = 70, see_invis = 0, raid_target = 0, runspeed = 1.25 WHERE id = 447047;
INSERT IGNORE INTO npc_types SELECT * FROM sof_guardian_nt;
DELETE FROM sof_guardian_nt;

-- #Coleoptera_Assault_Sweeper: top floor (casts Rust-Tainted Bite)
INSERT INTO sof_guardian_nt SELECT * FROM npc_types WHERE id = 447029;
UPDATE sof_guardian_nt SET id = 447078, name = '#Coleoptera_Assault_Sweeper', level = 85, hp = 360000, mindmg = 0, maxdmg = 2500, AC = 520, ATK = 250, Accuracy = 250, slow_mitigation = 0, loottable_id = 1520007909, npc_spells_id = 94903, special_abilities = '', aggroradius = 70, see_invis = 0, raid_target = 0, runspeed = 1.25 WHERE id = 447029;
INSERT IGNORE INTO npc_types SELECT * FROM sof_guardian_nt;
DELETE FROM sof_guardian_nt;

DROP TEMPORARY TABLE IF EXISTS sof_guardian_nt;

-- ---------------------------------------------------------------- loot
DELETE FROM `loottable_entries` WHERE `loottable_id` BETWEEN 1520007901 AND 1520007920;
DELETE FROM `lootdrop_entries` WHERE `lootdrop_id` BETWEEN 1520007901 AND 1520007920;
DELETE FROM `lootdrop` WHERE `id` BETWEEN 1520007901 AND 1520007920;
DELETE FROM `loottable` WHERE `id` BETWEEN 1520007901 AND 1520007920;

INSERT INTO `loottable` (`id`,`name`,`mincash`,`maxcash`,`avgcoin`) VALUES
(1520007901,'SoF_Guardian_steam_engineer_liiv',20000,40000,20000),
(1520007902,'SoF_Guardian_jon_e_v',20000,40000,20000),
(1520007903,'SoF_Guardian_the_destructorizor_xoox',20000,40000,20000),
(1520007904,'SoF_Guardian_whirlie_fizzlebot',20000,40000,20000),
(1520007905,'SoF_Guardian_fuzzbert_cogsworth',20000,40000,20000),
(1520007906,'SoF_Guardian_metal_slime',20000,40000,20000),
(1520007907,'SoF_Guardian_gearlord_memorantis',20000,40000,20000),
(1520007908,'SoF_Guardian_mechano_sendaii_dronequeen',20000,40000,20000),
(1520007909,'SoF_Guardian_coleoptera_assault_sweeper',20000,40000,20000);
INSERT INTO `lootdrop` (`id`,`name`) VALUES
(1520007901,'SoF_Guardian_steam_engineer_liiv_drop'),
(1520007902,'SoF_Guardian_jon_e_v_drop'),
(1520007903,'SoF_Guardian_the_destructorizor_xoox_drop'),
(1520007904,'SoF_Guardian_whirlie_fizzlebot_drop'),
(1520007905,'SoF_Guardian_fuzzbert_cogsworth_drop'),
(1520007906,'SoF_Guardian_metal_slime_drop'),
(1520007907,'SoF_Guardian_gearlord_memorantis_drop'),
(1520007908,'SoF_Guardian_mechano_sendaii_dronequeen_drop'),
(1520007909,'SoF_Guardian_coleoptera_assault_sweeper_drop');
INSERT INTO `lootdrop_entries` (`lootdrop_id`,`item_id`,`item_charges`,`equip_item`,`chance`) VALUES
(1520007901,101104,1,0,25),
(1520007901,101175,1,0,25),
(1520007901,101604,1,0,15),
(1520007902,101119,1,0,25),
(1520007902,101164,1,0,25),
(1520007902,101619,1,0,15),
(1520007903,101134,1,0,25),
(1520007903,101634,1,0,15),
(1520007904,101124,1,0,25),
(1520007904,101172,1,0,25),
(1520007904,101624,1,0,15),
(1520007905,101105,1,0,25),
(1520007905,101132,1,0,25),
(1520007905,101605,1,0,20),
(1520007905,101632,1,0,15),
(1520007906,101111,1,0,25),
(1520007906,101170,1,0,25),
(1520007906,101611,1,0,15),
(1520007907,101157,1,0,25),
(1520007908,101156,1,0,25),
(1520007909,101158,1,0,30);
INSERT INTO `loottable_entries` (`loottable_id`,`lootdrop_id`,`multiplier`,`droplimit`,`mindrop`,`probability`) VALUES
(1520007901,1520007901,1,0,0,100),
(1520007902,1520007902,1,0,0,100),
(1520007903,1520007903,1,0,0,100),
(1520007904,1520007904,1,0,0,100),
(1520007905,1520007905,1,0,0,100),
(1520007906,1520007906,1,0,0,100),
(1520007907,1520007907,1,0,0,100),
(1520007908,1520007908,1,0,0,100),
(1520007909,1520007909,1,0,0,100);

-- ---------------------------------------------------------------- spawns
DELETE FROM `spawnentry` WHERE `spawngroupID` BETWEEN 1520007911 AND 1520007930;
DELETE FROM `spawn2` WHERE `spawngroupID` BETWEEN 1520007911 AND 1520007930;
DELETE FROM `spawngroup` WHERE `id` BETWEEN 1520007911 AND 1520007930;

INSERT INTO `spawngroup` (`id`,`name`,`spawn_limit`,`dist`,`max_x`,`min_x`,`max_y`,`min_y`,`delay`,`mindelay`,`despawn`,`despawn_timer`,`wp_spawns`) VALUES
(1520007911,'sof_guardian_rare_447070',1,0,0,0,0,0,0,7200,0,300,0),
(1520007912,'sof_guardian_rare_447071',1,0,0,0,0,0,0,7200,0,300,0),
(1520007913,'sof_guardian_rare_447072',1,0,0,0,0,0,0,7200,0,300,0),
(1520007914,'sof_guardian_rare_447073',1,0,0,0,0,0,0,7200,0,300,0),
(1520007915,'sof_guardian_rare_447074',1,0,0,0,0,0,0,7200,0,300,0),
(1520007916,'sof_guardian_rare_447075',1,0,0,0,0,0,0,7200,0,300,0),
(1520007917,'sof_guardian_rare_447076',1,0,0,0,0,0,0,7200,0,300,0),
(1520007918,'sof_guardian_rare_447077',1,0,0,0,0,0,0,7200,0,300,0),
(1520007919,'sof_guardian_rare_447078',1,0,0,0,0,0,0,7200,0,300,0);
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`,`condition_value_filter`,`min_time`,`max_time`,`min_expansion`,`max_expansion`,`content_flags`,`content_flags_disabled`) VALUES
(1520007911,447070,100,1,0,0,-1,-1,NULL,NULL),
(1520007912,447071,100,1,0,0,-1,-1,NULL,NULL),
(1520007913,447072,100,1,0,0,-1,-1,NULL,NULL),
(1520007914,447073,100,1,0,0,-1,-1,NULL,NULL),
(1520007915,447074,100,1,0,0,-1,-1,NULL,NULL),
(1520007916,447075,100,1,0,0,-1,-1,NULL,NULL),
(1520007917,447076,100,1,0,0,-1,-1,NULL,NULL),
(1520007918,447077,100,1,0,0,-1,-1,NULL,NULL),
(1520007919,447078,100,1,0,0,-1,-1,NULL,NULL);
-- Anchored (gated) spawns: each rare parks on a same-floor trash spawn (TUNABLE).
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`,`_condition`,`cond_value`) SELECT 1520007911,'guardian',0,s2.x+-20,s2.y+-20,s2.z,0,7200,1,15 FROM `spawn2` s2 JOIN `spawnentry` se ON se.spawngroupID = s2.spawngroupID WHERE s2.zone='guardian' AND s2.version=0 AND (s2.z >= 0) ORDER BY s2.id LIMIT 1;
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`,`_condition`,`cond_value`) SELECT 1520007912,'guardian',0,s2.x+0,s2.y+-20,s2.z,0,7200,1,15 FROM `spawn2` s2 JOIN `spawnentry` se ON se.spawngroupID = s2.spawngroupID WHERE s2.zone='guardian' AND s2.version=0 AND (s2.z < 0 AND s2.z >= -300) ORDER BY s2.id LIMIT 1;
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`,`_condition`,`cond_value`) SELECT 1520007913,'guardian',0,s2.x+20,s2.y+-20,s2.z,0,7200,1,15 FROM `spawn2` s2 JOIN `spawnentry` se ON se.spawngroupID = s2.spawngroupID WHERE s2.zone='guardian' AND s2.version=0 AND (s2.z < 0 AND s2.z >= -300) ORDER BY s2.id LIMIT 1;
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`,`_condition`,`cond_value`) SELECT 1520007914,'guardian',0,s2.x+-20,s2.y+0,s2.z,0,7200,1,15 FROM `spawn2` s2 JOIN `spawnentry` se ON se.spawngroupID = s2.spawngroupID WHERE s2.zone='guardian' AND s2.version=0 AND (s2.z < 0 AND s2.z >= -300) ORDER BY s2.id LIMIT 1;
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`,`_condition`,`cond_value`) SELECT 1520007915,'guardian',0,s2.x+0,s2.y+0,s2.z,0,7200,1,15 FROM `spawn2` s2 JOIN `spawnentry` se ON se.spawngroupID = s2.spawngroupID WHERE s2.zone='guardian' AND s2.version=0 AND (s2.z < -300 AND s2.z >= -450) ORDER BY s2.id LIMIT 1;
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`,`_condition`,`cond_value`) SELECT 1520007916,'guardian',0,s2.x+20,s2.y+0,s2.z,0,7200,1,15 FROM `spawn2` s2 JOIN `spawnentry` se ON se.spawngroupID = s2.spawngroupID WHERE s2.zone='guardian' AND s2.version=0 AND (s2.z < -300 AND s2.z >= -450) ORDER BY s2.id LIMIT 1;
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`,`_condition`,`cond_value`) SELECT 1520007917,'guardian',0,s2.x+-20,s2.y+20,s2.z,0,7200,1,15 FROM `spawn2` s2 JOIN `spawnentry` se ON se.spawngroupID = s2.spawngroupID WHERE s2.zone='guardian' AND s2.version=0 AND (s2.z < -450 AND s2.z >= -650) ORDER BY s2.id LIMIT 1;
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`,`_condition`,`cond_value`) SELECT 1520007918,'guardian',0,s2.x+0,s2.y+20,s2.z,0,7200,1,15 FROM `spawn2` s2 JOIN `spawnentry` se ON se.spawngroupID = s2.spawngroupID WHERE s2.zone='guardian' AND s2.version=0 AND (s2.z < -450 AND s2.z >= -650) ORDER BY s2.id LIMIT 1;
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`,`_condition`,`cond_value`) SELECT 1520007919,'guardian',0,s2.x+20,s2.y+20,s2.z,0,7200,1,15 FROM `spawn2` s2 JOIN `spawnentry` se ON se.spawngroupID = s2.spawngroupID WHERE s2.zone='guardian' AND s2.version=0 AND (s2.z < -650) ORDER BY s2.id LIMIT 1;
