-- ============================================================================
-- TBS Solteris Access arc: Solteris (421) raid entry
-- Generated by hand (2026-09-20).
--
-- The arc rewards access to Solteris, the Throne of Ro. Solteris is a raid
-- zone, so it is opened as an Expedition (DynamicZoneType::Expedition) from
-- template 6109 rather than a Shared task. Elnot's [solteris] prompt creates
-- the expedition (one requester) and moves the player in; group members join
-- from the expedition window and enter with MovePCDynamicZone(421, 0).
-- Gated on completion of the final arc task 620063.
-- ============================================================================

DELETE FROM `dynamic_zone_templates` WHERE `id` = 6109;

INSERT INTO `dynamic_zone_templates`
  (`id`,`zone_id`,`zone_version`,`name`,`min_players`,`max_players`,
   `duration_seconds`,`dz_switch_id`,`compass_zone_id`,`compass_x`,`compass_y`,
   `compass_z`,`return_zone_id`,`return_x`,`return_y`,`return_z`,`return_h`,
   `override_zone_in`,`zone_in_x`,`zone_in_y`,`zone_in_z`,`zone_in_h`) VALUES
(6109,421,0,'Solteris, the Throne of Ro',1,54,21600,0,0,0,0,0,416,-2,-425,-20,0,0,0,0,0,0);
