-- ============================================================================
-- Secrets of Faydwer -- Fortress Mechanotus open world: 10 missing rares,
-- Octa the Collector raid stats + adds, rare cast wiring, Part Sorter fix.
-- Rasper: raspersrealm.com/Everquest/SoF/openFortress.html
-- Generated by sof_content/gen_rares.py -- do not hand-edit.
-- Idempotent: DELETE+INSERT on explicit verified-free ids.
-- ============================================================================

-- ---------------------------------------------------------------- rares
DELETE FROM `npc_types` WHERE `id` IN (
  436700,436701,436702,436703,436704,
  436705,436706,436707,436708,436709,
  436710,436711,436712,436713,
  436714,436715,436716,436717,436718,436719);

DELETE FROM `npc_spells_entries` WHERE `npc_spells_id` BETWEEN 1520007901 AND 1520007930;
DELETE FROM `npc_spells` WHERE `id` BETWEEN 1520007901 AND 1520007930;
INSERT INTO `npc_spells` (`id`,`name`,`parent_list`,`attack_proc`,`proc_chance`,
  `range_proc`,`rproc_chance`,`defensive_proc`,`dproc_chance`,`fail_recast`) VALUES
(1520007905,'SoF_Fortress_BITE',0,-1,3,-1,0,-1,0,0),
(1520007909,'SoF_Fortress_ELDER',0,-1,3,-1,0,-1,0,0),
(1520007906,'SoF_Fortress_FBREATH',0,-1,3,-1,0,-1,0,0),
(1520007902,'SoF_Fortress_FREEZE',0,-1,3,-1,0,-1,0,0),
(1520007908,'SoF_Fortress_GRAV',0,-1,3,-1,0,-1,0,0),
(1520007904,'SoF_Fortress_KICK',0,-1,3,-1,0,-1,0,0),
(1520007910,'SoF_Fortress_OCTA',0,-1,3,-1,0,-1,0,0),
(1520007901,'SoF_Fortress_SPRAY',0,-1,3,-1,0,-1,0,0),
(1520007903,'SoF_Fortress_STATIC',0,-1,3,-1,0,-1,0,0),
(1520007907,'SoF_Fortress_WALL',0,-1,3,-1,0,-1,0,0);
INSERT INTO `npc_spells_entries` (`npc_spells_id`,`spellid`,`type`,`minlevel`,
  `maxlevel`,`manacost`,`recast_delay`,`priority`,`resist_adjust`,`min_hp`,
  `max_hp`,`min_expansion`,`max_expansion`) VALUES
(1520007905,7943,1,0,255,-1,30,0,0,0,0,-1,-1),
(1520007909,11486,1,0,255,-1,30,0,0,0,0,-1,-1),
(1520007909,9027,1,0,255,-1,45,0,0,0,0,-1,-1),
(1520007909,8106,4,0,255,-1,25,0,0,0,0,-1,-1),
(1520007906,7946,1,0,255,-1,30,0,0,0,0,-1,-1),
(1520007902,7939,1,0,255,-1,30,0,0,0,0,-1,-1),
(1520007908,7940,1,0,255,-1,45,0,0,0,0,-1,-1),
(1520007904,7945,1,0,255,-1,30,0,0,0,0,-1,-1),
(1520007910,7739,1,0,255,-1,45,0,0,0,0,-1,-1),
(1520007901,7942,1,0,255,-1,30,0,0,0,0,-1,-1),
(1520007903,7630,1,0,255,-1,45,0,0,0,0,-1,-1),
(1520007907,7941,1,0,255,-1,30,0,0,0,0,-1,-1);

DROP TEMPORARY TABLE IF EXISTS sof_rare_nt;
CREATE TEMPORARY TABLE sof_rare_nt AS SELECT * FROM npc_types WHERE 0;

INSERT INTO sof_rare_nt SELECT * FROM npc_types WHERE id = 436037;
UPDATE sof_rare_nt SET id = 436700, name = '#Belchforth_the_Unclean', level = 82, hp = 420000, maxdmg = 3000, AC = 500, ATK = 250, Accuracy = 250, slow_mitigation = 75, loottable_id = 1520007301, npc_faction_id = 1520000073, npc_spells_id = 1520007901, special_abilities = '', aggroradius = 70, see_invis = 0, raid_target = 0 WHERE id = 436037;
INSERT IGNORE INTO npc_types SELECT * FROM sof_rare_nt;
DELETE FROM sof_rare_nt;

INSERT INTO sof_rare_nt SELECT * FROM npc_types WHERE id = 436037;
UPDATE sof_rare_nt SET id = 436701, name = '#Firemarshal_Unit_IV', level = 82, hp = 420000, maxdmg = 3000, AC = 500, ATK = 250, Accuracy = 250, slow_mitigation = 0, loottable_id = 1520007302, npc_faction_id = 1520000073, npc_spells_id = 1520007902, special_abilities = '', aggroradius = 70, see_invis = 0, raid_target = 0 WHERE id = 436037;
INSERT IGNORE INTO npc_types SELECT * FROM sof_rare_nt;
DELETE FROM sof_rare_nt;

INSERT INTO sof_rare_nt SELECT * FROM npc_types WHERE id = 436013;
UPDATE sof_rare_nt SET id = 436702, name = '#Groundskeeper_Cotongle', level = 82, hp = 420000, maxdmg = 3000, AC = 500, ATK = 250, Accuracy = 250, slow_mitigation = 0, loottable_id = 1520007303, npc_faction_id = 1520000073, npc_spells_id = 0, special_abilities = '', aggroradius = 70, see_invis = 0, raid_target = 0 WHERE id = 436013;
INSERT IGNORE INTO npc_types SELECT * FROM sof_rare_nt;
DELETE FROM sof_rare_nt;

INSERT INTO sof_rare_nt SELECT * FROM npc_types WHERE id = 436013;
UPDATE sof_rare_nt SET id = 436703, name = '#Hardbottom_Recycler_Union', level = 82, hp = 460000, maxdmg = 3500, AC = 520, ATK = 250, Accuracy = 250, slow_mitigation = 0, loottable_id = 1520007304, npc_faction_id = 1520000073, npc_spells_id = 0, special_abilities = '', aggroradius = 70, see_invis = 0, raid_target = 0 WHERE id = 436013;
INSERT IGNORE INTO npc_types SELECT * FROM sof_rare_nt;
DELETE FROM sof_rare_nt;

INSERT INTO sof_rare_nt SELECT * FROM npc_types WHERE id = 436013;
UPDATE sof_rare_nt SET id = 436704, name = '#Hogswaller', level = 82, hp = 420000, maxdmg = 3000, AC = 500, ATK = 250, Accuracy = 250, slow_mitigation = 0, loottable_id = 1520007305, npc_faction_id = 1520000073, npc_spells_id = 1520007903, special_abilities = '', aggroradius = 70, see_invis = 0, raid_target = 0 WHERE id = 436013;
INSERT IGNORE INTO npc_types SELECT * FROM sof_rare_nt;
DELETE FROM sof_rare_nt;

INSERT INTO sof_rare_nt SELECT * FROM npc_types WHERE id = 436044;
UPDATE sof_rare_nt SET id = 436705, name = '#Ironfoot', level = 83, hp = 460000, maxdmg = 3500, AC = 520, ATK = 250, Accuracy = 250, slow_mitigation = 0, loottable_id = 1520007306, npc_faction_id = 1520000073, npc_spells_id = 1520007904, special_abilities = '', aggroradius = 70, see_invis = 0, raid_target = 0 WHERE id = 436044;
INSERT IGNORE INTO npc_types SELECT * FROM sof_rare_nt;
DELETE FROM sof_rare_nt;

INSERT INTO sof_rare_nt SELECT * FROM npc_types WHERE id = 436013;
UPDATE sof_rare_nt SET id = 436706, name = '#Rusty', level = 83, hp = 460000, maxdmg = 3500, AC = 520, ATK = 250, Accuracy = 250, slow_mitigation = 0, loottable_id = 1520007307, npc_faction_id = 1520000073, npc_spells_id = 1520007905, special_abilities = '', aggroradius = 70, see_invis = 0, raid_target = 0 WHERE id = 436013;
INSERT IGNORE INTO npc_types SELECT * FROM sof_rare_nt;
DELETE FROM sof_rare_nt;

INSERT INTO sof_rare_nt SELECT * FROM npc_types WHERE id = 436044;
UPDATE sof_rare_nt SET id = 436707, name = '#Sootmane_the_Brute', level = 83, hp = 460000, maxdmg = 3500, AC = 520, ATK = 250, Accuracy = 250, slow_mitigation = 0, loottable_id = 1520007308, npc_faction_id = 1520000073, npc_spells_id = 1520007906, special_abilities = '', aggroradius = 70, see_invis = 0, raid_target = 0 WHERE id = 436044;
INSERT IGNORE INTO npc_types SELECT * FROM sof_rare_nt;
DELETE FROM sof_rare_nt;

INSERT INTO sof_rare_nt SELECT * FROM npc_types WHERE id = 436169;
UPDATE sof_rare_nt SET id = 436708, name = '#Steamwork_Guardian_Model_I', level = 84, hp = 520000, maxdmg = 4000, AC = 540, ATK = 260, Accuracy = 260, slow_mitigation = 0, loottable_id = 1520007309, npc_faction_id = 1520000073, npc_spells_id = 0, special_abilities = '1,1^4,1^8,1^24,1', aggroradius = 70, see_invis = 0, raid_target = 0 WHERE id = 436169;
INSERT IGNORE INTO npc_types SELECT * FROM sof_rare_nt;
DELETE FROM sof_rare_nt;

INSERT INTO sof_rare_nt SELECT * FROM npc_types WHERE id = 436037;
UPDATE sof_rare_nt SET id = 436709, name = '#Siegemarshal_Kenti_Tinwhistle', level = 83, hp = 460000, maxdmg = 3500, AC = 520, ATK = 250, Accuracy = 250, slow_mitigation = 0, loottable_id = 1520007310, npc_faction_id = 1520000073, npc_spells_id = 1520007907, special_abilities = '', aggroradius = 70, see_invis = 0, raid_target = 0 WHERE id = 436037;
INSERT IGNORE INTO npc_types SELECT * FROM sof_rare_nt;
DELETE FROM sof_rare_nt;

-- #a_large_systems_mechanic: boosts Octa's plate (simplified: hard-hitting guard)
INSERT INTO sof_rare_nt SELECT * FROM npc_types WHERE id = 436013;
UPDATE sof_rare_nt SET id = 436710, name = '#a_large_systems_mechanic', level = 80, hp = 160000, maxdmg = 2400, AC = 480, ATK = 240, Accuracy = 240, loottable_id = 1520007311, npc_faction_id = 1520000073, npc_spells_id = 0, aggroradius = 0 WHERE id = 436013;
INSERT IGNORE INTO npc_types SELECT * FROM sof_rare_nt;
DELETE FROM sof_rare_nt;

-- #a_large_systems_mender: 2k PBAE caster; absorbed hits punish the raid (script)
INSERT INTO sof_rare_nt SELECT * FROM npc_types WHERE id = 436037;
UPDATE sof_rare_nt SET id = 436711, name = '#a_large_systems_mender', level = 80, hp = 140000, maxdmg = 1800, AC = 480, ATK = 240, Accuracy = 240, loottable_id = 1520007311, npc_faction_id = 1520000073, npc_spells_id = 0, aggroradius = 0 WHERE id = 436037;
INSERT IGNORE INTO npc_types SELECT * FROM sof_rare_nt;
DELETE FROM sof_rare_nt;

-- #a_large_systems_trooper: DPS guard
INSERT INTO sof_rare_nt SELECT * FROM npc_types WHERE id = 436013;
UPDATE sof_rare_nt SET id = 436712, name = '#a_large_systems_trooper', level = 80, hp = 170000, maxdmg = 2600, AC = 480, ATK = 240, Accuracy = 240, loottable_id = 1520007311, npc_faction_id = 1520000073, npc_spells_id = 0, aggroradius = 0 WHERE id = 436013;
INSERT IGNORE INTO npc_types SELECT * FROM sof_rare_nt;
DELETE FROM sof_rare_nt;

-- #a_large_systems_reaper: lifetap caster; absorbed hits punish the raid (script)
INSERT INTO sof_rare_nt SELECT * FROM npc_types WHERE id = 436037;
UPDATE sof_rare_nt SET id = 436713, name = '#a_large_systems_reaper', level = 80, hp = 150000, maxdmg = 2000, AC = 480, ATK = 240, Accuracy = 240, loottable_id = 1520007311, npc_faction_id = 1520000073, npc_spells_id = 0, aggroradius = 0 WHERE id = 436037;
INSERT IGNORE INTO npc_types SELECT * FROM sof_rare_nt;
DELETE FROM sof_rare_nt;

INSERT INTO sof_rare_nt SELECT * FROM npc_types WHERE id = 436013;
UPDATE sof_rare_nt SET id = 436714, name = 'a_machinist_guard', level = 80, hp = 140000, maxdmg = 2200, AC = 460, ATK = 230, Accuracy = 230, loottable_id = 0, npc_faction_id = 1520000073, aggroradius = 0 WHERE id = 436013;
INSERT IGNORE INTO npc_types SELECT * FROM sof_rare_nt;
DELETE FROM sof_rare_nt;

INSERT INTO sof_rare_nt SELECT * FROM npc_types WHERE id = 436013;
UPDATE sof_rare_nt SET id = 436715, name = 'a_machinist_guard', level = 80, hp = 140000, maxdmg = 2200, AC = 460, ATK = 230, Accuracy = 230, loottable_id = 0, npc_faction_id = 1520000073, aggroradius = 0 WHERE id = 436013;
INSERT IGNORE INTO npc_types SELECT * FROM sof_rare_nt;
DELETE FROM sof_rare_nt;

INSERT INTO sof_rare_nt SELECT * FROM npc_types WHERE id = 436013;
UPDATE sof_rare_nt SET id = 436716, name = 'a_groundskeeper_hand', level = 80, hp = 130000, maxdmg = 2100, AC = 460, ATK = 230, Accuracy = 230, loottable_id = 0, npc_faction_id = 1520000073, aggroradius = 0 WHERE id = 436013;
INSERT IGNORE INTO npc_types SELECT * FROM sof_rare_nt;
DELETE FROM sof_rare_nt;

INSERT INTO sof_rare_nt SELECT * FROM npc_types WHERE id = 436013;
UPDATE sof_rare_nt SET id = 436717, name = 'a_groundskeeper_hand', level = 80, hp = 130000, maxdmg = 2100, AC = 460, ATK = 230, Accuracy = 230, loottable_id = 0, npc_faction_id = 1520000073, aggroradius = 0 WHERE id = 436013;
INSERT IGNORE INTO npc_types SELECT * FROM sof_rare_nt;
DELETE FROM sof_rare_nt;

INSERT INTO sof_rare_nt SELECT * FROM npc_types WHERE id = 436037;
UPDATE sof_rare_nt SET id = 436718, name = 'a_static_discharge', level = 79, hp = 110000, maxdmg = 1500, AC = 460, ATK = 230, Accuracy = 230, loottable_id = 0, npc_faction_id = 1520000073, aggroradius = 0 WHERE id = 436037;
INSERT IGNORE INTO npc_types SELECT * FROM sof_rare_nt;
DELETE FROM sof_rare_nt;

INSERT INTO sof_rare_nt SELECT * FROM npc_types WHERE id = 436037;
UPDATE sof_rare_nt SET id = 436719, name = 'a_static_discharge', level = 79, hp = 110000, maxdmg = 1500, AC = 460, ATK = 230, Accuracy = 230, loottable_id = 0, npc_faction_id = 1520000073, aggroradius = 0 WHERE id = 436037;
INSERT IGNORE INTO npc_types SELECT * FROM sof_rare_nt;
DELETE FROM sof_rare_nt;

DELETE FROM `loottable_entries` WHERE `loottable_id` BETWEEN 1520007301 AND 1520007311;
DELETE FROM `lootdrop_entries` WHERE `lootdrop_id` BETWEEN 1520007301 AND 1520007399;
DELETE FROM `lootdrop` WHERE `id` BETWEEN 1520007301 AND 1520007399;
DELETE FROM `loottable` WHERE `id` BETWEEN 1520007301 AND 1520007311;

INSERT INTO `loottable` (`id`,`name`,`mincash`,`maxcash`,`avgcoin`) VALUES
(1520007301,'SoF_Fort_belchforth_the_unclean',20000,40000,20000),
(1520007302,'SoF_Fort_firemarshal_unit_iv',20000,40000,20000),
(1520007303,'SoF_Fort_groundskeeper_cotongle',20000,40000,20000),
(1520007304,'SoF_Fort_hardbottom_recycler_union',20000,40000,20000),
(1520007305,'SoF_Fort_hogswaller',20000,40000,20000),
(1520007306,'SoF_Fort_ironfoot',20000,40000,20000),
(1520007307,'SoF_Fort_rusty',20000,40000,20000),
(1520007308,'SoF_Fort_sootmane_the_brute',20000,40000,20000),
(1520007309,'SoF_Fort_steamwork_guardian_model_i',20000,40000,20000),
(1520007310,'SoF_Fort_siegemarshal_kenti_tinwhistle',20000,40000,20000),
(1520007311,'SoF_Fort_adds',2000,4000,2000);
INSERT INTO `lootdrop` (`id`,`name`) VALUES
(1520007301,'SoF_Fort_belchforth_the_unclean_drop'),
(1520007302,'SoF_Fort_firemarshal_unit_iv_drop'),
(1520007303,'SoF_Fort_groundskeeper_cotongle_drop'),
(1520007304,'SoF_Fort_hardbottom_recycler_union_drop'),
(1520007305,'SoF_Fort_hogswaller_drop'),
(1520007306,'SoF_Fort_ironfoot_drop'),
(1520007307,'SoF_Fort_rusty_drop'),
(1520007308,'SoF_Fort_sootmane_the_brute_drop'),
(1520007309,'SoF_Fort_steamwork_guardian_model_i_drop'),
(1520007310,'SoF_Fort_siegemarshal_kenti_tinwhistle_drop'),
(1520007311,'SoF_Fort_adds_drop');
INSERT INTO `lootdrop_entries` (`lootdrop_id`,`item_id`,`item_charges`,`equip_item`,`chance`) VALUES
(1520007301,101125,1,0,30),
(1520007301,101625,1,0,15),
(1520007301,100200,1,0,6),
(1520007301,100207,1,0,6),
(1520007301,100214,1,0,6),
(1520007301,100221,1,0,6),
(1520007302,101110,1,0,30),
(1520007302,101126,1,0,20),
(1520007302,101610,1,0,15),
(1520007302,101626,1,0,15),
(1520007303,101129,1,0,30),
(1520007303,101179,1,0,25),
(1520007303,101629,1,0,15),
(1520007304,101143,1,0,30),
(1520007304,101643,1,0,15),
(1520007304,100200,1,0,6),
(1520007304,100207,1,0,6),
(1520007304,100214,1,0,6),
(1520007304,100221,1,0,6),
(1520007305,101138,1,0,30),
(1520007305,101638,1,0,15),
(1520007305,100202,1,0,6),
(1520007305,100209,1,0,6),
(1520007305,100216,1,0,6),
(1520007305,100223,1,0,6),
(1520007306,101153,1,0,30),
(1520007306,100204,1,0,6),
(1520007306,100211,1,0,6),
(1520007306,100218,1,0,6),
(1520007306,100225,1,0,6),
(1520007307,101147,1,0,30),
(1520007307,101647,1,0,15),
(1520007307,100201,1,0,6),
(1520007307,100208,1,0,6),
(1520007307,100215,1,0,6),
(1520007307,100222,1,0,6),
(1520007308,101154,1,0,30),
(1520007308,100205,1,0,6),
(1520007308,100212,1,0,6),
(1520007308,100219,1,0,6),
(1520007308,100226,1,0,6),
(1520007309,101146,1,0,30),
(1520007309,101646,1,0,15),
(1520007309,100203,1,0,6),
(1520007309,100210,1,0,6),
(1520007309,100217,1,0,6),
(1520007309,100224,1,0,6),
(1520007310,101128,1,0,30),
(1520007310,101177,1,0,25),
(1520007310,101628,1,0,15),
(1520007311,17465,1,0,15),
(1520007311,97334,1,0,15),
(1520007311,37532,1,0,8);
INSERT INTO `loottable_entries` (`loottable_id`,`lootdrop_id`,`multiplier`,`droplimit`,`mindrop`,`probability`) VALUES
(1520007301,1520007301,1,0,0,100),
(1520007302,1520007302,1,0,0,100),
(1520007303,1520007303,1,0,0,100),
(1520007304,1520007304,1,0,0,100),
(1520007305,1520007305,1,0,0,100),
(1520007306,1520007306,1,0,0,100),
(1520007307,1520007307,1,0,0,100),
(1520007308,1520007308,1,0,0,100),
(1520007309,1520007309,1,0,0,100),
(1520007310,1520007310,1,0,0,100),
(1520007311,1520007311,1,0,0,100);

-- Part Sorter (436188) ships without his two hard-mode drops; append them
-- to his live lootdrop (resolve the drop id from his table).
INSERT INTO `lootdrop_entries` (`lootdrop_id`,`item_id`,`item_charges`,`equip_item`,`chance`)
SELECT le.lootdrop_id, x.item_id, 1, 0, x.ch FROM loottable_entries le,
(SELECT 101609 item_id, 15 ch UNION ALL SELECT 101617, 15) x
WHERE le.loottable_id = 436188
  AND NOT EXISTS (SELECT 1 FROM lootdrop_entries de WHERE de.lootdrop_id = le.lootdrop_id AND de.item_id = x.item_id);

UPDATE `npc_types` SET `npc_spells_id` = 1520007908 WHERE `id` = 436179 AND `npc_spells_id` = 0;
UPDATE `npc_types` SET `npc_spells_id` = 1520007909 WHERE `id` = 436196 AND `npc_spells_id` = 0;
UPDATE `npc_types` SET `special_abilities` = '1,1^4,1^8,1^13,1' WHERE `id` = 436189 AND (`special_abilities` = '' OR `special_abilities` IS NULL);

-- Octa the Collector (436133): live loot already on table 93838
-- (decoders + T1 visible + the five named rares). Give him real stats.
UPDATE `npc_types` SET
  `class` = 1, `hp` = 3500000, `maxdmg` = 8000, `AC` = 600, `ATK` = 280,
  `Accuracy` = 280, `attack_speed` = 0, `slow_mitigation` = 80,
  `special_abilities` = '1,1^4,1^8,1^13,1^14,1^15,1^16,1^17,1^21,1^24,1^31,1', `see_invis` = 1,
  `MR` = 200, `CR` = 150, `DR` = 150, `FR` = 150, `PR` = 150,
  `npc_spells_id` = 1520007910, `raid_target` = 1
WHERE `id` = 436133;
UPDATE `spawn2` SET `respawntime` = 86400 WHERE `id` = 122900 AND `zone` = 'mechanotus';

DELETE FROM `spawnentry` WHERE `spawngroupID` BETWEEN 1520007101 AND 1520007119;
DELETE FROM `spawn2` WHERE `spawngroupID` BETWEEN 1520007101 AND 1520007119;
DELETE FROM `spawngroup` WHERE `id` BETWEEN 1520007101 AND 1520007119;

INSERT INTO `spawngroup` (`id`,`name`,`spawn_limit`,`dist`,`delay`,`mindelay`,`despawn`) VALUES
(1520007101,'sof_fort_rare_436700',1,0,7200,3600,0),
(1520007102,'sof_fort_rare_436701',1,0,7200,3600,0),
(1520007103,'sof_fort_rare_436702',1,0,7200,3600,0),
(1520007104,'sof_fort_rare_436703',1,0,7200,3600,0),
(1520007105,'sof_fort_rare_436704',1,0,7200,3600,0),
(1520007106,'sof_fort_rare_436705',1,0,7200,3600,0),
(1520007107,'sof_fort_rare_436706',1,0,7200,3600,0),
(1520007108,'sof_fort_rare_436707',1,0,7200,3600,0),
(1520007109,'sof_fort_rare_436708',1,0,7200,3600,0),
(1520007110,'sof_fort_rare_436709',1,0,7200,3600,0),
(1520007111,'sof_fort_add_436714',1,0,7200,3600,0),
(1520007112,'sof_fort_add_436715',1,0,7200,3600,0),
(1520007113,'sof_fort_add_436716',1,0,7200,3600,0),
(1520007114,'sof_fort_add_436717',1,0,7200,3600,0),
(1520007115,'sof_fort_add_436718',1,0,7200,3600,0),
(1520007116,'sof_fort_add_436719',1,0,7200,3600,0);
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES
(1520007101,436700,100),
(1520007102,436701,100),
(1520007103,436702,100),
(1520007104,436703,100),
(1520007105,436704,100),
(1520007106,436705,100),
(1520007107,436706,100),
(1520007108,436707,100),
(1520007109,436708,100),
(1520007110,436709,100),
(1520007111,436714,100),
(1520007112,436715,100),
(1520007113,436716,100),
(1520007114,436717,100),
(1520007115,436718,100),
(1520007116,436719,100);
-- Anchored spawns (TUNABLE): each rare parks on its area-trash cluster.
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) SELECT 1520007101,'mechanotus',0,s2.x,s2.y,s2.z,0,7200 FROM `spawn2` s2 JOIN `spawnentry` se ON se.spawngroupID = s2.spawngroupID WHERE s2.zone='mechanotus' AND s2.version=0 AND se.npcID=436132 ORDER BY s2.id LIMIT 1;
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) SELECT 1520007102,'mechanotus',0,s2.x,s2.y,s2.z,0,7200 FROM `spawn2` s2 JOIN `spawnentry` se ON se.spawngroupID = s2.spawngroupID WHERE s2.zone='mechanotus' AND s2.version=0 AND se.npcID=436056 ORDER BY s2.id LIMIT 1;
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) SELECT 1520007103,'mechanotus',0,s2.x,s2.y,s2.z,0,7200 FROM `spawn2` s2 JOIN `spawnentry` se ON se.spawngroupID = s2.spawngroupID WHERE s2.zone='mechanotus' AND s2.version=0 AND se.npcID=436050 ORDER BY s2.id LIMIT 1;
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) SELECT 1520007104,'mechanotus',0,s2.x,s2.y,s2.z,0,7200 FROM `spawn2` s2 JOIN `spawnentry` se ON se.spawngroupID = s2.spawngroupID WHERE s2.zone='mechanotus' AND s2.version=0 AND se.npcID=436201 ORDER BY s2.id LIMIT 1;
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) SELECT 1520007105,'mechanotus',0,s2.x,s2.y,s2.z,0,7200 FROM `spawn2` s2 JOIN `spawnentry` se ON se.spawngroupID = s2.spawngroupID WHERE s2.zone='mechanotus' AND s2.version=0 AND se.npcID=436159 ORDER BY s2.id LIMIT 1;
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) SELECT 1520007106,'mechanotus',0,s2.x,s2.y,s2.z,0,7200 FROM `spawn2` s2 JOIN `spawnentry` se ON se.spawngroupID = s2.spawngroupID WHERE s2.zone='mechanotus' AND s2.version=0 AND se.npcID=436044 ORDER BY s2.id LIMIT 1;
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) SELECT 1520007107,'mechanotus',0,s2.x,s2.y,s2.z,0,7200 FROM `spawn2` s2 JOIN `spawnentry` se ON se.spawngroupID = s2.spawngroupID WHERE s2.zone='mechanotus' AND s2.version=0 AND se.npcID=436029 ORDER BY s2.id LIMIT 1;
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) SELECT 1520007108,'mechanotus',0,s2.x,s2.y,s2.z,0,7200 FROM `spawn2` s2 JOIN `spawnentry` se ON se.spawngroupID = s2.spawngroupID WHERE s2.zone='mechanotus' AND s2.version=0 AND se.npcID=436044 ORDER BY s2.id LIMIT 1;
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) SELECT 1520007109,'mechanotus',0,s2.x,s2.y,s2.z,0,7200 FROM `spawn2` s2 JOIN `spawnentry` se ON se.spawngroupID = s2.spawngroupID WHERE s2.zone='mechanotus' AND s2.version=0 AND se.npcID=436169 ORDER BY s2.id LIMIT 1;
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) SELECT 1520007110,'mechanotus',0,s2.x,s2.y,s2.z,0,7200 FROM `spawn2` s2 JOIN `spawnentry` se ON se.spawngroupID = s2.spawngroupID WHERE s2.zone='mechanotus' AND s2.version=0 AND se.npcID=436022 ORDER BY s2.id LIMIT 1;
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) SELECT 1520007111,'mechanotus',0,s2.x+-25,s2.y+25,s2.z,0,7200 FROM `spawn2` s2 JOIN `spawnentry` se ON se.spawngroupID = s2.spawngroupID WHERE s2.zone='mechanotus' AND s2.version=0 AND se.npcID=436182 ORDER BY s2.id LIMIT 1;
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) SELECT 1520007112,'mechanotus',0,s2.x+25,s2.y+-25,s2.z,0,7200 FROM `spawn2` s2 JOIN `spawnentry` se ON se.spawngroupID = s2.spawngroupID WHERE s2.zone='mechanotus' AND s2.version=0 AND se.npcID=436182 ORDER BY s2.id LIMIT 1;
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) SELECT 1520007113,'mechanotus',0,s2.x+-25,s2.y+25,s2.z,0,7200 FROM `spawn2` s2 JOIN `spawnentry` se ON se.spawngroupID = s2.spawngroupID WHERE s2.zone='mechanotus' AND s2.version=0 AND se.npcID=436702 ORDER BY s2.id LIMIT 1;
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) SELECT 1520007114,'mechanotus',0,s2.x+25,s2.y+-25,s2.z,0,7200 FROM `spawn2` s2 JOIN `spawnentry` se ON se.spawngroupID = s2.spawngroupID WHERE s2.zone='mechanotus' AND s2.version=0 AND se.npcID=436702 ORDER BY s2.id LIMIT 1;
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) SELECT 1520007115,'mechanotus',0,s2.x+-25,s2.y+25,s2.z,0,7200 FROM `spawn2` s2 JOIN `spawnentry` se ON se.spawngroupID = s2.spawngroupID WHERE s2.zone='mechanotus' AND s2.version=0 AND se.npcID=436704 ORDER BY s2.id LIMIT 1;
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) SELECT 1520007116,'mechanotus',0,s2.x+25,s2.y+-25,s2.z,0,7200 FROM `spawn2` s2 JOIN `spawnentry` se ON se.spawngroupID = s2.spawngroupID WHERE s2.zone='mechanotus' AND s2.version=0 AND se.npcID=436704 ORDER BY s2.id LIMIT 1;

-- Octa's adds are script-spawned during the encounter
-- (quests/mechanotus/436133.lua); no static spawns.
