-- ============================================================================
-- TBS Katta Castrum: 12 Orux missions (tasks 620100-620111)
-- Generated by gen_katta_missions.py (2026-09-21).
-- All zone ids are runtime zone ids (zone.zoneidnumber):
--   kattacastrum=416, thalassius=417, atiiki=418, zhisza=419,
--   silyssar=420, solteris=421, barren=422.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- A1. quest items (clone of Etching Transcript 33959, quest-safe NoDrop)
DELETE FROM `items` WHERE `id` IN (9910002,9910003,9910004,9910005,9910006,9910007,9910008,9910009,9910010,9910011,9910012,9910013,9910014,9910015,9910016,9910017);
CREATE TEMPORARY TABLE tmp_km_item AS SELECT * FROM items WHERE id = 33959;
UPDATE tmp_km_item SET id = 9910002, Name = 'Tongue Fragment', lore = 'A rough shard of the Stone Tongue of Ateleka', loregroup = 0, NoDrop = 1;
INSERT IGNORE INTO items SELECT * FROM tmp_km_item;
DROP TEMPORARY TABLE tmp_km_item;
CREATE TEMPORARY TABLE tmp_km_item AS SELECT * FROM items WHERE id = 33959;
UPDATE tmp_km_item SET id = 9910003, Name = 'Stone Key', lore = 'A key chiseled from living stone', loregroup = 0, NoDrop = 1;
INSERT IGNORE INTO items SELECT * FROM tmp_km_item;
DROP TEMPORARY TABLE tmp_km_item;
CREATE TEMPORARY TABLE tmp_km_item AS SELECT * FROM items WHERE id = 33959;
UPDATE tmp_km_item SET id = 9910004, Name = 'Gorilla Wrangler''s Staff', lore = 'A gnarled prod used by the efreeti gardeners', loregroup = 0, NoDrop = 1;
INSERT IGNORE INTO items SELECT * FROM tmp_km_item;
DROP TEMPORARY TABLE tmp_km_item;
CREATE TEMPORARY TABLE tmp_km_item AS SELECT * FROM items WHERE id = 33959;
UPDATE tmp_km_item SET id = 9910005, Name = 'Jungle Flower', lore = 'A rare blossom from the Atiiki gardens', loregroup = 0, NoDrop = 1;
INSERT IGNORE INTO items SELECT * FROM tmp_km_item;
DROP TEMPORARY TABLE tmp_km_item;
CREATE TEMPORARY TABLE tmp_km_item AS SELECT * FROM items WHERE id = 33959;
UPDATE tmp_km_item SET id = 9910006, Name = 'Glowing Fire Coral', lore = 'A cutting of coral that pulses with inner heat', loregroup = 0, NoDrop = 1;
INSERT IGNORE INTO items SELECT * FROM tmp_km_item;
DROP TEMPORARY TABLE tmp_km_item;
CREATE TEMPORARY TABLE tmp_km_item AS SELECT * FROM items WHERE id = 33959;
UPDATE tmp_km_item SET id = 9910007, Name = 'Sneaky Shissar Scale', lore = 'A scale shed by a shissar moving through the caves', loregroup = 0, NoDrop = 1;
INSERT IGNORE INTO items SELECT * FROM tmp_km_item;
DROP TEMPORARY TABLE tmp_km_item;
CREATE TEMPORARY TABLE tmp_km_item AS SELECT * FROM items WHERE id = 33959;
UPDATE tmp_km_item SET id = 9910008, Name = 'Encoded Message', lore = 'Orders written in a cipher of the Kedge', loregroup = 0, NoDrop = 1;
INSERT IGNORE INTO items SELECT * FROM tmp_km_item;
DROP TEMPORARY TABLE tmp_km_item;
CREATE TEMPORARY TABLE tmp_km_item AS SELECT * FROM items WHERE id = 33959;
UPDATE tmp_km_item SET id = 9910009, Name = 'Kedge Secrets', lore = 'A decree bearing the marks of the Kedge elders', loregroup = 0, NoDrop = 1;
INSERT IGNORE INTO items SELECT * FROM tmp_km_item;
DROP TEMPORARY TABLE tmp_km_item;
CREATE TEMPORARY TABLE tmp_km_item AS SELECT * FROM items WHERE id = 33959;
UPDATE tmp_km_item SET id = 9910010, Name = 'Dome Repair Device', lore = 'Dewas''s field kit for sealing Shissar dome cracks', loregroup = 0, NoDrop = 1;
INSERT IGNORE INTO items SELECT * FROM tmp_km_item;
DROP TEMPORARY TABLE tmp_km_item;
CREATE TEMPORARY TABLE tmp_km_item AS SELECT * FROM items WHERE id = 33959;
UPDATE tmp_km_item SET id = 9910011, Name = 'Mark of Emperor Zhisza', lore = 'The sigil of the true Emperor, used to challenge the loyal', loregroup = 0, NoDrop = 1;
INSERT IGNORE INTO items SELECT * FROM tmp_km_item;
DROP TEMPORARY TABLE tmp_km_item;
CREATE TEMPORARY TABLE tmp_km_item AS SELECT * FROM items WHERE id = 33959;
UPDATE tmp_km_item SET id = 9910012, Name = 'Collection Bowl', lore = 'A ceremonial bowl used to gather shissar power', loregroup = 0, NoDrop = 1;
INSERT IGNORE INTO items SELECT * FROM tmp_km_item;
DROP TEMPORARY TABLE tmp_km_item;
CREATE TEMPORARY TABLE tmp_km_item AS SELECT * FROM items WHERE id = 33959;
UPDATE tmp_km_item SET id = 9910013, Name = 'Power Conduit Shard', lore = 'A fragment of a shattered power conduit', loregroup = 0, NoDrop = 1;
INSERT IGNORE INTO items SELECT * FROM tmp_km_item;
DROP TEMPORARY TABLE tmp_km_item;
CREATE TEMPORARY TABLE tmp_km_item AS SELECT * FROM items WHERE id = 33959;
UPDATE tmp_km_item SET id = 9910014, Name = 'Vial of Inky Blood', lore = 'Blood drawn from a Shissar ritualist', loregroup = 0, NoDrop = 1;
INSERT IGNORE INTO items SELECT * FROM tmp_km_item;
DROP TEMPORARY TABLE tmp_km_item;
CREATE TEMPORARY TABLE tmp_km_item AS SELECT * FROM items WHERE id = 33959;
UPDATE tmp_km_item SET id = 9910015, Name = 'Shedded Snakeskin', lore = 'An intact skin shed by one of the immortal coils', loregroup = 0, NoDrop = 1;
INSERT IGNORE INTO items SELECT * FROM tmp_km_item;
DROP TEMPORARY TABLE tmp_km_item;
CREATE TEMPORARY TABLE tmp_km_item AS SELECT * FROM items WHERE id = 33959;
UPDATE tmp_km_item SET id = 9910016, Name = 'Rituals of Essence and Blood', lore = 'A codex of the rituals that bind the coils', loregroup = 0, NoDrop = 1;
INSERT IGNORE INTO items SELECT * FROM tmp_km_item;
DROP TEMPORARY TABLE tmp_km_item;
CREATE TEMPORARY TABLE tmp_km_item AS SELECT * FROM items WHERE id = 33959;
UPDATE tmp_km_item SET id = 9910017, Name = 'Bloodletting Kris', lore = 'A ritual blade used to feed the coils', loregroup = 0, NoDrop = 1;
INSERT IGNORE INTO items SELECT * FROM tmp_km_item;
DROP TEMPORARY TABLE tmp_km_item;

-- A2. mission NPCs (clones; loottable/loot below)
DELETE FROM `npc_types` WHERE `id` IN (423915,423916,423917,423918,423919,423920,423921,423922,423923,423924,423925,423926,423927,423928,423929,423930,423931,423932,423933,423934,423935,423936,423937,423938,423939,423940,423941,423942,423943,423944);
CREATE TEMPORARY TABLE tmp_km_npc AS SELECT * FROM npc_types WHERE id = 317003 LIMIT 1;
UPDATE tmp_km_npc SET id = 423915, name = 'a_stone_tongue_golem', level = 77, maxlevel = 77, hp = 900000, AC = 550, ATK = 300, Accuracy = 380, loottable_id = 0, npc_faction_id = 0, findable = 1;
INSERT IGNORE INTO npc_types SELECT * FROM tmp_km_npc;
DROP TEMPORARY TABLE tmp_km_npc;
CREATE TEMPORARY TABLE tmp_km_npc AS SELECT * FROM npc_types WHERE name = 'Efreeti_Lord_Djarn' LIMIT 1;
UPDATE tmp_km_npc SET id = 423916, name = 'a_noble_efreeti', level = 78, maxlevel = 78, hp = 500000, AC = 550, ATK = 280, Accuracy = 360, loottable_id = 0, npc_faction_id = 0, findable = 1;
INSERT IGNORE INTO npc_types SELECT * FROM tmp_km_npc;
DROP TEMPORARY TABLE tmp_km_npc;
CREATE TEMPORARY TABLE tmp_km_npc AS SELECT * FROM npc_types WHERE id = 419021 LIMIT 1;
UPDATE tmp_km_npc SET id = 423917, name = 'an_invader_shissar', level = 75, maxlevel = 75, hp = 250000, AC = 550, ATK = 240, Accuracy = 320, loottable_id = 0, npc_faction_id = 0, findable = 1;
INSERT IGNORE INTO npc_types SELECT * FROM tmp_km_npc;
DROP TEMPORARY TABLE tmp_km_npc;
CREATE TEMPORARY TABLE tmp_km_npc AS SELECT * FROM npc_types WHERE id = 419023 LIMIT 1;
UPDATE tmp_km_npc SET id = 423918, name = 'an_invader_priest', level = 77, maxlevel = 77, hp = 350000, AC = 550, ATK = 240, Accuracy = 320, loottable_id = 0, npc_faction_id = 0, findable = 1;
INSERT IGNORE INTO npc_types SELECT * FROM tmp_km_npc;
DROP TEMPORARY TABLE tmp_km_npc;
CREATE TEMPORARY TABLE tmp_km_npc AS SELECT * FROM npc_types WHERE id = 423913 LIMIT 1;
UPDATE tmp_km_npc SET id = 423919, name = 'Emperor_Zhizuzun', level = 79, maxlevel = 79, hp = 1500000, AC = 550, ATK = 350, Accuracy = 400, loottable_id = 0, npc_faction_id = 0, findable = 1;
INSERT IGNORE INTO npc_types SELECT * FROM tmp_km_npc;
DROP TEMPORARY TABLE tmp_km_npc;
CREATE TEMPORARY TABLE tmp_km_npc AS SELECT * FROM npc_types WHERE name = 'a_hulking_gorilla' LIMIT 1;
UPDATE tmp_km_npc SET id = 423920, name = 'an_escaped_gorilla', level = 74, maxlevel = 74, hp = 300000, AC = 550, ATK = 230, Accuracy = 310, loottable_id = 0, npc_faction_id = 0, findable = 1;
INSERT IGNORE INTO npc_types SELECT * FROM tmp_km_npc;
DROP TEMPORARY TABLE tmp_km_npc;
CREATE TEMPORARY TABLE tmp_km_npc AS SELECT * FROM npc_types WHERE name = 'a_hulking_gorilla' LIMIT 1;
UPDATE tmp_km_npc SET id = 423921, name = 'Matriarch_Tusdum', level = 78, maxlevel = 78, hp = 900000, AC = 550, ATK = 300, Accuracy = 380, loottable_id = 0, npc_faction_id = 0, findable = 1;
INSERT IGNORE INTO npc_types SELECT * FROM tmp_km_npc;
DROP TEMPORARY TABLE tmp_km_npc;
CREATE TEMPORARY TABLE tmp_km_npc AS SELECT * FROM npc_types WHERE id = 417013 LIMIT 1;
UPDATE tmp_km_npc SET id = 423922, name = 'Patrikus_Grimor', level = 77, maxlevel = 77, hp = 700000, AC = 550, ATK = 280, Accuracy = 360, loottable_id = 0, npc_faction_id = 0, findable = 1;
INSERT IGNORE INTO npc_types SELECT * FROM tmp_km_npc;
DROP TEMPORARY TABLE tmp_km_npc;
CREATE TEMPORARY TABLE tmp_km_npc AS SELECT * FROM npc_types WHERE id = 417013 LIMIT 1;
UPDATE tmp_km_npc SET id = 423923, name = 'Brinor_Schmidtzen', level = 77, maxlevel = 77, hp = 700000, AC = 550, ATK = 280, Accuracy = 360, loottable_id = 0, npc_faction_id = 0, findable = 1;
INSERT IGNORE INTO npc_types SELECT * FROM tmp_km_npc;
DROP TEMPORARY TABLE tmp_km_npc;
CREATE TEMPORARY TABLE tmp_km_npc AS SELECT * FROM npc_types WHERE id = 417013 LIMIT 1;
UPDATE tmp_km_npc SET id = 423924, name = 'Wulthin_Unagi', level = 78, maxlevel = 78, hp = 1000000, AC = 550, ATK = 300, Accuracy = 380, loottable_id = 0, npc_faction_id = 0, findable = 1;
INSERT IGNORE INTO npc_types SELECT * FROM tmp_km_npc;
DROP TEMPORARY TABLE tmp_km_npc;
CREATE TEMPORARY TABLE tmp_km_npc AS SELECT * FROM npc_types WHERE id = 419021 LIMIT 1;
UPDATE tmp_km_npc SET id = 423925, name = 'Salashar_the_Blade', level = 78, maxlevel = 78, hp = 1000000, AC = 550, ATK = 310, Accuracy = 390, loottable_id = 0, npc_faction_id = 0, findable = 1;
INSERT IGNORE INTO npc_types SELECT * FROM tmp_km_npc;
DROP TEMPORARY TABLE tmp_km_npc;
CREATE TEMPORARY TABLE tmp_km_npc AS SELECT * FROM npc_types WHERE id = 417013 LIMIT 1;
UPDATE tmp_km_npc SET id = 423926, name = 'Ulthagor_Polaris', level = 79, maxlevel = 79, hp = 1100000, AC = 550, ATK = 320, Accuracy = 400, loottable_id = 0, npc_faction_id = 0, findable = 1;
INSERT IGNORE INTO npc_types SELECT * FROM tmp_km_npc;
DROP TEMPORARY TABLE tmp_km_npc;
CREATE TEMPORARY TABLE tmp_km_npc AS SELECT * FROM npc_types WHERE id = 419021 LIMIT 1;
UPDATE tmp_km_npc SET id = 423927, name = 'Rak''Tharak', level = 79, maxlevel = 79, hp = 1100000, AC = 550, ATK = 320, Accuracy = 400, loottable_id = 0, npc_faction_id = 0, findable = 1;
INSERT IGNORE INTO npc_types SELECT * FROM tmp_km_npc;
DROP TEMPORARY TABLE tmp_km_npc;
CREATE TEMPORARY TABLE tmp_km_npc AS SELECT * FROM npc_types WHERE id = 417013 LIMIT 1;
UPDATE tmp_km_npc SET id = 423928, name = 'Xao_Aulin', level = 80, maxlevel = 80, hp = 1600000, AC = 550, ATK = 340, Accuracy = 420, loottable_id = 0, npc_faction_id = 0, findable = 1;
INSERT IGNORE INTO npc_types SELECT * FROM tmp_km_npc;
DROP TEMPORARY TABLE tmp_km_npc;
CREATE TEMPORARY TABLE tmp_km_npc AS SELECT * FROM npc_types WHERE id = 417013 LIMIT 1;
UPDATE tmp_km_npc SET id = 423929, name = 'a_darkwater_clawfiend', level = 77, maxlevel = 77, hp = 200000, AC = 550, ATK = 250, Accuracy = 330, loottable_id = 0, npc_faction_id = 0, findable = 1;
INSERT IGNORE INTO npc_types SELECT * FROM tmp_km_npc;
DROP TEMPORARY TABLE tmp_km_npc;
CREATE TEMPORARY TABLE tmp_km_npc AS SELECT * FROM npc_types WHERE id = 417013 LIMIT 1;
UPDATE tmp_km_npc SET id = 423930, name = 'a_raging_sea_dervish', level = 77, maxlevel = 77, hp = 200000, AC = 550, ATK = 250, Accuracy = 330, loottable_id = 0, npc_faction_id = 0, findable = 1;
INSERT IGNORE INTO npc_types SELECT * FROM tmp_km_npc;
DROP TEMPORARY TABLE tmp_km_npc;
CREATE TEMPORARY TABLE tmp_km_npc AS SELECT * FROM npc_types WHERE id = 417013 LIMIT 1;
UPDATE tmp_km_npc SET id = 423931, name = 'a_sea_mephit', level = 76, maxlevel = 76, hp = 150000, AC = 550, ATK = 220, Accuracy = 300, loottable_id = 0, npc_faction_id = 0, findable = 1;
INSERT IGNORE INTO npc_types SELECT * FROM tmp_km_npc;
DROP TEMPORARY TABLE tmp_km_npc;
CREATE TEMPORARY TABLE tmp_km_npc AS SELECT * FROM npc_types WHERE id = 421000 LIMIT 1;
UPDATE tmp_km_npc SET id = 423932, name = 'a_fire_coral', level = 1, maxlevel = 1, hp = 12, AC = 550, ATK = 0, Accuracy = 0, loottable_id = 6210111, npc_faction_id = 0, findable = 1;
INSERT IGNORE INTO npc_types SELECT * FROM tmp_km_npc;
DROP TEMPORARY TABLE tmp_km_npc;
CREATE TEMPORARY TABLE tmp_km_npc AS SELECT * FROM npc_types WHERE id = 419021 LIMIT 1;
UPDATE tmp_km_npc SET id = 423933, name = 'Shissar_Supervisor_Sslarn', level = 79, maxlevel = 79, hp = 1000000, AC = 550, ATK = 320, Accuracy = 400, loottable_id = 0, npc_faction_id = 0, findable = 1;
INSERT IGNORE INTO npc_types SELECT * FROM tmp_km_npc;
DROP TEMPORARY TABLE tmp_km_npc;
CREATE TEMPORARY TABLE tmp_km_npc AS SELECT * FROM npc_types WHERE id = 419021 LIMIT 1;
UPDATE tmp_km_npc SET id = 423934, name = 'Shissar_Supervisor_Enpsa', level = 79, maxlevel = 79, hp = 1000000, AC = 550, ATK = 320, Accuracy = 400, loottable_id = 0, npc_faction_id = 0, findable = 1;
INSERT IGNORE INTO npc_types SELECT * FROM tmp_km_npc;
DROP TEMPORARY TABLE tmp_km_npc;
CREATE TEMPORARY TABLE tmp_km_npc AS SELECT * FROM npc_types WHERE id = 419021 LIMIT 1;
UPDATE tmp_km_npc SET id = 423935, name = 'Shissar_Supervisor_Mozull', level = 79, maxlevel = 79, hp = 1000000, AC = 550, ATK = 320, Accuracy = 400, loottable_id = 0, npc_faction_id = 0, findable = 1;
INSERT IGNORE INTO npc_types SELECT * FROM tmp_km_npc;
DROP TEMPORARY TABLE tmp_km_npc;
CREATE TEMPORARY TABLE tmp_km_npc AS SELECT * FROM npc_types WHERE id = 421000 LIMIT 1;
UPDATE tmp_km_npc SET id = 423936, name = 'a_dome_crack', level = 1, maxlevel = 1, hp = 11, AC = 550, ATK = 0, Accuracy = 0, loottable_id = 0, npc_faction_id = 0, findable = 1;
INSERT IGNORE INTO npc_types SELECT * FROM tmp_km_npc;
DROP TEMPORARY TABLE tmp_km_npc;
CREATE TEMPORARY TABLE tmp_km_npc AS SELECT * FROM npc_types WHERE id = 419021 LIMIT 1;
UPDATE tmp_km_npc SET id = 423937, name = 'an_ambush_shissar', level = 76, maxlevel = 76, hp = 300000, AC = 550, ATK = 260, Accuracy = 340, loottable_id = 0, npc_faction_id = 0, findable = 1;
INSERT IGNORE INTO npc_types SELECT * FROM tmp_km_npc;
DROP TEMPORARY TABLE tmp_km_npc;
CREATE TEMPORARY TABLE tmp_km_npc AS SELECT * FROM npc_types WHERE id = 419023 LIMIT 1;
UPDATE tmp_km_npc SET id = 423938, name = 'a_shissar_ritualist', level = 78, maxlevel = 78, hp = 700000, AC = 550, ATK = 300, Accuracy = 380, loottable_id = 6210113, npc_faction_id = 0, findable = 1;
INSERT IGNORE INTO npc_types SELECT * FROM tmp_km_npc;
DROP TEMPORARY TABLE tmp_km_npc;
CREATE TEMPORARY TABLE tmp_km_npc AS SELECT * FROM npc_types WHERE id = 317003 LIMIT 1;
UPDATE tmp_km_npc SET id = 423939, name = 'a_power_conduit', level = 75, maxlevel = 75, hp = 150000, AC = 550, ATK = 0, Accuracy = 0, loottable_id = 6210112, npc_faction_id = 0, findable = 1;
INSERT IGNORE INTO npc_types SELECT * FROM tmp_km_npc;
DROP TEMPORARY TABLE tmp_km_npc;
CREATE TEMPORARY TABLE tmp_km_npc AS SELECT * FROM npc_types WHERE id = 421000 LIMIT 1;
UPDATE tmp_km_npc SET id = 423940, name = 'a_collection_bowl', level = 1, maxlevel = 1, hp = 12, AC = 550, ATK = 0, Accuracy = 0, loottable_id = 6210114, npc_faction_id = 0, findable = 1;
INSERT IGNORE INTO npc_types SELECT * FROM tmp_km_npc;
DROP TEMPORARY TABLE tmp_km_npc;
CREATE TEMPORARY TABLE tmp_km_npc AS SELECT * FROM npc_types WHERE id = 421000 LIMIT 1;
UPDATE tmp_km_npc SET id = 423941, name = 'an_ornate_chest', level = 1, maxlevel = 1, hp = 12, AC = 550, ATK = 0, Accuracy = 0, loottable_id = 6210115, npc_faction_id = 0, findable = 1;
INSERT IGNORE INTO npc_types SELECT * FROM tmp_km_npc;
DROP TEMPORARY TABLE tmp_km_npc;
CREATE TEMPORARY TABLE tmp_km_npc AS SELECT * FROM npc_types WHERE id = 419023 LIMIT 1;
UPDATE tmp_km_npc SET id = 423942, name = 'a_shissar_slave', level = 50, maxlevel = 50, hp = 100, AC = 550, ATK = 0, Accuracy = 0, loottable_id = 0, npc_faction_id = 0, findable = 1;
INSERT IGNORE INTO npc_types SELECT * FROM tmp_km_npc;
DROP TEMPORARY TABLE tmp_km_npc;
CREATE TEMPORARY TABLE tmp_km_npc AS SELECT * FROM npc_types WHERE id = 421000 LIMIT 1;
UPDATE tmp_km_npc SET id = 423943, name = 'Rituals_of_Essence_and_Blood', level = 1, maxlevel = 1, hp = 12, AC = 550, ATK = 0, Accuracy = 0, loottable_id = 6210116, npc_faction_id = 0, findable = 1;
INSERT IGNORE INTO npc_types SELECT * FROM tmp_km_npc;
DROP TEMPORARY TABLE tmp_km_npc;
CREATE TEMPORARY TABLE tmp_km_npc AS SELECT * FROM npc_types WHERE id = 419023 LIMIT 1;
UPDATE tmp_km_npc SET id = 423944, name = 'a_shissar_sacrificer', level = 77, maxlevel = 77, hp = 500000, AC = 550, ATK = 280, Accuracy = 360, loottable_id = 6210117, npc_faction_id = 0, findable = 1;
INSERT IGNORE INTO npc_types SELECT * FROM tmp_km_npc;
DROP TEMPORARY TABLE tmp_km_npc;

-- A3. loot
DELETE FROM `loottable_entries` WHERE `loottable_id` BETWEEN 6210111 AND 6210118;
DELETE FROM `lootdrop_entries` WHERE `lootdrop_id` BETWEEN 6210101 AND 6210107;
DELETE FROM `lootdrop` WHERE `id` BETWEEN 6210101 AND 6210107;
DELETE FROM `loottable` WHERE `id` BETWEEN 6210111 AND 6210118;
INSERT INTO `lootdrop` (`id`,`name`) VALUES
(6210101,'TBSM_6210101'),
(6210102,'TBSM_6210102'),
(6210103,'TBSM_6210103'),
(6210104,'TBSM_6210104'),
(6210105,'TBSM_6210105'),
(6210106,'TBSM_6210106'),
(6210107,'TBSM_6210107');
INSERT INTO `lootdrop_entries` (`lootdrop_id`,`item_id`,`item_charges`,`chance`) VALUES
(6210101,9910006,1,100),
(6210102,9910013,1,100),
(6210103,9910014,1,100),
(6210104,9910015,1,100),
(6210105,9910016,1,100),
(6210106,9910017,1,100),
(6210107,9910007,1,8);
INSERT INTO `loottable` (`id`,`name`) VALUES
(6210111,'TBSM_Fire_Coral'),
(6210112,'TBSM_Power_Conduit'),
(6210113,'TBSM_Ritualist'),
(6210114,'TBSM_Collection_Bowl'),
(6210115,'TBSM_Ornate_Chest'),
(6210116,'TBSM_Rituals_Book'),
(6210117,'TBSM_Sacrificer'),
(6210118,'TBSM_Sneaky_Scale');
INSERT INTO `loottable_entries` (`loottable_id`,`lootdrop_id`,`multiplier`,`droplimit`,`mindrop`,`probability`) VALUES
(6210111,6210101,1,0,0,100),
(6210112,6210102,1,0,0,100),
(6210113,6210103,1,0,0,100),
(6210115,6210104,1,0,0,100),
(6210116,6210105,1,0,0,100),
(6210117,6210106,1,0,0,100),
(6210118,6210107,1,0,0,100);

-- Sneaky Shissar Scale rides existing Thalassius trash loottables (additive).
INSERT IGNORE INTO `loottable_entries` (`loottable_id`,`lootdrop_id`,`multiplier`,`droplimit`,`mindrop`,`probability`) VALUES
(93375,6210107,1,0,0,100),(93376,6210107,1,0,0,100),(93384,6210107,1,0,0,100);

-- A4. spawns (anchored at existing same-zone spawns; tune with #npcspawn)
DELETE FROM `spawn2` WHERE `spawngroupID` IN (SELECT `spawngroupID` FROM `spawnentry` WHERE `npcID` = 423920) AND `zone` = 'atiiki';
DELETE FROM `spawn2` WHERE `spawngroupID` IN (SELECT `spawngroupID` FROM `spawnentry` WHERE `npcID` = 423920) AND `zone` = 'atiiki';
DELETE FROM `spawn2` WHERE `spawngroupID` IN (SELECT `spawngroupID` FROM `spawnentry` WHERE `npcID` = 423920) AND `zone` = 'atiiki';
DELETE FROM `spawn2` WHERE `spawngroupID` IN (SELECT `spawngroupID` FROM `spawnentry` WHERE `npcID` = 423920) AND `zone` = 'atiiki';
DELETE FROM `spawn2` WHERE `spawngroupID` IN (SELECT `spawngroupID` FROM `spawnentry` WHERE `npcID` = 423920) AND `zone` = 'atiiki';
DELETE FROM `spawn2` WHERE `spawngroupID` IN (SELECT `spawngroupID` FROM `spawnentry` WHERE `npcID` = 423920) AND `zone` = 'atiiki';
DELETE FROM `spawn2` WHERE `spawngroupID` IN (SELECT `spawngroupID` FROM `spawnentry` WHERE `npcID` = 423920) AND `zone` = 'atiiki';
DELETE FROM `spawn2` WHERE `spawngroupID` IN (SELECT `spawngroupID` FROM `spawnentry` WHERE `npcID` = 423920) AND `zone` = 'atiiki';
DELETE FROM `spawn2` WHERE `spawngroupID` IN (SELECT `spawngroupID` FROM `spawnentry` WHERE `npcID` = 423920) AND `zone` = 'atiiki';
DELETE FROM `spawn2` WHERE `spawngroupID` IN (SELECT `spawngroupID` FROM `spawnentry` WHERE `npcID` = 423920) AND `zone` = 'atiiki';
DELETE FROM `spawn2` WHERE `spawngroupID` IN (SELECT `spawngroupID` FROM `spawnentry` WHERE `npcID` = 423921) AND `zone` = 'atiiki';
DELETE FROM `spawn2` WHERE `spawngroupID` IN (SELECT `spawngroupID` FROM `spawnentry` WHERE `npcID` = 423932) AND `zone` = 'thalassius';
DELETE FROM `spawn2` WHERE `spawngroupID` IN (SELECT `spawngroupID` FROM `spawnentry` WHERE `npcID` = 423932) AND `zone` = 'thalassius';
DELETE FROM `spawn2` WHERE `spawngroupID` IN (SELECT `spawngroupID` FROM `spawnentry` WHERE `npcID` = 423932) AND `zone` = 'thalassius';
DELETE FROM `spawn2` WHERE `spawngroupID` IN (SELECT `spawngroupID` FROM `spawnentry` WHERE `npcID` = 423932) AND `zone` = 'thalassius';
DELETE FROM `spawn2` WHERE `spawngroupID` IN (SELECT `spawngroupID` FROM `spawnentry` WHERE `npcID` = 423932) AND `zone` = 'thalassius';
DELETE FROM `spawn2` WHERE `spawngroupID` IN (SELECT `spawngroupID` FROM `spawnentry` WHERE `npcID` = 423932) AND `zone` = 'thalassius';
DELETE FROM `spawn2` WHERE `spawngroupID` IN (SELECT `spawngroupID` FROM `spawnentry` WHERE `npcID` = 423932) AND `zone` = 'thalassius';
DELETE FROM `spawn2` WHERE `spawngroupID` IN (SELECT `spawngroupID` FROM `spawnentry` WHERE `npcID` = 423932) AND `zone` = 'thalassius';
DELETE FROM `spawn2` WHERE `spawngroupID` IN (SELECT `spawngroupID` FROM `spawnentry` WHERE `npcID` = 423932) AND `zone` = 'thalassius';
DELETE FROM `spawn2` WHERE `spawngroupID` IN (SELECT `spawngroupID` FROM `spawnentry` WHERE `npcID` = 423932) AND `zone` = 'thalassius';
DELETE FROM `spawn2` WHERE `spawngroupID` IN (SELECT `spawngroupID` FROM `spawnentry` WHERE `npcID` = 423922) AND `zone` = 'thalassius';
DELETE FROM `spawn2` WHERE `spawngroupID` IN (SELECT `spawngroupID` FROM `spawnentry` WHERE `npcID` = 423923) AND `zone` = 'thalassius';
DELETE FROM `spawn2` WHERE `spawngroupID` IN (SELECT `spawngroupID` FROM `spawnentry` WHERE `npcID` = 423924) AND `zone` = 'thalassius';
DELETE FROM `spawn2` WHERE `spawngroupID` IN (SELECT `spawngroupID` FROM `spawnentry` WHERE `npcID` = 423925) AND `zone` = 'thalassius';
DELETE FROM `spawn2` WHERE `spawngroupID` IN (SELECT `spawngroupID` FROM `spawnentry` WHERE `npcID` = 423926) AND `zone` = 'thalassius';
DELETE FROM `spawn2` WHERE `spawngroupID` IN (SELECT `spawngroupID` FROM `spawnentry` WHERE `npcID` = 423927) AND `zone` = 'thalassius';
DELETE FROM `spawn2` WHERE `spawngroupID` IN (SELECT `spawngroupID` FROM `spawnentry` WHERE `npcID` = 423928) AND `zone` = 'thalassius';
DELETE FROM `spawn2` WHERE `spawngroupID` IN (SELECT `spawngroupID` FROM `spawnentry` WHERE `npcID` = 423933) AND `zone` = 'zhisza';
DELETE FROM `spawn2` WHERE `spawngroupID` IN (SELECT `spawngroupID` FROM `spawnentry` WHERE `npcID` = 423934) AND `zone` = 'zhisza';
DELETE FROM `spawn2` WHERE `spawngroupID` IN (SELECT `spawngroupID` FROM `spawnentry` WHERE `npcID` = 423935) AND `zone` = 'zhisza';
DELETE FROM `spawn2` WHERE `spawngroupID` IN (SELECT `spawngroupID` FROM `spawnentry` WHERE `npcID` = 423936) AND `zone` = 'zhisza';
DELETE FROM `spawn2` WHERE `spawngroupID` IN (SELECT `spawngroupID` FROM `spawnentry` WHERE `npcID` = 423936) AND `zone` = 'zhisza';
DELETE FROM `spawn2` WHERE `spawngroupID` IN (SELECT `spawngroupID` FROM `spawnentry` WHERE `npcID` = 423936) AND `zone` = 'zhisza';
DELETE FROM `spawn2` WHERE `spawngroupID` IN (SELECT `spawngroupID` FROM `spawnentry` WHERE `npcID` = 423940) AND `zone` = 'silyssar';
DELETE FROM `spawn2` WHERE `spawngroupID` IN (SELECT `spawngroupID` FROM `spawnentry` WHERE `npcID` = 423940) AND `zone` = 'silyssar';
DELETE FROM `spawn2` WHERE `spawngroupID` IN (SELECT `spawngroupID` FROM `spawnentry` WHERE `npcID` = 423940) AND `zone` = 'silyssar';
DELETE FROM `spawn2` WHERE `spawngroupID` IN (SELECT `spawngroupID` FROM `spawnentry` WHERE `npcID` = 423940) AND `zone` = 'silyssar';
DELETE FROM `spawn2` WHERE `spawngroupID` IN (SELECT `spawngroupID` FROM `spawnentry` WHERE `npcID` = 423939) AND `zone` = 'silyssar';
DELETE FROM `spawn2` WHERE `spawngroupID` IN (SELECT `spawngroupID` FROM `spawnentry` WHERE `npcID` = 423939) AND `zone` = 'silyssar';
DELETE FROM `spawn2` WHERE `spawngroupID` IN (SELECT `spawngroupID` FROM `spawnentry` WHERE `npcID` = 423938) AND `zone` = 'silyssar';
DELETE FROM `spawn2` WHERE `spawngroupID` IN (SELECT `spawngroupID` FROM `spawnentry` WHERE `npcID` = 423938) AND `zone` = 'silyssar';
DELETE FROM `spawn2` WHERE `spawngroupID` IN (SELECT `spawngroupID` FROM `spawnentry` WHERE `npcID` = 423941) AND `zone` = 'silyssar';
DELETE FROM `spawn2` WHERE `spawngroupID` IN (SELECT `spawngroupID` FROM `spawnentry` WHERE `npcID` = 423941) AND `zone` = 'silyssar';
DELETE FROM `spawn2` WHERE `spawngroupID` IN (SELECT `spawngroupID` FROM `spawnentry` WHERE `npcID` = 423941) AND `zone` = 'silyssar';
DELETE FROM `spawn2` WHERE `spawngroupID` IN (SELECT `spawngroupID` FROM `spawnentry` WHERE `npcID` = 423941) AND `zone` = 'silyssar';
DELETE FROM `spawn2` WHERE `spawngroupID` IN (SELECT `spawngroupID` FROM `spawnentry` WHERE `npcID` = 423941) AND `zone` = 'silyssar';
DELETE FROM `spawn2` WHERE `spawngroupID` IN (SELECT `spawngroupID` FROM `spawnentry` WHERE `npcID` = 423941) AND `zone` = 'silyssar';
DELETE FROM `spawn2` WHERE `spawngroupID` IN (SELECT `spawngroupID` FROM `spawnentry` WHERE `npcID` = 423943) AND `zone` = 'silyssar';
DELETE FROM `spawn2` WHERE `spawngroupID` IN (SELECT `spawngroupID` FROM `spawnentry` WHERE `npcID` = 423943) AND `zone` = 'silyssar';
DELETE FROM `spawn2` WHERE `spawngroupID` IN (SELECT `spawngroupID` FROM `spawnentry` WHERE `npcID` = 423943) AND `zone` = 'silyssar';
DELETE FROM `spawn2` WHERE `spawngroupID` IN (SELECT `spawngroupID` FROM `spawnentry` WHERE `npcID` = 423942) AND `zone` = 'silyssar';
DELETE FROM `spawn2` WHERE `spawngroupID` IN (SELECT `spawngroupID` FROM `spawnentry` WHERE `npcID` = 423942) AND `zone` = 'silyssar';
DELETE FROM `spawn2` WHERE `spawngroupID` IN (SELECT `spawngroupID` FROM `spawnentry` WHERE `npcID` = 423942) AND `zone` = 'silyssar';
DELETE FROM `spawn2` WHERE `spawngroupID` IN (SELECT `spawngroupID` FROM `spawnentry` WHERE `npcID` = 423942) AND `zone` = 'silyssar';
DELETE FROM `spawn2` WHERE `spawngroupID` IN (SELECT `spawngroupID` FROM `spawnentry` WHERE `npcID` = 423942) AND `zone` = 'silyssar';
DELETE FROM `spawn2` WHERE `spawngroupID` IN (SELECT `spawngroupID` FROM `spawnentry` WHERE `npcID` = 423942) AND `zone` = 'silyssar';
DELETE FROM `spawn2` WHERE `spawngroupID` IN (SELECT `spawngroupID` FROM `spawnentry` WHERE `npcID` = 423944) AND `zone` = 'silyssar';
DELETE FROM `spawn2` WHERE `spawngroupID` IN (SELECT `spawngroupID` FROM `spawnentry` WHERE `npcID` = 423944) AND `zone` = 'silyssar';
DELETE FROM `spawn2` WHERE `spawngroupID` IN (SELECT `spawngroupID` FROM `spawnentry` WHERE `npcID` = 423944) AND `zone` = 'silyssar';
DELETE FROM `spawn2` WHERE `spawngroupID` IN (SELECT `spawngroupID` FROM `spawnentry` WHERE `npcID` = 423944) AND `zone` = 'silyssar';
DELETE FROM `spawn2` WHERE `spawngroupID` IN (SELECT `spawngroupID` FROM `spawnentry` WHERE `npcID` = 423944) AND `zone` = 'silyssar';
DELETE FROM `spawn2` WHERE `spawngroupID` IN (SELECT `spawngroupID` FROM `spawnentry` WHERE `npcID` = 423944) AND `zone` = 'silyssar';
DELETE FROM `spawnentry` WHERE `npcID` BETWEEN 423915 AND 423944;
DELETE FROM `spawngroup` WHERE `name` LIKE 'tbs_mission_%';

INSERT INTO `spawngroup` (`name`,`spawn_limit`,`dist`,`max_x`,`min_x`,`max_y`,`min_y`,`delay`,`mindelay`,`despawn`,`despawn_timer`,`wp_spawns`) VALUES ('tbs_mission_gorilla1',0,0,0,0,0,0,0,15000,0,100,0);
SET @g := LAST_INSERT_ID();
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (@g,423920,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) SELECT @g,'atiiki',0,s2.x+15,s2.y+15,s2.z+0,0,640 FROM spawn2 s2 WHERE s2.id = 116702 LIMIT 1;

INSERT INTO `spawngroup` (`name`,`spawn_limit`,`dist`,`max_x`,`min_x`,`max_y`,`min_y`,`delay`,`mindelay`,`despawn`,`despawn_timer`,`wp_spawns`) VALUES ('tbs_mission_gorilla2',0,0,0,0,0,0,0,15000,0,100,0);
SET @g := LAST_INSERT_ID();
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (@g,423920,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) SELECT @g,'atiiki',0,s2.x+-25,s2.y+30,s2.z+0,0,640 FROM spawn2 s2 WHERE s2.id = 116702 LIMIT 1;

INSERT INTO `spawngroup` (`name`,`spawn_limit`,`dist`,`max_x`,`min_x`,`max_y`,`min_y`,`delay`,`mindelay`,`despawn`,`despawn_timer`,`wp_spawns`) VALUES ('tbs_mission_gorilla3',0,0,0,0,0,0,0,15000,0,100,0);
SET @g := LAST_INSERT_ID();
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (@g,423920,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) SELECT @g,'atiiki',0,s2.x+40,s2.y+-20,s2.z+0,0,640 FROM spawn2 s2 WHERE s2.id = 116702 LIMIT 1;

INSERT INTO `spawngroup` (`name`,`spawn_limit`,`dist`,`max_x`,`min_x`,`max_y`,`min_y`,`delay`,`mindelay`,`despawn`,`despawn_timer`,`wp_spawns`) VALUES ('tbs_mission_gorilla4',0,0,0,0,0,0,0,15000,0,100,0);
SET @g := LAST_INSERT_ID();
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (@g,423920,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) SELECT @g,'atiiki',0,s2.x+-40,s2.y+-30,s2.z+0,0,640 FROM spawn2 s2 WHERE s2.id = 116702 LIMIT 1;

INSERT INTO `spawngroup` (`name`,`spawn_limit`,`dist`,`max_x`,`min_x`,`max_y`,`min_y`,`delay`,`mindelay`,`despawn`,`despawn_timer`,`wp_spawns`) VALUES ('tbs_mission_gorilla5',0,0,0,0,0,0,0,15000,0,100,0);
SET @g := LAST_INSERT_ID();
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (@g,423920,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) SELECT @g,'atiiki',0,s2.x+20,s2.y+25,s2.z+0,0,640 FROM spawn2 s2 WHERE s2.id = 116712 LIMIT 1;

INSERT INTO `spawngroup` (`name`,`spawn_limit`,`dist`,`max_x`,`min_x`,`max_y`,`min_y`,`delay`,`mindelay`,`despawn`,`despawn_timer`,`wp_spawns`) VALUES ('tbs_mission_gorilla6',0,0,0,0,0,0,0,15000,0,100,0);
SET @g := LAST_INSERT_ID();
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (@g,423920,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) SELECT @g,'atiiki',0,s2.x+-30,s2.y+20,s2.z+0,0,640 FROM spawn2 s2 WHERE s2.id = 116712 LIMIT 1;

INSERT INTO `spawngroup` (`name`,`spawn_limit`,`dist`,`max_x`,`min_x`,`max_y`,`min_y`,`delay`,`mindelay`,`despawn`,`despawn_timer`,`wp_spawns`) VALUES ('tbs_mission_gorilla7',0,0,0,0,0,0,0,15000,0,100,0);
SET @g := LAST_INSERT_ID();
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (@g,423920,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) SELECT @g,'atiiki',0,s2.x+35,s2.y+35,s2.z+0,0,640 FROM spawn2 s2 WHERE s2.id = 116712 LIMIT 1;

INSERT INTO `spawngroup` (`name`,`spawn_limit`,`dist`,`max_x`,`min_x`,`max_y`,`min_y`,`delay`,`mindelay`,`despawn`,`despawn_timer`,`wp_spawns`) VALUES ('tbs_mission_gorilla8',0,0,0,0,0,0,0,15000,0,100,0);
SET @g := LAST_INSERT_ID();
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (@g,423920,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) SELECT @g,'atiiki',0,s2.x+-20,s2.y+-35,s2.z+0,0,640 FROM spawn2 s2 WHERE s2.id = 116712 LIMIT 1;

INSERT INTO `spawngroup` (`name`,`spawn_limit`,`dist`,`max_x`,`min_x`,`max_y`,`min_y`,`delay`,`mindelay`,`despawn`,`despawn_timer`,`wp_spawns`) VALUES ('tbs_mission_gorilla9',0,0,0,0,0,0,0,15000,0,100,0);
SET @g := LAST_INSERT_ID();
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (@g,423920,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) SELECT @g,'atiiki',0,s2.x+55,s2.y+5,s2.z+0,0,640 FROM spawn2 s2 WHERE s2.id = 116702 LIMIT 1;

INSERT INTO `spawngroup` (`name`,`spawn_limit`,`dist`,`max_x`,`min_x`,`max_y`,`min_y`,`delay`,`mindelay`,`despawn`,`despawn_timer`,`wp_spawns`) VALUES ('tbs_mission_gorilla10',0,0,0,0,0,0,0,15000,0,100,0);
SET @g := LAST_INSERT_ID();
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (@g,423920,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) SELECT @g,'atiiki',0,s2.x+5,s2.y+55,s2.z+0,0,640 FROM spawn2 s2 WHERE s2.id = 116702 LIMIT 1;

INSERT INTO `spawngroup` (`name`,`spawn_limit`,`dist`,`max_x`,`min_x`,`max_y`,`min_y`,`delay`,`mindelay`,`despawn`,`despawn_timer`,`wp_spawns`) VALUES ('tbs_mission_matriarch',0,0,0,0,0,0,0,15000,0,100,0);
SET @g := LAST_INSERT_ID();
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (@g,423921,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) SELECT @g,'atiiki',0,s2.x+60,s2.y+60,s2.z+0,0,640 FROM spawn2 s2 WHERE s2.id = 116712 LIMIT 1;

INSERT INTO `spawngroup` (`name`,`spawn_limit`,`dist`,`max_x`,`min_x`,`max_y`,`min_y`,`delay`,`mindelay`,`despawn`,`despawn_timer`,`wp_spawns`) VALUES ('tbs_mission_coral1',0,0,0,0,0,0,0,15000,0,100,0);
SET @g := LAST_INSERT_ID();
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (@g,423932,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) SELECT @g,'thalassius',0,s2.x+20,s2.y+10,s2.z+0,0,640 FROM spawn2 s2 WHERE s2.id = 117059 LIMIT 1;

INSERT INTO `spawngroup` (`name`,`spawn_limit`,`dist`,`max_x`,`min_x`,`max_y`,`min_y`,`delay`,`mindelay`,`despawn`,`despawn_timer`,`wp_spawns`) VALUES ('tbs_mission_coral2',0,0,0,0,0,0,0,15000,0,100,0);
SET @g := LAST_INSERT_ID();
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (@g,423932,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) SELECT @g,'thalassius',0,s2.x+-20,s2.y+25,s2.z+0,0,640 FROM spawn2 s2 WHERE s2.id = 117059 LIMIT 1;

INSERT INTO `spawngroup` (`name`,`spawn_limit`,`dist`,`max_x`,`min_x`,`max_y`,`min_y`,`delay`,`mindelay`,`despawn`,`despawn_timer`,`wp_spawns`) VALUES ('tbs_mission_coral3',0,0,0,0,0,0,0,15000,0,100,0);
SET @g := LAST_INSERT_ID();
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (@g,423932,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) SELECT @g,'thalassius',0,s2.x+15,s2.y+-20,s2.z+0,0,640 FROM spawn2 s2 WHERE s2.id = 117060 LIMIT 1;

INSERT INTO `spawngroup` (`name`,`spawn_limit`,`dist`,`max_x`,`min_x`,`max_y`,`min_y`,`delay`,`mindelay`,`despawn`,`despawn_timer`,`wp_spawns`) VALUES ('tbs_mission_coral4',0,0,0,0,0,0,0,15000,0,100,0);
SET @g := LAST_INSERT_ID();
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (@g,423932,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) SELECT @g,'thalassius',0,s2.x+30,s2.y+15,s2.z+0,0,640 FROM spawn2 s2 WHERE s2.id = 117060 LIMIT 1;

INSERT INTO `spawngroup` (`name`,`spawn_limit`,`dist`,`max_x`,`min_x`,`max_y`,`min_y`,`delay`,`mindelay`,`despawn`,`despawn_timer`,`wp_spawns`) VALUES ('tbs_mission_coral5',0,0,0,0,0,0,0,15000,0,100,0);
SET @g := LAST_INSERT_ID();
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (@g,423932,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) SELECT @g,'thalassius',0,s2.x+-25,s2.y+-15,s2.z+0,0,640 FROM spawn2 s2 WHERE s2.id = 117061 LIMIT 1;

INSERT INTO `spawngroup` (`name`,`spawn_limit`,`dist`,`max_x`,`min_x`,`max_y`,`min_y`,`delay`,`mindelay`,`despawn`,`despawn_timer`,`wp_spawns`) VALUES ('tbs_mission_coral6',0,0,0,0,0,0,0,15000,0,100,0);
SET @g := LAST_INSERT_ID();
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (@g,423932,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) SELECT @g,'thalassius',0,s2.x+20,s2.y+30,s2.z+0,0,640 FROM spawn2 s2 WHERE s2.id = 117061 LIMIT 1;

INSERT INTO `spawngroup` (`name`,`spawn_limit`,`dist`,`max_x`,`min_x`,`max_y`,`min_y`,`delay`,`mindelay`,`despawn`,`despawn_timer`,`wp_spawns`) VALUES ('tbs_mission_coral7',0,0,0,0,0,0,0,15000,0,100,0);
SET @g := LAST_INSERT_ID();
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (@g,423932,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) SELECT @g,'thalassius',0,s2.x+10,s2.y+20,s2.z+0,0,640 FROM spawn2 s2 WHERE s2.id = 117062 LIMIT 1;

INSERT INTO `spawngroup` (`name`,`spawn_limit`,`dist`,`max_x`,`min_x`,`max_y`,`min_y`,`delay`,`mindelay`,`despawn`,`despawn_timer`,`wp_spawns`) VALUES ('tbs_mission_coral8',0,0,0,0,0,0,0,15000,0,100,0);
SET @g := LAST_INSERT_ID();
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (@g,423932,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) SELECT @g,'thalassius',0,s2.x+-30,s2.y+10,s2.z+0,0,640 FROM spawn2 s2 WHERE s2.id = 117062 LIMIT 1;

INSERT INTO `spawngroup` (`name`,`spawn_limit`,`dist`,`max_x`,`min_x`,`max_y`,`min_y`,`delay`,`mindelay`,`despawn`,`despawn_timer`,`wp_spawns`) VALUES ('tbs_mission_coral9',0,0,0,0,0,0,0,15000,0,100,0);
SET @g := LAST_INSERT_ID();
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (@g,423932,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) SELECT @g,'thalassius',0,s2.x+0,s2.y+-30,s2.z+0,0,640 FROM spawn2 s2 WHERE s2.id = 117059 LIMIT 1;

INSERT INTO `spawngroup` (`name`,`spawn_limit`,`dist`,`max_x`,`min_x`,`max_y`,`min_y`,`delay`,`mindelay`,`despawn`,`despawn_timer`,`wp_spawns`) VALUES ('tbs_mission_coral10',0,0,0,0,0,0,0,15000,0,100,0);
SET @g := LAST_INSERT_ID();
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (@g,423932,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) SELECT @g,'thalassius',0,s2.x+-15,s2.y+40,s2.z+0,0,640 FROM spawn2 s2 WHERE s2.id = 117060 LIMIT 1;

INSERT INTO `spawngroup` (`name`,`spawn_limit`,`dist`,`max_x`,`min_x`,`max_y`,`min_y`,`delay`,`mindelay`,`despawn`,`despawn_timer`,`wp_spawns`) VALUES ('tbs_mission_patrikus',0,0,0,0,0,0,0,15000,0,100,0);
SET @g := LAST_INSERT_ID();
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (@g,423922,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) SELECT @g,'thalassius',0,s2.x+30,s2.y+-30,s2.z+0,0,640 FROM spawn2 s2 WHERE s2.id = 117061 LIMIT 1;

INSERT INTO `spawngroup` (`name`,`spawn_limit`,`dist`,`max_x`,`min_x`,`max_y`,`min_y`,`delay`,`mindelay`,`despawn`,`despawn_timer`,`wp_spawns`) VALUES ('tbs_mission_brinor',0,0,0,0,0,0,0,15000,0,100,0);
SET @g := LAST_INSERT_ID();
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (@g,423923,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) SELECT @g,'thalassius',0,s2.x+-30,s2.y+-30,s2.z+0,0,640 FROM spawn2 s2 WHERE s2.id = 117061 LIMIT 1;

INSERT INTO `spawngroup` (`name`,`spawn_limit`,`dist`,`max_x`,`min_x`,`max_y`,`min_y`,`delay`,`mindelay`,`despawn`,`despawn_timer`,`wp_spawns`) VALUES ('tbs_mission_wulthin',0,0,0,0,0,0,0,15000,0,100,0);
SET @g := LAST_INSERT_ID();
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (@g,423924,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) SELECT @g,'thalassius',0,s2.x+45,s2.y+0,s2.z+0,0,640 FROM spawn2 s2 WHERE s2.id = 117059 LIMIT 1;

INSERT INTO `spawngroup` (`name`,`spawn_limit`,`dist`,`max_x`,`min_x`,`max_y`,`min_y`,`delay`,`mindelay`,`despawn`,`despawn_timer`,`wp_spawns`) VALUES ('tbs_mission_salashar',0,0,0,0,0,0,0,15000,0,100,0);
SET @g := LAST_INSERT_ID();
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (@g,423925,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) SELECT @g,'thalassius',0,s2.x+-45,s2.y+0,s2.z+0,0,640 FROM spawn2 s2 WHERE s2.id = 117059 LIMIT 1;

INSERT INTO `spawngroup` (`name`,`spawn_limit`,`dist`,`max_x`,`min_x`,`max_y`,`min_y`,`delay`,`mindelay`,`despawn`,`despawn_timer`,`wp_spawns`) VALUES ('tbs_mission_ulthagor',0,0,0,0,0,0,0,15000,0,100,0);
SET @g := LAST_INSERT_ID();
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (@g,423926,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) SELECT @g,'thalassius',0,s2.x+50,s2.y+0,s2.z+0,0,640 FROM spawn2 s2 WHERE s2.id = 117062 LIMIT 1;

INSERT INTO `spawngroup` (`name`,`spawn_limit`,`dist`,`max_x`,`min_x`,`max_y`,`min_y`,`delay`,`mindelay`,`despawn`,`despawn_timer`,`wp_spawns`) VALUES ('tbs_mission_raktharak',0,0,0,0,0,0,0,15000,0,100,0);
SET @g := LAST_INSERT_ID();
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (@g,423927,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) SELECT @g,'thalassius',0,s2.x+-50,s2.y+0,s2.z+0,0,640 FROM spawn2 s2 WHERE s2.id = 117062 LIMIT 1;

INSERT INTO `spawngroup` (`name`,`spawn_limit`,`dist`,`max_x`,`min_x`,`max_y`,`min_y`,`delay`,`mindelay`,`despawn`,`despawn_timer`,`wp_spawns`) VALUES ('tbs_mission_xao',0,0,0,0,0,0,0,15000,0,100,0);
SET @g := LAST_INSERT_ID();
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (@g,423928,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) SELECT @g,'thalassius',0,s2.x+0,s2.y+70,s2.z+0,0,640 FROM spawn2 s2 WHERE s2.id = 117062 LIMIT 1;

INSERT INTO `spawngroup` (`name`,`spawn_limit`,`dist`,`max_x`,`min_x`,`max_y`,`min_y`,`delay`,`mindelay`,`despawn`,`despawn_timer`,`wp_spawns`) VALUES ('tbs_mission_sslarn',0,0,0,0,0,0,0,15000,0,100,0);
SET @g := LAST_INSERT_ID();
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (@g,423933,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) VALUES (@g,'zhisza',0,995.375,-107.75,204.27,0,640);

INSERT INTO `spawngroup` (`name`,`spawn_limit`,`dist`,`max_x`,`min_x`,`max_y`,`min_y`,`delay`,`mindelay`,`despawn`,`despawn_timer`,`wp_spawns`) VALUES ('tbs_mission_enpsa',0,0,0,0,0,0,0,15000,0,100,0);
SET @g := LAST_INSERT_ID();
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (@g,423934,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) VALUES (@g,'zhisza',0,-809.25,-1153.625,363.7,0,640);

INSERT INTO `spawngroup` (`name`,`spawn_limit`,`dist`,`max_x`,`min_x`,`max_y`,`min_y`,`delay`,`mindelay`,`despawn`,`despawn_timer`,`wp_spawns`) VALUES ('tbs_mission_mozull',0,0,0,0,0,0,0,15000,0,100,0);
SET @g := LAST_INSERT_ID();
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (@g,423935,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) VALUES (@g,'zhisza',0,71.75,-1249.375,363.0,0,640);

INSERT INTO `spawngroup` (`name`,`spawn_limit`,`dist`,`max_x`,`min_x`,`max_y`,`min_y`,`delay`,`mindelay`,`despawn`,`despawn_timer`,`wp_spawns`) VALUES ('tbs_mission_crack1',0,0,0,0,0,0,0,15000,0,100,0);
SET @g := LAST_INSERT_ID();
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (@g,423936,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) SELECT @g,'zhisza',0,s2.x+60,s2.y+20,s2.z+0,0,640 FROM spawn2 s2 WHERE s2.id = 124712 LIMIT 1;

INSERT INTO `spawngroup` (`name`,`spawn_limit`,`dist`,`max_x`,`min_x`,`max_y`,`min_y`,`delay`,`mindelay`,`despawn`,`despawn_timer`,`wp_spawns`) VALUES ('tbs_mission_crack2',0,0,0,0,0,0,0,15000,0,100,0);
SET @g := LAST_INSERT_ID();
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (@g,423936,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) SELECT @g,'zhisza',0,s2.x+-40,s2.y+30,s2.z+0,0,640 FROM spawn2 s2 WHERE s2.id = 124713 LIMIT 1;

INSERT INTO `spawngroup` (`name`,`spawn_limit`,`dist`,`max_x`,`min_x`,`max_y`,`min_y`,`delay`,`mindelay`,`despawn`,`despawn_timer`,`wp_spawns`) VALUES ('tbs_mission_crack3',0,0,0,0,0,0,0,15000,0,100,0);
SET @g := LAST_INSERT_ID();
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (@g,423936,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) SELECT @g,'zhisza',0,s2.x+25,s2.y+-35,s2.z+0,0,640 FROM spawn2 s2 WHERE s2.id = 124714 LIMIT 1;

INSERT INTO `spawngroup` (`name`,`spawn_limit`,`dist`,`max_x`,`min_x`,`max_y`,`min_y`,`delay`,`mindelay`,`despawn`,`despawn_timer`,`wp_spawns`) VALUES ('tbs_mission_bowl1',0,0,0,0,0,0,0,15000,0,100,0);
SET @g := LAST_INSERT_ID();
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (@g,423940,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) VALUES (@g,'silyssar',0,497.0,-7.0,584.0,0,640);

INSERT INTO `spawngroup` (`name`,`spawn_limit`,`dist`,`max_x`,`min_x`,`max_y`,`min_y`,`delay`,`mindelay`,`despawn`,`despawn_timer`,`wp_spawns`) VALUES ('tbs_mission_bowl2',0,0,0,0,0,0,0,15000,0,100,0);
SET @g := LAST_INSERT_ID();
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (@g,423940,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) VALUES (@g,'silyssar',0,560.0,-274.0,642.0,0,640);

INSERT INTO `spawngroup` (`name`,`spawn_limit`,`dist`,`max_x`,`min_x`,`max_y`,`min_y`,`delay`,`mindelay`,`despawn`,`despawn_timer`,`wp_spawns`) VALUES ('tbs_mission_bowl3',0,0,0,0,0,0,0,15000,0,100,0);
SET @g := LAST_INSERT_ID();
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (@g,423940,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) VALUES (@g,'silyssar',0,438.0,-243.0,642.0,0,640);

INSERT INTO `spawngroup` (`name`,`spawn_limit`,`dist`,`max_x`,`min_x`,`max_y`,`min_y`,`delay`,`mindelay`,`despawn`,`despawn_timer`,`wp_spawns`) VALUES ('tbs_mission_bowl4',0,0,0,0,0,0,0,15000,0,100,0);
SET @g := LAST_INSERT_ID();
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (@g,423940,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) VALUES (@g,'silyssar',0,629.0,-25.0,638.0,0,640);

INSERT INTO `spawngroup` (`name`,`spawn_limit`,`dist`,`max_x`,`min_x`,`max_y`,`min_y`,`delay`,`mindelay`,`despawn`,`despawn_timer`,`wp_spawns`) VALUES ('tbs_mission_conduit1',0,0,0,0,0,0,0,15000,0,100,0);
SET @g := LAST_INSERT_ID();
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (@g,423939,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) VALUES (@g,'silyssar',0,660.0,-87.0,588.0,0,640);

INSERT INTO `spawngroup` (`name`,`spawn_limit`,`dist`,`max_x`,`min_x`,`max_y`,`min_y`,`delay`,`mindelay`,`despawn`,`despawn_timer`,`wp_spawns`) VALUES ('tbs_mission_conduit2',0,0,0,0,0,0,0,15000,0,100,0);
SET @g := LAST_INSERT_ID();
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (@g,423939,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) VALUES (@g,'silyssar',0,419.0,-69.0,638.0,0,640);

INSERT INTO `spawngroup` (`name`,`spawn_limit`,`dist`,`max_x`,`min_x`,`max_y`,`min_y`,`delay`,`mindelay`,`despawn`,`despawn_timer`,`wp_spawns`) VALUES ('tbs_mission_ritualist1',0,0,0,0,0,0,0,15000,0,100,0);
SET @g := LAST_INSERT_ID();
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (@g,423938,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) VALUES (@g,'silyssar',0,411.0,-154.0,589.475,0,640);

INSERT INTO `spawngroup` (`name`,`spawn_limit`,`dist`,`max_x`,`min_x`,`max_y`,`min_y`,`delay`,`mindelay`,`despawn`,`despawn_timer`,`wp_spawns`) VALUES ('tbs_mission_ritualist2',0,0,0,0,0,0,0,15000,0,100,0);
SET @g := LAST_INSERT_ID();
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (@g,423938,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) VALUES (@g,'silyssar',0,808.0,-23.0,589.475,0,640);

INSERT INTO `spawngroup` (`name`,`spawn_limit`,`dist`,`max_x`,`min_x`,`max_y`,`min_y`,`delay`,`mindelay`,`despawn`,`despawn_timer`,`wp_spawns`) VALUES ('tbs_mission_chest1',0,0,0,0,0,0,0,15000,0,100,0);
SET @g := LAST_INSERT_ID();
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (@g,423941,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) SELECT @g,'silyssar',0,s2.x+25,s2.y+10,s2.z+0,0,640 FROM spawn2 s2 WHERE s2.id = 135484 LIMIT 1;

INSERT INTO `spawngroup` (`name`,`spawn_limit`,`dist`,`max_x`,`min_x`,`max_y`,`min_y`,`delay`,`mindelay`,`despawn`,`despawn_timer`,`wp_spawns`) VALUES ('tbs_mission_chest2',0,0,0,0,0,0,0,15000,0,100,0);
SET @g := LAST_INSERT_ID();
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (@g,423941,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) SELECT @g,'silyssar',0,s2.x+-25,s2.y+15,s2.z+0,0,640 FROM spawn2 s2 WHERE s2.id = 135484 LIMIT 1;

INSERT INTO `spawngroup` (`name`,`spawn_limit`,`dist`,`max_x`,`min_x`,`max_y`,`min_y`,`delay`,`mindelay`,`despawn`,`despawn_timer`,`wp_spawns`) VALUES ('tbs_mission_chest3',0,0,0,0,0,0,0,15000,0,100,0);
SET @g := LAST_INSERT_ID();
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (@g,423941,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) SELECT @g,'silyssar',0,s2.x+20,s2.y+-20,s2.z+0,0,640 FROM spawn2 s2 WHERE s2.id = 135485 LIMIT 1;

INSERT INTO `spawngroup` (`name`,`spawn_limit`,`dist`,`max_x`,`min_x`,`max_y`,`min_y`,`delay`,`mindelay`,`despawn`,`despawn_timer`,`wp_spawns`) VALUES ('tbs_mission_chest4',0,0,0,0,0,0,0,15000,0,100,0);
SET @g := LAST_INSERT_ID();
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (@g,423941,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) SELECT @g,'silyssar',0,s2.x+-20,s2.y+-15,s2.z+0,0,640 FROM spawn2 s2 WHERE s2.id = 135485 LIMIT 1;

INSERT INTO `spawngroup` (`name`,`spawn_limit`,`dist`,`max_x`,`min_x`,`max_y`,`min_y`,`delay`,`mindelay`,`despawn`,`despawn_timer`,`wp_spawns`) VALUES ('tbs_mission_chest5',0,0,0,0,0,0,0,15000,0,100,0);
SET @g := LAST_INSERT_ID();
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (@g,423941,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) SELECT @g,'silyssar',0,s2.x+15,s2.y+25,s2.z+0,0,640 FROM spawn2 s2 WHERE s2.id = 135486 LIMIT 1;

INSERT INTO `spawngroup` (`name`,`spawn_limit`,`dist`,`max_x`,`min_x`,`max_y`,`min_y`,`delay`,`mindelay`,`despawn`,`despawn_timer`,`wp_spawns`) VALUES ('tbs_mission_chest6',0,0,0,0,0,0,0,15000,0,100,0);
SET @g := LAST_INSERT_ID();
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (@g,423941,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) SELECT @g,'silyssar',0,s2.x+-15,s2.y+-25,s2.z+0,0,640 FROM spawn2 s2 WHERE s2.id = 135486 LIMIT 1;

INSERT INTO `spawngroup` (`name`,`spawn_limit`,`dist`,`max_x`,`min_x`,`max_y`,`min_y`,`delay`,`mindelay`,`despawn`,`despawn_timer`,`wp_spawns`) VALUES ('tbs_mission_book1',0,0,0,0,0,0,0,15000,0,100,0);
SET @g := LAST_INSERT_ID();
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (@g,423943,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) SELECT @g,'silyssar',0,s2.x+0,s2.y+40,s2.z+0,0,640 FROM spawn2 s2 WHERE s2.id = 135484 LIMIT 1;

INSERT INTO `spawngroup` (`name`,`spawn_limit`,`dist`,`max_x`,`min_x`,`max_y`,`min_y`,`delay`,`mindelay`,`despawn`,`despawn_timer`,`wp_spawns`) VALUES ('tbs_mission_book2',0,0,0,0,0,0,0,15000,0,100,0);
SET @g := LAST_INSERT_ID();
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (@g,423943,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) SELECT @g,'silyssar',0,s2.x+40,s2.y+0,s2.z+0,0,640 FROM spawn2 s2 WHERE s2.id = 135485 LIMIT 1;

INSERT INTO `spawngroup` (`name`,`spawn_limit`,`dist`,`max_x`,`min_x`,`max_y`,`min_y`,`delay`,`mindelay`,`despawn`,`despawn_timer`,`wp_spawns`) VALUES ('tbs_mission_book3',0,0,0,0,0,0,0,15000,0,100,0);
SET @g := LAST_INSERT_ID();
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (@g,423943,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) SELECT @g,'silyssar',0,s2.x+-40,s2.y+0,s2.z+0,0,640 FROM spawn2 s2 WHERE s2.id = 135486 LIMIT 1;

INSERT INTO `spawngroup` (`name`,`spawn_limit`,`dist`,`max_x`,`min_x`,`max_y`,`min_y`,`delay`,`mindelay`,`despawn`,`despawn_timer`,`wp_spawns`) VALUES ('tbs_mission_slave1',0,0,0,0,0,0,0,15000,0,100,0);
SET @g := LAST_INSERT_ID();
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (@g,423942,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) SELECT @g,'silyssar',0,s2.x+30,s2.y+-20,s2.z+0,0,640 FROM spawn2 s2 WHERE s2.id = 135484 LIMIT 1;

INSERT INTO `spawngroup` (`name`,`spawn_limit`,`dist`,`max_x`,`min_x`,`max_y`,`min_y`,`delay`,`mindelay`,`despawn`,`despawn_timer`,`wp_spawns`) VALUES ('tbs_mission_slave2',0,0,0,0,0,0,0,15000,0,100,0);
SET @g := LAST_INSERT_ID();
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (@g,423942,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) SELECT @g,'silyssar',0,s2.x+-30,s2.y+20,s2.z+0,0,640 FROM spawn2 s2 WHERE s2.id = 135484 LIMIT 1;

INSERT INTO `spawngroup` (`name`,`spawn_limit`,`dist`,`max_x`,`min_x`,`max_y`,`min_y`,`delay`,`mindelay`,`despawn`,`despawn_timer`,`wp_spawns`) VALUES ('tbs_mission_slave3',0,0,0,0,0,0,0,15000,0,100,0);
SET @g := LAST_INSERT_ID();
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (@g,423942,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) SELECT @g,'silyssar',0,s2.x+30,s2.y+20,s2.z+0,0,640 FROM spawn2 s2 WHERE s2.id = 135485 LIMIT 1;

INSERT INTO `spawngroup` (`name`,`spawn_limit`,`dist`,`max_x`,`min_x`,`max_y`,`min_y`,`delay`,`mindelay`,`despawn`,`despawn_timer`,`wp_spawns`) VALUES ('tbs_mission_slave4',0,0,0,0,0,0,0,15000,0,100,0);
SET @g := LAST_INSERT_ID();
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (@g,423942,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) SELECT @g,'silyssar',0,s2.x+-30,s2.y+-20,s2.z+0,0,640 FROM spawn2 s2 WHERE s2.id = 135485 LIMIT 1;

INSERT INTO `spawngroup` (`name`,`spawn_limit`,`dist`,`max_x`,`min_x`,`max_y`,`min_y`,`delay`,`mindelay`,`despawn`,`despawn_timer`,`wp_spawns`) VALUES ('tbs_mission_slave5',0,0,0,0,0,0,0,15000,0,100,0);
SET @g := LAST_INSERT_ID();
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (@g,423942,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) SELECT @g,'silyssar',0,s2.x+20,s2.y+20,s2.z+0,0,640 FROM spawn2 s2 WHERE s2.id = 135486 LIMIT 1;

INSERT INTO `spawngroup` (`name`,`spawn_limit`,`dist`,`max_x`,`min_x`,`max_y`,`min_y`,`delay`,`mindelay`,`despawn`,`despawn_timer`,`wp_spawns`) VALUES ('tbs_mission_slave6',0,0,0,0,0,0,0,15000,0,100,0);
SET @g := LAST_INSERT_ID();
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (@g,423942,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) SELECT @g,'silyssar',0,s2.x+-20,s2.y+-20,s2.z+0,0,640 FROM spawn2 s2 WHERE s2.id = 135486 LIMIT 1;

INSERT INTO `spawngroup` (`name`,`spawn_limit`,`dist`,`max_x`,`min_x`,`max_y`,`min_y`,`delay`,`mindelay`,`despawn`,`despawn_timer`,`wp_spawns`) VALUES ('tbs_mission_sacrificer1',0,0,0,0,0,0,0,15000,0,100,0);
SET @g := LAST_INSERT_ID();
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (@g,423944,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) SELECT @g,'silyssar',0,s2.x+35,s2.y+-25,s2.z+0,0,640 FROM spawn2 s2 WHERE s2.id = 135484 LIMIT 1;

INSERT INTO `spawngroup` (`name`,`spawn_limit`,`dist`,`max_x`,`min_x`,`max_y`,`min_y`,`delay`,`mindelay`,`despawn`,`despawn_timer`,`wp_spawns`) VALUES ('tbs_mission_sacrificer2',0,0,0,0,0,0,0,15000,0,100,0);
SET @g := LAST_INSERT_ID();
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (@g,423944,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) SELECT @g,'silyssar',0,s2.x+-35,s2.y+25,s2.z+0,0,640 FROM spawn2 s2 WHERE s2.id = 135484 LIMIT 1;

INSERT INTO `spawngroup` (`name`,`spawn_limit`,`dist`,`max_x`,`min_x`,`max_y`,`min_y`,`delay`,`mindelay`,`despawn`,`despawn_timer`,`wp_spawns`) VALUES ('tbs_mission_sacrificer3',0,0,0,0,0,0,0,15000,0,100,0);
SET @g := LAST_INSERT_ID();
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (@g,423944,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) SELECT @g,'silyssar',0,s2.x+35,s2.y+25,s2.z+0,0,640 FROM spawn2 s2 WHERE s2.id = 135485 LIMIT 1;

INSERT INTO `spawngroup` (`name`,`spawn_limit`,`dist`,`max_x`,`min_x`,`max_y`,`min_y`,`delay`,`mindelay`,`despawn`,`despawn_timer`,`wp_spawns`) VALUES ('tbs_mission_sacrificer4',0,0,0,0,0,0,0,15000,0,100,0);
SET @g := LAST_INSERT_ID();
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (@g,423944,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) SELECT @g,'silyssar',0,s2.x+-35,s2.y+-25,s2.z+0,0,640 FROM spawn2 s2 WHERE s2.id = 135485 LIMIT 1;

INSERT INTO `spawngroup` (`name`,`spawn_limit`,`dist`,`max_x`,`min_x`,`max_y`,`min_y`,`delay`,`mindelay`,`despawn`,`despawn_timer`,`wp_spawns`) VALUES ('tbs_mission_sacrificer5',0,0,0,0,0,0,0,15000,0,100,0);
SET @g := LAST_INSERT_ID();
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (@g,423944,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) SELECT @g,'silyssar',0,s2.x+25,s2.y+25,s2.z+0,0,640 FROM spawn2 s2 WHERE s2.id = 135487 LIMIT 1;

INSERT INTO `spawngroup` (`name`,`spawn_limit`,`dist`,`max_x`,`min_x`,`max_y`,`min_y`,`delay`,`mindelay`,`despawn`,`despawn_timer`,`wp_spawns`) VALUES ('tbs_mission_sacrificer6',0,0,0,0,0,0,0,15000,0,100,0);
SET @g := LAST_INSERT_ID();
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (@g,423944,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) SELECT @g,'silyssar',0,s2.x+-25,s2.y+-25,s2.z+0,0,640 FROM spawn2 s2 WHERE s2.id = 135487 LIMIT 1;

-- True up PEQ's stub quest NPCs in Atiiki
UPDATE `npc_types` SET `hp` = 1500000, `AC` = 580, `ATK` = 320, `Accuracy` = 400, `findable` = 1 WHERE `id` IN (418020,418068,418071);

-- A5. dz templates 6110-6121 (runtime zone ids, default zone-in, return Katta)
DELETE FROM `dynamic_zone_templates` WHERE `id` BETWEEN 6110 AND 6121;
INSERT INTO `dynamic_zone_templates`
  (`id`,`zone_id`,`zone_version`,`name`,`min_players`,`max_players`,
   `duration_seconds`,`dz_switch_id`,`compass_zone_id`,`compass_x`,`compass_y`,
   `compass_z`,`return_zone_id`,`return_x`,`return_y`,`return_z`,`return_h`,
   `override_zone_in`,`zone_in_x`,`zone_in_y`,`zone_in_z`,`zone_in_h`) VALUES
(6110,418,0,'Katta Castrum: Stone Tongue of Ateleka',1,6,21600,0,0,0,0,0,416,-2,-425,-20,0,0,0,0,0,0),
(6111,418,0,'Katta Castrum: The Great Invasion',1,6,21600,0,0,0,0,0,416,-2,-425,-20,0,0,0,0,0,0),
(6112,418,0,'Katta Castrum: Fate of the Combine',1,6,21600,0,0,0,0,0,416,-2,-425,-20,0,0,0,0,0,0),
(6113,418,0,'Katta Castrum: Gorillas in the Garden',1,6,21600,0,0,0,0,0,416,-2,-425,-20,0,0,0,0,0,0),
(6114,417,0,'Katta Castrum: Coral Diving',1,6,21600,0,0,0,0,0,416,-2,-425,-20,0,0,0,0,0,0),
(6115,417,0,'Katta Castrum: Evidence of Unity',1,6,21600,0,0,0,0,0,416,-2,-425,-20,0,0,0,0,0,0),
(6116,417,0,'Katta Castrum: Sea Serpents',1,6,21600,0,0,0,0,0,416,-2,-425,-20,0,0,0,0,0,0),
(6117,417,0,'Katta Castrum: The Hydromancer',1,6,21600,0,0,0,0,0,416,-2,-425,-20,0,0,0,0,0,0),
(6118,419,0,'Katta Castrum: The Domes are Cracking',1,6,21600,0,0,0,0,0,416,-2,-425,-20,0,0,0,0,0,0),
(6119,419,0,'Katta Castrum: Leave No Stone Unturned',1,6,21600,0,0,0,0,0,416,-2,-425,-20,0,0,0,0,0,0),
(6120,420,0,'Katta Castrum: The Source of Shissar Power',1,6,21600,0,0,0,0,0,416,-2,-425,-20,0,0,0,0,0,0),
(6121,420,0,'Katta Castrum: Immortal Coils',1,6,21600,0,0,0,0,0,416,-2,-425,-20,0,0,0,0,0,0);

-- A6. tasks 620100-620111 (shared/instanced, min 1 player)
DELETE FROM `task_activities` WHERE `taskid` IN (620100,620101,620102,620103,620104,620105,620106,620107,620108,620109,620110,620111);
DELETE FROM `tasks` WHERE `id` IN (620100,620101,620102,620103,620104,620105,620106,620107,620108,620109,620110,620111);

INSERT INTO `tasks` (id,type,duration,duration_code,title,
description,reward_text,reward_id_list,cash_reward,exp_reward,
reward_method,reward_points,reward_point_type,min_level,max_level,
level_spread,min_players,max_players,repeatable,faction_reward,
completion_emote,replay_timer_group,replay_timer_seconds,
request_timer_group,request_timer_seconds,dz_template_id,
lock_activity_id,faction_amount,enabled) VALUES
(620100,1,0,0,'Stone Tongue of Ateleka','A mission for the Combine survivors of Katta Castrum: Stone Tongue of Ateleka.','Experience','',0,2000000,0,0,0,0,0,0,1,6,0,1170,'',0,0,0,0,6110,-1,10,1),
(620101,1,0,0,'The Great Invasion','A mission for the Combine survivors of Katta Castrum: The Great Invasion.','Experience','',0,2000000,0,0,0,0,0,0,1,6,0,1170,'',0,0,0,0,6111,-1,10,1),
(620102,1,0,0,'Fate of the Combine','A mission for the Combine survivors of Katta Castrum: Fate of the Combine.','Experience','',0,2000000,0,0,0,0,0,0,1,6,0,1170,'',0,0,0,0,6112,-1,10,1),
(620103,1,0,0,'Gorillas in the Garden','A mission for the Combine survivors of Katta Castrum: Gorillas in the Garden.','Experience','',0,2000000,0,0,0,0,0,0,1,6,0,1170,'',0,0,0,0,6113,-1,10,1),
(620104,1,0,0,'Coral Diving','A mission for the Combine survivors of Katta Castrum: Coral Diving.','Experience','',0,2000000,0,0,0,0,0,0,1,6,0,1170,'',0,0,0,0,6114,-1,10,1),
(620105,1,0,0,'Evidence of Unity','A mission for the Combine survivors of Katta Castrum: Evidence of Unity.','Experience','',0,2000000,0,0,0,0,0,0,1,6,0,1170,'',0,0,0,0,6115,-1,10,1),
(620106,1,0,0,'Sea Serpents','A mission for the Combine survivors of Katta Castrum: Sea Serpents.','Experience','',0,2000000,0,0,0,0,0,0,1,6,0,1170,'',0,0,0,0,6116,-1,10,1),
(620107,1,0,0,'The Hydromancer','A mission for the Combine survivors of Katta Castrum: The Hydromancer.','Experience','',0,2000000,0,0,0,0,0,0,1,6,0,1170,'',0,0,0,0,6117,-1,10,1),
(620108,1,0,0,'The Domes are Cracking','A mission for the Combine survivors of Katta Castrum: The Domes are Cracking.','Experience','',0,2000000,0,0,0,0,0,0,1,6,0,1170,'',0,0,0,0,6118,-1,10,1),
(620109,1,0,0,'Leave No Stone Unturned','A mission for the Combine survivors of Katta Castrum: Leave No Stone Unturned.','Experience','',0,2000000,0,0,0,0,0,0,1,6,0,1170,'',0,0,0,0,6119,-1,10,1),
(620110,1,0,0,'The Source of Shissar Power','A mission for the Combine survivors of Katta Castrum: The Source of Shissar Power.','Experience','',0,2000000,0,0,0,0,0,0,1,6,0,1170,'',0,0,0,0,6120,-1,10,1),
(620111,1,0,0,'Immortal Coils','A mission for the Combine survivors of Katta Castrum: Immortal Coils.','Experience','',0,2000000,0,0,0,0,0,0,1,6,0,1170,'',0,0,0,0,6121,-1,10,1);

INSERT INTO `task_activities` (taskid,activityid,req_activity_id,
step,activitytype,target_name,goalmethod,goalcount,
description_override,npc_match_list,item_id_list,item_list,
dz_switch_id,min_x,min_y,min_z,max_x,max_y,max_z,skill_list,
spell_list,zones,zone_version,optional,list_group) VALUES
(620100,0,-1,1,2,'Guardian of Ateleka',1,4,'Slay the golems Osinzuhazhfet raises: 4 times','423915','','',0,0,0,0,0,0,0,'-1','0','418',-1,0,0),
(620100,1,-1,2,4,'Associate Researcher Plik',1,1,'Speak with Associate Researcher Plik','416011','','',0,0,0,0,0,0,0,'-1','0','416',-1,0,0),
(620101,0,-1,1,4,'Akarahotuten',1,1,'Speak with Akarahotuten','418071','','',0,0,0,0,0,0,0,'-1','0','418',-1,0,0),
(620101,1,-1,2,2,'invader shissar',1,10,'Kill 10 invader shissar','423917','','',0,0,0,0,0,0,0,'-1','0','418',-1,0,0),
(620101,2,-1,3,2,'invader priest',1,4,'Kill 4 invader priest','423918','','',0,0,0,0,0,0,0,'-1','0','418',-1,0,0),
(620101,3,-1,4,4,'Sergeant Zetren',1,1,'Speak with Sergeant Zetren','416034','','',0,0,0,0,0,0,0,'-1','0','416',-1,0,0),
(620102,0,-1,1,4,'Akarahotuten',1,1,'Speak with Akarahotuten','418071','','',0,0,0,0,0,0,0,'-1','0','418',-1,0,0),
(620102,1,-1,2,2,'Emperor Zhizuzun',1,1,'Hunt Emperor Zhizuzun across the temple floors','423919','','',0,0,0,0,0,0,0,'-1','0','418',-1,0,0),
(620102,2,-1,3,4,'Akarahotuten',1,1,'Speak with Akarahotuten','418071','','',0,0,0,0,0,0,0,'-1','0','418',-1,0,0),
(620102,3,-1,4,4,'Tuzart Relenfold',1,1,'Speak with Tuzart Relenfold','416002','','',0,0,0,0,0,0,0,'-1','0','416',-1,0,0),
(620103,0,-1,1,2,'an escaped gorilla',1,10,'Subdue 10 escaped gorillas','423920','','',0,0,0,0,0,0,0,'-1','0','418',-1,0,0),
(620103,1,-1,2,2,'Matriarch Tusdum',1,1,'Kill 1 Matriarch Tusdum','423921','','',0,0,0,0,0,0,0,'-1','0','418',-1,0,0),
(620103,2,-1,3,4,'Head Attendant Haestus',1,1,'Speak with Head Attendant Haestus','416005','','',0,0,0,0,0,0,0,'-1','0','416',-1,0,0),
(620104,0,-1,1,2,'kedge',1,20,'Kill 20 kedge creatures in the caves','417011,417012,417013,417023,417026,417028,417035','','',0,0,0,0,0,0,0,'-1','0','417',-1,0,0),
(620104,1,-1,2,2,'fire coral',1,10,'Harvest 10 Glowing Fire Coral','423932','','',0,0,0,0,0,0,0,'-1','0','417',-1,0,0),
(620104,2,-1,3,4,'Sorcerer Hearah',1,1,'Speak with Sorcerer Hearah','416014','','',0,0,0,0,0,0,0,'-1','0','416',-1,0,0),
(620105,0,-1,1,2,'kedge and puddles',1,8,'Kill 8 kedge or puddles along the way','417011,417012,417013,417023,417026,417028,417035','','',0,0,0,0,0,0,0,'-1','0','417',-1,0,0),
(620105,1,-1,2,1,'Sneaky Shissar Scale',1,5,'Loot 5 Sneaky Shissar Scale','','9910007','',0,0,0,0,0,0,0,'-1','0','417',-1,0,0),
(620105,2,-1,3,2,'Patrikus Grimor',1,1,'Kill 1 Patrikus Grimor','423922','','',0,0,0,0,0,0,0,'-1','0','417',-1,0,0),
(620105,3,-1,4,2,'Brinor Schmidtzen',1,1,'Kill 1 Brinor Schmidtzen','423923','','',0,0,0,0,0,0,0,'-1','0','417',-1,0,0),
(620105,4,-1,5,1,'Encoded Message',1,1,'Loot 1 Encoded Message','','9910008','',0,0,0,0,0,0,0,'-1','0','417',-1,0,0),
(620105,5,-1,6,1,'Kedge Secrets',1,1,'Loot 1 Kedge Secrets','','9910009','',0,0,0,0,0,0,0,'-1','0','417',-1,0,0),
(620105,6,-1,7,4,'Flora Venloe',1,1,'Speak with Flora Venloe','416055','','',0,0,0,0,0,0,0,'-1','0','416',-1,0,0),
(620106,0,-1,1,2,'Wulthin Unagi',1,1,'Kill 1 Wulthin Unagi','423924','','',0,0,0,0,0,0,0,'-1','0','417',-1,0,0),
(620106,1,-1,2,2,'Salashar the Blade',1,1,'Kill 1 Salashar the Blade','423925','','',0,0,0,0,0,0,0,'-1','0','417',-1,0,0),
(620106,2,-1,3,2,'Ulthagor Polaris',1,1,'Kill 1 Ulthagor Polaris','423926','','',0,0,0,0,0,0,0,'-1','0','417',-1,0,0),
(620106,3,-1,4,2,'Rak''Tharak',1,1,'Kill 1 Rak''Tharak','423927','','',0,0,0,0,0,0,0,'-1','0','417',-1,0,0),
(620106,4,-1,5,4,'Flora Venloe',1,1,'Speak with Flora Venloe','416055','','',0,0,0,0,0,0,0,'-1','0','416',-1,0,0),
(620107,0,-1,1,2,'Xao Aulin',1,1,'Slay Xao Aulin before his darkwater allies drown the temple','423928','','',0,0,0,0,0,0,0,'-1','0','417',-1,0,0),
(620107,1,-1,2,4,'Flora Venloe',1,1,'Speak with Flora Venloe','416055','','',0,0,0,0,0,0,0,'-1','0','416',-1,0,0),
(620108,0,-1,1,2,'ambush shissar',1,12,'Survive and slay the three dome-crack ambushes (12 shissar)','423937','','',0,0,0,0,0,0,0,'-1','0','419',-1,0,0),
(620108,1,-1,2,4,'Structural Engineer Dewas',1,1,'Speak with Structural Engineer Dewas','416033','','',0,0,0,0,0,0,0,'-1','0','416',-1,0,0),
(620109,0,-1,1,2,'shissar patroller',1,10,'Challenge the shissar: 10 refuse the Emperor and must die','419001','','',0,0,0,0,0,0,0,'-1','0','419',-1,0,0),
(620109,1,-1,2,4,'Shissar Supervisor Sslarn',1,1,'Speak with Shissar Supervisor Sslarn','423933','','',0,0,0,0,0,0,0,'-1','0','419',-1,0,0),
(620109,2,-1,3,4,'Shissar Supervisor Enpsa',1,1,'Speak with Shissar Supervisor Enpsa','423934','','',0,0,0,0,0,0,0,'-1','0','419',-1,0,0),
(620109,3,-1,4,4,'Shissar Supervisor Mozull',1,1,'Speak with Shissar Supervisor Mozull','423935','','',0,0,0,0,0,0,0,'-1','0','419',-1,0,0),
(620109,4,-1,5,4,'Vizier Zio',1,1,'Speak with Vizier Zio','416140','','',0,0,0,0,0,0,0,'-1','0','416',-1,0,0),
(620110,0,-1,1,1,'Collection Bowl',1,4,'Loot 4 Collection Bowl','','9910012','',0,0,0,0,0,0,0,'-1','0','420',-1,0,0),
(620110,1,-1,2,2,'a power conduit',1,2,'Destroy 2 power conduits','423939','','',0,0,0,0,0,0,0,'-1','0','420',-1,0,0),
(620110,2,-1,3,1,'Power Conduit Shard',1,2,'Loot 2 Power Conduit Shard','','9910013','',0,0,0,0,0,0,0,'-1','0','420',-1,0,0),
(620110,3,-1,4,2,'a Shissar ritualist',1,2,'Kill 2 a Shissar ritualist','423938','','',0,0,0,0,0,0,0,'-1','0','420',-1,0,0),
(620110,4,-1,5,1,'Vial of Inky Blood',1,2,'Loot 2 Vial of Inky Blood','','9910014','',0,0,0,0,0,0,0,'-1','0','420',-1,0,0),
(620110,5,-1,6,4,'Arcanist Tivalin',1,1,'Speak with Arcanist Tivalin','416016','','',0,0,0,0,0,0,0,'-1','0','416',-1,0,0),
(620111,0,-1,1,1,'Shedded Snakeskin',1,3,'Loot 3 Shedded Snakeskin','','9910015','',0,0,0,0,0,0,0,'-1','0','420',-1,0,0),
(620111,1,-1,2,1,'Rituals of Essence and Blood',1,1,'Loot 1 Rituals of Essence and Blood','','9910016','',0,0,0,0,0,0,0,'-1','0','420',-1,0,0),
(620111,2,-1,3,4,'a shissar slave',1,1,'Speak with a shissar slave','423942','','',0,0,0,0,0,0,0,'-1','0','420',-1,0,0),
(620111,3,-1,4,1,'Bloodletting Kris',1,3,'Loot 3 Bloodletting Kris','','9910017','',0,0,0,0,0,0,0,'-1','0','420',-1,0,0),
(620111,4,-1,5,4,'Arcanist Tivalin',1,1,'Speak with Arcanist Tivalin','416016','','',0,0,0,0,0,0,0,'-1','0','416',-1,0,0);
