-- ============================================================================
-- Secrets of Faydwer -- Crystallos open world: trash retune + named rares.
-- Rasper: raspersrealm.com/Everquest/SoF/openCrystallos.html
-- Generated by sof_content/gen_crystallos_rares.py -- do not hand-edit.
-- Idempotent: DELETE+INSERT on explicit verified-free ids.
-- ============================================================================

-- ---------------------------------------------------------------- npc_spells
DELETE FROM `npc_spells_entries` WHERE `npc_spells_id` BETWEEN 1520007201 AND 1520007201+59;
DELETE FROM `npc_spells` WHERE `id` BETWEEN 1520007201 AND 1520007201+59;

INSERT INTO `npc_spells` (`id`,`name`,`parent_list`,`attack_proc`) VALUES (1520007201,'sof_crystallos_sentry',0,0),(1520007202,'sof_crystallos_evoker',0,0);

-- ---------------------------------------------------------------- retune existing stubs
-- a_prismatic_wyvern (446000)
UPDATE `npc_types` SET `level`=82, `hp`=420000, `mindmg`=0, `maxdmg`=3200, `AC`=500, `ATK`=250, `Accuracy`=250, `slow_mitigation`=0, `see_invis`=0, `npc_spells_id`=0 WHERE `id`=446000 AND `maxdmg` <= 4;

-- an_ice_drake (446003)
UPDATE `npc_types` SET `level`=82, `hp`=420000, `mindmg`=0, `maxdmg`=3200, `AC`=500, `ATK`=250, `Accuracy`=250, `slow_mitigation`=0, `see_invis`=0, `npc_spells_id`=0 WHERE `id`=446003 AND `maxdmg` <= 4;

-- a_prismatic_overlord (446006)
UPDATE `npc_types` SET `level`=82, `hp`=520000, `mindmg`=0, `maxdmg`=3800, `AC`=540, `ATK`=260, `Accuracy`=260, `slow_mitigation`=0, `see_invis`=0, `npc_spells_id`=0 WHERE `id`=446006 AND `maxdmg` <= 4;

-- a_fire_drake (446007)
UPDATE `npc_types` SET `level`=82, `hp`=420000, `mindmg`=0, `maxdmg`=3200, `AC`=500, `ATK`=250, `Accuracy`=250, `slow_mitigation`=0, `see_invis`=0, `npc_spells_id`=0 WHERE `id`=446007 AND `maxdmg` <= 4;

-- a_watchful_sentry (446008)
UPDATE `npc_types` SET `level`=82, `hp`=520000, `mindmg`=0, `maxdmg`=4000, `AC`=540, `ATK`=260, `Accuracy`=260, `slow_mitigation`=0, `see_invis`=1, `npc_spells_id`=1520007201 WHERE `id`=446008 AND `maxdmg` <= 4;

-- a_trapped_elemental (446009)
UPDATE `npc_types` SET `level`=79, `hp`=340000, `mindmg`=0, `maxdmg`=2800, `AC`=480, `ATK`=240, `Accuracy`=240, `slow_mitigation`=0, `see_invis`=0, `npc_spells_id`=0 WHERE `id`=446009 AND `maxdmg` <= 4;

-- a_prismatic_champion (446011)
UPDATE `npc_types` SET `level`=82, `hp`=480000, `mindmg`=0, `maxdmg`=3600, `AC`=520, `ATK`=255, `Accuracy`=255, `slow_mitigation`=0, `see_invis`=0, `npc_spells_id`=0 WHERE `id`=446011 AND `maxdmg` <= 4;

-- a_prismatic_evoker (446012)
UPDATE `npc_types` SET `level`=82, `hp`=420000, `mindmg`=0, `maxdmg`=3000, `AC`=500, `ATK`=250, `Accuracy`=250, `slow_mitigation`=0, `see_invis`=0, `npc_spells_id`=1520007202 WHERE `id`=446012 AND `maxdmg` <= 4;

-- a_prismatic_lifebringer (446013)
UPDATE `npc_types` SET `level`=82, `hp`=420000, `mindmg`=0, `maxdmg`=3000, `AC`=500, `ATK`=250, `Accuracy`=250, `slow_mitigation`=0, `see_invis`=0, `npc_spells_id`=0 WHERE `id`=446013 AND `maxdmg` <= 4;

-- An_Elder_Fire_Wyvern (446015)
UPDATE `npc_types` SET `level`=82, `hp`=500000, `mindmg`=0, `maxdmg`=4000, `AC`=540, `ATK`=260, `Accuracy`=260, `slow_mitigation`=75, `see_invis`=1, `npc_spells_id`=0 WHERE `id`=446015 AND `maxdmg` <= 4;

-- a_captive_elemental (446016)
UPDATE `npc_types` SET `level`=79, `hp`=340000, `mindmg`=0, `maxdmg`=2800, `AC`=480, `ATK`=240, `Accuracy`=240, `slow_mitigation`=0, `see_invis`=0, `npc_spells_id`=0 WHERE `id`=446016 AND `maxdmg` <= 4;

-- an_air_drake (446017)
UPDATE `npc_types` SET `level`=82, `hp`=420000, `mindmg`=0, `maxdmg`=3200, `AC`=500, `ATK`=250, `Accuracy`=250, `slow_mitigation`=0, `see_invis`=0, `npc_spells_id`=0 WHERE `id`=446017 AND `maxdmg` <= 4;

-- An_Elder_Fire_Drake (446023)
UPDATE `npc_types` SET `level`=82, `hp`=500000, `mindmg`=0, `maxdmg`=4000, `AC`=540, `ATK`=260, `Accuracy`=260, `slow_mitigation`=75, `see_invis`=1, `npc_spells_id`=0 WHERE `id`=446023 AND `maxdmg` <= 4;

-- an_earth_drake (446028)
UPDATE `npc_types` SET `level`=82, `hp`=420000, `mindmg`=0, `maxdmg`=3200, `AC`=500, `ATK`=250, `Accuracy`=250, `slow_mitigation`=0, `see_invis`=0, `npc_spells_id`=0 WHERE `id`=446028 AND `maxdmg` <= 4;

-- a_contained_elemental (446034)
UPDATE `npc_types` SET `level`=79, `hp`=340000, `mindmg`=0, `maxdmg`=2800, `AC`=480, `ATK`=240, `Accuracy`=240, `slow_mitigation`=0, `see_invis`=0, `npc_spells_id`=0 WHERE `id`=446034 AND `maxdmg` <= 4;

-- An_Elder_Earth_Drake (446044)
UPDATE `npc_types` SET `level`=82, `hp`=500000, `mindmg`=0, `maxdmg`=4000, `AC`=540, `ATK`=260, `Accuracy`=260, `slow_mitigation`=75, `see_invis`=1, `npc_spells_id`=0 WHERE `id`=446044 AND `maxdmg` <= 4;

-- a_servant_of_the_Ancients (446057)
UPDATE `npc_types` SET `level`=82, `hp`=480000, `mindmg`=0, `maxdmg`=3600, `AC`=520, `ATK`=255, `Accuracy`=255, `slow_mitigation`=0, `see_invis`=0, `npc_spells_id`=0 WHERE `id`=446057 AND `maxdmg` <= 4;

-- An_Elder_Ice_Wyvern (446078)
UPDATE `npc_types` SET `level`=82, `hp`=500000, `mindmg`=0, `maxdmg`=4000, `AC`=540, `ATK`=260, `Accuracy`=260, `slow_mitigation`=75, `see_invis`=1, `npc_spells_id`=0 WHERE `id`=446078 AND `maxdmg` <= 4;

-- ---------------------------------------------------------------- new named rares
DROP TEMPORARY TABLE IF EXISTS sof_cry_nt;
CREATE TEMPORARY TABLE sof_cry_nt AS SELECT * FROM npc_types WHERE 0;

-- An_Elder_Air_Drake: replaces any drake in the Air wing
INSERT INTO sof_cry_nt SELECT * FROM npc_types WHERE id = 446017;
UPDATE sof_cry_nt SET id = 446100, name = 'An_Elder_Air_Drake', level = 82, hp = 500000, mindmg = 0, maxdmg = 4000, AC = 540, ATK = 250, Accuracy = 250, slow_mitigation = 75, loottable_id = 1520007801, npc_faction_id = 1520000103, npc_spells_id = 0, special_abilities = '', aggroradius = 70, see_invis = 1, raid_target = 0 WHERE id = 446017;
INSERT IGNORE INTO npc_types SELECT * FROM sof_cry_nt;
DELETE FROM sof_cry_nt;

-- An_Elder_Air_Wyvern: replaces any wyvern in the Air wing
INSERT INTO sof_cry_nt SELECT * FROM npc_types WHERE id = 446015;
UPDATE sof_cry_nt SET id = 446101, name = 'An_Elder_Air_Wyvern', level = 82, hp = 500000, mindmg = 0, maxdmg = 4000, AC = 540, ATK = 250, Accuracy = 250, slow_mitigation = 75, loottable_id = 1520007802, npc_faction_id = 1520000103, npc_spells_id = 0, special_abilities = '', aggroradius = 70, see_invis = 1, raid_target = 0 WHERE id = 446015;
INSERT IGNORE INTO npc_types SELECT * FROM sof_cry_nt;
DELETE FROM sof_cry_nt;

-- An_Elder_Earth_Wyvern: replaces any wyvern in the Earth wing
INSERT INTO sof_cry_nt SELECT * FROM npc_types WHERE id = 446015;
UPDATE sof_cry_nt SET id = 446102, name = 'An_Elder_Earth_Wyvern', level = 82, hp = 500000, mindmg = 0, maxdmg = 4000, AC = 540, ATK = 250, Accuracy = 250, slow_mitigation = 75, loottable_id = 1520007803, npc_faction_id = 1520000103, npc_spells_id = 0, special_abilities = '', aggroradius = 70, see_invis = 1, raid_target = 0 WHERE id = 446015;
INSERT IGNORE INTO npc_types SELECT * FROM sof_cry_nt;
DELETE FROM sof_cry_nt;

-- An_Elder_Ice_Drake: replaces any drake in the Ice wing
INSERT INTO sof_cry_nt SELECT * FROM npc_types WHERE id = 446017;
UPDATE sof_cry_nt SET id = 446103, name = 'An_Elder_Ice_Drake', level = 82, hp = 500000, mindmg = 0, maxdmg = 4000, AC = 540, ATK = 250, Accuracy = 250, slow_mitigation = 75, loottable_id = 1520007804, npc_faction_id = 1520000103, npc_spells_id = 0, special_abilities = '', aggroradius = 70, see_invis = 1, raid_target = 0 WHERE id = 446017;
INSERT IGNORE INTO npc_types SELECT * FROM sof_cry_nt;
DELETE FROM sof_cry_nt;

-- Heart_of_the_Avalanche: replaces any golem; splits into 4 if not killed fast
INSERT INTO sof_cry_nt SELECT * FROM npc_types WHERE id = 446006;
UPDATE sof_cry_nt SET id = 446104, name = 'Heart_of_the_Avalanche', level = 82, hp = 520000, mindmg = 0, maxdmg = 4200, AC = 540, ATK = 250, Accuracy = 250, slow_mitigation = 75, loottable_id = 1520007805, npc_faction_id = 1520000103, npc_spells_id = 0, special_abilities = '', aggroradius = 70, see_invis = 0, raid_target = 0 WHERE id = 446006;
INSERT IGNORE INTO npc_types SELECT * FROM sof_cry_nt;
DELETE FROM sof_cry_nt;

-- Rockcrush: replaces any golem; splits into 4
INSERT INTO sof_cry_nt SELECT * FROM npc_types WHERE id = 446006;
UPDATE sof_cry_nt SET id = 446105, name = 'Rockcrush', level = 82, hp = 540000, mindmg = 0, maxdmg = 5000, AC = 560, ATK = 250, Accuracy = 250, slow_mitigation = 75, loottable_id = 1520007806, npc_faction_id = 1520000103, npc_spells_id = 0, special_abilities = '', aggroradius = 70, see_invis = 0, raid_target = 0 WHERE id = 446006;
INSERT IGNORE INTO npc_types SELECT * FROM sof_cry_nt;
DELETE FROM sof_cry_nt;

-- Squire_Alkaa: fixed, Fire wing
INSERT INTO sof_cry_nt SELECT * FROM npc_types WHERE id = 446050;
UPDATE sof_cry_nt SET id = 446110, name = 'Squire_Alkaa', level = 82, hp = 800000, mindmg = 0, maxdmg = 8000, AC = 580, ATK = 250, Accuracy = 250, slow_mitigation = 75, loottable_id = 1520007811, npc_faction_id = 1520000103, npc_spells_id = 0, special_abilities = '', aggroradius = 70, see_invis = 0, raid_target = 0 WHERE id = 446050;
INSERT IGNORE INTO npc_types SELECT * FROM sof_cry_nt;
DELETE FROM sof_cry_nt;

-- Squire_Tectoran: fixed, Earth wing
INSERT INTO sof_cry_nt SELECT * FROM npc_types WHERE id = 446050;
UPDATE sof_cry_nt SET id = 446111, name = 'Squire_Tectoran', level = 82, hp = 800000, mindmg = 0, maxdmg = 8000, AC = 580, ATK = 250, Accuracy = 250, slow_mitigation = 75, loottable_id = 1520007812, npc_faction_id = 1520000103, npc_spells_id = 0, special_abilities = '', aggroradius = 70, see_invis = 0, raid_target = 0 WHERE id = 446050;
INSERT IGNORE INTO npc_types SELECT * FROM sof_cry_nt;
DELETE FROM sof_cry_nt;

-- Squire_Zirkanamef: fixed, Air wing
INSERT INTO sof_cry_nt SELECT * FROM npc_types WHERE id = 446050;
UPDATE sof_cry_nt SET id = 446112, name = 'Squire_Zirkanamef', level = 82, hp = 800000, mindmg = 0, maxdmg = 8000, AC = 580, ATK = 250, Accuracy = 250, slow_mitigation = 75, loottable_id = 1520007813, npc_faction_id = 1520000103, npc_spells_id = 0, special_abilities = '', aggroradius = 70, see_invis = 0, raid_target = 0 WHERE id = 446050;
INSERT IGNORE INTO npc_types SELECT * FROM sof_cry_nt;
DELETE FROM sof_cry_nt;

-- a_vengeful_captive_elemental: spawns from any fire-wing elemental
INSERT INTO sof_cry_nt SELECT * FROM npc_types WHERE id = 446016;
UPDATE sof_cry_nt SET id = 446116, name = 'a_vengeful_captive_elemental', level = 79, hp = 440000, mindmg = 0, maxdmg = 3200, AC = 500, ATK = 250, Accuracy = 250, slow_mitigation = 75, loottable_id = 1520007817, npc_faction_id = 1520000103, npc_spells_id = 0, special_abilities = '', aggroradius = 70, see_invis = 0, raid_target = 0 WHERE id = 446016;
INSERT IGNORE INTO npc_types SELECT * FROM sof_cry_nt;
DELETE FROM sof_cry_nt;

-- a_vengeful_contained_elemental: spawns from any air-wing elemental
INSERT INTO sof_cry_nt SELECT * FROM npc_types WHERE id = 446034;
UPDATE sof_cry_nt SET id = 446117, name = 'a_vengeful_contained_elemental', level = 79, hp = 440000, mindmg = 0, maxdmg = 3200, AC = 500, ATK = 250, Accuracy = 250, slow_mitigation = 75, loottable_id = 1520007818, npc_faction_id = 1520000103, npc_spells_id = 0, special_abilities = '', aggroradius = 70, see_invis = 0, raid_target = 0 WHERE id = 446034;
INSERT IGNORE INTO npc_types SELECT * FROM sof_cry_nt;
DELETE FROM sof_cry_nt;

-- a_vengeful_trapped_elemental: spawns from any ice-wing elemental
INSERT INTO sof_cry_nt SELECT * FROM npc_types WHERE id = 446009;
UPDATE sof_cry_nt SET id = 446118, name = 'a_vengeful_trapped_elemental', level = 79, hp = 440000, mindmg = 0, maxdmg = 3200, AC = 500, ATK = 250, Accuracy = 250, slow_mitigation = 75, loottable_id = 1520007819, npc_faction_id = 1520000103, npc_spells_id = 0, special_abilities = '', aggroradius = 70, see_invis = 0, raid_target = 0 WHERE id = 446009;
INSERT IGNORE INTO npc_types SELECT * FROM sof_cry_nt;
DELETE FROM sof_cry_nt;

DROP TEMPORARY TABLE IF EXISTS sof_cry_nt;

-- ---------------------------------------------------------------- rare loot
DELETE FROM `loottable_entries` WHERE `loottable_id` BETWEEN 1520007801 AND 1520007801+59;
DELETE FROM `lootdrop_entries` WHERE `lootdrop_id` BETWEEN 1520007801 AND 1520007801+59;
DELETE FROM `lootdrop` WHERE `id` BETWEEN 1520007801 AND 1520007801+59;
DELETE FROM `loottable` WHERE `id` BETWEEN 1520007801 AND 1520007801+59;

INSERT INTO `loottable` (`id`,`name`,`mincash`,`maxcash`,`avgcoin`) VALUES
(1520007801,'SoF_Cry_elder_air_drake',20000,40000,20000),
(1520007802,'SoF_Cry_elder_air_wyvern',20000,40000,20000),
(1520007803,'SoF_Cry_elder_earth_wyvern',20000,40000,20000),
(1520007804,'SoF_Cry_elder_ice_drake',20000,40000,20000),
(1520007805,'SoF_Cry_heart_of_the_avalanche',20000,40000,20000),
(1520007806,'SoF_Cry_rockcrush',20000,40000,20000),
(1520007811,'SoF_Cry_squire_alkaa',20000,40000,20000),
(1520007812,'SoF_Cry_squire_tectoran',20000,40000,20000),
(1520007813,'SoF_Cry_squire_zirkanamef',20000,40000,20000),
(1520007817,'SoF_Cry_vengeful_captive_elemental',20000,40000,20000),
(1520007818,'SoF_Cry_vengeful_contained_elemental',20000,40000,20000),
(1520007819,'SoF_Cry_vengeful_trapped_elemental',20000,40000,20000);
INSERT INTO `lootdrop` (`id`,`name`) VALUES
(1520007801,'SoF_Cry_elder_air_drake_drop'),
(1520007802,'SoF_Cry_elder_air_wyvern_drop'),
(1520007803,'SoF_Cry_elder_earth_wyvern_drop'),
(1520007804,'SoF_Cry_elder_ice_drake_drop'),
(1520007805,'SoF_Cry_heart_of_the_avalanche_drop'),
(1520007806,'SoF_Cry_rockcrush_drop'),
(1520007811,'SoF_Cry_squire_alkaa_drop'),
(1520007812,'SoF_Cry_squire_tectoran_drop'),
(1520007813,'SoF_Cry_squire_zirkanamef_drop'),
(1520007817,'SoF_Cry_vengeful_captive_elemental_drop'),
(1520007818,'SoF_Cry_vengeful_contained_elemental_drop'),
(1520007819,'SoF_Cry_vengeful_trapped_elemental_drop');
INSERT INTO `lootdrop_entries` (`lootdrop_id`,`item_id`,`item_charges`,`equip_item`,`chance`) VALUES
(1520007801,101333,1,0,15),
(1520007801,101833,1,0,8),
(1520007801,100011,1,0,35),
(1520007802,101336,1,0,15),
(1520007802,101836,1,0,8),
(1520007802,100011,1,0,35),
(1520007803,101337,1,0,15),
(1520007803,100010,1,0,35),
(1520007804,101334,1,0,15),
(1520007804,101834,1,0,8),
(1520007804,100009,1,0,35),
(1520007805,102708,1,0,10),
(1520007806,102705,1,0,10),
(1520007811,101301,1,0,10),
(1520007811,101302,1,0,10),
(1520007811,101340,1,0,8),
(1520007811,102703,1,0,6),
(1520007812,101305,1,0,10),
(1520007812,101343,1,0,8),
(1520007812,102703,1,0,6),
(1520007813,101325,1,0,10),
(1520007813,101338,1,0,8),
(1520007813,102703,1,0,6),
(1520007817,102713,1,0,8),
(1520007817,102715,1,0,6),
(1520007818,102713,1,0,8),
(1520007818,102715,1,0,6),
(1520007819,102713,1,0,8),
(1520007819,102715,1,0,6);
INSERT INTO `loottable_entries` (`loottable_id`,`lootdrop_id`,`multiplier`,`droplimit`,`mindrop`,`probability`) VALUES
(1520007801,1520007801,1,0,0,100),
(1520007802,1520007802,1,0,0,100),
(1520007803,1520007803,1,0,0,100),
(1520007804,1520007804,1,0,0,100),
(1520007805,1520007805,1,0,0,100),
(1520007806,1520007806,1,0,0,100),
(1520007811,1520007811,1,0,0,100),
(1520007812,1520007812,1,0,0,100),
(1520007813,1520007813,1,0,0,100),
(1520007817,1520007817,1,0,0,100),
(1520007818,1520007818,1,0,0,100),
(1520007819,1520007819,1,0,0,100);

-- ---------------------------------------------------------------- rare spawns (fixed anchors, TUNABLE)
DELETE FROM `spawnentry` WHERE `spawngroupID` BETWEEN 1520007301 AND 1520007301+59;
DELETE FROM `spawn2` WHERE `spawngroupID` BETWEEN 1520007301 AND 1520007301+59;
DELETE FROM `spawngroup` WHERE `id` BETWEEN 1520007301 AND 1520007301+59;

INSERT INTO `spawngroup` (`id`,`name`,`spawn_limit`,`dist`,`delay`,`mindelay`,`despawn`) VALUES
(1520007301,'sof_cry_rare_446100',1,0,7200,3600,0),
(1520007302,'sof_cry_rare_446101',1,0,7200,3600,0),
(1520007303,'sof_cry_rare_446102',1,0,7200,3600,0),
(1520007304,'sof_cry_rare_446103',1,0,7200,3600,0),
(1520007305,'sof_cry_rare_446104',1,0,7200,3600,0),
(1520007306,'sof_cry_rare_446105',1,0,7200,3600,0),
(1520007307,'sof_cry_rare_446110',1,0,7200,3600,0),
(1520007308,'sof_cry_rare_446111',1,0,7200,3600,0),
(1520007309,'sof_cry_rare_446112',1,0,7200,3600,0),
(1520007310,'sof_cry_rare_446116',1,0,7200,3600,0),
(1520007311,'sof_cry_rare_446117',1,0,7200,3600,0),
(1520007312,'sof_cry_rare_446118',1,0,7200,3600,0);
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES
(1520007301,446100,100),
(1520007302,446101,100),
(1520007303,446102,100),
(1520007304,446103,100),
(1520007305,446104,100),
(1520007306,446105,100),
(1520007307,446110,100),
(1520007308,446111,100),
(1520007309,446112,100),
(1520007310,446116,100),
(1520007311,446117,100),
(1520007312,446118,100);
-- Anchored spawns (TUNABLE): park each rare on its wing trash cluster.
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) VALUES (1520007301,'crystallos',0,1050,1100,-30,0,7200);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) VALUES (1520007302,'crystallos',0,1900,900,200,0,7200);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) VALUES (1520007303,'crystallos',0,-340,1950,-210,0,7200);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) VALUES (1520007304,'crystallos',0,1370,-150,151,0,7200);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) VALUES (1520007305,'crystallos',0,950,-250,151,0,7200);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) VALUES (1520007306,'crystallos',0,1150,-320,151,0,7200);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) VALUES (1520007307,'crystallos',0,-1200,450,50,0,7200);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) VALUES (1520007308,'crystallos',0,-300,2400,-380,0,7200);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) VALUES (1520007309,'crystallos',0,1250,1300,60,0,7200);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) VALUES (1520007310,'crystallos',0,-1100,900,26,0,7200);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) VALUES (1520007311,'crystallos',0,1200,1000,55,0,7200);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) VALUES (1520007312,'crystallos',0,1250,-260,151,0,7200);

-- ---------------------------------------------------------------- PH replacement
-- The guide says rares 'spawn in place of' trash. Turn the squire/golem PH
-- lines into real PH spawnentries: rare joins the PH trash spawn group.

-- strung PH entries: INSERT IGNORE the rare into each PH trash group at low chance.

-- 446017 -> 446100
INSERT IGNORE INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) SELECT sg.id, 446100, 2 FROM spawngroup sg WHERE EXISTS (SELECT 1 FROM spawnentry se WHERE se.spawngroupID=sg.id AND se.npcID=446017);

-- 446028 -> 446103
INSERT IGNORE INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) SELECT sg.id, 446103, 2 FROM spawngroup sg WHERE EXISTS (SELECT 1 FROM spawnentry se WHERE se.spawngroupID=sg.id AND se.npcID=446028);

-- 446003 -> 446103
INSERT IGNORE INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) SELECT sg.id, 446103, 2 FROM spawngroup sg WHERE EXISTS (SELECT 1 FROM spawnentry se WHERE se.spawngroupID=sg.id AND se.npcID=446003);

-- 446006 -> 446105
INSERT IGNORE INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) SELECT sg.id, 446105, 2 FROM spawngroup sg WHERE EXISTS (SELECT 1 FROM spawnentry se WHERE se.spawngroupID=sg.id AND se.npcID=446006);

-- 446016 -> 446116
INSERT IGNORE INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) SELECT sg.id, 446116, 2 FROM spawngroup sg WHERE EXISTS (SELECT 1 FROM spawnentry se WHERE se.spawngroupID=sg.id AND se.npcID=446016);

-- 446034 -> 446117
INSERT IGNORE INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) SELECT sg.id, 446117, 2 FROM spawngroup sg WHERE EXISTS (SELECT 1 FROM spawnentry se WHERE se.spawngroupID=sg.id AND se.npcID=446034);

-- 446009 -> 446118
INSERT IGNORE INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) SELECT sg.id, 446118, 2 FROM spawngroup sg WHERE EXISTS (SELECT 1 FROM spawnentry se WHERE se.spawngroupID=sg.id AND se.npcID=446009);
