-- SoD raid expeditions: real bosses for raid request tasks 303060-67.
-- Generated by sod_content/gen_raids.py -- do not hand-edit.
-- Twin content of manifest entry '20261002_sod_raids' (v91).
-- Rasper: raidOG2/raidKith/raidKunark1/raidRathe3/raidKorafax/raidDiscord.
-- Rules + request flow: plugins/NMS_sod_utils.pl (%SOD_RAIDS).
-- Encounters: <zone>/<npc_id>.lua; controllers 478730-478737;
-- npc ids 478700-478749; spawngroups 1520008620+.
-- Chests are loot-event anchors only (raid loot economy out of scope).

-- ============================================================
-- Raid task activities: single boss-kill step, versioned instance.
-- ============================================================
DELETE FROM `task_activities` WHERE `taskid` IN (303060,303061,303062,303063,303064,303065,303066,303067);
UPDATE `tasks` SET `title` = 'Stop the Ascension', `description` = 'Apothecary Cadmael requests the raid: stop the ascension at the Temple of Bertoxxulous. Rottrued the Twisted must not rise. Request with ''request'', zone in with ''ready''.' WHERE `id` = 303060;
UPDATE `tasks` SET `title` = 'Fall of General Bahgresh', `description` = 'Firiona Vie requests the raid: the fall of General Bahgresh. Break the kyv vanguard and the dark camps, then the general. Request with ''request'', zone in with ''ready''.' WHERE `id` = 303061;
UPDATE `tasks` SET `title` = 'A Council Divided', `description` = 'Jaled`Dar requests the raid: the Kaesora council debates joining Discord. Break the council before it decides. Request with ''request'', zone in with ''ready''.' WHERE `id` = 303062;
UPDATE `tasks` SET `title` = 'Eriak''s Downfall', `description` = 'Ylatra the Vassal requests the raid: Eriak''s downfall. Silence Xadrith the Voice, then bring down Eriak Dechard. Request with ''request'', zone in with ''ready''.' WHERE `id` = 303063;
UPDATE `tasks` SET `title` = 'Korafax Raid: Pallorax the Soul Slayer', `description` = 'Herald of Druzzil Ro requests the raid. Pallorax the Soul Slayer hunts the riftseeker portals. Request with ''request'', zone in with ''ready''.' WHERE `id` = 303064;
UPDATE `tasks` SET `title` = 'Korafax Raid: The Mindshear Avatar', `description` = 'Herald of Druzzil Ro requests the raid. Wade through the mindshear acolytes and destroy the Avatar. Request with ''request'', zone in with ''ready''.' WHERE `id` = 303065;
UPDATE `tasks` SET `title` = 'Korafax Raid: Venom Lord Ksathrax', `description` = 'Herald of Druzzil Ro requests the raid. Venom Lord Ksathrax must fall; do not cure his venom. Request with ''request'', zone in with ''ready''.' WHERE `id` = 303066;
UPDATE `tasks` SET `title` = 'Citadel Raid: The Mindblight', `description` = 'With Korafax broken and a Tower Key in hand, breach the Citadel of the Worldslayer and destroy the Mindblight. Request with ''request'', zone in with ''ready''.' WHERE `id` = 303067;
INSERT INTO `task_activities` (taskid,activityid,req_activity_id,step,activitytype,target_name,goalmethod,goalcount,description_override,npc_match_list,item_id_list,item_list,dz_switch_id,min_x,min_y,min_z,max_x,max_y,max_z,skill_list,spell_list,zones,zone_version,optional,list_group) VALUES
(303060,0,-1,1,2,'Stop the Ascension',0,1,'Stop the Ascension','478700','','',0,0,0,0,0,0,0,'-1','0','bertoxtemple',51,0,0),
(303061,0,-1,1,2,'Fall of General Bahgresh',0,1,'Fall of General Bahgresh','478701','','',0,0,0,0,0,0,0,'-1','0','oldkithicor',51,0,0),
(303062,0,-1,1,2,'the Kaesora council',0,4,'the Kaesora council','478707|478708|478709|478710|478711|478712|478713|478714','','',0,0,0,0,0,0,0,'-1','0','oldkaesoraa',51,0,0),
(303063,0,-1,1,2,'Eriak''s Downfall',0,1,'Eriak''s Downfall','478716','','',0,0,0,0,0,0,0,'-1','0','rathechamber',51,0,0),
(303064,0,-1,1,2,'Pallorax the Soul Slayer',0,1,'Pallorax the Soul Slayer','478717','','',0,0,0,0,0,0,0,'-1','0','discord',51,0,0),
(303065,0,-1,1,2,'The Mindshear Avatar',0,1,'The Mindshear Avatar','478718','','',0,0,0,0,0,0,0,'-1','0','discord',52,0,0),
(303066,0,-1,1,2,'Venom Lord Ksathrax',0,1,'Venom Lord Ksathrax','478719','','',0,0,0,0,0,0,0,'-1','0','discord',53,0,0),
(303067,0,-1,1,2,'The Mindblight',0,1,'The Mindblight','471001','','',0,0,0,0,0,0,0,'-1','0','discordtower',51,0,0);

-- ============================================================
-- Raid NPCs (cloned models; stats TUNABLE).
-- ============================================================
DELETE FROM `npc_types` WHERE `id` BETWEEN 478700 AND 478749;
UPDATE `npc_types` SET `hp` = 400000, `level` = 90 WHERE `id` = 471001;
DROP TEMPORARY TABLE IF EXISTS sod_raid_nt;
CREATE TEMPORARY TABLE sod_raid_nt AS SELECT * FROM npc_types WHERE 0;
INSERT INTO sod_raid_nt SELECT * FROM npc_types WHERE id = 469040;
UPDATE sod_raid_nt SET id = 478700, name = '#Rottrued_the_Twisted', level = 90, hp = 550000, mana = 0, loottable_id = 0, merchant_id = 0 WHERE id = 469040;
INSERT INTO sod_raid_nt SELECT * FROM npc_types WHERE id = 456086;
UPDATE sod_raid_nt SET id = 478701, name = '#General_Bahgresh', level = 90, hp = 650000, mana = 0, loottable_id = 0, merchant_id = 0 WHERE id = 456086;
INSERT INTO sod_raid_nt SELECT * FROM npc_types WHERE id = 470005;
UPDATE sod_raid_nt SET id = 478715, name = '#Xadrith_the_Voice', level = 88, hp = 350000, mana = 0, loottable_id = 0, merchant_id = 0 WHERE id = 470005;
INSERT INTO sod_raid_nt SELECT * FROM npc_types WHERE id = 475026;
UPDATE sod_raid_nt SET id = 478716, name = '#Eriak_Dechard', level = 90, hp = 750000, mana = 0, loottable_id = 0, merchant_id = 0 WHERE id = 475026;
INSERT INTO sod_raid_nt SELECT * FROM npc_types WHERE id = 470005;
UPDATE sod_raid_nt SET id = 478717, name = '#Pallorax_the_Soul_Slayer', level = 90, hp = 800000, mana = 0, loottable_id = 0, merchant_id = 0 WHERE id = 470005;
INSERT INTO sod_raid_nt SELECT * FROM npc_types WHERE id = 470003;
UPDATE sod_raid_nt SET id = 478718, name = '#Mindshear_Avatar', level = 90, hp = 900000, mana = 0, loottable_id = 0, merchant_id = 0 WHERE id = 470003;
INSERT INTO sod_raid_nt SELECT * FROM npc_types WHERE id = 470005;
UPDATE sod_raid_nt SET id = 478719, name = '#Venom_Lord_Ksathrax', level = 90, hp = 850000, mana = 0, loottable_id = 0, merchant_id = 0 WHERE id = 470005;
INSERT INTO sod_raid_nt SELECT * FROM npc_types WHERE id = 456086;
UPDATE sod_raid_nt SET id = 478702, name = '#Rasven', level = 88, hp = 200000, mana = 0, loottable_id = 0, merchant_id = 0 WHERE id = 456086;
INSERT INTO sod_raid_nt SELECT * FROM npc_types WHERE id = 456086;
UPDATE sod_raid_nt SET id = 478703, name = '#Ythalym', level = 88, hp = 200000, mana = 0, loottable_id = 0, merchant_id = 0 WHERE id = 456086;
INSERT INTO sod_raid_nt SELECT * FROM npc_types WHERE id = 456086;
UPDATE sod_raid_nt SET id = 478704, name = '#Vacklun', level = 88, hp = 200000, mana = 0, loottable_id = 0, merchant_id = 0 WHERE id = 456086;
INSERT INTO sod_raid_nt SELECT * FROM npc_types WHERE id = 456118;
UPDATE sod_raid_nt SET id = 478705, name = 'a_dark_ritualist', level = 85, hp = 30000, mana = 0, loottable_id = 0, merchant_id = 0 WHERE id = 456118;
INSERT INTO sod_raid_nt SELECT * FROM npc_types WHERE id = 456118;
UPDATE sod_raid_nt SET id = 478706, name = 'a_dark_priest', level = 86, hp = 40000, mana = 0, loottable_id = 0, merchant_id = 0 WHERE id = 456118;
INSERT INTO sod_raid_nt SELECT * FROM npc_types WHERE id = 452018;
UPDATE sod_raid_nt SET id = 478707, name = '#Councilor_Akheen', level = 88, hp = 150000, mana = 0, loottable_id = 0, merchant_id = 0 WHERE id = 452018;
INSERT INTO sod_raid_nt SELECT * FROM npc_types WHERE id = 452018;
UPDATE sod_raid_nt SET id = 478708, name = '#Councilor_Vasska', level = 88, hp = 150000, mana = 0, loottable_id = 0, merchant_id = 0 WHERE id = 452018;
INSERT INTO sod_raid_nt SELECT * FROM npc_types WHERE id = 452018;
UPDATE sod_raid_nt SET id = 478709, name = '#Councilor_Zissik', level = 88, hp = 150000, mana = 0, loottable_id = 0, merchant_id = 0 WHERE id = 452018;
INSERT INTO sod_raid_nt SELECT * FROM npc_types WHERE id = 452018;
UPDATE sod_raid_nt SET id = 478710, name = '#Councilor_Krathok', level = 88, hp = 150000, mana = 0, loottable_id = 0, merchant_id = 0 WHERE id = 452018;
INSERT INTO sod_raid_nt SELECT * FROM npc_types WHERE id = 452018;
UPDATE sod_raid_nt SET id = 478711, name = '#Councilor_Ssivak', level = 88, hp = 150000, mana = 0, loottable_id = 0, merchant_id = 0 WHERE id = 452018;
INSERT INTO sod_raid_nt SELECT * FROM npc_types WHERE id = 452018;
UPDATE sod_raid_nt SET id = 478712, name = '#Councilor_Darruk', level = 88, hp = 150000, mana = 0, loottable_id = 0, merchant_id = 0 WHERE id = 452018;
INSERT INTO sod_raid_nt SELECT * FROM npc_types WHERE id = 452018;
UPDATE sod_raid_nt SET id = 478713, name = '#Councilor_Osskan', level = 88, hp = 150000, mana = 0, loottable_id = 0, merchant_id = 0 WHERE id = 452018;
INSERT INTO sod_raid_nt SELECT * FROM npc_types WHERE id = 452018;
UPDATE sod_raid_nt SET id = 478714, name = '#Councilor_Trezzik', level = 88, hp = 150000, mana = 0, loottable_id = 0, merchant_id = 0 WHERE id = 452018;
INSERT INTO sod_raid_nt SELECT * FROM npc_types WHERE id = 470002;
UPDATE sod_raid_nt SET id = 478720, name = 'a_riftseeker_sentinel', level = 87, hp = 80000, mana = 0, loottable_id = 0, merchant_id = 0 WHERE id = 470002;
INSERT INTO sod_raid_nt SELECT * FROM npc_types WHERE id = 470003;
UPDATE sod_raid_nt SET id = 478721, name = 'a_mindshear_acolyte', level = 86, hp = 60000, mana = 0, loottable_id = 0, merchant_id = 0 WHERE id = 470003;
INSERT INTO sod_raid_nt SELECT * FROM npc_types WHERE id = 470003;
UPDATE sod_raid_nt SET id = 478722, name = 'a_mindshear_maniac', level = 85, hp = 30000, mana = 0, loottable_id = 0, merchant_id = 0 WHERE id = 470003;
INSERT INTO sod_raid_nt SELECT * FROM npc_types WHERE id = 470005;
UPDATE sod_raid_nt SET id = 478723, name = '#Venomous_Projection', level = 88, hp = 200000, mana = 0, loottable_id = 0, merchant_id = 0 WHERE id = 470005;
INSERT INTO sod_raid_nt SELECT * FROM npc_types WHERE id = 470002;
UPDATE sod_raid_nt SET id = 478724, name = 'a_venomous_tunat', level = 86, hp = 60000, mana = 0, loottable_id = 0, merchant_id = 0 WHERE id = 470002;
INSERT INTO sod_raid_nt SELECT * FROM npc_types WHERE id = 470003;
UPDATE sod_raid_nt SET id = 478725, name = 'a_mindgnawer', level = 84, hp = 15000, mana = 0, loottable_id = 0, merchant_id = 0 WHERE id = 470003;
INSERT INTO sod_raid_nt SELECT * FROM npc_types WHERE id = 470014;
UPDATE sod_raid_nt SET id = 478726, name = 'a_mindshear_ooze', level = 86, hp = 45000, mana = 0, loottable_id = 0, merchant_id = 0 WHERE id = 470014;
INSERT INTO sod_raid_nt SELECT * FROM npc_types WHERE id = 470001;
UPDATE sod_raid_nt SET id = 478730, name = 'an_anchor_of_the_timeshear', level = 100, hp = 100000, mana = 0, loottable_id = 0, merchant_id = 0 WHERE id = 470001;
INSERT INTO sod_raid_nt SELECT * FROM npc_types WHERE id = 470001;
UPDATE sod_raid_nt SET id = 478731, name = 'an_anchor_of_the_timeshear', level = 100, hp = 100000, mana = 0, loottable_id = 0, merchant_id = 0 WHERE id = 470001;
INSERT INTO sod_raid_nt SELECT * FROM npc_types WHERE id = 470001;
UPDATE sod_raid_nt SET id = 478732, name = 'an_anchor_of_the_timeshear', level = 100, hp = 100000, mana = 0, loottable_id = 0, merchant_id = 0 WHERE id = 470001;
INSERT INTO sod_raid_nt SELECT * FROM npc_types WHERE id = 470001;
UPDATE sod_raid_nt SET id = 478733, name = 'an_anchor_of_the_timeshear', level = 100, hp = 100000, mana = 0, loottable_id = 0, merchant_id = 0 WHERE id = 470001;
INSERT INTO sod_raid_nt SELECT * FROM npc_types WHERE id = 470001;
UPDATE sod_raid_nt SET id = 478734, name = 'an_anchor_of_the_timeshear', level = 100, hp = 100000, mana = 0, loottable_id = 0, merchant_id = 0 WHERE id = 470001;
INSERT INTO sod_raid_nt SELECT * FROM npc_types WHERE id = 470001;
UPDATE sod_raid_nt SET id = 478735, name = 'an_anchor_of_the_timeshear', level = 100, hp = 100000, mana = 0, loottable_id = 0, merchant_id = 0 WHERE id = 470001;
INSERT INTO sod_raid_nt SELECT * FROM npc_types WHERE id = 470001;
UPDATE sod_raid_nt SET id = 478736, name = 'an_anchor_of_the_timeshear', level = 100, hp = 100000, mana = 0, loottable_id = 0, merchant_id = 0 WHERE id = 470001;
INSERT INTO sod_raid_nt SELECT * FROM npc_types WHERE id = 470001;
UPDATE sod_raid_nt SET id = 478737, name = 'an_anchor_of_the_timeshear', level = 100, hp = 100000, mana = 0, loottable_id = 0, merchant_id = 0 WHERE id = 470001;
INSERT INTO sod_raid_nt SELECT * FROM npc_types WHERE id = 460580;
UPDATE sod_raid_nt SET id = 478740, name = 'Treasure_of_Rottrued', level = 65, hp = 7375, mana = 0, loottable_id = 0, merchant_id = 0 WHERE id = 460580;
INSERT INTO sod_raid_nt SELECT * FROM npc_types WHERE id = 460580;
UPDATE sod_raid_nt SET id = 478741, name = 'Treasure_of_Bahgresh', level = 65, hp = 7375, mana = 0, loottable_id = 0, merchant_id = 0 WHERE id = 460580;
INSERT INTO sod_raid_nt SELECT * FROM npc_types WHERE id = 460580;
UPDATE sod_raid_nt SET id = 478742, name = 'Treasure_of_the_Council', level = 65, hp = 7375, mana = 0, loottable_id = 0, merchant_id = 0 WHERE id = 460580;
INSERT INTO sod_raid_nt SELECT * FROM npc_types WHERE id = 460580;
UPDATE sod_raid_nt SET id = 478743, name = 'Treasure_of_Eriak', level = 65, hp = 7375, mana = 0, loottable_id = 0, merchant_id = 0 WHERE id = 460580;
INSERT INTO sod_raid_nt SELECT * FROM npc_types WHERE id = 460580;
UPDATE sod_raid_nt SET id = 478744, name = 'Treasure_of_Pallorax', level = 65, hp = 7375, mana = 0, loottable_id = 0, merchant_id = 0 WHERE id = 460580;
INSERT INTO sod_raid_nt SELECT * FROM npc_types WHERE id = 460580;
UPDATE sod_raid_nt SET id = 478745, name = 'Treasure_of_the_Mindshear', level = 65, hp = 7375, mana = 0, loottable_id = 0, merchant_id = 0 WHERE id = 460580;
INSERT INTO sod_raid_nt SELECT * FROM npc_types WHERE id = 460580;
UPDATE sod_raid_nt SET id = 478746, name = 'Treasure_of_Ksathrax', level = 65, hp = 7375, mana = 0, loottable_id = 0, merchant_id = 0 WHERE id = 460580;
INSERT INTO sod_raid_nt SELECT * FROM npc_types WHERE id = 460580;
UPDATE sod_raid_nt SET id = 478747, name = 'Treasure_of_the_Mindblight', level = 65, hp = 7375, mana = 0, loottable_id = 0, merchant_id = 0 WHERE id = 460580;
INSERT INTO `npc_types` SELECT * FROM sod_raid_nt;
DROP TEMPORARY TABLE sod_raid_nt;

-- ============================================================
-- Instance spawns (versioned; static in raid instances only).
-- ============================================================
DELETE FROM `spawnentry` WHERE `spawngroupID` BETWEEN 1520008620 AND 1520008643;
DELETE FROM `spawn2` WHERE `spawngroupID` BETWEEN 1520008620 AND 1520008643;
DELETE FROM `spawngroup` WHERE `id` BETWEEN 1520008620 AND 1520008643;
INSERT INTO `spawngroup` (`id`,`name`,`spawn_limit`,`dist`,`delay`,`mindelay`,`despawn`) VALUES (1520008620,'sod_raid_478700_bertoxtemple_v51',0,0,600,300,0);
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (1520008620,478700,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) VALUES (1520008620,'bertoxtemple',51,252,248,2,0,600);

INSERT INTO `spawngroup` (`id`,`name`,`spawn_limit`,`dist`,`delay`,`mindelay`,`despawn`) VALUES (1520008621,'sod_raid_478730_bertoxtemple_v51',0,0,600,300,0);
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (1520008621,478730,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) VALUES (1520008621,'bertoxtemple',51,2,-2,2,0,600);

INSERT INTO `spawngroup` (`id`,`name`,`spawn_limit`,`dist`,`delay`,`mindelay`,`despawn`) VALUES (1520008622,'sod_raid_478701_oldkithicor_v51',0,0,600,300,0);
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (1520008622,478701,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) VALUES (1520008622,'oldkithicor',51,-5,1439,10,0,600);

INSERT INTO `spawngroup` (`id`,`name`,`spawn_limit`,`dist`,`delay`,`mindelay`,`despawn`) VALUES (1520008623,'sod_raid_478731_oldkithicor_v51',0,0,600,300,0);
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (1520008623,478731,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) VALUES (1520008623,'oldkithicor',51,-255,1189,10,0,600);

INSERT INTO `spawngroup` (`id`,`name`,`spawn_limit`,`dist`,`delay`,`mindelay`,`despawn`) VALUES (1520008624,'sod_raid_478732_oldkaesoraa_v51',0,0,600,300,0);
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (1520008624,478732,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) VALUES (1520008624,'oldkaesoraa',51,33,-20,3,0,600);

INSERT INTO `spawngroup` (`id`,`name`,`spawn_limit`,`dist`,`delay`,`mindelay`,`despawn`) VALUES (1520008625,'sod_raid_478716_rathechamber_v51',0,0,600,300,0);
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (1520008625,478716,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) VALUES (1520008625,'rathechamber',51,231,240,-22,0,600);

INSERT INTO `spawngroup` (`id`,`name`,`spawn_limit`,`dist`,`delay`,`mindelay`,`despawn`) VALUES (1520008626,'sod_raid_478733_rathechamber_v51',0,0,600,300,0);
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (1520008626,478733,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) VALUES (1520008626,'rathechamber',51,-19,-10,-22,0,600);

INSERT INTO `spawngroup` (`id`,`name`,`spawn_limit`,`dist`,`delay`,`mindelay`,`despawn`) VALUES (1520008627,'sod_raid_478717_discord_v51',0,0,600,300,0);
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (1520008627,478717,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) VALUES (1520008627,'discord',51,278,230,-16,0,600);

INSERT INTO `spawngroup` (`id`,`name`,`spawn_limit`,`dist`,`delay`,`mindelay`,`despawn`) VALUES (1520008628,'sod_raid_478734_discord_v51',0,0,600,300,0);
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (1520008628,478734,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) VALUES (1520008628,'discord',51,28,-20,-16,0,600);

INSERT INTO `spawngroup` (`id`,`name`,`spawn_limit`,`dist`,`delay`,`mindelay`,`despawn`) VALUES (1520008629,'sod_raid_478718_discord_v52',0,0,600,300,0);
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (1520008629,478718,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) VALUES (1520008629,'discord',52,278,230,-16,0,600);

INSERT INTO `spawngroup` (`id`,`name`,`spawn_limit`,`dist`,`delay`,`mindelay`,`despawn`) VALUES (1520008630,'sod_raid_478735_discord_v52',0,0,600,300,0);
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (1520008630,478735,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) VALUES (1520008630,'discord',52,28,-20,-16,0,600);

INSERT INTO `spawngroup` (`id`,`name`,`spawn_limit`,`dist`,`delay`,`mindelay`,`despawn`) VALUES (1520008631,'sod_raid_478719_discord_v53',0,0,600,300,0);
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (1520008631,478719,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) VALUES (1520008631,'discord',53,278,230,-16,0,600);

INSERT INTO `spawngroup` (`id`,`name`,`spawn_limit`,`dist`,`delay`,`mindelay`,`despawn`) VALUES (1520008632,'sod_raid_478736_discord_v53',0,0,600,300,0);
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (1520008632,478736,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) VALUES (1520008632,'discord',53,28,-20,-16,0,600);

INSERT INTO `spawngroup` (`id`,`name`,`spawn_limit`,`dist`,`delay`,`mindelay`,`despawn`) VALUES (1520008633,'sod_raid_478737_discordtower_v51',0,0,600,300,0);
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (1520008633,478737,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) VALUES (1520008633,'discordtower',51,0,-48,-48,0,600);

INSERT INTO `spawngroup` (`id`,`name`,`spawn_limit`,`dist`,`delay`,`mindelay`,`despawn`) VALUES (1520008634,'sod_raid_478707_oldkaesoraa_v51',0,0,600,300,0);
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (1520008634,478707,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) VALUES (1520008634,'oldkaesoraa',51,113,60,3,0,600);

INSERT INTO `spawngroup` (`id`,`name`,`spawn_limit`,`dist`,`delay`,`mindelay`,`despawn`) VALUES (1520008635,'sod_raid_478708_oldkaesoraa_v51',0,0,600,300,0);
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (1520008635,478708,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) VALUES (1520008635,'oldkaesoraa',51,173,60,3,0,600);

INSERT INTO `spawngroup` (`id`,`name`,`spawn_limit`,`dist`,`delay`,`mindelay`,`despawn`) VALUES (1520008636,'sod_raid_478709_oldkaesoraa_v51',0,0,600,300,0);
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (1520008636,478709,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) VALUES (1520008636,'oldkaesoraa',51,233,60,3,0,600);

INSERT INTO `spawngroup` (`id`,`name`,`spawn_limit`,`dist`,`delay`,`mindelay`,`despawn`) VALUES (1520008637,'sod_raid_478710_oldkaesoraa_v51',0,0,600,300,0);
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (1520008637,478710,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) VALUES (1520008637,'oldkaesoraa',51,293,60,3,0,600);

INSERT INTO `spawngroup` (`id`,`name`,`spawn_limit`,`dist`,`delay`,`mindelay`,`despawn`) VALUES (1520008638,'sod_raid_478711_oldkaesoraa_v51',0,0,600,300,0);
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (1520008638,478711,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) VALUES (1520008638,'oldkaesoraa',51,113,120,3,0,600);

INSERT INTO `spawngroup` (`id`,`name`,`spawn_limit`,`dist`,`delay`,`mindelay`,`despawn`) VALUES (1520008639,'sod_raid_478712_oldkaesoraa_v51',0,0,600,300,0);
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (1520008639,478712,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) VALUES (1520008639,'oldkaesoraa',51,173,120,3,0,600);

INSERT INTO `spawngroup` (`id`,`name`,`spawn_limit`,`dist`,`delay`,`mindelay`,`despawn`) VALUES (1520008640,'sod_raid_478713_oldkaesoraa_v51',0,0,600,300,0);
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (1520008640,478713,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) VALUES (1520008640,'oldkaesoraa',51,233,120,3,0,600);

INSERT INTO `spawngroup` (`id`,`name`,`spawn_limit`,`dist`,`delay`,`mindelay`,`despawn`) VALUES (1520008641,'sod_raid_478714_oldkaesoraa_v51',0,0,600,300,0);
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (1520008641,478714,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) VALUES (1520008641,'oldkaesoraa',51,293,120,3,0,600);

INSERT INTO `spawngroup` (`id`,`name`,`spawn_limit`,`dist`,`delay`,`mindelay`,`despawn`) VALUES (1520008642,'sod_raid_478715_rathechamber_v51',0,0,600,300,0);
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (1520008642,478715,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) VALUES (1520008642,'rathechamber',51,101,110,-22,0,600);

INSERT INTO `spawngroup` (`id`,`name`,`spawn_limit`,`dist`,`delay`,`mindelay`,`despawn`) VALUES (1520008643,'sod_raid_471001_discordtower_v51',0,0,600,300,0);
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (1520008643,471001,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) VALUES (1520008643,'discordtower',51,1,150,-48.375,0,600);
