-- SoD Rank III spell loremasters (The Void): one Loremaster of the
-- Timeshear per thevoida..thevoidg. Say 'reclaim' to scribe the Rk. III
-- tiers the character's raid flags unlock. Generated by
-- sod_content/gen_rk3.py -- do not hand-edit.
-- Twin content of manifest entry '20261002_sod_rk3' (v92).
-- Data: plugins/NMS_sod_rk3_data.pl; rules: plugins/NMS_sod_utils.pl.

DELETE FROM `npc_types` WHERE `id` BETWEEN 478750 AND 478756;
DELETE FROM `spawnentry` WHERE `spawngroupID` BETWEEN 1520008650 AND 1520008656;
DELETE FROM `spawn2` WHERE `spawngroupID` BETWEEN 1520008650 AND 1520008656;
DELETE FROM `spawngroup` WHERE `id` BETWEEN 1520008650 AND 1520008656;
DROP TEMPORARY TABLE IF EXISTS sod_rk3_nt;
CREATE TEMPORARY TABLE sod_rk3_nt AS SELECT * FROM npc_types WHERE 0;
INSERT INTO sod_rk3_nt SELECT * FROM npc_types WHERE id = 470001;
UPDATE sod_rk3_nt SET id = 478750, name = 'Loremaster_of_the_Timeshear', level = 90, hp = 30000, mana = 0, loottable_id = 0, npc_faction_id = 0, merchant_id = 0 WHERE id = 470001;

INSERT INTO `spawngroup` (`id`,`name`,`spawn_limit`,`dist`,`delay`,`mindelay`,`despawn`) VALUES (1520008650,'sod_rk3_loremaster_thevoida',0,0,600,300,0);
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (1520008650,478750,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) VALUES (1520008650,'thevoida',0,-79,-158,33,0,600);

INSERT INTO sod_rk3_nt SELECT * FROM npc_types WHERE id = 470001;
UPDATE sod_rk3_nt SET id = 478751, name = 'Loremaster_of_the_Timeshear', level = 90, hp = 30000, mana = 0, loottable_id = 0, npc_faction_id = 0, merchant_id = 0 WHERE id = 470001;

INSERT INTO `spawngroup` (`id`,`name`,`spawn_limit`,`dist`,`delay`,`mindelay`,`despawn`) VALUES (1520008651,'sod_rk3_loremaster_thevoidb',0,0,600,300,0);
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (1520008651,478751,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) VALUES (1520008651,'thevoidb',0,-79,-158,33,0,600);

INSERT INTO sod_rk3_nt SELECT * FROM npc_types WHERE id = 470001;
UPDATE sod_rk3_nt SET id = 478752, name = 'Loremaster_of_the_Timeshear', level = 90, hp = 30000, mana = 0, loottable_id = 0, npc_faction_id = 0, merchant_id = 0 WHERE id = 470001;

INSERT INTO `spawngroup` (`id`,`name`,`spawn_limit`,`dist`,`delay`,`mindelay`,`despawn`) VALUES (1520008652,'sod_rk3_loremaster_thevoidc',0,0,600,300,0);
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (1520008652,478752,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) VALUES (1520008652,'thevoidc',0,-79,-158,33,0,600);

INSERT INTO sod_rk3_nt SELECT * FROM npc_types WHERE id = 470001;
UPDATE sod_rk3_nt SET id = 478753, name = 'Loremaster_of_the_Timeshear', level = 90, hp = 30000, mana = 0, loottable_id = 0, npc_faction_id = 0, merchant_id = 0 WHERE id = 470001;

INSERT INTO `spawngroup` (`id`,`name`,`spawn_limit`,`dist`,`delay`,`mindelay`,`despawn`) VALUES (1520008653,'sod_rk3_loremaster_thevoidd',0,0,600,300,0);
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (1520008653,478753,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) VALUES (1520008653,'thevoidd',0,-79,-158,33,0,600);

INSERT INTO sod_rk3_nt SELECT * FROM npc_types WHERE id = 470001;
UPDATE sod_rk3_nt SET id = 478754, name = 'Loremaster_of_the_Timeshear', level = 90, hp = 30000, mana = 0, loottable_id = 0, npc_faction_id = 0, merchant_id = 0 WHERE id = 470001;

INSERT INTO `spawngroup` (`id`,`name`,`spawn_limit`,`dist`,`delay`,`mindelay`,`despawn`) VALUES (1520008654,'sod_rk3_loremaster_thevoide',0,0,600,300,0);
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (1520008654,478754,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) VALUES (1520008654,'thevoide',0,-79,-158,33,0,600);

INSERT INTO sod_rk3_nt SELECT * FROM npc_types WHERE id = 470001;
UPDATE sod_rk3_nt SET id = 478755, name = 'Loremaster_of_the_Timeshear', level = 90, hp = 30000, mana = 0, loottable_id = 0, npc_faction_id = 0, merchant_id = 0 WHERE id = 470001;

INSERT INTO `spawngroup` (`id`,`name`,`spawn_limit`,`dist`,`delay`,`mindelay`,`despawn`) VALUES (1520008655,'sod_rk3_loremaster_thevoidf',0,0,600,300,0);
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (1520008655,478755,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) VALUES (1520008655,'thevoidf',0,-79,-158,33,0,600);

INSERT INTO sod_rk3_nt SELECT * FROM npc_types WHERE id = 470001;
UPDATE sod_rk3_nt SET id = 478756, name = 'Loremaster_of_the_Timeshear', level = 90, hp = 30000, mana = 0, loottable_id = 0, npc_faction_id = 0, merchant_id = 0 WHERE id = 470001;

INSERT INTO `spawngroup` (`id`,`name`,`spawn_limit`,`dist`,`delay`,`mindelay`,`despawn`) VALUES (1520008656,'sod_rk3_loremaster_thevoidg',0,0,600,300,0);
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (1520008656,478756,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) VALUES (1520008656,'thevoidg',0,-79,-158,33,0,600);

INSERT INTO `npc_types` SELECT * FROM sod_rk3_nt;
DROP TEMPORARY TABLE sod_rk3_nt;
