-- SoF Loping Plains scripted arcs: Vrald + Purified Flawless Faycite
-- Triad (302000-302009). Generated by sof_content/gen_loping_arcs.py
-- -- do not hand-edit. Static approximations; see generator docstring.

DELETE FROM `task_activities` WHERE `taskid` IN (302000,302001,302002,302003,302004,302005,302006,302007,302008,302009);
DELETE FROM `tasks` WHERE `id` IN (302000,302001,302002,302003,302004,302005,302006,302007,302008,302009);

INSERT INTO `tasks` (id,type,duration,duration_code,title,description,reward_text,reward_id_list,cash_reward,exp_reward,reward_method,reward_points,reward_point_type,min_level,max_level,level_spread,min_players,max_players,repeatable,faction_reward,completion_emote,replay_timer_group,replay_timer_seconds,request_timer_group,request_timer_seconds,dz_template_id,lock_activity_id,faction_amount,enabled) VALUES
(302000,2,0,0,'Vrald\'s Lost Brother','Vrald\'s brother Wegar went to the Festival of Nightmares and never came back. Follow his trail from a corpse west of the Fangbreaker camp to the phantoms that hold him.','Experience','17215',0,500000,0,0,0,70,0,0,0,0,0,0,'',0,0,0,0,0,-1,0,1),
(302001,2,0,0,'What Are They?','Dwinn Axeheaver needs a Wereorc Arm and a Wereorc Leg -- rare spoils from the Bloodmoon packs of Loping Plains.','Experience','',0,250000,0,0,0,70,0,0,0,0,0,0,'',0,0,0,0,0,-1,0,1),
(302002,2,0,0,'An Interrogation','A rare Bloodmoon wolf named Fearfang carries a blood-smudged journal. Take it from him for Dwinn Axeheaver.','Experience','',0,250000,0,0,0,70,0,0,0,0,0,0,'',0,0,0,0,0,-1,0,1),
(302003,2,0,0,'The Investigation Continues','Apprentice Guggor keeps an illegible tome the Fangbreakers need. Relieve him of it.','Experience','',0,250000,0,0,0,70,0,0,0,0,0,0,'',0,0,0,0,0,-1,0,1),
(302004,2,0,0,'An Orcish Ritual','Kassailla Flameleaf can decode Dwinn\'s tome, but the Bloodmoon rites must be broken first: slay High Shaman Gangus, then bring Kassailla the tome and a Shadowmane Spellbook.','Experience','',0,250000,0,0,0,70,0,0,0,0,0,0,'',0,0,0,0,0,-1,0,1),
(302005,2,0,0,'Assessing the Danger','Scout the warg country by the Hills of Shade pass. If the Bloodmoon ambushers show themselves, break them -- and report to Dwinn.','Experience','',0,250000,0,0,0,70,0,0,0,0,0,0,'',0,0,0,0,0,-1,0,1),
(302006,2,0,0,'The Black Crystal','Dwinn needs a Black Crystal charged by the Bloodmoon ambushers. Bring him one, then break the four that guard it.','Experience','',0,250000,0,0,0,70,0,0,0,0,0,0,'',0,0,0,0,0,-1,0,1),
(302007,2,0,0,'The Proof is in the Bucket','Dwinn\'s bucket of blood will draw the Bloodmoon guard at their western camp. Spring the trap and clean up after it.','Experience','',0,250000,0,0,0,70,0,0,0,0,0,0,'',0,0,0,0,0,-1,0,1),
(302008,2,0,0,'A Working Crystal','Kassailla has found where the orcs charge their crystals. Watch the night ritual site, take High Shaman Nirvag\'s humming crystal, and bring it to Dwinn.','Experience','',0,250000,0,0,0,70,0,0,0,0,0,0,'',0,0,0,0,0,-1,0,1),
(302009,2,0,0,'It Ends Now','Take Dwinn\'s working crystal to the ruins, break Grand Shaman Talun\'s guard, and end the Bloodmoon pact forever.','Experience','100082',0,500000,0,0,0,70,0,0,0,0,0,0,'',0,0,0,0,0,-1,0,1);

INSERT INTO `task_activities` (taskid,activityid,req_activity_id,step,activitytype,target_name,goalmethod,goalcount,description_override,npc_match_list,item_id_list,item_list,dz_switch_id,min_x,min_y,min_z,max_x,max_y,max_z,skill_list,spell_list,zones,zone_version,optional,list_group) VALUES
(302000,0,-1,1,5,'Find Wegar\'s remains',1,1,'Find Wegar\'s remains under a bush west of the Fangbreaker camp','','','',0,-3440,-1390,663,-3360,-1310,743,'-1','0','443',-1,0,0),
(302000,1,-1,2,3,'',0,1,'Take Wegar\'s Journal from his remains','','36632','Wegar\'s Journal',0,0,0,0,0,0,0,'-1','0','443',-1,0,0),
(302000,2,-1,3,1,'Vrald',0,1,'Deliver 1 Wegar\'s Journal to Vrald','443155','36632','Wegar\'s Journal',0,0,0,0,0,0,0,'-1','0','443',-1,0,0),
(302000,3,-1,4,5,'Search the old festival road',1,1,'Follow the road north to where Wegar was waylaid','','','',0,360,-3270,-20,440,-3190,60,'-1','0','443',-1,0,0),
(302000,4,-1,5,2,'Shadowloper',0,1,'Destroy the Shadowloper that stalks the old road','443621','','',0,0,0,0,0,0,0,'-1','0','443',-1,0,0),
(302000,5,-1,6,3,'',0,1,'Loot 1 Garish Festival Charm','','36634','Garish Festival Charm',0,0,0,0,0,0,0,'-1','0','443',-1,0,0),
(302000,6,-1,7,1,'Vrald',0,1,'Deliver 1 Garish Festival Charm to Vrald','443155','36634','Garish Festival Charm',0,0,0,0,0,0,0,'-1','0','443',-1,0,0),
(302000,7,-1,8,2,'Nightwalker sentries',0,5,'Kill 5 Nightwalker sentries at their camp northeast of the festival','443029|443035','','',0,0,0,0,0,0,0,'-1','0','443',-1,0,0),
(302000,8,-1,9,2,'a plague-ridden Nightwalker',0,1,'Slay 1 a plague-ridden Nightwalker','443037','','',0,0,0,0,0,0,0,'-1','0','443',-1,0,0),
(302000,9,-1,10,4,'the Oracle of the Oak',0,1,'Speak with the Oracle of the Oak','443622','','',0,0,0,0,0,0,0,'-1','0','443',-1,0,0),
(302000,10,-1,11,2,'a blighted glog imp',0,1,'Root out the blighted glog imp beneath the oracle\'s oak','443623','','',0,0,0,0,0,0,0,'-1','0','443',-1,0,0),
(302000,11,-1,12,5,'Search the roots beneath the oak',1,1,'Reach the hollow beneath the oracle\'s oak','','','',0,2395,2025,272,2475,2105,352,'-1','0','443',-1,0,0),
(302000,12,-1,13,3,'',0,1,'Loot 1 Idlegrime Spore','','36633','Idlegrime Spore',0,0,0,0,0,0,0,'-1','0','443',-1,0,0),
(302000,13,-1,14,1,'the Oracle of the Oak',0,1,'Deliver 1 Idlegrime Spore to the Oracle of the Oak','443622','36633','Idlegrime Spore',0,0,0,0,0,0,0,'-1','0','443',-1,0,0),
(302000,14,-1,15,2,'Larwynn the Haunting',0,1,'Larwynn the Haunting prowls the festival grounds','443624','','',0,0,0,0,0,0,0,'-1','0','443',-1,0,0),
(302000,15,-1,16,3,'',0,1,'Loot 1 Wegar\'s Missing Pages','','36635','Wegar\'s Missing Pages',0,0,0,0,0,0,0,'-1','0','443',-1,0,0),
(302000,16,-1,17,1,'Vrald',0,1,'Deliver 1 Wegar\'s Missing Pages to Vrald','443155','36635','Wegar\'s Missing Pages',0,0,0,0,0,0,0,'-1','0','443',-1,0,0),
(302000,17,-1,18,2,'Wegar\'s Ghost',0,1,'Put Wegar\'s Ghost to rest on the festival grounds','443625','','',0,0,0,0,0,0,0,'-1','0','443',-1,0,0),
(302000,18,-1,19,2,'Elladrial',0,1,'Destroy the phantom Elladrial','443626','','',0,0,0,0,0,0,0,'-1','0','443',-1,0,0),
(302000,19,-1,20,3,'',0,1,'Loot 1 Wegar\'s Last Words','','36636','Wegar\'s Last Words',0,0,0,0,0,0,0,'-1','0','443',-1,0,0),
(302000,20,-1,21,1,'Vrald',0,1,'Deliver 1 Wegar\'s Last Words to Vrald','443155','36636','Wegar\'s Last Words',0,0,0,0,0,0,0,'-1','0','443',-1,0,0),
(302001,0,-1,1,3,'',0,1,'Loot 1 Wereorc Arm','','84288','Wereorc Arm',0,0,0,0,0,0,0,'-1','0','443',-1,0,0),
(302001,1,-1,2,3,'',0,1,'Loot 1 Wereorc Leg','','84287','Wereorc Leg',0,0,0,0,0,0,0,'-1','0','443',-1,0,0),
(302001,2,-1,3,1,'Dwinn Axeheaver',0,1,'Deliver 1 Wereorc Arm to Dwinn Axeheaver','443164','84288','Wereorc Arm',0,0,0,0,0,0,0,'-1','0','443',-1,0,0),
(302001,3,-1,4,1,'Dwinn Axeheaver',0,1,'Deliver 1 Wereorc Leg to Dwinn Axeheaver','443164','84287','Wereorc Leg',0,0,0,0,0,0,0,'-1','0','443',-1,0,0),
(302002,0,-1,1,2,'Fearfang',0,1,'Slay 1 Fearfang','443627','','',0,0,0,0,0,0,0,'-1','0','443',-1,0,0),
(302002,1,-1,2,3,'',0,1,'Loot 1 Blood-Smudged Journal','','84289','Blood-Smudged Journal',0,0,0,0,0,0,0,'-1','0','443',-1,0,0),
(302002,2,-1,3,1,'Dwinn Axeheaver',0,1,'Deliver 1 Blood-Smudged Journal to Dwinn Axeheaver','443164','84289','Blood-Smudged Journal',0,0,0,0,0,0,0,'-1','0','443',-1,0,0),
(302003,0,-1,1,2,'Apprentice Guggor',0,1,'Slay 1 Apprentice Guggor','443628','','',0,0,0,0,0,0,0,'-1','0','443',-1,0,0),
(302003,1,-1,2,3,'',0,1,'Loot 1 Illegible Tome','','84290','Illegible Tome',0,0,0,0,0,0,0,'-1','0','443',-1,0,0),
(302003,2,-1,3,1,'Dwinn Axeheaver',0,1,'Deliver 1 Illegible Tome to Dwinn Axeheaver','443164','84290','Illegible Tome',0,0,0,0,0,0,0,'-1','0','443',-1,0,0),
(302004,0,-1,1,4,'Kassailla Flameleaf',0,1,'Speak with Kassailla Flameleaf','443098','','',0,0,0,0,0,0,0,'-1','0','443',-1,0,0),
(302004,1,-1,2,2,'High Shaman Gangus',0,1,'Slay 1 High Shaman Gangus','443629','','',0,0,0,0,0,0,0,'-1','0','443',-1,0,0),
(302004,2,-1,3,1,'Kassailla Flameleaf',0,1,'Deliver 1 Illegible Tome to Kassailla Flameleaf','443098','84290','Illegible Tome',0,0,0,0,0,0,0,'-1','0','443',-1,0,0),
(302004,3,-1,4,3,'',0,1,'Loot 1 Shadowmane Spellbook','','84291','Shadowmane Spellbook',0,0,0,0,0,0,0,'-1','0','443',-1,0,0),
(302004,4,-1,5,1,'Kassailla Flameleaf',0,1,'Deliver 1 Shadowmane Spellbook to Kassailla Flameleaf','443098','84291','Shadowmane Spellbook',0,0,0,0,0,0,0,'-1','0','443',-1,0,0),
(302004,5,-1,6,4,'Dwinn Axeheaver',0,1,'Speak with Dwinn Axeheaver','443164','','',0,0,0,0,0,0,0,'-1','0','443',-1,0,0),
(302005,0,-1,1,5,'Scout the warg country by the pass',1,1,'Scout the warg country near the Hills of Shade pass (west)','','','',0,-3280,2540,286,-3200,2620,366,'-1','0','443',-1,0,0),
(302005,1,-1,2,2,'Bloodmoon ambushers',0,2,'Slay 2 Bloodmoon ambushers','443607','','',0,0,0,0,0,0,0,'-1','0','443',-1,0,0),
(302005,2,-1,3,4,'Dwinn Axeheaver',0,1,'Speak with Dwinn Axeheaver','443164','','',0,0,0,0,0,0,0,'-1','0','443',-1,0,0),
(302006,0,-1,1,3,'',0,1,'Recover a Black Crystal from the minotaurs of the plains','','84292','Black Crystal',0,0,0,0,0,0,0,'-1','0','443',-1,0,0),
(302006,1,-1,2,1,'Dwinn Axeheaver',0,1,'Deliver 1 Black Crystal to Dwinn Axeheaver','443164','84292','Black Crystal',0,0,0,0,0,0,0,'-1','0','443',-1,0,0),
(302006,2,-1,3,2,'Bloodmoon ambushers',0,4,'Slay 4 Bloodmoon ambushers','443607','','',0,0,0,0,0,0,0,'-1','0','443',-1,0,0),
(302006,3,-1,4,4,'Dwinn Axeheaver',0,1,'Speak with Dwinn Axeheaver','443164','','',0,0,0,0,0,0,0,'-1','0','443',-1,0,0),
(302007,0,-1,1,5,'Draw out the guard at the western camp',1,1,'Spring Dwinn\'s trap at the western camp','','','',0,-240,3360,363,-160,3440,443,'-1','0','443',-1,0,0),
(302007,1,-1,2,2,'Bloodmoon orcs',0,4,'Slay 4 Bloodmoon orcs','443022|443047|443048|443050|443055|443057|443062|443069|443070|443072|443075|443076|443077|443079|443080|443084|443090|443091|443094|443095|443096|443097|443100|443103|443106|443111|443117|443120|443121|443122|443123|443124|443125|443126|443132|443139|443181','','',0,0,0,0,0,0,0,'-1','0','443',-1,0,0),
(302007,2,-1,3,4,'Dwinn Axeheaver',0,1,'Speak with Dwinn Axeheaver','443164','','',0,0,0,0,0,0,0,'-1','0','443',-1,0,0),
(302008,0,-1,1,4,'Kassailla Flameleaf',0,1,'Speak with Kassailla Flameleaf','443098','','',0,0,0,0,0,0,0,'-1','0','443',-1,0,0),
(302008,1,-1,2,5,'Find the night ritual site',1,1,'Find the night ritual site on the northern rim','','','',0,820,3800,363,900,3880,443,'-1','0','443',-1,0,0),
(302008,2,-1,3,2,'High Shaman Nirvag',0,1,'Slay 1 High Shaman Nirvag','443630','','',0,0,0,0,0,0,0,'-1','0','443',-1,0,0),
(302008,3,-1,4,3,'',0,1,'Loot 1 Humming Black Crystal','','84293','Humming Black Crystal',0,0,0,0,0,0,0,'-1','0','443',-1,0,0),
(302008,4,-1,5,1,'Dwinn Axeheaver',0,1,'Deliver 1 Humming Black Crystal to Dwinn Axeheaver','443164','84293','Humming Black Crystal',0,0,0,0,0,0,0,'-1','0','443',-1,0,0),
(302009,0,-1,1,5,'Reach the Bloodmoon ruins',1,1,'Reach the ruins where the pact was sealed','','','',0,-1965,360,166,-1885,440,246,'-1','0','443',-1,0,0),
(302009,1,-1,2,2,'Bloodmoon orc guards',0,6,'Break the Bloodmoon guard at the ruins','443022|443047|443048|443050|443055|443057|443062|443069|443070|443072|443075|443076|443077|443079|443080|443084|443090|443091|443094|443095|443096|443097|443100|443103|443106|443111|443117|443120|443121|443122|443123|443124|443125|443126|443132|443139|443181','','',0,0,0,0,0,0,0,'-1','0','443',-1,0,0),
(302009,2,-1,3,2,'Grand Shaman Talun',0,1,'Slay 1 Grand Shaman Talun','443631','','',0,0,0,0,0,0,0,'-1','0','443',-1,0,0),
(302009,3,-1,4,4,'a freed spirit',0,1,'Speak with a freed spirit','443632','','',0,0,0,0,0,0,0,'-1','0','443',-1,0,0),
(302009,4,-1,5,4,'Dwinn Axeheaver',0,1,'Speak with Dwinn Axeheaver','443164','','',0,0,0,0,0,0,0,'-1','0','443',-1,0,0);

-- ============================================================
-- Support NPCs (443620+, clone templates + authored stat envelope).
-- Corpse/Oracle/freed spirit are inert dialog NPCs (faction 0).
-- ============================================================
DELETE FROM `npc_types` WHERE `id` IN (443620,443621,443622,443623,443624,443625,443626,443627,443628,443629,443630,443631,443632);
DROP TEMPORARY TABLE IF EXISTS sof_lpa_nt;
CREATE TEMPORARY TABLE sof_lpa_nt AS SELECT * FROM npc_types WHERE 0;
INSERT INTO sof_lpa_nt SELECT * FROM npc_types WHERE id = 443141;
UPDATE sof_lpa_nt SET id = 443620, name = '#Wegar`s_Corpse', level = 80, maxlevel = 80, hp = 2000, mindmg = 0, maxdmg = 10, AC = 100, ATK = 0, Accuracy = 0, loottable_id = 0, npc_faction_id = 0, aggroradius = 0 WHERE id = 443141;
INSERT INTO sof_lpa_nt SELECT * FROM npc_types WHERE id = 443029;
UPDATE sof_lpa_nt SET id = 443621, name = '#Shadowloper', level = 80, maxlevel = 80, hp = 110000, mindmg = 110, maxdmg = 2400, AC = 500, ATK = 250, Accuracy = 300, loottable_id = 1520001211 WHERE id = 443029;
INSERT INTO sof_lpa_nt SELECT * FROM npc_types WHERE id = 443012;
UPDATE sof_lpa_nt SET id = 443622, name = '#Oracle_of_the_Oak', level = 80, maxlevel = 80, hp = 5000, mindmg = 0, maxdmg = 10, AC = 100, ATK = 0, Accuracy = 0, loottable_id = 0, npc_faction_id = 0, aggroradius = 0 WHERE id = 443012;
INSERT INTO sof_lpa_nt SELECT * FROM npc_types WHERE id = 443023;
UPDATE sof_lpa_nt SET id = 443623, name = '#a_blighted_glog_imp', level = 78, maxlevel = 78, hp = 65000, mindmg = 90, maxdmg = 1900, AC = 460, ATK = 230, Accuracy = 290, loottable_id = 1520001212 WHERE id = 443023;
INSERT INTO sof_lpa_nt SELECT * FROM npc_types WHERE id = 445011;
UPDATE sof_lpa_nt SET id = 443624, name = '#Larwynn_the_Haunting', level = 80, maxlevel = 80, hp = 130000, mindmg = 120, maxdmg = 2600, AC = 520, ATK = 260, Accuracy = 320, loottable_id = 1520001213 WHERE id = 445011;
INSERT INTO sof_lpa_nt SELECT * FROM npc_types WHERE id = 445011;
UPDATE sof_lpa_nt SET id = 443625, name = '#Wegar`s_Ghost', level = 80, maxlevel = 80, hp = 110000, mindmg = 110, maxdmg = 2400, AC = 500, ATK = 250, Accuracy = 310, loottable_id = 1520001214 WHERE id = 445011;
INSERT INTO sof_lpa_nt SELECT * FROM npc_types WHERE id = 445011;
UPDATE sof_lpa_nt SET id = 443626, name = '#Elladrial', level = 82, maxlevel = 82, hp = 150000, mindmg = 130, maxdmg = 2800, AC = 540, ATK = 270, Accuracy = 330, loottable_id = 1520001215 WHERE id = 445011;
INSERT INTO sof_lpa_nt SELECT * FROM npc_types WHERE id = 443022;
UPDATE sof_lpa_nt SET id = 443627, name = '#Fearfang', level = 80, maxlevel = 80, hp = 100000, mindmg = 110, maxdmg = 2500, AC = 500, ATK = 250, Accuracy = 310, loottable_id = 1520001216 WHERE id = 443022;
INSERT INTO sof_lpa_nt SELECT * FROM npc_types WHERE id = 443022;
UPDATE sof_lpa_nt SET id = 443628, name = '#Apprentice_Guggor', level = 79, maxlevel = 79, hp = 95000, mindmg = 100, maxdmg = 2300, AC = 480, ATK = 240, Accuracy = 300, loottable_id = 1520001217 WHERE id = 443022;
INSERT INTO sof_lpa_nt SELECT * FROM npc_types WHERE id = 445002;
UPDATE sof_lpa_nt SET id = 443629, name = '#High_Shaman_Gangus', level = 82, maxlevel = 82, hp = 160000, mindmg = 140, maxdmg = 3200, AC = 560, ATK = 280, Accuracy = 340, loottable_id = 1520001218 WHERE id = 445002;
INSERT INTO sof_lpa_nt SELECT * FROM npc_types WHERE id = 445002;
UPDATE sof_lpa_nt SET id = 443630, name = '#High_Shaman_Nirvag', level = 81, maxlevel = 81, hp = 140000, mindmg = 130, maxdmg = 2800, AC = 540, ATK = 270, Accuracy = 330, loottable_id = 1520001219 WHERE id = 445002;
INSERT INTO sof_lpa_nt SELECT * FROM npc_types WHERE id = 445002;
UPDATE sof_lpa_nt SET id = 443631, name = '#Grand_Shaman_Talun', level = 83, maxlevel = 83, hp = 220000, mindmg = 150, maxdmg = 3400, AC = 580, ATK = 290, Accuracy = 350, loottable_id = 1520001220 WHERE id = 445002;
INSERT INTO sof_lpa_nt SELECT * FROM npc_types WHERE id = 445011;
UPDATE sof_lpa_nt SET id = 443632, name = '#a_freed_spirit', level = 80, maxlevel = 80, hp = 5000, mindmg = 0, maxdmg = 10, AC = 100, ATK = 0, Accuracy = 0, loottable_id = 0, npc_faction_id = 0, aggroradius = 0 WHERE id = 445011;
INSERT INTO `npc_types` SELECT * FROM sof_lpa_nt;
DROP TEMPORARY TABLE sof_lpa_nt;

-- ============================================================
-- Static spawns (spawngroups 1520001151+). TUNABLE coords: page
-- coords where documented, nearest-live-spawn anchors elsewhere.
-- ============================================================
DELETE FROM `spawnentry` WHERE `spawngroupID` BETWEEN 1520001151 AND 1520001170;
DELETE FROM `spawn2` WHERE `spawngroupID` BETWEEN 1520001151 AND 1520001170;
DELETE FROM `spawngroup` WHERE `id` BETWEEN 1520001151 AND 1520001170;
INSERT INTO `spawngroup` (`id`,`name`,`spawn_limit`,`dist`,`delay`,`mindelay`,`despawn`) VALUES
(1520001151,'sof_lpa_443620',1,0,300,150,0),
(1520001152,'sof_lpa_443621',1,0,600,300,0),
(1520001153,'sof_lpa_443622',1,0,300,150,0),
(1520001154,'sof_lpa_443623',1,0,450,225,0),
(1520001155,'sof_lpa_443624',1,0,600,300,0),
(1520001156,'sof_lpa_443625',1,0,600,300,0),
(1520001157,'sof_lpa_443626',1,0,600,300,0),
(1520001158,'sof_lpa_443627',1,0,1800,900,0),
(1520001159,'sof_lpa_443628',1,0,1800,900,0),
(1520001160,'sof_lpa_443629',1,0,900,450,0),
(1520001161,'sof_lpa_443630',1,0,900,450,0),
(1520001162,'sof_lpa_443631',1,0,900,450,0),
(1520001163,'sof_lpa_443632',1,0,450,225,0);
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES
(1520001151,443620,100),
(1520001152,443621,100),
(1520001153,443622,100),
(1520001154,443623,100),
(1520001155,443624,100),
(1520001156,443625,100),
(1520001157,443626,100),
(1520001158,443627,100),
(1520001159,443628,100),
(1520001160,443629,100),
(1520001161,443630,100),
(1520001162,443631,100),
(1520001163,443632,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) VALUES
(1520001151,'lopingplains',0,-3400,-1350,703,0,600),
(1520001152,'lopingplains',0,400,-3230,20,0,1200),
(1520001153,'lopingplains',0,2450,2050,312,0,600),
(1520001154,'lopingplains',0,2435,2065,312,0,900),
(1520001155,'lopingplains',0,3110,1400,401,0,1200),
(1520001156,'lopingplains',0,3300,1130,415,0,1200),
(1520001157,'lopingplains',0,3440,1360,401,0,1200),
(1520001158,'lopingplains',0,1500,-1750,98,0,3600),
(1520001159,'lopingplains',0,20,-1700,211,0,3600),
(1520001160,'lopingplains',0,2650,600,266,0,1800),
(1520001161,'lopingplains',0,860,3840,403,0,1800),
(1520001162,'lopingplains',0,-1930,400,206,0,1800),
(1520001163,'lopingplains',0,-1910,420,206,0,900);

-- ============================================================
-- Loot. Named tables 1520001211+; trash rare-drops 1520001201+
-- attached to the live wereorc/shadowmane/minotaur tables.
-- ============================================================
DELETE FROM `loottable_entries` WHERE `loottable_id` BETWEEN 1520001201 AND 1520001230;
DELETE FROM `loottable_entries` WHERE `lootdrop_id` BETWEEN 1520001201 AND 1520001230;
DELETE FROM `lootdrop_entries` WHERE `lootdrop_id` BETWEEN 1520001201 AND 1520001230;
DELETE FROM `lootdrop` WHERE `id` BETWEEN 1520001201 AND 1520001230;
DELETE FROM `loottable` WHERE `id` BETWEEN 1520001201 AND 1520001230;
INSERT INTO `loottable` (`id`,`name`,`mincash`,`maxcash`,`avgcoin`) VALUES
(1520001211,'SoF_LPA_1520001211',2000,6000,4000),
(1520001212,'SoF_LPA_1520001212',2000,6000,4000),
(1520001213,'SoF_LPA_1520001213',2000,6000,4000),
(1520001214,'SoF_LPA_1520001214',2000,6000,4000),
(1520001215,'SoF_LPA_1520001215',2000,6000,4000),
(1520001216,'SoF_LPA_1520001216',2000,6000,4000),
(1520001217,'SoF_LPA_1520001217',2000,6000,4000),
(1520001218,'SoF_LPA_1520001218',2000,6000,4000),
(1520001219,'SoF_LPA_1520001219',2000,6000,4000),
(1520001220,'SoF_LPA_1520001220',2000,6000,4000);
INSERT INTO `lootdrop` (`id`,`name`) VALUES
(1520001211,'SoF_LPA_1520001211_drop'),
(1520001212,'SoF_LPA_1520001212_drop'),
(1520001213,'SoF_LPA_1520001213_drop'),
(1520001214,'SoF_LPA_1520001214_drop'),
(1520001215,'SoF_LPA_1520001215_drop'),
(1520001216,'SoF_LPA_1520001216_drop'),
(1520001217,'SoF_LPA_1520001217_drop'),
(1520001218,'SoF_LPA_1520001218_drop'),
(1520001219,'SoF_LPA_1520001219_drop'),
(1520001220,'SoF_LPA_1520001220_drop'),
(1520001201,'SoF_LPA_trash_1520001201'),
(1520001202,'SoF_LPA_trash_1520001202'),
(1520001203,'SoF_LPA_trash_1520001203');
INSERT INTO `lootdrop_entries` (`lootdrop_id`,`item_id`,`item_charges`,`equip_item`,`chance`) VALUES
(1520001211,36634,1,0,100),
(1520001212,36633,1,0,100),
(1520001213,36635,1,0,100),
(1520001215,36636,1,0,100),
(1520001216,84289,1,0,100),
(1520001217,84290,1,0,100),
(1520001219,84293,1,0,100),
(1520001201,84288,1,0,25),
(1520001201,84287,1,0,25),
(1520001202,84291,1,0,50),
(1520001203,84292,1,0,50);
-- attach trash drops to live tables (idempotent: clean then insert)
INSERT INTO `loottable_entries` (`loottable_id`,`lootdrop_id`,`multiplier`,`droplimit`,`mindrop`,`probability`) VALUES
(1520001211,1520001211,6,0,0,100),
(1520001212,1520001212,6,0,0,100),
(1520001213,1520001213,6,0,0,100),
(1520001215,1520001215,6,0,0,100),
(1520001216,1520001216,1,0,0,100),
(1520001217,1520001217,1,0,0,100),
(1520001219,1520001219,1,0,0,100),
(94131,1520001201,1,0,0,100),
(94132,1520001201,1,0,0,100),
(94133,1520001201,1,0,0,100),
(94134,1520001201,1,0,0,100),
(94135,1520001201,1,0,0,100),
(94136,1520001201,1,0,0,100),
(94157,1520001202,1,0,0,100),
(94158,1520001202,1,0,0,100),
(94159,1520001202,1,0,0,100),
(94160,1520001202,1,0,0,100),
(94161,1520001202,1,0,0,100),
(94162,1520001202,1,0,0,100),
(94163,1520001202,1,0,0,100),
(94164,1520001202,1,0,0,100),
(94146,1520001203,1,0,0,100),
(94147,1520001203,1,0,0,100);

-- ============================================================
-- Ground spawn: Wegar's Journal beside his remains (the journal is
-- taken, not looted from a kill; fix_z snaps to terrain).
-- ============================================================
DELETE FROM `ground_spawns` WHERE `id` = 1520006411;
INSERT INTO `ground_spawns` (`id`,`zoneid`,`version`,`max_x`,`max_y`,`max_z`,`min_x`,`min_y`,`heading`,`name`,`item`,`max_allowed`,`comment`,`respawn_timer`,`fix_z`) VALUES
(1520006411,443,0,-3395,-1345,10000,-3405,-1355,0,'','36632',1,'SoF: Wegar s Journal at his remains',900,1);
