-- S.H.I.P. Workshop rares: five missing named Head Scientists.
DELETE FROM `npc_types` WHERE `id` IN (439710,439711,439712,439713,439714);
-- Generated by sof_content/gen_ship_rares.py -- do not hand-edit.

DROP TEMPORARY TABLE IF EXISTS `sof_ship_nt`;
CREATE TEMPORARY TABLE `sof_ship_nt` LIKE `npc_types`;
INSERT INTO `sof_ship_nt` SELECT * FROM `npc_types` WHERE `id` = 439108;
UPDATE `sof_ship_nt` SET `id` = 439710, `name` = '#Head_Scientist_Bozle', `level` = 85, `maxlevel` = 85, `hp` = 200000, `mindmg` = 120, `maxdmg` = 2500, `AC` = 500, `ATK` = 250, `Accuracy` = 300, `npc_faction_id` = 1520000069, `loottable_id` = 94020 WHERE `id` = 439108;
INSERT INTO `npc_types` SELECT * FROM `sof_ship_nt`;
UPDATE `sof_ship_nt` SET `id` = 439711, `name` = '#Head_Scientist_Belnot', `level` = 85, `maxlevel` = 85, `hp` = 200000, `mindmg` = 120, `maxdmg` = 2500, `AC` = 500, `ATK` = 250, `Accuracy` = 300, `npc_faction_id` = 1520000069, `loottable_id` = 94021 WHERE `id` = 439710;
INSERT INTO `npc_types` SELECT * FROM `sof_ship_nt`;
UPDATE `sof_ship_nt` SET `id` = 439712, `name` = '#Head_Scientist_Fizzil', `level` = 85, `maxlevel` = 85, `hp` = 200000, `mindmg` = 120, `maxdmg` = 2000, `AC` = 500, `ATK` = 250, `Accuracy` = 300, `npc_faction_id` = 1520000069, `loottable_id` = 94022 WHERE `id` = 439711;
INSERT INTO `npc_types` SELECT * FROM `sof_ship_nt`;
UPDATE `sof_ship_nt` SET `id` = 439713, `name` = '#Head_Scientist_Gripwir', `level` = 85, `maxlevel` = 85, `hp` = 200000, `mindmg` = 120, `maxdmg` = 2900, `AC` = 500, `ATK` = 250, `Accuracy` = 300, `npc_faction_id` = 1520000069, `loottable_id` = 94023 WHERE `id` = 439712;
INSERT INTO `npc_types` SELECT * FROM `sof_ship_nt`;
UPDATE `sof_ship_nt` SET `id` = 439714, `name` = '#Head_Scientist_Spodwork', `level` = 85, `maxlevel` = 85, `hp` = 200000, `mindmg` = 120, `maxdmg` = 2500, `AC` = 500, `ATK` = 250, `Accuracy` = 300, `npc_faction_id` = 1520000069, `loottable_id` = 94024 WHERE `id` = 439713;
INSERT INTO `npc_types` SELECT * FROM `sof_ship_nt`;
DROP TEMPORARY TABLE `sof_ship_nt`;

DELETE FROM `spawnentry` WHERE `spawngroupID` BETWEEN 1520001151 AND 1520001160;
DELETE FROM `spawn2` WHERE `spawngroupID` BETWEEN 1520001151 AND 1520001160;
DELETE FROM `spawngroup` WHERE `id` BETWEEN 1520001151 AND 1520001160;
INSERT INTO `spawngroup` (`id`,`name`,`spawn_limit`,`dist`,`delay`,`mindelay`,`despawn`) VALUES
(1520001151,'sof_ship_rare_bozle',1,0,640,300,0),
(1520001152,'sof_ship_rare_belnot',1,0,640,300,0),
(1520001153,'sof_ship_rare_fizzil',1,0,640,300,0),
(1520001154,'sof_ship_rare_gripwir',1,0,640,300,0),
(1520001155,'sof_ship_rare_spodwork',1,0,640,300,0);
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES
(1520001151,439710,100),
(1520001152,439711,100),
(1520001153,439712,100),
(1520001154,439713,100),
(1520001155,439714,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`) VALUES
(1520001151,'shipworkshop',0,350,450,157,0,640),
(1520001152,'shipworkshop',0,830,565,208,0,640),
(1520001153,'shipworkshop',0,264,532,232,0,640),
(1520001154,'shipworkshop',0,23,743,232,0,640),
(1520001155,'shipworkshop',0,830,350,208,0,640);

DELETE FROM `loottable_entries` WHERE `loottable_id` BETWEEN 94020 AND 94029;
DELETE FROM `lootdrop_entries` WHERE `lootdrop_id` BETWEEN 1520001120 AND 1520001129;
DELETE FROM `lootdrop` WHERE `id` BETWEEN 1520001120 AND 1520001129;
DELETE FROM `loottable` WHERE `id` BETWEEN 94020 AND 94029;
INSERT INTO `loottable` (`id`,`name`,`mincash`,`maxcash`,`avgcoin`) VALUES
(94020,'SoF_SHIP_Rare_Bozle',5000,12000,8000),
(94021,'SoF_SHIP_Rare_Belnot',5000,12000,8000),
(94022,'SoF_SHIP_Rare_Fizzil',5000,12000,8000),
(94023,'SoF_SHIP_Rare_Gripwir',5000,12000,8000),
(94024,'SoF_SHIP_Rare_Spodwork',5000,12000,8000);
INSERT INTO `lootdrop` (`id`,`name`) VALUES
(1520001120,'SoF_SHIP_Rare_Bozle_Drop'),
(1520001121,'SoF_SHIP_Rare_Belnot_Drop'),
(1520001122,'SoF_SHIP_Rare_Fizzil_Drop'),
(1520001123,'SoF_SHIP_Rare_Gripwir_Drop'),
(1520001124,'SoF_SHIP_Rare_Spodwork_Drop');
INSERT INTO `lootdrop_entries` (`lootdrop_id`,`item_id`,`item_charges`,`equip_item`,`chance`) VALUES
(1520001120,101243,1,1,100),
(1520001120,100002,1,0,55),
(1520001120,100006,1,0,45),
(1520001121,101232,1,1,100),
(1520001121,100001,1,0,55),
(1520001121,100005,1,0,45),
(1520001122,101239,1,1,100),
(1520001122,100002,1,0,55),
(1520001122,100006,1,0,45),
(1520001123,101240,1,1,100),
(1520001123,100003,1,0,55),
(1520001123,100007,1,0,45),
(1520001124,101231,1,1,100),
(1520001124,100000,1,0,55),
(1520001124,100004,1,0,45);
INSERT INTO `loottable_entries` (`loottable_id`,`lootdrop_id`,`multiplier`,`droplimit`,`mindrop`,`probability`) VALUES
(94020,1520001120,1,0,0,100),
(94021,1520001121,1,0,0,100),
(94022,1520001122,1,0,0,100),
(94023,1520001123,1,0,0,100),
(94024,1520001124,1,0,0,100);
