-- ============================================================================
-- TBS Solteris Access arc: instanced missions + blocker fixes
-- Generated by hand (2026-09-20).
--
-- Converts the eight group missions of the "A City in Peril" Solteris-access
-- arc to Shared tasks (tasks.type = 1) that create a DynamicZoneType::Mission
-- instance from a dynamic_zone_templates row. A single player can request
-- (min_players = 1); the whole group is auto-added to the shared task and the
-- instance. Enter with Elnot Waymun's [enter] prompt
-- (Client::MovePCDynamicZone(zone_id, 0)).
--
--   task   mission                       zone (id)          template
--   620051 Knowledge for Power           Jewel of Atiiki   6101
--   620053 Locating the Statue           Barren Coast      6102
--   620056 Snakes Hiding Something       Zhisza            6103
--   620057 Counter-Attack!               Zhisza            6104
--   620059 Confront Emperor Vaakiszh     Zhisza            6105
--   620061 Where There's a Will          (not instanced)   -
--   620062 Slay the Serpent              Silyssar          6107
--   620063 Stop the Ritual               Silyssar          6108
--
-- zone_version = 0 for every template: the instance is an isolated copy of the
-- static zone, so existing spawns (including the mission bosses already placed
-- by tbs_content/migrations/tbs_solteris_npcs.sql) are present per-instance
-- with no extra content.
--
-- Also fixes three defects found in the generated content:
--   * 620051 activity 2 spoke to Elnot (416006) while gated to Atiiki (418),
--     which is unreachable: retarget to Yinihortinkah (418110) in Atiiki.
--   * 620062 activity 8 spoke to Vizier Zio (416140) while gated to Silyssar
--     (420), but Zio only spawns in Katta Castrum: retarget zone to 416.
--   * all arc tasks paid faction 1095 (Crusade of the Scale); the Combine
--     vendors use 1170 (Combine Empire Merchants).
--   * Shissar Poison Sac (33895) and the Golem/Temple Schematics (9910000/
--     9910001) had no drop source, making 620056/620057 impossible. They are
--     added to the Zhisza Shissar loottables at 100% chance.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- 1. Player-facing faction fix
-- ---------------------------------------------------------------------------
UPDATE `tasks` SET `faction_reward` = 1170, `faction_amount` = 10
  WHERE `id` BETWEEN 620050 AND 620063;

-- ---------------------------------------------------------------------------
-- 2. Activity zone/target defects
-- ---------------------------------------------------------------------------
UPDATE `task_activities`
   SET `activitytype`        = 4,
       `target_name`         = 'Yinihortinkah',
       `npc_match_list`      = '418110',
       `zones`               = '418',
       `description_override`= 'Speak with Yinihortinkah'
 WHERE `taskid` = 620051 AND `activityid` = 2;

UPDATE `task_activities` SET `zones` = '416'
 WHERE `taskid` = 620062 AND `activityid` = 8;

-- 620053 "Locating the Statue" is played in Barren Coast (422), not Thalassius:
-- the generator emitted the explore step against Katta Castrum (416).
UPDATE `task_activities` SET `zones` = '422'
 WHERE `taskid` = 620053 AND `activityid` = 0;

-- ---------------------------------------------------------------------------
-- 3. Dynamic zone templates (one per mission; version 0 = full static copy)
-- ---------------------------------------------------------------------------
DELETE FROM `dynamic_zone_templates` WHERE `id` BETWEEN 6101 AND 6108;

INSERT INTO `dynamic_zone_templates`
  (`id`,`zone_id`,`zone_version`,`name`,`min_players`,`max_players`,
   `duration_seconds`,`dz_switch_id`,`compass_zone_id`,`compass_x`,`compass_y`,
   `compass_z`,`return_zone_id`,`return_x`,`return_y`,`return_z`,`return_h`,
   `override_zone_in`,`zone_in_x`,`zone_in_y`,`zone_in_z`,`zone_in_h`) VALUES
(6101,418,0,'Katta Castrum: Knowledge for Power',1,6,21600,0,0,0,0,0,416,-2,-425,-20,0,0,-916,-1089,-39,0),
(6102,422,0,'Katta Castrum: Locating the Statue',1,6,21600,0,0,0,0,0,416,-2,-425,-20,0,0,1203,698,54,0),
(6103,419,0,'Katta Castrum: Snakes Hiding Something',1,6,21600,0,0,0,0,0,416,-2,-425,-20,0,0,6,-856,5,0),
(6104,419,0,'Katta Castrum: Counter-Attack!',1,6,21600,0,0,0,0,0,416,-2,-425,-20,0,0,6,-856,5,0),
(6105,419,0,'Katta Castrum: Confront Emperor Vaakiszh',1,6,21600,0,0,0,0,0,416,-2,-425,-20,0,0,6,-856,5,0),
(6107,420,0,'Katta Castrum: Slay the Serpent',1,6,21600,0,0,0,0,0,416,-2,-425,-20,0,0,167,-50,-66,0),
(6108,420,0,'Katta Castrum: Stop the Ritual',1,6,21600,0,0,0,0,0,416,-2,-425,-20,0,0,167,-50,-66,0);

-- ---------------------------------------------------------------------------
-- 4. Convert the eight missions to Shared (instanced) tasks
-- ---------------------------------------------------------------------------
UPDATE `tasks` SET `type` = 1, `dz_template_id` = 6101, `min_players` = 1, `max_players` = 6 WHERE `id` = 620051;
UPDATE `tasks` SET `type` = 1, `dz_template_id` = 6102, `min_players` = 1, `max_players` = 6 WHERE `id` = 620053;
UPDATE `tasks` SET `type` = 1, `dz_template_id` = 6103, `min_players` = 1, `max_players` = 6 WHERE `id` = 620056;
UPDATE `tasks` SET `type` = 1, `dz_template_id` = 6104, `min_players` = 1, `max_players` = 6 WHERE `id` = 620057;
UPDATE `tasks` SET `type` = 1, `dz_template_id` = 6105, `min_players` = 1, `max_players` = 6 WHERE `id` = 620059;
-- 620061 "Where There's a Will" has no in-instance objective in the generated
-- data (only a Katta Castrum turn-in to Zio), so it stays a normal task.
UPDATE `tasks` SET `type` = 1, `dz_template_id` = 0, `min_players` = 1, `max_players` = 6 WHERE `id` = 620061;
UPDATE `tasks` SET `type` = 1, `dz_template_id` = 6107, `min_players` = 1, `max_players` = 6 WHERE `id` = 620062;
UPDATE `tasks` SET `type` = 1, `dz_template_id` = 6108, `min_players` = 1, `max_players` = 6 WHERE `id` = 620063;

-- ---------------------------------------------------------------------------
-- 5. Mission key drops (Shissar Poison Sac + Golem/Temple Schematics)
--    One lootdrop holding all three at 100%; attached to the Zhisza Shissar
--    trash table (93429) and the two named Shissar tables.
-- ---------------------------------------------------------------------------
DELETE FROM `loottable_entries` WHERE `lootdrop_id` = 6200001;
DELETE FROM `lootdrop_entries`  WHERE `lootdrop_id` = 6200001;
DELETE FROM `lootdrop`          WHERE `id` = 6200001;

INSERT INTO `lootdrop` (`id`,`name`) VALUES
  (6200001,'TBS Solteris arc mission keys');

INSERT INTO `lootdrop_entries` (`lootdrop_id`,`item_id`,`item_charges`,`chance`) VALUES
  (6200001,9910000,1,100),
  (6200001,9910001,1,100),
  (6200001,33895,1,100);

INSERT IGNORE INTO `loottable_entries`
  (`loottable_id`,`lootdrop_id`,`multiplier`,`droplimit`,`mindrop`,`probability`) VALUES
  (93429,6200001,1,0,0,100),
  (93422,6200001,1,0,0,100),
  (93423,6200001,1,0,0,100);
