-- ============================================================================
-- Secrets of Faydwer -- Bloodmoon Keep open-world named rares (10).
-- Rasper: raspersrealm.com/Everquest/SoF/openBloodmoon.html
-- Generated by sof_content/gen_bloodmoon_rares.py -- do not hand-edit.
-- Idempotent: DELETE+INSERT on explicit verified-free ids; stub rares
-- retuned in place. PH entries are data-driven SELECTs.
-- ============================================================================

-- -------------------------------------------------------------- loot
DELETE FROM `loottable_entries` WHERE `loottable_id` BETWEEN 1520008100 AND 1520008109;
DELETE FROM `lootdrop_entries` WHERE `lootdrop_id` BETWEEN 1520008150 AND 1520008159;
DELETE FROM `lootdrop` WHERE `id` BETWEEN 1520008150 AND 1520008159;
DELETE FROM `loottable` WHERE `id` BETWEEN 1520008100 AND 1520008109;
INSERT INTO `loottable` (`id`,`name`,`mincash`,`maxcash`,`avgcoin`) VALUES
(1520008100,'SoF_BM_warden_jaklor',15000,30000,20000),
(1520008101,'SoF_BM_grawlthin',15000,30000,20000),
(1520008102,'SoF_BM_crawtooth',15000,30000,20000),
(1520008103,'SoF_BM_raknos_the_fang',15000,30000,20000),
(1520008104,'SoF_BM_balkor_the_knife',15000,30000,20000),
(1520008105,'SoF_BM_hikor_the_pitmaster',15000,30000,20000),
(1520008106,'SoF_BM_horak',15000,30000,20000),
(1520008107,'SoF_BM_ralfin',15000,30000,20000),
(1520008108,'SoF_BM_vorash',15000,30000,20000),
(1520008109,'SoF_BM_wulren_venomdrinker',15000,30000,20000);
INSERT INTO `lootdrop` (`id`,`name`) VALUES
(1520008150,'SoF_BM_warden_jaklor_drop'),
(1520008151,'SoF_BM_grawlthin_drop'),
(1520008152,'SoF_BM_crawtooth_drop'),
(1520008153,'SoF_BM_raknos_the_fang_drop'),
(1520008154,'SoF_BM_balkor_the_knife_drop'),
(1520008155,'SoF_BM_hikor_the_pitmaster_drop'),
(1520008156,'SoF_BM_horak_drop'),
(1520008157,'SoF_BM_ralfin_drop'),
(1520008158,'SoF_BM_vorash_drop'),
(1520008159,'SoF_BM_wulren_venomdrinker_drop');
INSERT INTO `lootdrop_entries` (`lootdrop_id`,`item_id`,`item_charges`,`equip_item`,`chance`) VALUES
(1520008150,101148,1,0,40),
(1520008150,101648,1,0,15),
(1520008150,102752,1,0,5),
(1520008150,101350,1,0,3),
(1520008150,101351,1,0,3),
(1520008150,101360,1,0,3),
(1520008150,101361,1,0,3),
(1520008151,101120,1,0,40),
(1520008151,101167,1,0,15),
(1520008151,101620,1,0,10),
(1520008151,102752,1,0,5),
(1520008151,101350,1,0,3),
(1520008151,101351,1,0,3),
(1520008151,101360,1,0,3),
(1520008151,101361,1,0,3),
(1520008152,101113,1,0,40),
(1520008152,101613,1,0,15),
(1520008152,102752,1,0,5),
(1520008152,101350,1,0,3),
(1520008152,101351,1,0,3),
(1520008152,101360,1,0,3),
(1520008152,101361,1,0,3),
(1520008153,101151,1,0,40),
(1520008153,102752,1,0,5),
(1520008153,101350,1,0,3),
(1520008153,101351,1,0,3),
(1520008153,101360,1,0,3),
(1520008153,101361,1,0,3),
(1520008154,101102,1,0,40),
(1520008154,101115,1,0,30),
(1520008154,101602,1,0,15),
(1520008154,101615,1,0,10),
(1520008154,102752,1,0,5),
(1520008154,101350,1,0,3),
(1520008154,101351,1,0,3),
(1520008154,101360,1,0,3),
(1520008154,101361,1,0,3),
(1520008155,101152,1,0,40),
(1520008155,102752,1,0,5),
(1520008155,101350,1,0,3),
(1520008155,101351,1,0,3),
(1520008155,101360,1,0,3),
(1520008155,101361,1,0,3),
(1520008156,101145,1,0,40),
(1520008156,101645,1,0,15),
(1520008156,102752,1,0,5),
(1520008156,101350,1,0,3),
(1520008156,101351,1,0,3),
(1520008156,101360,1,0,3),
(1520008156,101361,1,0,3),
(1520008157,101130,1,0,40),
(1520008157,101180,1,0,15),
(1520008157,101630,1,0,10),
(1520008157,102752,1,0,5),
(1520008157,101350,1,0,3),
(1520008157,101351,1,0,3),
(1520008157,101360,1,0,3),
(1520008157,101361,1,0,3),
(1520008158,101137,1,0,40),
(1520008158,101637,1,0,15),
(1520008158,102752,1,0,5),
(1520008158,101350,1,0,3),
(1520008158,101351,1,0,3),
(1520008158,101360,1,0,3),
(1520008158,101361,1,0,3),
(1520008159,101144,1,0,40),
(1520008159,101644,1,0,15),
(1520008159,102752,1,0,5),
(1520008159,101350,1,0,3),
(1520008159,101351,1,0,3),
(1520008159,101360,1,0,3),
(1520008159,101361,1,0,3);
INSERT INTO `loottable_entries` (`loottable_id`,`lootdrop_id`,`multiplier`,`droplimit`,`mindrop`,`probability`) VALUES
(1520008100,1520008150,1,0,0,100),
(1520008101,1520008151,1,0,0,100),
(1520008102,1520008152,1,0,0,100),
(1520008103,1520008153,1,0,0,100),
(1520008104,1520008154,1,0,0,100),
(1520008105,1520008155,1,0,0,100),
(1520008106,1520008156,1,0,0,100),
(1520008107,1520008157,1,0,0,100),
(1520008108,1520008158,1,0,0,100),
(1520008109,1520008159,1,0,0,100);

-- -------------------------------------------------------------- existing stubs (retune)
UPDATE `npc_types` SET `level` = 82, `maxlevel` = 82, `hp` = 150000, `mindmg` = 120, `maxdmg` = 2400, `AC` = 500, `ATK` = 250, `Accuracy` = 300, `slow_mitigation` = 0, `loottable_id` = 1520008100, `npc_faction_id` = 1520000074, `npc_spells_id` = 0, `special_abilities` = '', `aggroradius` = 70, `raid_target` = 0 WHERE `id` = 445017;
UPDATE `npc_types` SET `level` = 82, `maxlevel` = 82, `hp` = 150000, `mindmg` = 120, `maxdmg` = 2200, `AC` = 500, `ATK` = 250, `Accuracy` = 300, `slow_mitigation` = 0, `loottable_id` = 1520008101, `npc_faction_id` = 1520000074, `npc_spells_id` = 0, `special_abilities` = '', `aggroradius` = 70, `raid_target` = 0 WHERE `id` = 445018;
UPDATE `npc_types` SET `level` = 82, `maxlevel` = 82, `hp` = 150000, `mindmg` = 120, `maxdmg` = 2200, `AC` = 500, `ATK` = 250, `Accuracy` = 300, `slow_mitigation` = 0, `loottable_id` = 1520008102, `npc_faction_id` = 1520000074, `npc_spells_id` = 0, `special_abilities` = '', `aggroradius` = 70, `raid_target` = 0 WHERE `id` = 445019;
UPDATE `npc_types` SET `level` = 82, `maxlevel` = 82, `hp` = 150000, `mindmg` = 120, `maxdmg` = 2200, `AC` = 500, `ATK` = 250, `Accuracy` = 300, `slow_mitigation` = 0, `loottable_id` = 1520008103, `npc_faction_id` = 1520000074, `npc_spells_id` = 0, `special_abilities` = '', `aggroradius` = 70, `raid_target` = 0 WHERE `id` = 445028;

-- -------------------------------------------------------------- new rares (clone family trash)
DELETE FROM `npc_types` WHERE `id` IN (445500,445501,445502,445503,445504,445505);
DROP TEMPORARY TABLE IF EXISTS sof_bmr_nt;
CREATE TEMPORARY TABLE sof_bmr_nt AS SELECT * FROM npc_types WHERE 0;
-- #Balkor_the_Knife (in place of any a_Bloodmoon_warrior)
INSERT INTO sof_bmr_nt SELECT * FROM npc_types WHERE id = 445001;
UPDATE sof_bmr_nt SET id = 445500, name = '#Balkor_the_Knife', level = 82, maxlevel = 82, hp = 150000, mindmg = 120, maxdmg = 2400, AC = 500, ATK = 250, Accuracy = 300, slow_mitigation = 0, loottable_id = 1520008104, npc_faction_id = 1520000074, npc_spells_id = 0, special_abilities = '', aggroradius = 70, see_invis = 0, raid_target = 0 WHERE id = 445001;
INSERT IGNORE INTO `npc_types` SELECT * FROM sof_bmr_nt;
DELETE FROM sof_bmr_nt;
-- #Hikor_the_Pitmaster (in place of any a_Bloodmoon_slaver)
INSERT INTO sof_bmr_nt SELECT * FROM npc_types WHERE id = 445022;
UPDATE sof_bmr_nt SET id = 445501, name = '#Hikor_the_Pitmaster', level = 82, maxlevel = 82, hp = 160000, mindmg = 120, maxdmg = 2200, AC = 500, ATK = 250, Accuracy = 300, slow_mitigation = 0, loottable_id = 1520008105, npc_faction_id = 1520000074, npc_spells_id = 0, special_abilities = '', aggroradius = 70, see_invis = 0, raid_target = 0 WHERE id = 445022;
INSERT IGNORE INTO `npc_types` SELECT * FROM sof_bmr_nt;
DELETE FROM sof_bmr_nt;
-- #Horak (in place of any a_Bloodmoon_wolfcaller)
INSERT INTO sof_bmr_nt SELECT * FROM npc_types WHERE id = 445005;
UPDATE sof_bmr_nt SET id = 445502, name = '#Horak', level = 82, maxlevel = 82, hp = 150000, mindmg = 120, maxdmg = 2500, AC = 500, ATK = 250, Accuracy = 300, slow_mitigation = 0, loottable_id = 1520008106, npc_faction_id = 1520000074, npc_spells_id = 0, special_abilities = '', aggroradius = 70, see_invis = 0, raid_target = 0 WHERE id = 445005;
INSERT IGNORE INTO `npc_types` SELECT * FROM sof_bmr_nt;
DELETE FROM sof_bmr_nt;
-- #Ralfin (in place of any a_Bloodmoon_cleric)
INSERT INTO sof_bmr_nt SELECT * FROM npc_types WHERE id = 445008;
UPDATE sof_bmr_nt SET id = 445503, name = '#Ralfin', level = 82, maxlevel = 82, hp = 150000, mindmg = 120, maxdmg = 2500, AC = 500, ATK = 250, Accuracy = 300, slow_mitigation = 0, loottable_id = 1520008107, npc_faction_id = 1520000074, npc_spells_id = 0, special_abilities = '', aggroradius = 70, see_invis = 0, raid_target = 0 WHERE id = 445008;
INSERT IGNORE INTO `npc_types` SELECT * FROM sof_bmr_nt;
DELETE FROM sof_bmr_nt;
-- #Vorash (in place of any a_Bloodmoon_shaman)
INSERT INTO sof_bmr_nt SELECT * FROM npc_types WHERE id = 445002;
UPDATE sof_bmr_nt SET id = 445504, name = '#Vorash', level = 82, maxlevel = 82, hp = 150000, mindmg = 120, maxdmg = 2200, AC = 500, ATK = 250, Accuracy = 300, slow_mitigation = 0, loottable_id = 1520008108, npc_faction_id = 1520000074, npc_spells_id = 0, special_abilities = '', aggroradius = 70, see_invis = 0, raid_target = 0 WHERE id = 445002;
INSERT IGNORE INTO `npc_types` SELECT * FROM sof_bmr_nt;
DELETE FROM sof_bmr_nt;
-- #Wulren_Venomdrinker (in place of any a_Bloodmoon_spiderfang)
INSERT INTO sof_bmr_nt SELECT * FROM npc_types WHERE id = 445024;
UPDATE sof_bmr_nt SET id = 445505, name = '#Wulren_Venomdrinker', level = 82, maxlevel = 82, hp = 150000, mindmg = 120, maxdmg = 2200, AC = 500, ATK = 250, Accuracy = 300, slow_mitigation = 0, loottable_id = 1520008109, npc_faction_id = 1520000074, npc_spells_id = 0, special_abilities = '', aggroradius = 70, see_invis = 0, raid_target = 0 WHERE id = 445024;
INSERT IGNORE INTO `npc_types` SELECT * FROM sof_bmr_nt;
DELETE FROM sof_bmr_nt;
DROP TEMPORARY TABLE IF EXISTS sof_bmr_nt;

-- -------------------------------------------------------------- rare PH entries (spawn in place of trash)
DELETE FROM `spawnentry` WHERE `npcID` IN (445017,445018,445019,445028,445500,445501,445502,445503,445504,445505);
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`)
SELECT DISTINCT se.spawngroupID, 445017, 2
FROM `spawnentry` se
JOIN `spawn2` s2 ON s2.spawngroupID = se.spawngroupID
WHERE s2.zone = 'bloodmoon' AND s2.version = 0 AND se.npcID = 445012;
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`)
SELECT DISTINCT se.spawngroupID, 445018, 2
FROM `spawnentry` se
JOIN `spawn2` s2 ON s2.spawngroupID = se.spawngroupID
WHERE s2.zone = 'bloodmoon' AND s2.version = 0 AND se.npcID = 445013;
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`)
SELECT DISTINCT se.spawngroupID, 445019, 2
FROM `spawnentry` se
JOIN `spawn2` s2 ON s2.spawngroupID = se.spawngroupID
WHERE s2.zone = 'bloodmoon' AND s2.version = 0 AND se.npcID = 445006;
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`)
SELECT DISTINCT se.spawngroupID, 445028, 2
FROM `spawnentry` se
JOIN `spawn2` s2 ON s2.spawngroupID = se.spawngroupID
WHERE s2.zone = 'bloodmoon' AND s2.version = 0 AND se.npcID = 445027;
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`)
SELECT DISTINCT se.spawngroupID, 445500, 2
FROM `spawnentry` se
JOIN `spawn2` s2 ON s2.spawngroupID = se.spawngroupID
WHERE s2.zone = 'bloodmoon' AND s2.version = 0 AND se.npcID = 445001;
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`)
SELECT DISTINCT se.spawngroupID, 445501, 2
FROM `spawnentry` se
JOIN `spawn2` s2 ON s2.spawngroupID = se.spawngroupID
WHERE s2.zone = 'bloodmoon' AND s2.version = 0 AND se.npcID = 445022;
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`)
SELECT DISTINCT se.spawngroupID, 445502, 2
FROM `spawnentry` se
JOIN `spawn2` s2 ON s2.spawngroupID = se.spawngroupID
WHERE s2.zone = 'bloodmoon' AND s2.version = 0 AND se.npcID = 445005;
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`)
SELECT DISTINCT se.spawngroupID, 445503, 2
FROM `spawnentry` se
JOIN `spawn2` s2 ON s2.spawngroupID = se.spawngroupID
WHERE s2.zone = 'bloodmoon' AND s2.version = 0 AND se.npcID = 445008;
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`)
SELECT DISTINCT se.spawngroupID, 445504, 2
FROM `spawnentry` se
JOIN `spawn2` s2 ON s2.spawngroupID = se.spawngroupID
WHERE s2.zone = 'bloodmoon' AND s2.version = 0 AND se.npcID = 445002;
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`)
SELECT DISTINCT se.spawngroupID, 445505, 2
FROM `spawnentry` se
JOIN `spawn2` s2 ON s2.spawngroupID = se.spawngroupID
WHERE s2.zone = 'bloodmoon' AND s2.version = 0 AND se.npcID = 445024;

-- -------------------------------------------------------------- drop the four fixed rare stub spawns
DELETE FROM `spawnentry` WHERE `spawngroupID` IN (80774,80817,80853,80984);
DELETE FROM `spawn2` WHERE `spawngroupID` IN (80774,80817,80853,80984) AND `zone` = 'bloodmoon';
DELETE FROM `spawngroup` WHERE `id` IN (80774,80817,80853,80984);
