-- ============================================================================
-- Underfoot -- T7 raids (A Cunning Plan / The Fungal Corruption /
-- Trial of Deconstruction / Trial of Creation / An Audience with
-- Brell Serilis). Amulet of Brell: 6/6/9/9/9 + 2-of-5 named pool.
-- Rasper: raspersrealm.com/Everquest/Underfoot/miscRaidProg.html
-- Generated by uf_content/gen_uf_temple.py -- do not hand-edit.
-- ============================================================================

-- ------------------------------------------------ instance zone versions (full zone copies)
-- idempotent: existing version rows + their spawn clones are cleared first
DELETE FROM `spawn2` WHERE `zone` = 'lichencreep' AND `version` IN (1);
DELETE FROM `zone` WHERE `zoneidnumber` = 487 AND `version` IN (1);
DROP TEMPORARY TABLE IF EXISTS uf_zv;
CREATE TEMPORARY TABLE uf_zv AS SELECT * FROM `zone` WHERE `zoneidnumber` = 487 AND `version` = 0;
ALTER TABLE uf_zv MODIFY `id` INT NULL;
UPDATE uf_zv SET `version` = 1, `id` = NULL;
INSERT INTO `zone` SELECT * FROM uf_zv;
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`,`variance`,`pathgrid`,`path_when_zone_idle`,`_condition`,`cond_value`,`animation`,`min_expansion`,`max_expansion`,`content_flags`,`content_flags_disabled`)
SELECT `spawngroupID`,'lichencreep',1,`x`,`y`,`z`,`heading`,86400,`variance`,`pathgrid`,`path_when_zone_idle`,`_condition`,`cond_value`,`animation`,`min_expansion`,`max_expansion`,`content_flags`,`content_flags_disabled` FROM `spawn2` WHERE `zone` = 'lichencreep' AND `version` = 0;

DROP TEMPORARY TABLE uf_zv;
DELETE FROM `spawn2` WHERE `zone` = 'fungalforest' AND `version` IN (1);
DELETE FROM `zone` WHERE `zoneidnumber` = 481 AND `version` IN (1);
DROP TEMPORARY TABLE IF EXISTS uf_zv;
CREATE TEMPORARY TABLE uf_zv AS SELECT * FROM `zone` WHERE `zoneidnumber` = 481 AND `version` = 0;
ALTER TABLE uf_zv MODIFY `id` INT NULL;
UPDATE uf_zv SET `version` = 1, `id` = NULL;
INSERT INTO `zone` SELECT * FROM uf_zv;
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`,`variance`,`pathgrid`,`path_when_zone_idle`,`_condition`,`cond_value`,`animation`,`min_expansion`,`max_expansion`,`content_flags`,`content_flags_disabled`)
SELECT `spawngroupID`,'fungalforest',1,`x`,`y`,`z`,`heading`,86400,`variance`,`pathgrid`,`path_when_zone_idle`,`_condition`,`cond_value`,`animation`,`min_expansion`,`max_expansion`,`content_flags`,`content_flags_disabled` FROM `spawn2` WHERE `zone` = 'fungalforest' AND `version` = 0;

DROP TEMPORARY TABLE uf_zv;
DELETE FROM `spawn2` WHERE `zone` = 'brellstemple' AND `version` IN (1,2,3);
DELETE FROM `zone` WHERE `zoneidnumber` = 490 AND `version` IN (1,2,3);
DROP TEMPORARY TABLE IF EXISTS uf_zv;
CREATE TEMPORARY TABLE uf_zv AS SELECT * FROM `zone` WHERE `zoneidnumber` = 490 AND `version` = 0;
ALTER TABLE uf_zv MODIFY `id` INT NULL;
UPDATE uf_zv SET `version` = 1, `id` = NULL;
INSERT INTO `zone` SELECT * FROM uf_zv;
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`,`variance`,`pathgrid`,`path_when_zone_idle`,`_condition`,`cond_value`,`animation`,`min_expansion`,`max_expansion`,`content_flags`,`content_flags_disabled`)
SELECT `spawngroupID`,'brellstemple',1,`x`,`y`,`z`,`heading`,86400,`variance`,`pathgrid`,`path_when_zone_idle`,`_condition`,`cond_value`,`animation`,`min_expansion`,`max_expansion`,`content_flags`,`content_flags_disabled` FROM `spawn2` WHERE `zone` = 'brellstemple' AND `version` = 0;

UPDATE uf_zv SET `version` = 2, `id` = NULL;
INSERT INTO `zone` SELECT * FROM uf_zv;
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`,`variance`,`pathgrid`,`path_when_zone_idle`,`_condition`,`cond_value`,`animation`,`min_expansion`,`max_expansion`,`content_flags`,`content_flags_disabled`)
SELECT `spawngroupID`,'brellstemple',2,`x`,`y`,`z`,`heading`,86400,`variance`,`pathgrid`,`path_when_zone_idle`,`_condition`,`cond_value`,`animation`,`min_expansion`,`max_expansion`,`content_flags`,`content_flags_disabled` FROM `spawn2` WHERE `zone` = 'brellstemple' AND `version` = 0;

UPDATE uf_zv SET `version` = 3, `id` = NULL;
INSERT INTO `zone` SELECT * FROM uf_zv;
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`,`variance`,`pathgrid`,`path_when_zone_idle`,`_condition`,`cond_value`,`animation`,`min_expansion`,`max_expansion`,`content_flags`,`content_flags_disabled`)
SELECT `spawngroupID`,'brellstemple',3,`x`,`y`,`z`,`heading`,86400,`variance`,`pathgrid`,`path_when_zone_idle`,`_condition`,`cond_value`,`animation`,`min_expansion`,`max_expansion`,`content_flags`,`content_flags_disabled` FROM `spawn2` WHERE `zone` = 'brellstemple' AND `version` = 0;

DROP TEMPORARY TABLE uf_zv;
-- keep #Brell_Serilis out of the trial instances (he stands in v3 only)
DELETE FROM `spawn2` WHERE `zone` = 'brellstemple' AND `version` IN (1,2,3)
  AND `spawngroupID` <> 1520008537
  AND `spawngroupID` IN (SELECT `spawngroupID` FROM `spawnentry` WHERE `npcID` = 490041);

-- ------------------------------------------------ encounter NPCs (script-spawned)
DROP TEMPORARY TABLE IF EXISTS uf_tpl_add;
CREATE TEMPORARY TABLE uf_tpl_add AS SELECT * FROM npc_types WHERE 0;

-- Vzarn_the_Cunning: the mind behind the creep's cunning plan
INSERT INTO uf_tpl_add SELECT * FROM npc_types WHERE id = 487012;
UPDATE uf_tpl_add SET id = 487120, name = 'Vzarn_the_Cunning', level = 85, hp = 3200000, mindmg = 0, maxdmg = 6800, AC = 580, ATK = 260, Accuracy = 260, slow_mitigation = 0, loottable_id = 0, npc_faction_id = 1520000073, npc_spells_id = 0, special_abilities = '', aggroradius = 0, see_invis = 0, raid_target = 0 WHERE id = 487012;
INSERT IGNORE INTO npc_types SELECT * FROM uf_tpl_add;
DELETE FROM uf_tpl_add;

-- a_decoy_of_vzarn: Vzarn add: bursts if not killed in time
INSERT INTO uf_tpl_add SELECT * FROM npc_types WHERE id = 487012;
UPDATE uf_tpl_add SET id = 487121, name = 'a_decoy_of_vzarn', level = 83, hp = 40000, mindmg = 0, maxdmg = 1200, AC = 460, ATK = 200, Accuracy = 200, slow_mitigation = 0, loottable_id = 0, npc_faction_id = 1520000073, npc_spells_id = 0, special_abilities = '', aggroradius = 0, see_invis = 0, raid_target = 0 WHERE id = 487012;
INSERT IGNORE INTO npc_types SELECT * FROM uf_tpl_add;
DELETE FROM uf_tpl_add;

-- the_Fungal_Corruption: the bloom's rot given purpose
INSERT INTO uf_tpl_add SELECT * FROM npc_types WHERE id = 481000;
UPDATE uf_tpl_add SET id = 481220, name = 'the_Fungal_Corruption', level = 85, hp = 3400000, mindmg = 0, maxdmg = 7000, AC = 590, ATK = 265, Accuracy = 265, slow_mitigation = 0, loottable_id = 0, npc_faction_id = 1520000073, npc_spells_id = 0, special_abilities = '', aggroradius = 0, see_invis = 0, raid_target = 0 WHERE id = 481000;
INSERT IGNORE INTO npc_types SELECT * FROM uf_tpl_add;
DELETE FROM uf_tpl_add;

-- a_bursting_spore_pod: Fungal add: 5k poison burst if left alive
INSERT INTO uf_tpl_add SELECT * FROM npc_types WHERE id = 488039;
UPDATE uf_tpl_add SET id = 481221, name = 'a_bursting_spore_pod', level = 84, hp = 60000, mindmg = 0, maxdmg = 1000, AC = 450, ATK = 100, Accuracy = 100, slow_mitigation = 0, loottable_id = 0, npc_faction_id = 1520000073, npc_spells_id = 0, special_abilities = '', aggroradius = 0, see_invis = 0, raid_target = 0 WHERE id = 488039;
INSERT IGNORE INTO npc_types SELECT * FROM uf_tpl_add;
DELETE FROM uf_tpl_add;

-- a_fungal_creeper: Fungal add
INSERT INTO uf_tpl_add SELECT * FROM npc_types WHERE id = 481002;
UPDATE uf_tpl_add SET id = 481222, name = 'a_fungal_creeper', level = 84, hp = 130000, mindmg = 0, maxdmg = 2200, AC = 490, ATK = 220, Accuracy = 220, slow_mitigation = 0, loottable_id = 0, npc_faction_id = 1520000073, npc_spells_id = 0, special_abilities = '', aggroradius = 0, see_invis = 0, raid_target = 0 WHERE id = 481002;
INSERT IGNORE INTO npc_types SELECT * FROM uf_tpl_add;
DELETE FROM uf_tpl_add;

-- the_Deconstructor: temple trial: unmake the constructs
INSERT INTO uf_tpl_add SELECT * FROM npc_types WHERE id = 490008;
UPDATE uf_tpl_add SET id = 490120, name = 'the_Deconstructor', level = 85, hp = 3300000, mindmg = 0, maxdmg = 7000, AC = 590, ATK = 265, Accuracy = 265, slow_mitigation = 0, loottable_id = 0, npc_faction_id = 1520000073, npc_spells_id = 0, special_abilities = '', aggroradius = 0, see_invis = 0, raid_target = 0 WHERE id = 490008;
INSERT IGNORE INTO npc_types SELECT * FROM uf_tpl_add;
DELETE FROM uf_tpl_add;

-- a_waking_construct: Deconstructor trial wave add
INSERT INTO uf_tpl_add SELECT * FROM npc_types WHERE id = 490007;
UPDATE uf_tpl_add SET id = 490121, name = 'a_waking_construct', level = 84, hp = 150000, mindmg = 0, maxdmg = 2400, AC = 500, ATK = 220, Accuracy = 220, slow_mitigation = 0, loottable_id = 0, npc_faction_id = 1520000073, npc_spells_id = 0, special_abilities = '', aggroradius = 0, see_invis = 0, raid_target = 0 WHERE id = 490007;
INSERT IGNORE INTO npc_types SELECT * FROM uf_tpl_add;
DELETE FROM uf_tpl_add;

-- a_waking_construct: Deconstructor trial wave add
INSERT INTO uf_tpl_add SELECT * FROM npc_types WHERE id = 490008;
UPDATE uf_tpl_add SET id = 490122, name = 'a_waking_construct', level = 84, hp = 150000, mindmg = 0, maxdmg = 2400, AC = 500, ATK = 220, Accuracy = 220, slow_mitigation = 0, loottable_id = 0, npc_faction_id = 1520000073, npc_spells_id = 0, special_abilities = '', aggroradius = 0, see_invis = 0, raid_target = 0 WHERE id = 490008;
INSERT IGNORE INTO npc_types SELECT * FROM uf_tpl_add;
DELETE FROM uf_tpl_add;

-- the_Unfinished_Creation: temple trial: finish what Brell left broken
INSERT INTO uf_tpl_add SELECT * FROM npc_types WHERE id = 490030;
UPDATE uf_tpl_add SET id = 490130, name = 'the_Unfinished_Creation', level = 85, hp = 3400000, mindmg = 0, maxdmg = 7000, AC = 590, ATK = 265, Accuracy = 265, slow_mitigation = 0, loottable_id = 0, npc_faction_id = 1520000073, npc_spells_id = 0, special_abilities = '', aggroradius = 0, see_invis = 0, raid_target = 0 WHERE id = 490030;
INSERT IGNORE INTO npc_types SELECT * FROM uf_tpl_add;
DELETE FROM uf_tpl_add;

-- a_creation_mote: Creation trial: heals the boss if left alive
INSERT INTO uf_tpl_add SELECT * FROM npc_types WHERE id = 490030;
UPDATE uf_tpl_add SET id = 490131, name = 'a_creation_mote', level = 84, hp = 70000, mindmg = 0, maxdmg = 1200, AC = 460, ATK = 180, Accuracy = 180, slow_mitigation = 0, loottable_id = 0, npc_faction_id = 1520000073, npc_spells_id = 0, special_abilities = '', aggroradius = 0, see_invis = 0, raid_target = 0 WHERE id = 490030;
INSERT IGNORE INTO npc_types SELECT * FROM uf_tpl_add;
DELETE FROM uf_tpl_add;

-- a_serilian_attendant: Brell attendant
INSERT INTO uf_tpl_add SELECT * FROM npc_types WHERE id = 490032;
UPDATE uf_tpl_add SET id = 490141, name = 'a_serilian_attendant', level = 84, hp = 220000, mindmg = 0, maxdmg = 2800, AC = 520, ATK = 240, Accuracy = 240, slow_mitigation = 0, loottable_id = 0, npc_faction_id = 1520000073, npc_spells_id = 0, special_abilities = '', aggroradius = 0, see_invis = 0, raid_target = 0 WHERE id = 490032;
INSERT IGNORE INTO npc_types SELECT * FROM uf_tpl_add;
DELETE FROM uf_tpl_add;

-- a_serilian_attendant: Brell attendant
INSERT INTO uf_tpl_add SELECT * FROM npc_types WHERE id = 490032;
UPDATE uf_tpl_add SET id = 490142, name = 'a_serilian_attendant', level = 84, hp = 220000, mindmg = 0, maxdmg = 2800, AC = 520, ATK = 240, Accuracy = 240, slow_mitigation = 0, loottable_id = 0, npc_faction_id = 1520000073, npc_spells_id = 0, special_abilities = '', aggroradius = 0, see_invis = 0, raid_target = 0 WHERE id = 490032;
INSERT IGNORE INTO npc_types SELECT * FROM uf_tpl_add;
DELETE FROM uf_tpl_add;

-- a_serilian_attendant: Brell attendant
INSERT INTO uf_tpl_add SELECT * FROM npc_types WHERE id = 490032;
UPDATE uf_tpl_add SET id = 490143, name = 'a_serilian_attendant', level = 84, hp = 220000, mindmg = 0, maxdmg = 2800, AC = 520, ATK = 240, Accuracy = 240, slow_mitigation = 0, loottable_id = 0, npc_faction_id = 1520000073, npc_spells_id = 0, special_abilities = '', aggroradius = 0, see_invis = 0, raid_target = 0 WHERE id = 490032;
INSERT IGNORE INTO npc_types SELECT * FROM uf_tpl_add;
DELETE FROM uf_tpl_add;

-- a_gem_golem: Brell add: the mountain answers
INSERT INTO uf_tpl_add SELECT * FROM npc_types WHERE id = 490013;
UPDATE uf_tpl_add SET id = 490144, name = 'a_gem_golem', level = 84, hp = 200000, mindmg = 0, maxdmg = 2600, AC = 520, ATK = 240, Accuracy = 240, slow_mitigation = 0, loottable_id = 0, npc_faction_id = 1520000073, npc_spells_id = 0, special_abilities = '', aggroradius = 0, see_invis = 0, raid_target = 0 WHERE id = 490013;
INSERT IGNORE INTO npc_types SELECT * FROM uf_tpl_add;
DELETE FROM uf_tpl_add;

-- Temple_Warden_Halgrim (war camp giver)
INSERT INTO uf_tpl_add SELECT * FROM npc_types WHERE id = 480060;
UPDATE uf_tpl_add SET id = 490100, name = 'Temple_Warden_Halgrim', level = 85, hp = 40000, mindmg = 0, maxdmg = 100, AC = 500, loottable_id = 0, npc_faction_id = 0, npc_spells_id = 0, aggroradius = 0, see_invis = 1, special_abilities = '', raid_target = 0 WHERE id = 480060;
INSERT IGNORE INTO npc_types SELECT * FROM uf_tpl_add;
DELETE FROM uf_tpl_add;

DROP TEMPORARY TABLE IF EXISTS uf_tpl_add;

UPDATE `npc_types` SET `class` = 1, `special_abilities` = '1,1^4,1^8,1^13,1^14,1^15,1^16,1^17,1^21,1^24,1^31,1', `see_invis` = 1, `MR` = 175, `CR` = 150, `DR` = 150, `FR` = 150, `PR` = 150, `npc_spells_id` = 0, `raid_target` = 1, `attack_speed` = 0, `slow_mitigation` = 80 WHERE `id` = 487120;
UPDATE `npc_types` SET `class` = 1, `special_abilities` = '1,1^4,1^8,1^13,1^14,1^15,1^16,1^17,1^21,1^24,1^31,1', `see_invis` = 1, `MR` = 175, `CR` = 150, `DR` = 150, `FR` = 150, `PR` = 150, `npc_spells_id` = 0, `raid_target` = 1, `attack_speed` = 0, `slow_mitigation` = 80 WHERE `id` = 481220;
UPDATE `npc_types` SET `class` = 1, `special_abilities` = '1,1^4,1^8,1^13,1^14,1^15,1^16,1^17,1^21,1^24,1^31,1', `see_invis` = 1, `MR` = 175, `CR` = 150, `DR` = 150, `FR` = 150, `PR` = 150, `npc_spells_id` = 0, `raid_target` = 1, `attack_speed` = 0, `slow_mitigation` = 80 WHERE `id` = 490120;
UPDATE `npc_types` SET `class` = 1, `special_abilities` = '1,1^4,1^8,1^13,1^14,1^15,1^16,1^17,1^21,1^24,1^31,1', `see_invis` = 1, `MR` = 175, `CR` = 150, `DR` = 150, `FR` = 150, `PR` = 150, `npc_spells_id` = 0, `raid_target` = 1, `attack_speed` = 0, `slow_mitigation` = 80 WHERE `id` = 490130;
UPDATE `npc_types` SET `class` = 1, `special_abilities` = '1,1^4,1^8,1^13,1^14,1^15,1^16,1^17,1^21,1^24,1^31,1', `see_invis` = 1, `MR` = 175, `CR` = 150, `DR` = 150, `FR` = 150, `PR` = 150, `npc_spells_id` = 0, `raid_target` = 1, `attack_speed` = 0, `slow_mitigation` = 80 WHERE `id` = 490041;
UPDATE `npc_types` SET `level` = 87, `hp` = 4200000, `mindmg` = 0, `maxdmg` = 7600, `AC` = 620, `ATK` = 280, `Accuracy` = 280 WHERE `id` = 490041;

DELETE FROM `spawn2` WHERE `spawngroupID` = 1520008519;
DELETE FROM `spawnentry` WHERE `spawngroupID` = 1520008519;
DELETE FROM `spawngroup` WHERE `id` = 1520008519;
INSERT INTO `spawngroup` (`id`,`name`,`spawn_limit`,`dist`,`delay`,`mindelay`,`despawn`) VALUES
(1520008519,'uf_war_camp_halgrim',1,0,640,320,0);
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (1520008519,490100,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`)
VALUES (1520008519,'brellsrest',0,8.0,440.0,152.6,0,640);

-- ------------------------------------------------ static boss spawns (instance versions)
DELETE FROM `spawn2` WHERE `spawngroupID` BETWEEN 1520008533 AND 1520008537;
DELETE FROM `spawnentry` WHERE `spawngroupID` BETWEEN 1520008533 AND 1520008537;
DELETE FROM `spawngroup` WHERE `id` BETWEEN 1520008533 AND 1520008537;

INSERT INTO `spawngroup` (`id`,`name`,`spawn_limit`,`dist`,`delay`,`mindelay`,`despawn`) VALUES
(1520008533,'uf_boss_487120',1,0,86400,86400,0);
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (1520008533,487120,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`)
VALUES (1520008533,'lichencreep',1,557.0,-1444.0,22.0,0,86400);

INSERT INTO `spawngroup` (`id`,`name`,`spawn_limit`,`dist`,`delay`,`mindelay`,`despawn`) VALUES
(1520008534,'uf_boss_481220',1,0,86400,86400,0);
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (1520008534,481220,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`)
VALUES (1520008534,'fungalforest',1,-2111.0,602.0,223.75,0,86400);

INSERT INTO `spawngroup` (`id`,`name`,`spawn_limit`,`dist`,`delay`,`mindelay`,`despawn`) VALUES
(1520008535,'uf_boss_490120',1,0,86400,86400,0);
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (1520008535,490120,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`)
VALUES (1520008535,'brellstemple',1,156.0,559.0,20.0,250,86400);

INSERT INTO `spawngroup` (`id`,`name`,`spawn_limit`,`dist`,`delay`,`mindelay`,`despawn`) VALUES
(1520008536,'uf_boss_490130',1,0,86400,86400,0);
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (1520008536,490130,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`)
VALUES (1520008536,'brellstemple',2,156.0,559.0,20.0,250,86400);

INSERT INTO `spawngroup` (`id`,`name`,`spawn_limit`,`dist`,`delay`,`mindelay`,`despawn`) VALUES
(1520008537,'uf_boss_490041',1,0,86400,86400,0);
INSERT INTO `spawnentry` (`spawngroupID`,`npcID`,`chance`) VALUES (1520008537,490041,100);
INSERT INTO `spawn2` (`spawngroupID`,`zone`,`version`,`x`,`y`,`z`,`heading`,`respawntime`)
VALUES (1520008537,'brellstemple',3,156.0,559.0,20.0,250,86400);

-- ------------------------------------------------ punchable "Treasure of" chests
DROP TEMPORARY TABLE IF EXISTS uf_tpl_chest;
CREATE TEMPORARY TABLE uf_tpl_chest AS SELECT * FROM npc_types WHERE 0;
INSERT INTO uf_tpl_chest SELECT * FROM npc_types WHERE id = 317112;
UPDATE uf_tpl_chest SET id = 487160, name = 'Treasure_of_a_Cunning_Plan', loottable_id = 1520008317, npc_faction_id = 0 WHERE id = 317112;
INSERT IGNORE INTO npc_types SELECT * FROM uf_tpl_chest;
DELETE FROM uf_tpl_chest;
INSERT INTO uf_tpl_chest SELECT * FROM npc_types WHERE id = 317112;
UPDATE uf_tpl_chest SET id = 481260, name = 'Treasure_of_the_Fungal_Corruption', loottable_id = 1520008318, npc_faction_id = 0 WHERE id = 317112;
INSERT IGNORE INTO npc_types SELECT * FROM uf_tpl_chest;
DELETE FROM uf_tpl_chest;
INSERT INTO uf_tpl_chest SELECT * FROM npc_types WHERE id = 317112;
UPDATE uf_tpl_chest SET id = 490160, name = 'Treasure_of_Deconstruction', loottable_id = 1520008319, npc_faction_id = 0 WHERE id = 317112;
INSERT IGNORE INTO npc_types SELECT * FROM uf_tpl_chest;
DELETE FROM uf_tpl_chest;
INSERT INTO uf_tpl_chest SELECT * FROM npc_types WHERE id = 317112;
UPDATE uf_tpl_chest SET id = 490161, name = 'Treasure_of_Creation', loottable_id = 1520008320, npc_faction_id = 0 WHERE id = 317112;
INSERT IGNORE INTO npc_types SELECT * FROM uf_tpl_chest;
DELETE FROM uf_tpl_chest;
INSERT INTO uf_tpl_chest SELECT * FROM npc_types WHERE id = 317112;
UPDATE uf_tpl_chest SET id = 490162, name = 'Treasure_of_Brell_Serilis', loottable_id = 1520008321, npc_faction_id = 0 WHERE id = 317112;
INSERT IGNORE INTO npc_types SELECT * FROM uf_tpl_chest;
DELETE FROM uf_tpl_chest;
DROP TEMPORARY TABLE IF EXISTS uf_tpl_chest;

-- chests are spawned by the encounter scripts; no static spawns.

-- ------------------------------------------------ chest loot (1520008317-21 / 1520008344-53)
DELETE FROM `loottable_entries` WHERE `loottable_id` BETWEEN 1520008317 AND 1520008321;
DELETE FROM `lootdrop_entries` WHERE `lootdrop_id` BETWEEN 1520008344 AND 1520008353;
DELETE FROM `lootdrop` WHERE `id` BETWEEN 1520008344 AND 1520008353;
DELETE FROM `loottable` WHERE `id` BETWEEN 1520008317 AND 1520008321;

INSERT INTO `loottable` (`id`,`name`,`mincash`,`maxcash`,`avgcoin`) VALUES
(1520008317,'UF_T7_cunning_Chest',60000,120000,60000),
(1520008318,'UF_T7_fungal_Chest',60000,120000,60000),
(1520008319,'UF_T7_decon_Chest',60000,120000,60000),
(1520008320,'UF_T7_creation_Chest',60000,120000,60000),
(1520008321,'UF_T7_audience_Chest',60000,120000,60000);
INSERT INTO `lootdrop` (`id`,`name`) VALUES
(1520008344,'UF_T7_cunning_Named'),
(1520008345,'UF_T7_cunning_Amulets'),
(1520008346,'UF_T7_fungal_Named'),
(1520008347,'UF_T7_fungal_Amulets'),
(1520008348,'UF_T7_decon_Named'),
(1520008349,'UF_T7_decon_Amulets'),
(1520008350,'UF_T7_creation_Named'),
(1520008351,'UF_T7_creation_Amulets'),
(1520008352,'UF_T7_audience_Named'),
(1520008353,'UF_T7_audience_Amulets');
INSERT INTO `lootdrop_entries` (`lootdrop_id`,`item_id`,`item_charges`,`equip_item`,`chance`) VALUES
(1520008344,103891,1,0,30),
(1520008344,103893,1,0,30),
(1520008344,103894,1,0,30),
(1520008344,103898,1,0,30),
(1520008344,103901,1,0,30),
(1520008345,88393,1,0,100),
(1520008346,103892,1,0,30),
(1520008346,103893,1,0,30),
(1520008346,103899,1,0,30),
(1520008346,103900,1,0,30),
(1520008346,103901,1,0,30),
(1520008347,88393,1,0,100),
(1520008348,103891,1,0,30),
(1520008348,103894,1,0,30),
(1520008348,103898,1,0,30),
(1520008348,103905,1,0,30),
(1520008348,103906,1,0,30),
(1520008349,88393,1,0,100),
(1520008350,103892,1,0,30),
(1520008350,103893,1,0,30),
(1520008350,103899,1,0,30),
(1520008350,103900,1,0,30),
(1520008350,103905,1,0,30),
(1520008351,88393,1,0,100),
(1520008352,103891,1,0,30),
(1520008352,103894,1,0,30),
(1520008352,103898,1,0,30),
(1520008352,103901,1,0,30),
(1520008352,103906,1,0,30),
(1520008353,88393,1,0,100);
INSERT INTO `loottable_entries` (`loottable_id`,`lootdrop_id`,`multiplier`,`droplimit`,`mindrop`,`probability`) VALUES
(1520008317,1520008344,1,0,2,100),
(1520008317,1520008345,6,0,0,100),
(1520008318,1520008346,1,0,2,100),
(1520008318,1520008347,6,0,0,100),
(1520008319,1520008348,1,0,2,100),
(1520008319,1520008349,9,0,0,100),
(1520008320,1520008350,1,0,2,100),
(1520008320,1520008351,9,0,0,100),
(1520008321,1520008352,1,0,2,100),
(1520008321,1520008353,9,0,0,100);
