-- ============================================================================
-- Fabled roster seed for `fabled_npcs` (content DB).
-- GENERATED by utils/scripts/fabled_roster.py - edit the script, not this file.
--
-- live roster rows: 458   matched: 450   unmatched: 8   ambiguous: 16
-- seed rows (distinct npc ids): 472   Classic: 70   RoK: 72   SoV: 120   SoL: 85   PoP: 125
--
-- Columns not listed keep their defaults: hp_mult/min_hit_mult/max_hit_mult = -1 (derive),
-- npc_spells_id = 0 (keep), special_abilities_append = '', chance = 0 (season chance),
-- enabled = 1. Re-applying only refreshes era and level, so per-row tuning survives.
--
-- Apply to the CONTENT database (see CODEBASE.md 4.4):
--   mysql -u <user> -p <content_db> < utils/sql/fabled_roster_seed.sql
-- ============================================================================

INSERT INTO `fabled_npcs` (`npc_id`, `era`, `level`, `chance`) VALUES
(2001, 'Classic', 4, 0),  -- Fippy_Darkpaw (North Qeynos) - The Fabled Fippy Darkpaw
(2109, 'Classic', 4, 0),  -- Fippy_Darkpaw (North Qeynos) - The Fabled Fippy Darkpaw
(2119, 'Classic', 4, 0),  -- Fippy_Darkpaw (North Qeynos) - The Fabled Fippy Darkpaw
(4147, 'Classic', 30, 0),  -- Pyzjn (Qeynos Hills) - The Fabled Pyzjn
(5133, 'Classic', 30, 0),  -- Grenix_Mucktail (Highpass Hold) - The Fabled Grenix Mucktail
(12068, 'Classic', 34, 0),  -- Chief_Goonda (West Karana) - The Fabled Chief Goonda
(13110, 'Classic', 55, 0),  -- GrimFeather (North Karana) - The Fabled GrimFeather
(14123, 'Classic', 55, 0),  -- Coloth_Meadowgreen (South Karana) - The Fabled Coloth Meadowgreen
(14139, 'Classic', 50, 0),  -- #Quillmane (South Karana) - The Fabled Quillmane
(14142, 'Classic', 40, 0),  -- Grizzleknot (South Karana) - The Fabled Grizzleknot
(14175, 'Classic', 70, 0),  -- The_Ishva_Mal (South Karana) - The Fabled Ishva Mal
(15160, 'Classic', 55, 0),  -- Proon (East Karana) - The Fabled Proon
(16010, 'Classic', 38, 0),  -- an_evil_eye (Beholders Maze) - The Fabled Evil Eye (Beholders Maze)
(16017, 'Classic', 38, 0),  -- an_evil_eye (Beholders Maze) - The Fabled Evil Eye (Beholders Maze)
(16021, 'Classic', 38, 0),  -- an_evil_eye (Beholders Maze) - The Fabled Evil Eye (Beholders Maze)
(16024, 'Classic', 38, 0),  -- an_evil_eye (Beholders Maze) - The Fabled Evil Eye (Beholders Maze)
(16033, 'Classic', 35, 0),  -- King_Xorbb (Beholders Maze) - The Fabled King Xorbb
(21006, 'Classic', 25, 0),  -- Kizdean_Gix (Commonlands) - The Fabled Kizdean Gix
(30100, 'Classic', 45, 0),  -- Karg_IceBear (Everfrost Peaks) - The Fabled Karg IceBear
(31118, 'Classic', 45, 0),  -- CWG_Model_EXG (Solusek's Eye) - The Fabled CWG Model EXG
(31132, 'Classic', 50, 0),  -- Gabbie_Mardoddle (Solusek's Eye) - The Fabled Gabbie Mardoddle
(32020, 'Classic', 70, 0),  -- Warlord_Skarlon (Nagafen's Lair) - The Fabled Warlord Skarlon
(32022, 'Classic', 70, 0),  -- King_Tranix (Nagafen's Lair) - The Fabled King Tranix
(32041, 'Classic', 65, 0),  -- Magus_Rokyl (Nagafen's Lair) - The Fabled Magus Rokyl
(32045, 'Classic', 65, 0),  -- kobold_champion (Nagafen's Lair) - The Fabled Kobold Champion
(32059, 'Classic', 70, 0),  -- kobold_priest (Nagafen's Lair) - The Fabled Kobold Priest
(32062, 'Classic', 70, 0),  -- Efreeti_Lord_Djarn (Nagafen's Lair) - The Fabled Efreeti Lord Djarn
(32063, 'Classic', 65, 0),  -- kobold_noble (Nagafen's Lair) - The Fabled Kobold Noble
(32066, 'Classic', 65, 0),  -- Solusek_kobold_king (Nagafen's Lair) - The Fabled Solusek Kobold King
(32083, 'Classic', 60, 0),  -- death_beetle (Nagafen's Lair) - The Fabled Death Beetle
(33104, 'Classic', 11, 0),  -- Mooto (Misty Thicket) - The Fabled Mooto
(34141, 'Classic', 16, 0),  -- Rahotep (Northern Desert of Ro) - The Fabled Rahotep
(35139, 'Classic', 50, 0),  -- an_ancient_cyclops (Southern Desert of Ro) - The Fabled Ancient Cyclops
(35144, 'Classic', 50, 0),  -- Terrorantula (Southern Desert of Ro) - The Fabled Terrorantula
(36097, 'Classic', 20, 0),  -- the_thaumaturgist (Befallen) - The Fabled Thaumaturgist
(37104, 'Classic', 30, 0),  -- Lockjaw (Southern Desert of Ro) - The Fabled Lockjaw
(44094, 'Classic', 55, 0),  -- Drelzna (Najena) - The Fabled Drelzna
(44100, 'Classic', 28, 0),  -- Najena (Najena) - The Fabled Najena
(50348, 'Classic', 60, 0),  -- Mortificator_Syythrak (The Mountains of Rathe) - The Fabled Mortificator Syythrak
(51142, 'Classic', 25, 0),  -- Webclaw_Murkwave (Lake Rathetear) - The Fabled Webclaw Murkwave
(52083, 'Classic', 25, 0),  -- Webclaw_Murkwave (Lake Rathetear) - The Fabled Webclaw Murkwave
(58032, 'Classic', 25, 0),  -- Emperor_Crush (Crushbone) - The Fabled Emperor Crush
(58059, 'Classic', 30, 0),  -- Ambassador_DVinn (Crushbone) - The Fabled Ambassador Dvinn
(59102, 'Classic', 50, 0),  -- a_cloaked_dhampyre (Castle Mistmoore) - The Fabled Cloaked Dhampyre
(59115, 'Classic', 55, 0),  -- Maid_Issis (Castle Mistmoore) - The Fabled Maid Issis
(63003, 'Classic', 35, 0),  -- an_undead_knight_of_Unrest (Unrest) - The Fabled Undead Knight of Unrest
(63010, 'Classic', 35, 0),  -- an_undead_barkeep (Unrest) - The Fabled Undead Barkeep
(63062, 'Classic', 45, 0),  -- Garanel_Rucksif (Unrest) - The Fabled Garanel Rucksif
(63086, 'Classic', 45, 0),  -- reclusive_ghoul_magus (Unrest) - The Fabled Reclusive Ghoul Magus
(64013, 'Classic', 70, 0),  -- Estrella_of_Gloomwater (Kedge Keep) - The Fabled Estrella of Gloomwater
(64087, 'Classic', 65, 0),  -- Undertow (Kedge Keep) - The Fabled Undertow
(65128, 'Classic', 45, 0),  -- the_froglok_shin_lord (Upper Guk) - The Fabled Froglok Shin Lord
(66005, 'Classic', 65, 0),  -- the_ghoul_lord (Lower Guk) - The Fabled Ghoul Lord
(66014, 'Classic', 60, 0),  -- an_evil_eye (Lower Guk) - The Fabled Evil Eye
(66092, 'Classic', 65, 0),  -- a_ghoul_executioner (Lower Guk) - The Fabled Ghoul Executioner
(66135, 'Classic', 60, 0),  -- an_evil_eye (Lower Guk) - The Fabled Evil Eye
(66146, 'Classic', 65, 0),  -- a_frenzied_ghoul (Lower Guk) - The Fabled Frenzied Ghoul
(66159, 'Classic', 65, 0),  -- the_froglok_king (Lower Guk) - The Fabled Froglok King
(66169, 'Classic', 65, 0),  -- a_ghoul_cavalier (Lower Guk) - The Fabled Ghoul Cavalier
(66171, 'Classic', 60, 0),  -- a_ghoul_assassin (Lower Guk) - The Fabled Ghoul Assassin
(66175, 'Classic', 60, 0),  -- a_froglok_noble (Lower Guk) - The Fabled Froglok Noble
(68146, 'Classic', 15, 0),  -- Corflunk (Butcherblock Mountains) - The Fabled Corflunk
(68185, 'Classic', 20, 0),  -- Zarchoomi (Butcherblock Mountains) - The Fabled Zarchoomi
(69018, 'Classic', 70, 0),  -- Allizewsaur (Ocean of Tears) - The Fabled Allizewsaur
(70047, 'Classic', 30, 0),  -- Barnacle_Bones (Dagnor's Cauldron) - The Fabled Barnacle Bones
(70059, 'Classic', 50, 0),  -- #Bilge_Farfathom (Dagnor's Cauldron) - The Fabled Bilge Farfathom
(73068, 'Classic', 40, 0),  -- a_goblin_preacher (Permafrost Keep) - The Fabled Goblin Preacher
(73103, 'Classic', 40, 0),  -- King_Thex`Ka_IV (Permafrost Keep) - The Fabled King Thex'Ka IV
(408082, 'Classic', 25, 0),  -- Kizdean_Gix (Commonlands) - The Fabled Kizdean Gix
(408191, 'Classic', 25, 0),  -- Kizdean_Gix (Commonlands) - The Fabled Kizdean Gix
(79015, 'RoK', 42, 0),  -- Grachnist_the_Destroyer (Warsliks Woods) - The Fabled Grachnist The Destroyer
(79116, 'RoK', 35, 0),  -- Iksar_Bandit_Lord (Warsliks Woods) - The Fabled Iksar Bandit Lord
(83030, 'RoK', 60, 0),  -- Ulump_Pujluk (Swamp of No Hope) - The Fabled Ulump Pujluk
(83073, 'RoK', 60, 0),  -- Kaggy_Krup (Swamp of No Hope) - The Fabled Kaggy Krup
(85062, 'RoK', 50, 0),  -- Chancellor_of_Di`zok (Lake of Ill Omen) - The Fabled Chancellor of Di'Zok
(85125, 'RoK', 50, 0),  -- Lord_Gorelik (Lake of Ill Omen) - The Fabled Lord Gorelik
(85180, 'RoK', 45, 0),  -- a_bloodgill_marauder (Lake of Ill Omen) - The Fabled Bloodgill Marauder
(86014, 'RoK', 70, 0),  -- Gorenaire (Dreadlands) - The Fabled Gorenaire
(86152, 'RoK', 50, 0),  -- rotting_skeleton (Dreadlands) - The Fabled Rotting Skeleton
(87113, 'RoK', 55, 0),  -- #Gorgul_Paclock (Burning Woods) - The Fabled Gorgul Paclock
(87142, 'RoK', 60, 0),  -- Gullerback (Burning Woods) - The Fabled Gullerback
(87143, 'RoK', 50, 0),  -- Entalon (Burning Woods) - The Fabled Entalon
(87146, 'RoK', 50, 0),  -- Entalon (Burning Woods) - The Fabled Entalon
(88073, 'RoK', 55, 0),  -- Xalgoz (Kaesora) - The Fabled Xalgoz
(89000, 'RoK', 75, 0),  -- Tolapumj (Old Sebilis) - The Fabled Tolapumj
(89057, 'RoK', 55, 0),  -- froglok_ostiary (Old Sebilis) - The Fabled Froglok Ostiary
(89129, 'RoK', 65, 0),  -- Harbinger_Freglor (Old Sebilis) - The Fabled Harbringer Freglor
(89131, 'RoK', 70, 0),  -- froglok_bartender (Old Sebilis) - The Fabled Froglok Bartender
(89144, 'RoK', 75, 0),  -- Emperor_Chottal (Old Sebilis) - The Fabled Emperor Chottal
(89153, 'RoK', 75, 0),  -- myconid_spore_king (Old Sebilis) - The Fabled Myconid Spore King
(89154, 'RoK', 75, 0),  -- Trakanon (Old Sebilis) - The Fabled Trakanon
(89163, 'RoK', 70, 0),  -- Hierophant_Prime_Grekal (Old Sebilis) - The Fabled Hierophant Prime Grekal
(89164, 'RoK', 75, 0),  -- froglok_chef (Old Sebilis) - The Fabled Froglok Chef
(89166, 'RoK', 70, 0),  -- froglok_commander (Old Sebilis) - The Fabled Froglok Commander
(89167, 'RoK', 70, 0),  -- Brogg (Old Sebilis) - The Fabled Brogg
(89171, 'RoK', 65, 0),  -- froglok_pickler (Old Sebilis) - The Fabled Froglok Pickler
(89174, 'RoK', 65, 0),  -- Baron_Yosig (Old Sebilis) - The Fabled Baron Yosig
(89175, 'RoK', 70, 0),  -- Gruplinort (Old Sebilis) - The Fabled Gruplinort
(89177, 'RoK', 65, 0),  -- crypt_caretaker (Old Sebilis) - The Fabled Crypt Caretaker
(90174, 'RoK', 65, 0),  -- #Lord_Rak`Ashiir (City of Mist) - The Fabled Lord Rak'Ashiir
(90180, 'RoK', 60, 0),  -- Lord_Ghiosk (City of Mist) - The Fabled Lord Ghiosk
(90184, 'RoK', 60, 0),  -- #Neh`Ashiir (City of Mist) - The Fabled Neh'Ashiir
(91088, 'RoK', 50, 0),  -- Black_Scar (Skyfire Mountains) - The Fabled Black Scar
(91093, 'RoK', 70, 0),  -- Talendor (Skyfire Mountains) - The Fabled Talendor
(92014, 'RoK', 40, 0),  -- Soothsayer_Dregzak (Frontier Mountains) - The Fabled Soothsayer Dregzak
(92043, 'RoK', 55, 0),  -- Eldak_Howlingbear (Frontier Mountains) - The Fabled Eldak Howlingbear
(92135, 'RoK', 50, 0),  -- Chief_RokGus (Frontier Mountains) - The Fabled Chief RokGus
(92153, 'RoK', 30, 0),  -- Bonedigger (Frontier Mountains) - The Fabled Bonedigger
(92172, 'RoK', 30, 0),  -- Stonegrinder (Frontier Mountains) - The Fabled Stonegrinder
(94009, 'RoK', 70, 0),  -- Severilous (Emerald Jungle) - The Fabled Severilous
(95000, 'RoK', 50, 0),  -- froglok_hunter (Trakanon's Teeth) - The Fabled Froglok Hunter
(95004, 'RoK', 50, 0),  -- froglok_forager (Trakanon's Teeth) - The Fabled Froglok Forager
(95180, 'RoK', 60, 0),  -- pained_soul (Trakanon's Teeth) - The Fabled Pained Soul
(96004, 'RoK', 40, 0),  -- The_Great_Oowomp (Timorous Deep) - The Fabled Oowomp
(96087, 'RoK', 30, 0),  -- Ugrak_da_Raider (Timorous Deep) - The Fabled Ugrak da Raider
(96089, 'RoK', 70, 0),  -- Faydedar (Timorous Deep) - The Fabled Faydedar
(97075, 'RoK', 25, 0),  -- Bargynn (Kurn's Tower) - The Fabled Bargynn
(102008, 'RoK', 68, 0),  -- skeletal_warlord (Karnor's Castle) - The Fabled Skeletal Warlord
(102026, 'RoK', 68, 0),  -- skeletal_warlord (Karnor's Castle) - The Fabled Skeletal Warlord
(102046, 'RoK', 70, 0),  -- a_drolvarg_captain (Karnor's Castle) - The Fabled Drolvarg Captain
(102103, 'RoK', 70, 0),  -- a_Drolvarg_warlord (Karnor's Castle) - The Fabled Drolvarg Warlord
(102112, 'RoK', 75, 0),  -- #Venril_Sathir (Karnor's Castle) - The Fabled Venril Sathir
(102116, 'RoK', 65, 0),  -- skeletal_captain (Karnor's Castle) - The Fabled Skeletal Captain
(102120, 'RoK', 60, 0),  -- skeletal_berserker (Karnor's Castle) - The Fabled Skeletal Berserker
(102124, 'RoK', 60, 0),  -- Hangnail (Karnor's Castle) - The Fabled Hangnail
(103055, 'RoK', 75, 0),  -- Queen_Velazul_Di`zok (Chardok) - The Fabled Queen Velazul Di'Zok
(103056, 'RoK', 75, 0),  -- Overking_Bathezid (Chardok) - The Fabled Overking Bathezid
(103080, 'RoK', 75, 0),  -- Prince_Selrach_Di`zok (Chardok) - The Fabled Prince Selrach Di'zok
(103195, 'RoK', 70, 0),  -- The_Bridge_Keeper (Chardok) - The Fabled Bridge Keeper
(103197, 'RoK', 70, 0),  -- Watch_Captain_Hir`roul (Chardok) - The Fabled Watch Captain Hir'Roul
(105029, 'RoK', 65, 0),  -- #The_Crypt_Excavator (Howling Stones) - The Fabled Crypt Excavator
(105116, 'RoK', 65, 0),  -- #The_Crypt_Feaster (Howling Stones) - The Fabled Crypt Feaster
(105152, 'RoK', 65, 0),  -- #The_Crypt_Devourer (Howling Stones) - The Fabled Crypt Devourer
(105153, 'RoK', 75, 0),  -- Drusella_Sathir (Howling Stones) - The Fabled Drusella Sathir
(105157, 'RoK', 65, 0),  -- #Mortiferous_Protector (Howling Stones) - The Fabled Mortiferous Protector
(105167, 'RoK', 65, 0),  -- a_crypt_spectre (Howling Stones) - The Fabled Crypt Spectre
(105178, 'RoK', 65, 0),  -- a_crypt_wurm (Howling Stones) - The Fabled Crypt Wurm
(105181, 'RoK', 65, 0),  -- the_Crypt_Keeper (Howling Stones) - The Fabled Crypt Keeper
(107084, 'RoK', 55, 0),  -- #Overseer_Pruckib (Mines of Nurga) - The Fabled Overseer Pruckib
(107146, 'RoK', 55, 0),  -- #Overseer_Malam (Mines of Nurga) - The Fabled Overseer Malam
(107153, 'RoK', 55, 0),  -- #Taskmaster_Huflam (Mines of Nurga) - The Fabled Taskmaster Huflam
(107159, 'RoK', 55, 0),  -- #Blackguard_Thabis (Mines of Nurga) - The Fabled Blackguard Thabis
(110099, 'SoV', 75, 0),  -- Lodizal (Iceclad Ocean) - The Fabled Lodizal
(110100, 'SoV', 60, 0),  -- Stormfeather (Iceclad Ocean) - The Fabled Stormfeather
(111031, 'SoV', 45, 0),  -- Priest_Majes_Medory (Tower of Frozen Shadow) - The Fabled Priest Majes Medory
(111059, 'SoV', 55, 0),  -- incoherent_spirit (Tower of Frozen Shadow) - The Fabled Incoherent Spirit
(111132, 'SoV', 45, 0),  -- #Zorglim_the_Dead (Tower of Frozen Shadow) - The Fabled Zorglim the Dead
(111150, 'SoV', 45, 0),  -- #The_Head_Usher (Tower of Frozen Shadow) - The Fabled Head Usher
(111154, 'SoV', 60, 0),  -- #Tserrina_Syl`Tor (Tower of Frozen Shadow) - The Fabled Tserrina Syl'Tor
(111160, 'SoV', 50, 0),  -- #maggot_infested_flesh (Tower of Frozen Shadow) - The Fabled Maggot Infested Flesh
(111163, 'SoV', 55, 0),  -- #Cara_Omica (Tower of Frozen Shadow) - The Fabled Cara Omica
(111167, 'SoV', 45, 0),  -- #Narmak_Berreka (Tower of Frozen Shadow) - The Fabled Narmak Berekka
(112025, 'SoV', 70, 0),  -- Velketor_the_Sorcerer (Velketor's Labyrinth) - Velketor the Fabled Sorcerer
(112049, 'SoV', 70, 0),  -- Lord_Doljonijiarnimorinar (Velketor's Labyrinth) - The Fabled Lord Doljonijiarnimorinar
(112083, 'SoV', 60, 0),  -- Crystal_Eyes (Velketor's Labyrinth) - The Fabled Crystal Eyes
(112100, 'SoV', 60, 0),  -- Crystal_Fang (Velketor's Labyrinth) - The Fabled Crystal Fang
(112105, 'SoV', 70, 0),  -- #Velketor`s_Experiment (Velketor's Labyrinth) - Velketor's Fabled Experiment
(113071, 'SoV', 72, 0),  -- The_Statue_of_Rallos_Zek (Kael Drakkel) - The Fabled Statue of Rallos Zek
(113079, 'SoV', 70, 0),  -- Kallis_Stormcaller (Kael Drakkel) - The Fabled Kallis Stormcaller
(113118, 'SoV', 70, 0),  -- Derakor_the_Vindicator (Kael Drakkel) - The Fabled Derakor the Vindicator
(113135, 'SoV', 75, 0),  -- Keldor_Dek`Torek (Kael Drakkel) - The Fabled Keldor Dek'Torek
(113153, 'SoV', 70, 0),  -- Fjokar_Frozenshard (Kael Drakkel) - The Fabled Fjokar Frozenshard
(113215, 'SoV', 70, 0),  -- King_Tormax (Kael Drakkel) - The Fabled King Tormax
(113341, 'SoV', 70, 0),  -- #The_Idol_of_Rallos_Zek (Kael Drakkel) - The Fabled Idol of Rallos Zek
(113457, 'SoV', 80, 0),  -- The_Avatar_of_War (Kael Drakkel) - The Fabled Avatar of War
(114106, 'SoV', 75, 0),  -- Lord_Yelinak (Skyshrine) - The Fabled Lord Yelinak
(114242, 'SoV', 70, 0),  -- Charayan_the_Crusader (Skyshrine) - The Fabled Charayan the Crusader
(114243, 'SoV', 70, 0),  -- Susarrak_the_Crusader (Skyshrine) - The Fabled Susarrak the Crusader
(114245, 'SoV', 75, 0),  -- Grendish_the_Crusader (Skyshrine) - The Fabled Grendish the Crusader
(114246, 'SoV', 70, 0),  -- Jortreva_the_Crusader (Skyshrine) - The Fabled Jortreva the Crusader
(114618, 'SoV', 75, 0),  -- Lord_Yelinak (Skyshrine) - The Fabled Lord Yelinak
(116006, 'SoV', 60, 0),  -- Oracle_of_Ry`Gorr (Eastern Wastes) - The Fabled Oracle of Ry'Gorr
(116012, 'SoV', 50, 0),  -- Firbrand_the_Black (Eastern Wastes) - The Fabled Firbrand
(116041, 'SoV', 10, 0),  -- a_snow_bunny (Eastern Wastes) - The Fabled Snow Bunny
(116165, 'SoV', 55, 0),  -- Chief_Ry`Gorr (Eastern Wastes) - The Fabled Chief Ry'Gorr
(116180, 'SoV', 45, 0),  -- Captain_Ulmog (Eastern Wastes) - The Fabled Captain Ulmog
(117014, 'SoV', 60, 0),  -- #Yvolcarn (Cobalt Scar) - The Fabled Yvolcarn
(117073, 'SoV', 70, 0),  -- Kelorek`Dar (Cobalt Scar) - The Fabled Kelorek'Dar
(117075, 'SoV', 65, 0),  -- #Azureake (Cobalt Scar) - The Fabled Azureake
(118040, 'SoV', 60, 0),  -- shardwurm_broodmother (Great Divide) - The Fabled Shardwurm Broodmother
(118104, 'SoV', 55, 0),  -- shardwurm_matriarch (Great Divide) - The Fabled Shardwurm Matriarch
(118107, 'SoV', 50, 0),  -- #Shardtooth (Great Divide) - The Fabled Shardtooth
(118110, 'SoV', 55, 0),  -- Blizzent (Great Divide) - The Fabled Blizzent
(118117, 'SoV', 55, 0),  -- #Gorul_Longshanks (Great Divide) - The Fabled Gorul Longshanks
(118119, 'SoV', 55, 0),  -- #Icetooth (Great Divide) - The Fabled Icetooth
(119029, 'SoV', 65, 0),  -- Priest_Delar (The Wakening Land) - The Fabled Priest Delar
(119084, 'SoV', 65, 0),  -- Lady_Gelistial (The Wakening Land) - The Fabled Lady Gelistial
(119112, 'SoV', 70, 0),  -- Wuoshi (The Wakening Land) - The Fabled Wuoshi
(119116, 'SoV', 53, 0),  -- #Rapticor (Wakening Land) - The Fabled Rapticor
(119123, 'SoV', 65, 0),  -- Frostgiant_Overseer (The Wakening Land) - The Fabled Frostgiant Overseer
(119162, 'SoV', 60, 0),  -- Grand_Vizier_Poolakacha`tei (Wakening Lands) - The Fabled Grand Vizier Poolakacha'tei
(120005, 'SoV', 75, 0),  -- Sontalak (Western Wastes) - The Fabled Sontalak
(120014, 'SoV', 70, 0),  -- Derasinal (Western Wastes) - The Fabled Derasinal
(120015, 'SoV', 70, 0),  -- Ayillish (Western Wastes) - The Fabled Ayillish
(120016, 'SoV', 70, 0),  -- Karkona (Western Wastes) - The Fabled Karkona
(120017, 'SoV', 75, 0),  -- Ionat (Western Wastes) - The Fabled Ionat
(120018, 'SoV', 70, 0),  -- Entariz (Western Wastes) - The Fabled Entariz
(120019, 'SoV', 70, 0),  -- Draazak (Western Wastes) - The Fabled Draazak
(120048, 'SoV', 75, 0),  -- #Tantor (Western Wastes) - The Fabled Tantor
(120057, 'SoV', 70, 0),  -- Harla_Dar (Western Wastes) - The Fabled Harla Dar
(120064, 'SoV', 75, 0),  -- #Mraaka (Western Wastes) - The Fabled Mraaka
(120084, 'SoV', 70, 0),  -- Klandicar (Western Wastes) - The Fabled Klandicar
(120086, 'SoV', 70, 0),  -- Esorpa_of_the_Ring (Western Wastes) - The Fabled Esorpa of the Ring
(120087, 'SoV', 70, 0),  -- Myga (Western Wastes) - The Fabled Myga
(120125, 'SoV', 75, 0),  -- Del_Sapara (Western Wastes) - The Fabled Del Sapara
(121006, 'SoV', 40, 0),  -- #a_Ry`Gorr_herbalist (Crystal Caverns) - The Fabled Ry'Gorr Herbalist
(121062, 'SoV', 50, 0),  -- Foreman_Rixact (Crystal Caverns) - The Fabled Foreman Rixact
(121068, 'SoV', 50, 0),  -- Foreman_Rixact (Crystal Caverns) - The Fabled Foreman Rixact
(121070, 'SoV', 45, 0),  -- #Foreman_Smason (Crystal Caverns) - The Fabled Foreman Smason
(121072, 'SoV', 55, 0),  -- Queen_Dracnia (Crystal Caverns) - The Fabled Queen Dracnia
(121086, 'SoV', 50, 0),  -- #a_life_leech (Crystal Caverns) - The Fabled Life Leech
(123036, 'SoV', 70, 0),  -- Vilefang (Dragon Necropolis) - The Fabled Vilefang
(123090, 'SoV', 70, 0),  -- #Dominator_Yisaki (Dragon Necropolis) - The Fabled Dominator Yisaki
(123091, 'SoV', 70, 0),  -- Seeker_Bulava (Dragon Necropolis) - The Fabled Seeker Bulava
(123115, 'SoV', 70, 0),  -- Zlandicar (Dragon Necropolis) - The Fabled Zlandicar
(123131, 'SoV', 70, 0),  -- Warmaster_Utvara (Dragon Necropolis) - The Fabled Warmaster Utvara
(123142, 'SoV', 70, 0),  -- #Dustbinder_Grakina (Dragon Necropolis) - The Fabled Dustbinder Grakina
(123149, 'SoV', 75, 0),  -- Vaniki (Dragon Necropolis) - The Fabled Vaniki
(123154, 'SoV', 75, 0),  -- #Queen_Raltaas (Dragon Necropolis) - The Fabled Queen Raltaas
(124001, 'SoV', 70, 0),  -- #Ikatiar_the_Venom (Temple of Veeshan) - The Fabled Ikatiar the Venom
(124004, 'SoV', 70, 0),  -- #Eashen_of_the_Sky (Temple of Veeshan) - The Fabled Eashen of the Sky
(124008, 'SoV', 75, 0),  -- #Lord_Feshlak (Temple of Veeshan) - The Fabled Lord Feshlak
(124010, 'SoV', 75, 0),  -- #Aaryonar (Temple of Veeshan) - The Fabled Aaryonar
(124011, 'SoV', 75, 0),  -- Dagarn_the_Destroyer (Temple of Veeshan) - The Fabled Dagarn the Destroyer
(124017, 'SoV', 75, 0),  -- #Lord_Vyemm (Temple of Veeshan) - The Fabled Lord Vyemm
(124020, 'SoV', 70, 0),  -- #Lendiniara_the_Keeper (Temple of Veeshan) - The Fabled Lendiniara the Keeper
(124037, 'SoV', 70, 0),  -- #Dozekar_the_Cursed (Temple of Veeshan) - The Fabled Dozekar the Cursed
(124071, 'SoV', 75, 0),  -- #Cekenar (Temple of Veeshan) - The Fabled Cekenar
(124072, 'SoV', 75, 0),  -- #Jorlleag (Temple of Veeshan) - The Fabled Jorlleag
(124073, 'SoV', 75, 0),  -- #Zlexak (Temple of Veeshan) - The Fabled Zlexak
(124074, 'SoV', 75, 0),  -- #Lord_Kreizenn (Temple of Veeshan) - The Fabled Lord Kreizenn
(124075, 'SoV', 75, 0),  -- #Sevalak (Temple of Veeshan) - The Fabled Sevalak
(124076, 'SoV', 75, 0),  -- #Lady_Nevederia (Temple of Veeshan) - The Fabled Lady Nevederia
(124077, 'SoV', 75, 0),  -- #Lady_Mirenilla (Temple of Veeshan) - The Fabled Lady Mirenilla
(124103, 'SoV', 75, 0),  -- #Lord_Koi`Doken (Temple of Veeshan) - The Fabled Lord Koi'Doken
(124104, 'SoV', 75, 0),  -- #Telkorenar (Temple of Veeshan) - The Fabled Telkorenar
(124105, 'SoV', 75, 0),  -- #Gozzrem (Temple of Veeshan) - The Fabled Gozzrem
(124155, 'SoV', 80, 0),  -- #Vulak`Aerr (Temple of Veeshan) - The Fabled Vulak'Aerr
(125047, 'SoV', 70, 0),  -- #Mistress_Latazura (Siren's Grotto) - The Fabled Mistress Latazura
(125048, 'SoV', 70, 0),  -- #High_Priestess_Sercema (Siren's Grotto) - The Fabled High Priestess Sercema
(125062, 'SoV', 65, 0),  -- Fellspine (Siren's Grotto) - The Fabled Fellspine
(127001, 'SoV', 75, 0),  -- #_Tunare (Plane of Growth) - The Fabled Tunare
(127018, 'SoV', 70, 0),  -- Fayl_Everstrong (Plane of Growth) - The Fabled Fayl Everstrong
(127019, 'SoV', 70, 0),  -- Rumbleroot (Plane of Growth) - The Fabled Rumbleroot
(127020, 'SoV', 70, 0),  -- Ail_the_Elder (Plane of Growth) - The Fabled Ail the Elder
(127021, 'SoV', 70, 0),  -- Treah_Greenroot (Plane of Growth) - The Fabled Treah Greenroot
(127096, 'SoV', 70, 0),  -- Prince_Thirneg (Plane of Growth) - The Fabled Prince Thirneg
(128041, 'SoV', 75, 0),  -- #Kildrukaun_the_Ancient (Kerafyrm's Lair) - The Fabled Kildrukaun the Ancient
(128042, 'SoV', 75, 0),  -- #Vyskudra_the_Ancient (Kerafyrm's Lair) - The Fabled Vyskudra the Ancient
(128043, 'SoV', 75, 0),  -- #Tjudawos_the_Ancient (Kerafyrm's Lair) - The Fabled Tjudawos the Ancient
(128044, 'SoV', 75, 0),  -- #Zeixshi-Kar_the_Ancient (Kerafyrm's Lair) - The Fabled Zeixshi'Kar the Ancient
(128045, 'SoV', 75, 0),  -- #The_Final_Arbiter (Kerafyrm's Lair) - The Fabled Final Arbiter
(128053, 'SoV', 75, 0),  -- #The_Progenitor (Kerafyrm's Lair) - The Fabled Progenitor
(128054, 'SoV', 75, 0),  -- #Master_of_the_Guard (Kerafyrm's Lair) - The Fabled Master of the Guard
(128141, 'SoV', 75, 0),  -- The_Overseer (Kerafyrm's Lair) - The Fabled Overseer
(128143, 'SoV', 75, 0),  -- #The_Final_Arbiter (Kerafyrm's Lair) - The Fabled Final Arbiter
(128144, 'SoV', 75, 0),  -- #The_Progenitor (Kerafyrm's Lair) - The Fabled Progenitor
(128145, 'SoV', 75, 0),  -- #Master_of_the_Guard (Kerafyrm's Lair) - The Fabled Master of the Guard
(129003, 'SoV', 75, 0),  -- #Dain_Frostreaver_IV (Icewell Keep) - The Fabled Dain Frostreaver IV
(129028, 'SoV', 70, 0),  -- Chamberlain_Krystorf (Icewell Keep) - The Fabled Chamberlain Krystorf
(129092, 'SoV', 70, 0),  -- Grizznot (Icewell Keep) - The Fabled Grizznot
(129093, 'SoV', 65, 0),  -- Glucose (Icewell Keep) - The Fabled Glucose
(153095, 'SoL', 70, 0),  -- General_Jared_Blaystich (Echo Caverns) - The Fabled General Jared Blaystich
(153136, 'SoL', 40, 0),  -- The_Needlite_Queen (Echo Caverns) - The Fabled Needlite Queen
(154138, 'SoL', 80, 0),  -- Khati_Sha_the_Twisted (Acrylia Caverns) - The Fabled Khati Sha the Twisted
(154154, 'SoL', 80, 0),  -- #Warder_of_Life (Acrylia Caverns) - The Fabled Warder of Life
(154155, 'SoL', 80, 0),  -- #Warder_of_Death (Acrylia Caverns) - The Fabled Warder of Death
(156055, 'SoL', 35, 0),  -- The_Reishicyben (Paludal Caverns) - The Fabled Reishicyben
(156075, 'SoL', 30, 0),  -- Yelloweyes (Paludal Caverns) - The Fabled Yelloweyes
(156106, 'SoL', 30, 0),  -- Yelloweyes (Paludal Caverns) - The Fabled Yelloweyes
(156111, 'SoL', 30, 0),  -- Yelloweyes (Paludal Caverns) - The Fabled Yelloweyes
(156114, 'SoL', 30, 0),  -- Ch`ktok (Paludal Caverns) - The Fabled Ch'ktok
(157027, 'SoL', 70, 0),  -- Priest_Kak`thak (Fungus Grove) - The Fabled Priest Kak'thak
(157082, 'SoL', 65, 0),  -- #Tuchako (Fungus Grove) - The Fabled Tuchako
(157107, 'SoL', 75, 0),  -- Warlord_Tk`kik`tthik (Fungus Grove) - The Fabled Warlord Tk'kik'tthik
(158006, 'SoL', 85, 0),  -- #Aten_Ha_Ra (Vex Thal) - The Fabled Aten Ha Ra
(158007, 'SoL', 80, 0),  -- #Kaas_Thox_Xi_Aten_Ha_Ra (Vex Thal) - The Fabled Kaas Thox Xi Aten Ha Ra
(158008, 'SoL', 80, 0),  -- #Thall_Va_Kelun (Vex Thal) - The Fabled Thall Va Kelun
(158009, 'SoL', 80, 0),  -- #Va_Xi_Aten_Ha_Ra (Vex Thal) - The Fabled Va Xi Aten Ha Ra
(158010, 'SoL', 80, 0),  -- #Diabo_Xi_Va_Temariel (Vex Thal) - The Fabled Diabo Xi Va Temariel
(158011, 'SoL', 80, 0),  -- #Thall_Xundraux_Diabo (Vex Thal) - The Fabled Thall Xundraux Diabo
(158012, 'SoL', 80, 0),  -- #Diabo_Xi_Xin_Thall (Vex Thal) - The Fabled Diabo Xi Xin Thall
(158013, 'SoL', 80, 0),  -- #Kaas_Thox_Xi_Ans_Dyek (Vex Thal) - The Fabled Kaas Thox Xi Ans Dyek
(158014, 'SoL', 80, 0),  -- #Diabo_Xi_Va (Vex Thal) - The Fabled Diabo Xi Va
(158015, 'SoL', 80, 0),  -- #Diabo_Xi_Xin (Vex Thal) - The Fabled Diabo Xi Xin
(158016, 'SoL', 80, 0),  -- #Thall_Va_Xakra (Vex Thal) - The Fabled Thall Va Xakra
(158125, 'SoL', 80, 0),  -- #Thall_Va_Xakra (Vex Thal) - The Fabled Thall Va Xakra
(159691, 'SoL', 80, 0),  -- #Lord_Inquisitor_Seru_ (Sanctus Seru) - The Fabled Lord Inquisitor Seru
(160375, 'SoL', 75, 0),  -- Lcea_Katta (Katta Castellum) - The Fabled Lcea Katta
(161030, 'SoL', 40, 0),  -- #The_Swarm_Leader (Netherbian Lair) - The Fabled Swarm Leader
(161071, 'SoL', 35, 0),  -- #The_Trog_King (Netherbian Lair) - The Fabled Trog King
(162011, 'SoL', 75, 0),  -- Taskmaster_Zerumaz (Ssraeshza Temple) - The Fabled Taskmaster Zerumaz
(162012, 'SoL', 75, 0),  -- Taskmaster_Kavamezh (Ssraeshza Temple) - The Fabled Taskmaster Kavamezh
(162013, 'SoL', 75, 0),  -- Taskmaster_Mikazha (Ssraeshza Temple) - The Fabled Taskmaster Mikazha
(162021, 'SoL', 75, 0),  -- Taskmaster_Keuzozh (Ssraeshza Temple) - The Fabled Taskmaster Keuzozh
(162023, 'SoL', 75, 0),  -- Warden_Mekuzh (Ssraeshza Temple) - The Fabled Warden Mekuzh
(162024, 'SoL', 75, 0),  -- Taskmaster_Vezhkah (Ssraeshza Temple) - The Fabled Taskmaster Vezhkah
(162059, 'SoL', 75, 0),  -- Taskmaster_Zhe`Vozh (Ssraeshza Temple) - The Fabled Taskmaster Zhe'Vozh
(162060, 'SoL', 75, 0),  -- Taskmaster_Revan`Kezh (Ssraeshza Temple) - The Fabled Taskmaster Revan'Kezh
(162065, 'SoL', 85, 0),  -- #Emperor_Ssraeshza (Ssraeshza Temple) - The Fabled Emperor Ssraeshza
(162076, 'SoL', 80, 0),  -- High_Priest_of_Ssraeshza (Ssraeshza Temple) - The Fabled High Priest of Ssraeshza
(162089, 'SoL', 75, 0),  -- #Rhozth_Ssravizh (Ssraeshza Temple) - The Fabled Rhozth Ssravizh
(162190, 'SoL', 80, 0),  -- Xerkizh_The_Creator (Ssraeshza Temple) - The Fabled Xerkizh The Creator
(162206, 'SoL', 80, 0),  -- #Vyzh`dra_the_Cursed (Ssraeshza Temple) - The Fabled Vyzh'dra the Cursed
(162258, 'SoL', 75, 0),  -- #Rhozth_Ssrakezh (Ssraeshza Temple) - The Fabled Rhozth Ssrakezh
(163013, 'SoL', 75, 0),  -- #Servitor_of_Luclin (Grieg's End) - The Fabled Servitor of Luclin
(163048, 'SoL', 75, 0),  -- #Khemot_Agarthizar (Grieg's End) - The Fabled Khemot Agarthizar
(163057, 'SoL', 80, 0),  -- Grieg_Veneficus_ (Grieg's End) - The Fabled Grieg Veneficus
(164078, 'SoL', 80, 0),  -- Thought_Horror_Overfiend (The Deep) - The Fabled Thought Horror Overfiend
(164089, 'SoL', 75, 0),  -- A_burrower_parasite (The Deep) - The Fabled Burrower Parasite
(164098, 'SoL', 75, 0),  -- The_Burrower_Beast (The Deep) - The Fabled Burrower Beast
(165063, 'SoL', 55, 0),  -- Warlord_Gok_Thok (Shadeweaver's Thicket) - The Fabled Warlord Gok Thok
(165092, 'SoL', 65, 0),  -- Jynhadar (Shadeweaver's Thicket) - The Fabled Jynhadar
(165306, 'SoL', 55, 0),  -- Warlord_Shik_Thras (Shadeweaver's Thicket) - The Fabled Warlord Shik Thras
(166153, 'SoL', 35, 0),  -- #Ghowlik (Hollowshade Moor) - The Fabled Ghowlik
(166240, 'SoL', 40, 0),  -- #Grum_No_Eyes (Hollowshade Moors) - The Fabled Grum No Eyes
(166243, 'SoL', 45, 0),  -- #Gleeknot_Gnitrat (Hollowshade Moor) - The Fabled Gleeknot Gnitrat
(166248, 'SoL', 35, 0),  -- #Warpaw_Dankpelt (Hollowshade Moor) - The Fabled Warpaw Dankpelt
(166275, 'SoL', 50, 0),  -- #Gnarlick (Hollowshade Moor) - The Fabled Gnarlick
(166276, 'SoL', 45, 0),  -- #Gorehorn (Hollowshade Moor) - The Fabled Gorehorn
(167077, 'SoL', 55, 0),  -- Spymaster_Gephes (Grimling Forest) - The Fabled Spymaster Gephes
(168091, 'SoL', 50, 0),  -- #An_Ancient_Zelniak (Marus Seru) - The Fabled Ancient Zelniak
(168095, 'SoL', 45, 0),  -- #Queen_Kvaknak (Marus Seru) - The Fabled Queen Kvaknak
(169007, 'SoL', 65, 0),  -- #An_Ancient_Rockhopper (Mons Letalis) - The Fabled Ancient Rockhopper
(169035, 'SoL', 65, 0),  -- The_Spire_Lord (Mons Letalis) - The Fabled Spire Lord
(169054, 'SoL', 55, 0),  -- A_Fiery_Thought_Leech (Mons Letalis) - The Fabled Fiery Thought Leech
(170268, 'SoL', 45, 0),  -- #Hydro (Twilight Sea) - The Fabled Hydro
(171057, 'SoL', 70, 0),  -- #Revenant_Sthzzzizt (The Grey) - The Fabled Revenant Sthzzzizt
(171065, 'SoL', 60, 0),  -- #Heirophant_Grazan (The Grey) - The Fabled Heirophant Grazan
(171069, 'SoL', 70, 0),  -- #Boulder (The Grey) - The Fabled Boulder
(171073, 'SoL', 70, 0),  -- #Revenant_Zsshta (The Grey) - The Fabled Revenant Zsshta
(171074, 'SoL', 70, 0),  -- Crusader_Kezzal (The Grey) - The Fabled Crusader Kezzal
(172112, 'SoL', 60, 0),  -- an_ancient_darkwing_bat (Tenebrous Mountains) - The Fabled Ancient Darkwing Bat
(172151, 'SoL', 65, 0),  -- Emissary_Oomgado (The Tenebrous Mountains) - The Fabled Emissary Oomgado
(172155, 'SoL', 70, 0),  -- #Heratius_Grolden (The Tenebrous Mountains) - The Fabled Heratius Grolden
(172178, 'SoL', 60, 0),  -- Skyshadow (Tenebrous Mountains) - The Fabled Skyshadow
(172184, 'SoL', 75, 0),  -- #Valdanov_Zevfeer (The Tenebrous Mountains) - The Fabled Valdanov Zevfeer
(173137, 'SoL', 70, 0),  -- #a_goranga_battlemaster (The Maiden's Eye) - The Fabled Goranga Battlemaster
(173140, 'SoL', 70, 0),  -- A_Shadow_Overlord (The Maiden's Eye) - The Fabled Shadow Overlord
(174131, 'SoL', 50, 0),  -- #Sambata_Tribal_Keeper (Dawnshroud Peaks) - The Fabled Sambata Tribal Keeper
(174316, 'SoL', 55, 0),  -- #An_Age_Old_Rockhopper (Dawnshroud Peaks) - The Fabled Age Old Rockhopper
(175227, 'SoL', 55, 0),  -- #Kraen_Flameweaver (Scarlet Desert) - The Fabled Kraen Flameweaver
(176002, 'SoL', 80, 0),  -- #Rumblecrush (The Umbral Plains) - The Fabled Rumblecrush
(176088, 'SoL', 80, 0),  -- #Doomshade (The Umbral Plains) - The Fabled Doomshade
(179037, 'SoL', 75, 0),  -- The_Itraer_Vius (Akheva Ruins) - The Fabled Itraer Vius
(179157, 'SoL', 80, 0),  -- Shei_Vinitras (Akheva Ruins) - The Fabled Shei Vinitras
(179184, 'SoL', 80, 0),  -- The_Insanity_Crawler (Akheva Ruins) - The Fabled Insanity Crawler
(200055, 'PoP', 85, 0),  -- #Bertoxxulous (Ruins of Lxanvom) - The Fabled Bertoxxulous
(205091, 'PoP', 85, 0),  -- #Grummus (Plane of Disease) - The Fabled Grummus
(206046, 'PoP', 85, 0),  -- Manaetic_Behemoth (Plane of Innovation) - The Fabled Manaetic Behemoth
(206068, 'PoP', 85, 0),  -- Xanamech_Nezmirthafen (Plane of Innovation) - The Fabled Xanamech Nezmirthafen
(207001, 'PoP', 85, 0),  -- Saryrn (Plane of Torment) - The Fabled Saryrn
(207015, 'PoP', 85, 0),  -- The_Keeper_of_Sorrows (Plane of Torment) - The Fabled Keeper of Sorrows
(208074, 'PoP', 85, 0),  -- #Aerin`Dar (Plane of Valor) - The Fabled Aerin'Dar
(209016, 'PoP', 80, 0),  -- Brynju_Thunderclap (Torden, the Bastion of Thunder) - The Fabled Brynju Thunderclap
(209026, 'PoP', 90, 0),  -- Agnarr_the_Storm_Lord (Torden, the Bastion of Thunder) - The Fabled Agnarr the Storm Lord
(209059, 'PoP', 80, 0),  -- Auliffe_Chaoswind (Torden, the Bastion of Thunder) - The Fabled Auliffe Chaoswind
(209060, 'PoP', 80, 0),  -- Eindride_Icestorm (Torden, the Bastion of Thunder) - The Fabled Eindride Icestorm
(209061, 'PoP', 80, 0),  -- Kuanbyr_Hailstorm (Torden, the Bastion of Thunder) - The Fabled Kuanbyr Hailstorm
(209070, 'PoP', 80, 0),  -- Laef_Windfall (Torden, the Bastion of Thunder) - The Fabled Laef Windfall
(209071, 'PoP', 80, 0),  -- Gaukr_Sandstorm (Torden, the Bastion of Thunder) - The Fabled Gaukr Sandstorm
(209072, 'PoP', 80, 0),  -- Oreen_Wavecrasher (Torden, the Bastion of Thunder) - The Fabled Oreen Wavecrasher
(209082, 'PoP', 80, 0),  -- Hreidar_Lynhillig (Torden, the Bastion of Thunder) - The Fabled Hreidar Lynhillig
(210176, 'PoP', 80, 0),  -- Neffiken_Lord_of_Kelek`Vor (Plane of Storms) - The Fabled Neffiken, Lord of Kelek'Vor
(210178, 'PoP', 80, 0),  -- Gurebk_Lord_of_Krendic (Plane of Storms) - The Fabled Gurebk, Lord of Krendic
(210179, 'PoP', 80, 0),  -- Jeplak_Lord_of_Srerendi (Plane of Storms) - The Fabled Jeplak, Lord of Srerendi
(210245, 'PoP', 80, 0),  -- Lord_of_Thunder (Plane of Storms) - Fabled Falto, Lord of Thunder
(212014, 'PoP', 85, 0),  -- Jiva (Solusek Ro's Tower) - The Fabled Jiva
(212023, 'PoP', 85, 0),  -- Arlyxir (Solusek Ro's Tower) - The Fabled Arlyxir
(212025, 'PoP', 90, 0),  -- Solusek_Ro (Solusek Ro's Tower) - The Fabled Solusek Ro
(212026, 'PoP', 85, 0),  -- Rizlona (Solusek Ro's Tower) - The Fabled Rizlona
(212033, 'PoP', 85, 0),  -- Galremos (Solusek Ro's Tower) - The Fabled Galremos
(212055, 'PoP', 85, 0),  -- Xuzl (Solusek Ro's Tower) - The Fabled Xuzl
(212061, 'PoP', 85, 0),  -- The_Protector_of_Dresolik (Solusek Ro's Tower) - The Fabled Protector of Dresolik
(214053, 'PoP', 80, 0),  -- Glykus_Helmir (Drunder, Fortress of Zek) - The Fabled Glykus Helmir
(214054, 'PoP', 80, 0),  -- Tagrin_Maldric (Drunder, Fortress of Zek) - The Fabled Tagrin Maldric
(214083, 'PoP', 90, 0),  -- Vallon_Zek (Drunder, Fortress of Zek) - The Fabled Vallon Zek
(214101, 'PoP', 80, 0),  -- #a_Stampeding_Piglet (Drunder, Fortress of Zek) - The Fabled Stampeding Piglet
(214113, 'PoP', 90, 0),  -- #Rallos_Zek_the_Warlord (Drunder, Fortress of Zek) - The Fabled Warlord, Rallos Zek
(214120, 'PoP', 83, 0),  -- The_Diaku_Armorer (Drunder, Fortress of Zek) - The Fabled Diaku Armorer
(215003, 'PoP', 85, 0),  -- #Queen_Silandria (Eryslai, the Kingdom of Wind) - The Fabled Queen Silandria
(215007, 'PoP', 83, 0),  -- a_temple_guardian (Eryslai, the Kingdom of Wind) - Fabled Temple Guardian
(215008, 'PoP', 83, 0),  -- a_temple_guardian (Eryslai, the Kingdom of Wind) - Fabled Temple Guardian
(215015, 'PoP', 83, 0),  -- a_temple_guardian (Eryslai, the Kingdom of Wind) - Fabled Temple Guardian
(215017, 'PoP', 83, 0),  -- a_temple_guardian (Eryslai, the Kingdom of Wind) - Fabled Temple Guardian
(215034, 'PoP', 85, 0),  -- #Rinturion_Windblade (Eryslai, the Kingdom of Wind) - The Fabled Rinturion Windblade
(215056, 'PoP', 90, 0),  -- #Xegony_the_Queen_of_Air (Eryslai, the Kingdom of Wind) - The Fabled Xegony the Queen of Air
(215454, 'PoP', 85, 0),  -- The_Elemental_Masterpiece (Eryslai, the Kingdom of Wind) - The Fabled Elemental Masterpiece
(216037, 'PoP', 83, 0),  -- Gigadon (Reef of Coirnav) - Fabled Gigadon
(216038, 'PoP', 83, 0),  -- Monstrous_Sea_Turtle (Reef of Coirnav) - Fabled Monstrous Sea Turtle
(216041, 'PoP', 85, 0),  -- Krziik_the_Mighty (Reef of Coirnav) - The Fabled Krziik the Mighty
(216042, 'PoP', 85, 0),  -- Grioihin_the_Wise (Reef of Coirnav) - The Fabled Grioihin the Wise
(216043, 'PoP', 85, 0),  -- Hydrotha (Reef of Coirnav) - The Fabled Hydrotha
(216048, 'PoP', 90, 0),  -- Coirnav_the_Avatar_of_Water (Reef of Coirnav) - The Fabled Coirnav the Avatar of Water
(216050, 'PoP', 83, 0),  -- Swordfang (Reef of Coirnav) - Fabled Swordfang
(216053, 'PoP', 83, 0),  -- Regrua_Overlord (Reef of Coirnav) - Fabled Regrua Overlord
(216054, 'PoP', 83, 0),  -- Savage_Deepwater_Kraken (Reef of Coirnav) - Fabled Savage Deepwater Kraken
(216056, 'PoP', 83, 0),  -- Razorfin (Reef of Coirnav) - Fabled Razorfin
(216075, 'PoP', 83, 0),  -- Furious_Deepwater_Kraken (Reef of Coirnav) - Fabled Furious Deepwater Kraken
(216091, 'PoP', 83, 0),  -- Ferocious_Barracuda (Reef of Coirnav) - Fabled Ferocious Barracuda
(216092, 'PoP', 83, 0),  -- Frenzied_Anglerfish (Reef of Coirnav) - Fabled Frenzied Anglerfish
(216095, 'PoP', 83, 0),  -- Hammertooth (Reef of Coirnav) - Fabled Hammertooth
(216096, 'PoP', 83, 0),  -- Hraquis_Arch_Magus (Reef of Coirnav) - Fabled Hraquis Arch Mage
(216097, 'PoP', 83, 0),  -- Regrua_Protector (Reef of Coirnav) - Fabled Regrua Protector
(216105, 'PoP', 83, 0),  -- Triloun_Seer (Reef of Coirnav) - Fabled Triloun Seer
(217003, 'PoP', 85, 0),  -- Blazzax_the_Omnifiend (Doomfire, the Burning Lands) - The Fabled Blazzax the Omnifiend
(217005, 'PoP', 85, 0),  -- Babnoxis_the_Spider_Queen (Doomfire, the Burning Lands) - The Fabled Babnoxis the Spider Queen
(217018, 'PoP', 83, 0),  -- Captain_of_Fire (Doomfire, the Burning Lands) - Fabled Captain of Fire
(217019, 'PoP', 85, 0),  -- Arch_Mage_Yozanni (Doomfire, the Burning Lands) - The Fabled Arch Mage Yozanni
(217032, 'PoP', 85, 0),  -- General_Reparm (Doomfire, the Burning Lands) - The Fabled General Reparm
(217040, 'PoP', 83, 0),  -- Obsidian_War_Spider (Doomfire, the Burning Lands) - Fabled Obsidian War Spider
(217047, 'PoP', 83, 0),  -- a_jopal_lavahurler (Doomfire, the Burning Lands) - Fabled Jopal Lavahurler
(217049, 'PoP', 85, 0),  -- Jaxoliz_Dawneyes (Doomfire, the Burning Lands) - The Fabled Jaxoliz Dawneyes
(217051, 'PoP', 85, 0),  -- Criare_Sunmane (Doomfire, the Burning Lands) - The Fabled Criare Sunmane
(217054, 'PoP', 90, 0),  -- Fennin_Ro_the_Tyrant_of_Fire (Doomfire, the Burning Lands) - The Fabled Fennin Ro, the Tyrant of Fire
(217056, 'PoP', 85, 0),  -- Quavonis_Firetail (Doomfire, the Burning Lands) - The Fabled Quavonis Firetail
(217059, 'PoP', 85, 0),  -- Magmaton (Doomfire, the Burning Lands) - The Fabled Magmaton
(217060, 'PoP', 83, 0),  -- Jopal_Crafter (Doomfire, the Burning Lands) - Fabled Jopal Crafter
(217062, 'PoP', 83, 0),  -- Doomfire_Magus (Doomfire, the Burning Lands) - Fabled Doomfire Magus
(217063, 'PoP', 85, 0),  -- Pyronis (Doomfire, the Burning Lands) - The Fabled Pyronis
(217064, 'PoP', 83, 0),  -- Flame_Overlord (Doomfire, the Burning Lands) - Fabled Flame Overlord
(217065, 'PoP', 83, 0),  -- Doomfire_Warmaster (Doomfire, the Burning Lands) - Fabled Doomfire Warmaster
(217073, 'PoP', 83, 0),  -- Charmer_of_Fire (Doomfire, the Burning Lands) - Fabled Charmer of Fire
(217074, 'PoP', 83, 0),  -- Wild_Fiery_Spirit_Steed (Doomfire, the Burning Lands) - Fabled Wild Fiery Spirit Steed
(217075, 'PoP', 83, 0),  -- Vicar_of_Fire (Doomfire, the Burning Lands) - Fabled Vicar of Fire
(217077, 'PoP', 85, 0),  -- Azobian_the_Darklord (Doomfire, the Burning Lands) - The Fabled Azobian the Darklord
(217078, 'PoP', 85, 0),  -- Hebabbilys_the_Ragelord (Doomfire, the Burning Lands) - The Fabled Hebabbilys the Ragelord
(217079, 'PoP', 85, 0),  -- Javonn_the_Overlord (Doomfire, the Burning Lands) - The Fabled Javonn the Overlord
(217080, 'PoP', 85, 0),  -- Reaxnous_the_Chaoslord (Doomfire, the Burning Lands) - The Fabled Reaxnous the Chaoslord
(217081, 'PoP', 85, 0),  -- Warlord_Prollaz (Doomfire, the Burning Lands) - The Fabled Warlord Prollaz
(217082, 'PoP', 85, 0),  -- Omni_Magus_Crato (Doomfire, the Burning Lands) - The Fabled Omni Magus Crato
(217083, 'PoP', 85, 0),  -- Chancellor_Traxom (Doomfire, the Burning Lands) - The Fabled Chancellor Traxom
(217089, 'PoP', 83, 0),  -- Doomfire_Firecharmer (Doomfire, the Burning Lands) - Fabled Doomfire Firecharmer
(217091, 'PoP', 83, 0),  -- Doomfire_Vicar (Doomfire, the Burning Lands) - Fabled Doomfire Vicar
(217092, 'PoP', 83, 0),  -- Doomfire_Warlord (Doomfire, the Burning Lands) - Fabled Doomfire Warlord
(217093, 'PoP', 83, 0),  -- Fiery_Spirit_Equine_Overlord (Doomfire, the Burning Lands) - Fabled Fiery Spirit Equine Overlord
(217094, 'PoP', 83, 0),  -- Flame_Wilder (Doomfire, the Burning Lands) - Fabled Flame Wilder
(217096, 'PoP', 83, 0),  -- Jopal_Flame_Protector (Doomfire, the Burning Lands) - Fabled Jopal Flame Protector
(217097, 'PoP', 83, 0),  -- Jopal_Seer (Doomfire, the Burning Lands) - Fabled Jopal Seer
(217098, 'PoP', 83, 0),  -- Jopal_Tracker (Doomfire, the Burning Lands) - Fabled Jopal Tracker
(217099, 'PoP', 83, 0),  -- Obsidian_Tree_Spider_Queen (Doomfire, the Burning Lands) - Fabled Obsidian Tree Spider Queen
(217105, 'PoP', 83, 0),  -- Magma_Overlord (Doomfire, the Burning Lands) - Fabled Magma Overlord
(217106, 'PoP', 83, 0),  -- Dark_Obsidian_Lava_Spider (Doomfire, the Burning Lands) - Fabled Dark Obsidian Lava Spider
(218024, 'PoP', 83, 0),  -- An_Earthcrafted_Assassin (Vegarlson, the Earthen Badlands) - Fabled Earthcrafted Assassin
(218025, 'PoP', 83, 0),  -- A_Vekerchiki_Warrior (Vegarlson, the Earthen Badlands) - Fabled Vekerchiki Warrior
(218049, 'PoP', 85, 0),  -- Peregrin_Rockskull (Vegarlson, the Earthen Badlands) - The Fabled Peregrin Rockskull
(218050, 'PoP', 85, 0),  -- A_Monsterous_Mudwalker (Vegarlson, the Earthen Badlands) - A Fabled Monstrous Mudwalker
(218052, 'PoP', 83, 0),  -- An_Ancient_Vekerchiki_Champion (Vegarlson, the Earthen Badlands) - Fabled Ancient Vekerchiki Champion
(218053, 'PoP', 90, 0),  -- A_Mystical_Arbitor_of_Earth (Vegarlson, the Earthen Badlands) - The Fabled Mystical Arbitor of Earth
(218065, 'PoP', 83, 0),  -- A_Korascian_Warlord (Vegarlson, the Earthen Badlands) - Fabled A Korascian Warlord
(218074, 'PoP', 83, 0),  -- Glimmerstone (Vegarlson, the Earthen Badlands) - Fabled Glimmerstone
(218081, 'PoP', 83, 0),  -- Tribal_Leader_Diseranon (Vegarlson, the Earthen Badlands) - Fabled Tribal Leader Diseranon
(218083, 'PoP', 83, 0),  -- A_Perfect_Rock_Formation (Vegarlson, the Earthen Badlands) - Fabled A Perfect Rock Formation
(218087, 'PoP', 83, 0),  -- A_Shimmering_Gem_Sentry (Vegarlson, the Earthen Badlands) - Fabled A Shimmering Gem Sentry
(218096, 'PoP', 85, 0),  -- A_Perfected_Warder_of_Earth (Vegarlson, the Earthen Badlands) - A Fabled Perfected Warder of Earth
(218100, 'PoP', 83, 0),  -- A_Prismatic_Basilisk (Vegarlson, the Earthen Badlands) - Fabled A Prismatic Basilisk
(218101, 'PoP', 83, 0),  -- A_Pristine_Gem_Golem (Vegarlson, the Earthen Badlands) - Fabled A Pristine Gem Golem
(218115, 'PoP', 83, 0),  -- The_Living_Earth (Vegarlson, the Earthen Badlands) - Fabled The Living Earth
(218116, 'PoP', 83, 0),  -- Galsinak_Earthrumble (Vegarlson, the Earthen Badlands) - Fabled Galsinak Earthrumble
(218121, 'PoP', 85, 0),  -- Peregrin_Rockskull (Vegarlson, the Earthen Badlands) - The Fabled Peregrin Rockskull
(220015, 'PoP', 90, 0),  -- Lord_Mithaniel_Marr (Temple of Marr) - The Fabled Lord Mithaniel Marr
(221008, 'PoP', 85, 0),  -- #Terris_Thule (Lair of Terris Thule) - The Fabled Terris Thule
(222014, 'PoP', 90, 0),  -- #Avatar_of_Earth (Ragrax, Stronghold of the Twelve) - The Fabled Avatar of Earth
(222019, 'PoP', 85, 0),  -- #Warlord_Gintolaken (Ragrax, Stronghold of the Twelve) - The Fabled Warlord Gintolaken
(223000, 'PoP', 90, 0),  -- Innoruuk (Plane of Time B) - The Fabled Innoruuk
(223001, 'PoP', 90, 0),  -- Rallos_Zek (Plane of Time B) - The Fabled Rallos Zek
(223075, 'PoP', 90, 0),  -- Terris_Thule (Plane of Time B) - The Fabled Terris Thule
(223076, 'PoP', 90, 0),  -- Saryrn (Plane of Time B) - The Fabled Saryrn
(223077, 'PoP', 90, 0),  -- Tallon_Zek (Plane of Time B) - The Fabled Tallon Zek
(223098, 'PoP', 90, 0),  -- Bertoxxulous (Plane of Time B) - The Fabled Bertoxxulous
(223165, 'PoP', 90, 0),  -- Cazic_Thule (Plane of Time B) - The Fabled Cazic Thule
(223201, 'PoP', 90, 0)  -- Quarm (Plane of Time B) - The Fabled Quarm
ON DUPLICATE KEY UPDATE `era` = VALUES(`era`), `level` = VALUES(`level`);

-- Unmatched live rows (no npc_types row found; add an ALIASES entry in the generator):
--   The Fabled Ranvik Darkwaters | 50 | Twilight Sea
--   The Fabled Highpriest Giplish | 55 | Grimling Forest
--   The Fabled Corrupter Ahgra | 55 | Grimling Forest
--   The Fabled Arch Duke Latol | 65 | Old Sebilis
--   The Fabled Stronghorn | 70 | Western Wastes
--   A Fabled Triloun | 83 | Reef of Coirnav
--   A Fabled Jopal | 83 | Doomfire, the Burning Lands
--   The Fabled Chancellor Kirtra | 85 | Doomfire, the Burning Lands
