-- ============================================================================
-- B4: books
-- Generated by tools/db_additive_sync.py -- additive-only (INSERT IGNORE).
-- Source: peq_upstream (PEQ 2026-09-12). Target: peq. Literal values only.
-- fills (empty local text): 0
-- inserts (new by name): 0
-- ============================================================================


