-- ============================================================================
-- Fix: db_str client strings for new alternate currencies
-- Generated by tools/db_additive_sync.py -- additive-only (INSERT IGNORE).
-- Source: peq_upstream (PEQ 2026-09-12). Target: peq. Literal values only.
-- currencies: 12
-- rows: 24
-- type 17 = name, 18 = plural (same as singular)
-- ============================================================================

INSERT IGNORE INTO `db_str` (`id`, `type`, `value`) VALUES
(4, 17, 'Radiant Crystal'),
(4, 18, 'Radiant Crystal'),
(5, 17, 'Ebon Crystal'),
(5, 18, 'Ebon Crystal'),
(30, 17, 'Dreadstone'),
(30, 18, 'Dreadstone'),
(31, 17, 'Mark of Valor'),
(31, 18, 'Mark of Valor'),
(32, 17, 'Medal of Heroism'),
(32, 18, 'Medal of Heroism'),
(33, 17, 'Commemorative Coin'),
(33, 18, 'Commemorative Coin'),
(34, 17, 'Fist of Bayle'),
(34, 18, 'Fist of Bayle'),
(35, 17, 'Noble'),
(35, 18, 'Noble'),
(36, 17, 'Arx Energy Crystal'),
(36, 18, 'Arx Energy Crystal'),
(37, 17, 'Piece of Eight'),
(37, 18, 'Piece of Eight'),
(38, 17, 'Remnant of Tranquility'),
(38, 18, 'Remnant of Tranquility'),
(39, 17, 'Bifurcated Coin'),
(39, 18, 'Bifurcated Coin');

