-- ============================================================================
-- B6a: loot entries added to existing lootdrops -- LDoN
-- Generated by tools/db_additive_sync.py -- additive-only (INSERT IGNORE).
-- Source: peq_upstream (PEQ 2026-09-12). Target: peq. Literal values only.
-- canonical era: LDoN (6)
-- lootdrops: 19
-- entries: 23
-- existing lootdrops only -- no new lootdrop rows
-- ============================================================================

INSERT IGNORE INTO `lootdrop_entries` (`lootdrop_id`, `item_id`, `item_charges`, `equip_item`, `chance`, `disabled_chance`, `trivial_min_level`, `trivial_max_level`, `multiplier`, `npc_min_level`, `npc_max_level`, `min_expansion`, `max_expansion`, `content_flags`, `content_flags_disabled`) VALUES
(39822, 97286, 1, 0, 8.5, 0.0, 0, 0, 2, 0, 0, -1, -1, NULL, NULL),
(39825, 97002, 1, 0, 6.0, 0.0, 0, 0, 2, 0, 0, -1, -1, NULL, NULL),
(121404, 97002, 1, 1, 20.0, 0.0, 0, 0, 2, 0, 0, -1, -1, NULL, NULL),
(121415, 97003, 1, 1, 1.538, 0.0, 0, 0, 2, 0, 0, -1, -1, NULL, NULL),
(121415, 97286, 1, 1, 1.538, 0.0, 0, 0, 2, 0, 0, -1, -1, NULL, NULL),
(121671, 97001, 1, 1, 1.124, 0.0, 0, 0, 2, 0, 0, -1, -1, NULL, NULL),
(121836, 97286, 1, 1, 2.632, 0.0, 0, 0, 2, 0, 0, -1, -1, NULL, NULL),
(121850, 97286, 1, 1, 2.326, 0.0, 0, 0, 2, 0, 0, -1, -1, NULL, NULL),
(121867, 97286, 1, 1, 9.091, 0.0, 0, 0, 2, 0, 0, -1, -1, NULL, NULL),
(121884, 97002, 1, 1, 1.163, 0.0, 0, 0, 2, 0, 0, -1, -1, NULL, NULL),
(121884, 97286, 1, 1, 1.163, 0.0, 0, 0, 2, 0, 0, -1, -1, NULL, NULL),
(122259, 97002, 1, 1, 4.545, 0.0, 0, 0, 2, 0, 0, -1, -1, NULL, NULL),
(122272, 97001, 1, 1, 0.485, 0.0, 0, 0, 2, 0, 0, -1, -1, NULL, NULL),
(122272, 97003, 1, 1, 0.485, 0.0, 0, 0, 2, 0, 0, -1, -1, NULL, NULL),
(122272, 97286, 1, 1, 0.485, 0.0, 0, 0, 2, 0, 0, -1, -1, NULL, NULL),
(122273, 97002, 1, 1, 1.456, 0.0, 0, 0, 2, 0, 0, -1, -1, NULL, NULL),
(122277, 97002, 1, 1, 3.846, 0.0, 0, 0, 2, 0, 0, -1, -1, NULL, NULL),
(122522, 97003, 1, 1, 100.0, 0.0, 0, 0, 2, 0, 0, -1, -1, NULL, NULL),
(122592, 97003, 1, 1, 1.493, 0.0, 0, 0, 2, 0, 0, -1, -1, NULL, NULL),
(122616, 97001, 1, 1, 0.73, 0.0, 0, 0, 2, 0, 0, -1, -1, NULL, NULL),
(122621, 97001, 1, 1, 2.941, 0.0, 0, 0, 2, 0, 0, -1, -1, NULL, NULL),
(125743, 80381, 1, 0, 0.435, 0.0, 0, 0, 1, 0, 0, -1, -1, NULL, NULL),
(176892, 80381, 1, 0, 2.128, 0.0, 0, 0, 1, 0, 0, -1, -1, NULL, NULL);

