-- [[
-- Deepscar_Raid_Controller (451630) -- Deepscar's Den raid controller (dragonscaleb version 51).
-- Registers the win chest as a loot event on instance boot and adds the
-- 18h lockout when the encounter signals completion. Passive, non-combat.
-- Generated by gen_dsb_raid.py -- do not hand-edit.
-- ]]
local LOCKOUT = eq.seconds("18h")

function event_spawn(e)
	local exp = eq.get_expedition()
	if not exp.valid then return end
	exp:SetLootEventByNPCTypeID(451100, "Deepscar's Den")
end

function event_signal(e)
	if e.signal ~= 1201 then return end
	local exp = eq.get_expedition()
	if exp.valid and not exp:HasLockout("Deepscar's Den") then
		exp:AddLockout("Deepscar's Den", LOCKOUT)
		eq.zone_emote(15, "Deepscar's Den has been defeated!")
	end
end
