-- [[
-- Big_Bynn_Raid_Controller (451631) -- Big Bynn's Lair raid controller (dragonscaleb version 52).
-- Registers the win chest as a loot event on instance boot and adds the
-- 72h lockout when the encounter signals completion. Passive, non-combat.
-- Generated by gen_dsb_raid.py -- do not hand-edit.
-- ]]
local LOCKOUT = eq.seconds("72h")

function event_spawn(e)
	local exp = eq.get_expedition()
	if not exp.valid then return end
	exp:SetLootEventByNPCTypeID(451620, "Big Bynn's Lair")
end

function event_signal(e)
	if e.signal ~= 1202 then return end
	local exp = eq.get_expedition()
	if exp.valid and not exp:HasLockout("Big Bynn's Lair") then
		exp:AddLockout("Big Bynn's Lair", LOCKOUT)
		eq.zone_emote(15, "Big Bynn's Lair has been defeated!")
	end
end
