-- Define the task IDs in the database

task_ids = {
  bic_abysmal = 9,
  bic_qinimi = 10,
  bic_barindu = 11,
  bic_riwwi = 12,
  bic_ferubi = 13,
  bic_sewers = 14,
  bic_vxed = 15,
  bic_tipt = 16,
  bic_outer = 17,
  bic_yxtta = 18,
  bic_kodtaz = 19,
  trials_task = 20,
  kevren_task = 21,
  tublik_task = 22,
  trusik_task = 23,
  muramite_needle = 23,
  hynid_hair_thread = 24,
  inferno_scepter = 25,
  sewers_task = 26,
  plant_task = 27,
  crem_task = 28,
  lair_task = 29,
  pool_task = 30,
  mountains_task = 31,
  vxed_task = 32,
  tipt_task = 33,
}
